import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Afghanistan_universities = [

    // Afghanistan

    { name: "The American University of Afghanistan", domain: "auaf.edu.af", isVerified: true },
    { name: "Kabul University", domain: "ku.edu.af", isVerified: true },
    { name: "Kardan University", domain: "kardan.edu.af", isVerified: true },
    { name: "Khatam Al Nabieen University", domain: "kanz.edu.af", isVerified: true },
    { name: "Herat University", domain: "hu.edu.af", isVerified: true },
    { name: "Kabul Polytechnic University", domain: "kpu.edu.af", isVerified: true },
    { name: "Kateb University", domain: "kateb.edu.af", isVerified: true },
    { name: "Balkh University", domain: "bu.edu.af", isVerified: true },
    { name: "Nangarhar University", domain: "nu.edu.af", isVerified: true },
    { name: "Ghalib University", domain: "ghalib.edu.af", isVerified: true },
    { name: "Kabul University of Medical Sciences", domain: "kums.edu.af", isVerified: true },
    { name: "Salam University", domain: "salam.edu.af", isVerified: true },
    { name: "Gawharshad Institute of Higher Education", domain: "gawharshad.edu.af", isVerified: true },
    { name: "Kawun Institute of Higher Education", domain: "kawun.edu.af", isVerified: true },
    { name: "Bakhtar University", domain: "bakhtar.edu.af", isVerified: true },
    { name: "Mawlana University", domain: "mawlana.edu.af", isVerified: true },
    { name: "Bamiyan University", domain: "bu.edu.af", isVerified: false }, 
    { name: "Karwan University", domain: "karwan.edu.af", isVerified: true },
    { name: "Rana University", domain: "ru.edu.af", isVerified: true },
    { name: "Al-taqwa Institute of Higher Education", domain: "altaqwa.edu.af", isVerified: true },
    { name: "Kandahar University", domain: "ku.edu.af", isVerified: false },
    { name: "Shaikh Zayed University, Khost", domain: "szu.edu.af", isVerified: true },
    { name: "Jawzjan University", domain: "ju.edu.af", isVerified: true },
    { name: "Tabesh University", domain: "tabesh.edu.af", isVerified: true },
    { name: "Dunya University of Afghanistan", domain: "dunya.edu.af", isVerified: true },
    { name: "Bost University", domain: "bost.edu.af", isVerified: true },
    { name: "Kabul Education University", domain: "keu.edu.af", isVerified: true },
    { name: "Baghlan University", domain: "baghlan.edu.af", isVerified: true },
    { name: "Zawul Institute of Higher Education", domain: "zawul.edu.af", isVerified: true },
    { name: "Dawat University", domain: "dawat.edu.af", isVerified: true }, 
    { name: "Peshgam Institute of Higher Education", domain: null, isVerified: false },
    { name: "Al Beroni University", domain: "beroni.edu.af", isVerified: true },
    { name: "Badakhshan University", domain: "bu.edu.af", isVerified: false },
    { name: "Khurasan University", domain: "khurasan.edu.af", isVerified: true },
    { name: "Eshrag Institute of Higher Education", domain: "eshragh.edu.af", isVerified: true },
    { name: "Paktia University", domain: "paktia.edu.af", isVerified: true },
    { name: "Ariana Institute of Higher Education", domain: "ariana.edu.af", isVerified: true },
    { name: "Khana-e-Noor University", domain: "knu.edu.af", isVerified: true },
    { name: "Faryab University", domain: "faryab.edu.af", isVerified: true },
    { name: "Ghazni University", domain: "ghazni.edu.af", isVerified: true },
    { name: "Jahan University", domain: "jahan.edu.af", isVerified: true },
    { name: "Maryam University", domain: "maryam.edu.af", isVerified: true },
    { name: "Benawa Institute of Higher Education", domain: "benawa.edu.af", isVerified: true },
    { name: "Laghman University", domain: "laghman.edu.af", isVerified: true },
    { name: "Sayed Jamaluddin Afghani University", domain: "sjau.edu.af", isVerified: true },
    { name: "Moraa Female University", domain: "moraa.edu.af", isVerified: true },
    { name: "Kahkashan-e-Sharq Higher Education Institute", domain: "kahkashan.edu.af", isVerified: true },
    { name: "Parwan University", domain: "parwan.edu.af", isVerified: true },
    { name: "Takhar University", domain: "takhar.edu.af", isVerified: true },
    { name: "Khurshid Institute of Higher Education", domain: "khurshid.edu.af", isVerified: true },
    { name: "Abourihan Higher Education Institute", domain: "abourihan.edu.af", isVerified: true },
    { name: "Helmand University", domain: "helmand.edu.af", isVerified: true },
    { name: "Mili Institute of Higher Education", domain: "mili.edu.af", isVerified: true },
    { name: "Afghan Swiss Medical Institute of Higher Education", domain: "afghanswiss.edu.af", isVerified: true },
    { name: "Maihan Institute of Higher Education", domain: "maihan.edu.af", isVerified: true },
    { name: "Noman Sadat Institute of Higher Education", domain: "nomansadat.edu.af", isVerified: true },
    { name: "Maiwand institute of Higher Education", domain: "maiwand.edu.af", isVerified: true },
    { name: "Kunduz University", domain: "kunduz.edu.af", isVerified: true },
    { name: "Cheragh Medical Institute", domain: "cheragh.edu.af", isVerified: true },
    { name: "Azhar Higher Education Institute", domain: "azhar.edu.af", isVerified: true },
    { name: "Allameh Institute of Higher Education", domain: "allameh.edu.af", isVerified: true },
    { name: "Mashal University", domain: "mashal.edu.af", isVerified: true },
    { name: "Taj Institute of Higher Education", domain: "taj.edu.af", isVerified: true },
    { name: "Islamic Azad University Afghanistan", domain: "iau-af.com", isVerified: true },
    { name: "Ashna Institute of Higher Education", domain: "ashna.edu.af", isVerified: true },
    { name: "Rahnaward Institute of Higher Education", domain: "rahnaward.edu.af", isVerified: true },
    { name: "Gharjistan University", domain: "gharjistan.edu.af", isVerified: true },
    { name: "Pamir Institute of Higher Education", domain: "pamir.edu.af", isVerified: true },
    { name: "Rabia Balkhi University", domain: "rabia.edu.af", isVerified: true },
    { name: "Sharq Institute of Higher Education", domain: "sharq.edu.af", isVerified: true },
    { name: "Sadat Institute of Higher Education", domain: "sadat.edu.af", isVerified: true },
    { name: "Fanoos Institute of Higher Education", domain: "fanoos.edu.af", isVerified: true },
    { name: "Shifa Institute of Higher Education", domain: "shifa.edu.af", isVerified: true },
    { name: "Esteghlal Institute of Higher Education", domain: "esteghlal.edu.af", isVerified: true },
    { name: "Tolo-e-Aftab Institute of Higher Education", domain: "toloeaftab.edu.af", isVerified: true },
    { name: "Danish Institute of Higher Education", domain: "danish.edu.af", isVerified: true },
    { name: "Quds Higher Education Institute", domain: "quds.edu.af", isVerified: true },
    { name: "Turkestan Institute of Higher Education", domain: "turkestan.edu.af", isVerified: true },
    { name: "Payam Institute of Higher Education", domain: "payam.edu.af", isVerified: true },
    { name: "Ghazi Amanullah Khan Institute of Higher Education", domain: null, isVerified: false },
    { name: "Royan Institute of Higher Education", domain: null, isVerified: false },
    { name: "Hakim Sanayee University", domain: null, isVerified: false },
    { name: "Jahan E Noor Institute of Higher Education", domain: null, isVerified: false },
    { name: "Noorin Institute of Higher Education", domain: null, isVerified: false },
    { name: "Saber Institute of Higher Education", domain: null, isVerified: false },
    { name: "Avicenna University", domain: "avicenna.edu.af", isVerified: true },
    { name: "Alborz Institute of Higher Education", domain: null, isVerified: false },
    { name: "Nayestan Institute of Higher Education", domain: null, isVerified: false },
    { name: "Ahlobait Institute of Higher Education", domain: null, isVerified: false },
    { name: "Rah-e-Saadat University", domain: null, isVerified: false },
    { name: "Qalam Institute of Higher Education", domain: null, isVerified: false },
    { name: "Aria University", domain: "aria.edu.af", isVerified: true },
    { name: "Edrak Institute of Higher Education", domain: null, isVerified: false },
    { name: "Kaboora Institute of Higher Education", domain: null, isVerified: false },
    { name: "Esteqamat Higher Education Institute", domain: null, isVerified: false },
    { name: "Oruj Institute of Higher Education", domain: null, isVerified: false },
    { name: "Shaheed Rabani Education University", domain: "keu.edu.af", isVerified: true },
]