import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Algeria_universities = [

   // Algeria

   { name: "Université Abou Bekr Belkaid de Tlemcen", domain: "univ-tlemcen.dz", isVerified: true },
   { name: "Université Mohamed Boudiaf de M'sila", domain: "univ-msila.dz", isVerified: true },
   { name: "Université Frères Mentouri Constantine 1", domain: "umc.edu.dz", isVerified: true },
   { name: "Université Mouloud Mammeri de Tizi-Ouzou", domain: "ummto.dz", isVerified: true },
   { name: "Université Ferhat Abbas Sétif 1", domain: "univ-setif.dz", isVerified: true },
   { name: "Université Kasdi Merbah de Ouargla", domain: "univ-ouargla.dz", isVerified: true },
   { name: "Université Abbès Laghrour Khenchela", domain: "univ-khenchela.dz", isVerified: true },
   { name: "Université des Sciences et de la Technologie Houari Boumediène", domain: "usthb.dz", isVerified: true },
   { name: "Université Abderrahmane Mira de Béjaïa", domain: "univ-bejaia.dz", isVerified: true },
   { name: "Université Benyoucef Benkhedda d'Alger 1", domain: "univ-alger.dz", isVerified: true },
   { name: "Université Echahid Hamma Lakhdar d'El Oued", domain: "univ-eloued.dz", isVerified: true },
   { name: "Université Abdelhamid Ibn Badis de Mostaganem", domain: "univ-mosta.dz", isVerified: true },
   { name: "Université Badji Mokhtar de Annaba", domain: "univ-annaba.dz", isVerified: true },
   { name: "Université Mohamed Khider de Biskra", domain: "univ-biskra.dz", isVerified: true },
   { name: "Université 8 Mai 1945 Guelma", domain: "univ-guelma.dz", isVerified: true },
   { name: "Université Hadj Lakhder de Batna 1", domain: "univ-batna.dz", isVerified: true },
   { name: "Université de Batna 2", domain: "univ-batna2.dz", isVerified: true },
   { name: "Université M'hamed Bouguerra de Boumerdès", domain: "umbb.dz", isVerified: true },
   { name: "Université Larbi Tebessi de Tébessa", domain: "univ-tebessa.dz", isVerified: true },
   { name: "Université Hassiba Ben Bouali de Chlef", domain: "univ-chlef.dz", isVerified: true },
   { name: "Université des Sciences et de la Technologie d'Oran Mohamed Boudiaf", domain: "usto-mb.dz", isVerified: true },
   { name: "Université Ahmed Ben Bella d'Oran 1", domain: "univ-oran1.dz", isVerified: true },
   { name: "Université Salah Boubnider de Constantine 3", domain: "univ-constantine3.dz", isVerified: true },
   { name: "Université Mohamed Seddik Ben Yahia de Jijel", domain: "univ-jijel.dz", isVerified: true },
   { name: "Université Brahim Soltane Chaibout d'Alger 3", domain: "univ-alger3.dz", isVerified: true },
   { name: "Université Amar Telidji de Laghouat", domain: "lagh-univ.dz", isVerified: true },
   { name: "Université Larbi Ben Mhidi de Oum El Bouaghi", domain: "univ-oeb.dz", isVerified: true },
   { name: "Université Saad Dahlab de Blida 1", domain: "univ-blida.dz", isVerified: true },
   { name: "Université Ibn Khaldoun de Tiaret", domain: "univ-tiaret.dz", isVerified: true },
   { name: "Université Djillali Liabès de Sidi-Bel-Abbès", domain: "univ-sba.dz", isVerified: true },
   { name: "Université 20 Août 1955 de Skikda", domain: "univ-skikda.dz", isVerified: true },
   { name: "École Nationale Supérieure d'Informatique", domain: "esi.dz", isVerified: true },
   { name: "Université Tahar Moulay de Saida", domain: "univ-saida.dz", isVerified: true },
   { name: "Université Mohamed-Chérif Messaadia de Souk Ahras", domain: "univ-soukahras.dz", isVerified: true },
   { name: "Université Mohamed Lamine Debaghine de Sétif 2", domain: "univ-setif2.dz", isVerified: true },
   { name: "Université Akli Mohand Oulhadj de Bouira", domain: "univ-bouira.dz", isVerified: true },
   { name: "Université Ziane Achour de Djelfa", domain: "univ-djelfa.dz", isVerified: true },
   { name: "Université Yahia Fares de Médéa", domain: "univ-medea.dz", isVerified: true },
   { name: "Université Abou el Kacem Saâdallah d'Alger 2", domain: "univ-alger2.dz", isVerified: true },
   { name: "Université Abdelhamid Mehri de Constantine 2", domain: "univ-constantine2.dz", isVerified: true },
   { name: "Université Mohamed Ben Ahmed d'Oran 2", domain: "univ-oran2.dz", isVerified: true },
   { name: "École Nationale Polytechnique", domain: "enp.edu.dz", isVerified: true },
   { name: "Université Mohamed El Bachir El Ibrahimi de Bordj Bou Arréridj", domain: "univ-bba.dz", isVerified: true },
   { name: "Université Ahmed Draia d'Adrar", domain: "univ-adrar.edu.dz", isVerified: true },
   { name: "Université Lounici Ali de Blida 2", domain: "univ-blida2.dz", isVerified: true },
   { name: "Université Mustapha Stambouli de Mascara", domain: "univ-mascara.dz", isVerified: true },
   { name: "Université de Ghardaia", domain: "univ-ghardaia.edu.dz", isVerified: true },
   { name: "Université des Sciences Islamiques Emir Abdelkader", domain: "univ-emir-constantine.edu.dz", isVerified: true },
   { name: "Université Djilali Bounaama de Khemis Miliana", domain: "univ-dbkm.dz", isVerified: true },
   { name: "Université Tahri Mohammed de Béchar", domain: "univ-bechar.dz", isVerified: true },
   { name: "École Nationale Supérieure Agronomique", domain: "ensa.dz", isVerified: true },
   { name: "École Nationale Polytechnique d'Oran", domain: "enp-oran.dz", isVerified: true },
   { name: "École Polytechnique d'Architecture et d'Urbanisme", domain: "epau-alger.edu.dz", isVerified: true },
   { name: "Université de Ain Témouchent", domain: "univ-temouchent.edu.dz", isVerified: true },
   { name: "École Nationale d'Administration Moulay Ahmed Medeghri", domain: "ena.dz", isVerified: true },
   { name: "École Nationale Supérieure des Travaux Publics", domain: "enstp.edu.dz", isVerified: true },
   { name: "École Supérieure de Commerce", domain: "esc-alger.dz", isVerified: true },
   { name: "École Nationale Supérieure Vétérinaire d'Alger", domain: "ensv.dz", isVerified: true },
   { name: "École Nationale Supérieure d'Hydraulique", domain: "ensh.dz", isVerified: true },
   { name: "École Nationale Supérieure des Sciences de la Mer et de l'Aménagement du Littoral", domain: "enssmal.edu.dz", isVerified: true },
   { name: "École Normale Supérieure de Bouzaréah", domain: "ens-bouzareah.dz", isVerified: true },
   { name: "École Normale Supérieure de Kouba", domain: "ens-kouba.dz", isVerified: true },
   { name: "École Supérieure en Informatique", domain: "esi-sba.dz", isVerified: true },
   { name: "École Supérieure de la Magistrature", domain: "esm.dz", isVerified: true },
   { name: "Université Chadli Bendjedid d'El Tarf", domain: "univ-eltarf.dz", isVerified: true },
   { name: "École Nationale Supérieure de Management", domain: "ensm.dz", isVerified: true },
   { name: "École Supérieure des Sciences de Gestion de Annaba", domain: "essg-annaba.dz", isVerified: true },
   { name: "École Nationale Supérieure de Technologie", domain: "enst.dz", isVerified: true },
   { name: "École Nationale Polytechnique de Constantine", domain: "enp-constantine.dz", isVerified: true },
   { name: "École Nationale Supérieure de Biotechnologie", domain: "ensb.dz", isVerified: true },
   { name: "École des Hautes Etudes Commerciales", domain: "hec.dz", isVerified: true },
   { name: "École Nationale Supérieure en Statistique et en Economie Appliquée", domain: "enssea.dz", isVerified: true },
   { name: "École Supérieur en Génie Electrique et Energétique d'Oran", domain: "esgee.dz", isVerified: true },
   { name: "École Nationale Supérieure de Journalisme et des Sciences de l'Information", domain: "ensjsi.dz", isVerified: true },
   { name: "École Normale Supérieure de Constantine", domain: "ens-constantine.dz", isVerified: true },
   { name: "École Normale Supérieure d'Oran Ammour Ahmed", domain: "ens-oran.dz", isVerified: true },
   { name: "École Nationale Supérieure de Sciences Politiques", domain: "enssp.dz", isVerified: true },
   { name: "École Nationale Supérieure des Mines et de la Métallurgie", domain: "ensmm.dz", isVerified: true },
   { name: "École Supérieure en Sciences Appliquées de Tlemcen", domain: "essa-tlemcen.dz", isVerified: true },
   { name: "École Supérieure des Sciences de l'Aliment et Industries Agroalimentaires", domain: "esssia.dz", isVerified: true },
   { name: "École Normale Supérieure d'Enseignement Technologique de Skikda", domain: "enset-skikda.dz", isVerified: true },
   { name: "École Nationale Supérieure de Technologie et d'Ingénierie", domain: "ensti-annaba.dz", isVerified: true },
   { name: "École Supérieure de Management de Tlemcen", domain: "esm-tlemcen.dz", isVerified: true },
   { name: "École Supérieure d'Economie d'Oran", domain: "ese-oran.dz", isVerified: true },
   { name: "École Normale Supérieure de Sétif", domain: "ens-setif.dz", isVerified: true },
   { name: "École Supérieure des Sciences Appliquées d'Alger", domain: "essa-alger.edu.dz", isVerified: true },
   { name: "Université de Tissemsilt", domain: "univ-tissemsilt.dz", isVerified: true },
   { name: "École Normale Supérieure de Ouargla", domain: "ens-ouargla.dz", isVerified: true },
   { name: "École Normale Supérieure de Bou Saâda", domain: "ens-bousaada.dz", isVerified: true },
   { name: "École Normale Supérieure de Laghouat", domain: "ens-lagh.dz", isVerified: true },
   { name: "École Supérieure en Sciences Biologiques d'Oran", domain: "essb-oran.edu.dz", isVerified: true },
   { name: "École Supérieure de Comptabilité et de Finances de Constantine", domain: "escf-constantine.dz", isVerified: true },
   { name: "École Normale Supérieure de Béchar", domain: "ens-bechar.dz", isVerified: true },
   { name: "École Nationale Supérieure des Forêts", domain: "hnsf.dz", isVerified: true },
]