import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Argentina_universities = [

   // Argentina

   { name: "Universidad de Buenos Aires", domain: "uba.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de La Plata", domain: "unlp.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Córdoba", domain: "unc.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Tecnológica Nacional", domain: "utn.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Rosario", domain: "unr.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Litoral", domain: "unl.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Cuyo", domain: "uncuyo.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Pontificia Universidad Católica Argentina", domain: "uca.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Nordeste", domain: "unne.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Mar del Plata", domain: "mdp.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de San Martín", domain: "unsam.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Palermo", domain: "palermo.edu", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Tucumán", domain: "unt.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Sur", domain: "uns.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Centro de la Provincia de Buenos Aires", domain: "unicen.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Quilmes", domain: "unq.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Comahue", domain: "uncoma.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Argentina de la Empresa", domain: "uade.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de Salta", domain: "ucasal.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de La Matanza", domain: "unlam.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de San Luis", domain: "unsl.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Facultad Latinoamericana de Ciencias Sociales", domain: "flacso.org.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Entre Ríos", domain: "uner.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Austral", domain: "austral.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Empresarial Siglo 21", domain: "21.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de San Andrés", domain: "udesa.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Ciencias Empresariales y Sociales", domain: "uces.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Tres de Febrero", domain: "untref.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Salvador", domain: "usal.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de San Juan", domain: "unsj.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Misiones", domain: "unam.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad FASTA", domain: "ufasta.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de General Sarmiento", domain: "ungs.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de La Pampa", domain: "unlpam.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Río Cuarto", domain: "unrc.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Abierta Interamericana", domain: "uai.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Luján", domain: "unlu.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Belgrano", domain: "ub.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Lanús", domain: "unla.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Santiago del Estero", domain: "unse.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de las Artes", domain: "una.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de la Patagonia San Juan Bosco", domain: "unpsjb.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Río Negro", domain: "unrn.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Tecnológico de Buenos Aires", domain: "itba.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Blas Pascal", domain: "ubp.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de Córdoba", domain: "ucc.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Lomas de Zamora", domain: "unlz.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Jujuy", domain: "unju.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Mendoza", domain: "um.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del CEMA", domain: "cema.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional Arturo Jauretche", domain: "unaj.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de José C. Paz", domain: "unpaz.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Hurlingham", domain: "unahur.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de La Rioja", domain: "unlar.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Villa María", domain: "unvm.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Flores", domain: "uflo.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Catamarca", domain: "unca.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Avellaneda", domain: "unda.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Autónoma de Entre Ríos", domain: "uader.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario de Ciencias de la Salud", domain: null, region: "South America", country: "Argentina", isVerified: false },
   { name: "Universidad Nacional del Noroeste de la Provincia de Buenos Aires", domain: "unnoba.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Chaco Austral", domain: "uncaus.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Morón", domain: "unimoron.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional Guillermo Brown", domain: "unibrown.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Argentina John F. Kennedy", domain: null, region: "South America", country: "Argentina", isVerified: false },
   { name: "Universidad Nacional de la Patagonia Austral", domain: "unpa.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de Santiago del Estero", domain: "ucse.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de Cuyo", domain: "uccuyo.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Norte Santo Tomás de Aquino", domain: "unsta.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de La Plata", domain: "ucalp.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Juan Agustín Maza", domain: "umaza.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Adventista del Plata", domain: "uap.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Congreso", domain: "congreso.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Aconcagua", domain: null, region: "South America", country: "Argentina", isVerified: false },
   { name: "Universidad Pedagógica Nacional", domain: "upn.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de Santa Fe", domain: "ucsf.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de la Cuenca del Plata", domain: "ucp.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario Aeronáutico", domain: "iua.edu.ar", region: "South America", country: "Argentina", isVerified: true },      
   { name: "Universidad del Cine", domain: "ucine.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario CEMIC", domain: "cemic.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Moreno", domain: "unm.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario ESEADE", domain: "eseade.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Gran Rosario", domain: "ugr.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Museo Social Argentino", domain: "umsa.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Maimónides", domain: "maimonides.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Favaloro", domain: "favaloro.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Provincial de Córdoba", domain: "upc.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Centro Educativo Latinoamericano", domain: "ucel.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad CAECE", domain: "ucaece.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Oeste", domain: "uno.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad ISALUD", domain: "isalud.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de la Marina Mercante", domain: "udemm.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de Concepción del Uruguay", domain: "ucu.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Champagnat", domain: "uch.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto para el Desarrollo Empresarial de la Argentina", domain: "idea.org.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Rafaela", domain: "unraf.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Chilecito", domain: "undec.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Tierra del Fuego, Antártida e Islas del Atlántico Sur", domain: "untdf.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional Raúl Scalabrini Ortiz", domain: "unso.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Formosa", domain: "unf.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Metropolitana para la Educación y el Trabajo", domain: "umet.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Provincial del Sudoeste", domain: "upso.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Provincial de Ezeiza", domain: "upe.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Atlántida Argentina", domain: "atlantida.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional del Alto Uruguay", domain: "unau.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Escuela Argentina de Negocios", domain: "ean.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Derechos Humanos Madres de Plaza de Mayo", domain: "iunma.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad del Este", domain: "ude.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario Patagónico de las Artes", domain: "iupa.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Gastón Dachary", domain: "ugd.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de San Isidro", domain: "usi.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Católica de las Misiones", domain: "ucami.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad de San Pablo-T", domain: "uspt.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de los Comechingones", domain: "unlc.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario Italiano de Rosario", domain: "iunir.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de Villa Mercedes", domain: "unvime.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Nacional de San Antonio de Areco", domain: "unsada.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Notarial Argentina", domain: "universidadnotarial.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Universidad Salesiana", domain: "unisal.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario River Plate", domain: "iuriverplate.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario de Ciencias Biomédicas de Córdoba", domain: "iucbc.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario de Seguridad Marítima", domain: "iusm.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario del Hospital Italiano", domain: "iuhitaliano.edu.ar", region: "South America", country: "Argentina", isVerified: true },
   { name: "Instituto Universitario de Salud Mental", domain: null, region: "South America", country: "Argentina", isVerified: false },
]