import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Armenia_universities = [

    // Armenia

    { name: "Yerevan State University", domain: "ysu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "American University of Armenia", domain: "aua.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Russian-Armenian University", domain: "rau.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "National Polytechnic University of Armenia", domain: "polytech.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Armenian State University of Economics", domain: "asue.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Armenian National Agrarian University", domain: "anau.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan State Medical University", domain: "ysmu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Brusov State University of Languages and Social Sciences", domain: "brusov.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Armenian State Pedagogical University", domain: "aspu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "National University of Architecture and Construction of Armenia", domain: "nuaca.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Université Française en Arménie", domain: "ufar.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Shirak State University", domain: "shsu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Eurasia International University", domain: "eiu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Gavar State University", domain: "gsu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "European University", domain: "eua.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Komitas State Conservatory", domain: "konservatoria.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "State Academy of Fine Arts of Armenia", domain: "safa.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Vanadzor State University", domain: "vsu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Medical Institute after Mehrabyan", domain: "mehrabyan.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Haybusak University", domain: "haybusak.org", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Armenian State Institute of Physical Culture and Sport", domain: "sportedu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Northern University", domain: "northern.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan State Theatre and Film Institute", domain: "ystfi.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Goris State University", domain: "gorsu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Artsakh State University", domain: "asu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Humanitarian Institute of Hrazdan", domain: "hinstitute.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Mkhitar Gosh Armenian-Russian International University", domain: "mkhitargosh.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Gladzor University", domain: "gladzor.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Armenian Medical Institute", domain: "armedin.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "University of Traditional Medicine", domain: "utm.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Urartu University of Practical Psychology and Sociology", domain: "urartu.university", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Progress University of Gyumri", domain: "progressuniversity.net", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan Mesrop Mashtots University", domain: "mashtotsuniversity.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Anania Shirakatsi University of International Relations", domain: "shirakatsi.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "Yerevan University after Movses Khorenatsi", domain: "mkhu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "GALIK University", domain: "galick.do.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "University of International Economic Relations", domain: "uier-edu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "St. Theresa Medical University of Yerevan", domain: "stmu.am", region: "Europe", country: "Armenia", isVerified: true },
    { name: "University of Economy and Law after Avetik Mkrtchyan", domain: "mtih.am", region: "Europe", country: "Armenia", isVerified: true },
]