import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Australia_universities = [

    // Australia

    { name: "Australian Catholic University", domain: "acu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Australian University of Theology", domain: null, region: "Oceania", country: "Australia", isVerified: false },
    { name: "Australian National University", domain: "anu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Avondale University", domain: "avondale.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Bond University", domain: "bond.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Charles Darwin University", domain: "cdu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Charles Sturt University", domain: "csu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "CQUniversity", domain: "cqu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Curtin University", domain: "curtin.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Deakin University", domain: "deakin.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Edith Cowan University", domain: "ecu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Federation University Australia", domain: "federation.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Flinders University", domain: "flinders.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Griffith University", domain: "griffith.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "James Cook University", domain: "jcu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "La Trobe University", domain: "latrobe.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Macquarie University", domain: "mq.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Monash University", domain: "monash.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Murdoch University", domain: "murdoch.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Queensland University of Technology", domain: "qut.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "RMIT University", domain: "rmit.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Southern Cross University", domain: "scu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Swinburne University of Technology", domain: "swinburne.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Torrens University Australia", domain: "torrens.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Adelaide", domain: "adelaide.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Canberra", domain: "canberra.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Divinity", domain: "divinity.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Melbourne", domain: "unimelb.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of New England", domain: "une.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of New South Wales", domain: "unsw.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Newcastle", domain: "newcastle.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Notre Dame Australia", domain: "notredame.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Queensland", domain: "uq.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of South Australia", domain: "unisa.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Southern Queensland", domain: "usq.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Sydney", domain: "sydney.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Tasmania", domain: "utas.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Technology Sydney", domain: "uts.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of the Sunshine Coast", domain: "usc.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Western Australia", domain: "uwa.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "University of Wollongong", domain: "uow.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Victoria University", domain: "vu.edu.au", region: "Oceania", country: "Australia", isVerified: true },
    { name: "Western Sydney University", domain: "wsu.edu.au", region: "Oceania", country: "Australia", isVerified: true },

]