import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Austria_universities = [

    // Austria

    { name: "Universität Wien", domain: "univie.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Technische Universität Wien", domain: "tuwien.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität Innsbruck", domain: "uibk.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Technische Universität Graz", domain: "tu-graz.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität Graz", domain: "uni-graz.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Johannes Kepler Universität Linz", domain: "jku.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Alpen-Adria-Universität Klagenfurt", domain: "aau.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Wirtschaftsuniversität Wien", domain: "wu.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Medizinische Universität Wien", domain: "meduniwien.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität für Bodenkultur Wien", domain: "boku.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Paris Lodron Universität Salzburg", domain: "plus.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität für Weiterbildung Krems", domain: "donau-uni.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Veterinärmedizinische Universität Wien", domain: "vetmeduni.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Institute of Science and Technology Austria", domain: "ista.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "FH Joanneum", domain: "fh-joanneum.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Medizinische Universität Graz", domain: "medunigraz.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "mdw - Universität für Musik und darstellende Kunst Wien", domain: "mdw.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "FH Oberösterreich", domain: "fh-ooe.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Montanuniversität Leoben", domain: "mu-leoben.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität für Künstlerische und Industrielle Gestaltung Linz", domain: null, region: "Europe", country: "Austria", isVerified: false },
    { name: "Medizinische Universität Innsbruck", domain: "i-med.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Akademie der Bildenden Künste Wien", domain: "akbild.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Technikum Wien", domain: "fh-technikum.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule St. Pölten", domain: "fhstp.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität Mozarteum Salzburg", domain: "moz.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Salzburg", domain: "fh-salzburg.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität für Musik und darstellende Kunst Graz", domain: "kug.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "MCI Management Center Innsbruck", domain: "mci.edu", region: "Europe", country: "Austria", isVerified: true },
    { name: "Universität für angewandte Kunst Wien", domain: "dieangewandte.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Campus Wien", domain: "fh-campuswien.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Kärnten", domain: "fh-kaernten.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Vorarlberg", domain: "fhv.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "IMC Krems", domain: "imc.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Sigmund Freud Privatuniversität Wien", domain: "sfu.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Anton Bruckner Privatuniversität", domain: "abpu.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Kufstein Tirol", domain: "fh-kufstein.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Hochschule für Angewandte Wissenschaften Burgenland", domain: "haw-burgenland.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule Wiener Neustadt", domain: "fhwn.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Paracelsus Medizinische Privatuniversität", domain: "pmu.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "FHWien der WKW", domain: "fh-wien.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Fachhochschule des bfi Wien", domain: null, region: "Europe", country: "Austria", isVerified: false },
    { name: "Private Universität für Gesundheitswissenschaften, Medizinische Informatik und Technik", domain: "umit.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Musik und Kunst Privatuniversität der Stadt Wien", domain: "muk.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Wien", domain: "phwien.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Niederösterreich", domain: "ph-noe.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "MODUL University Vienna", domain: "modul.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Katholische Privat-Universität Linz", domain: "kpu.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Kirchliche Pädagogische Hochschule Wien/Krems", domain: "kphviekrems.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Oberösterreich", domain: "ph-ooe.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Karl Landsteiner Privatuniversität für Gesundheitswissenschaften", domain: "kl.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Steiermark", domain: "phst.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "CAMPUS 02 Fachhochschule der Wirtschaft", domain: "campus02.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Diplomatische Akademie Wien", domain: "da-vienna.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Webster Vienna Private University", domain: "webster.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Private Pädagogische Hochschule der Diözese Linz", domain: null, region: "Europe", country: "Austria", isVerified: false },
    { name: "Pädagogische Hochschule Kärnten", domain: "ph-kaernten.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Salzburg Stefan Zweig", domain: "phsalzburg.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "New Design University Privatuniversität", domain: "newdesignuniversity.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Tirol", domain: "ph-tirol.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Hochschule für Agrar- und Umweltpädagogik Wien", domain: "haup.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Private Pädagogische Hochschule Augustinum", domain: null, region: "Europe", country: "Austria", isVerified: false },
    { name: "fh gesundheit", domain: "fh-gesundheit.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Pädagogische Hochschule Vorarlberg", domain: "ph-vorarlberg.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "FH Gesundheitsberufe OÖ", domain: "fhgoe.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Ferdinand Porsche FernFH", domain: "fernhfh.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Private Pädagogische Hochschule Burgenland", domain: "ph-burgenland.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Privatuniversität Schloss Seeburg", domain: "seeburg.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Danube Private University", domain: "dpu.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Jam Music Lab Private University", domain: "jammusiclab.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Gustav Mahler Privatuniversität für Musik", domain: null, region: "Europe", country: "Austria", isVerified: false },
    { name: "Bertha von Suttner Privatuniversität", domain: "bvs.ac.at", region: "Europe", country: "Austria", isVerified: true },
    { name: "Kirchliche Pädagogische Hochschule Edith Stein", domain: null, region: "Europe", country: "Austria", isVerified: false },
    { name: "Lauder Business School", domain: "lbs.ac.at", region: "Europe", country: "Austria", isVerified: true },
]