import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Bangladesh_universities = [

    // Bangladesh

    { name: "National University, Bangladesh", domain: "nu.ac.bd", isVerified: true },
    { name: "Rajshahi University", domain: "ru.ac.bd", isVerified: true },
    { name: "University of Dhaka", domain: "du.ac.bd", isVerified: true },
    { name: "Jahangirnagar University", domain: "juniv.edu", isVerified: true },
    { name: "Bangladesh University of Engineering and Technology", domain: "buet.ac.bd", isVerified: true },
    { name: "University of Chittagong", domain: "cu.ac.bd", isVerified: true },
    { name: "BRAC University", domain: "bracu.ac.bd", isVerified: true },
    { name: "Daffodil International University", domain: "daffodilvarsity.edu.bd", isVerified: true },
    { name: "North South University", domain: "northsouth.edu", isVerified: true },
    { name: "Shahjalal University of Science and Technology", domain: "sust.edu", isVerified: true },
    { name: "American International University-Bangladesh", domain: "aiub.edu", isVerified: true },
    { name: "Khulna University", domain: "ku.ac.bd", isVerified: true },
    { name: "United International University", domain: "uiu.ac.bd", isVerified: true },
    { name: "Rajshahi University of Engineering and Technology", domain: "ruet.ac.bd", isVerified: true },
    { name: "Bangladesh Medical University", domain: "bmu.edu.bd", isVerified: true },
    { name: "Khulna University of Engineering and Technology", domain: "kuet.ac.bd", isVerified: true },
    { name: "Jagannath University", domain: "jnu.ac.bd", isVerified: true },
    { name: "East West University", domain: "ewubd.edu", isVerified: true },
    { name: "Chittagong University of Engineering and Technology", domain: "cuet.ac.bd", isVerified: true },
    { name: "Bangladesh Agricultural University", domain: "b au.edu.bd", isVerified: true },
    { name: "Asian University for Women", domain: "auw.edu.bd", isVerified: true },
    { name: "Ahsanullah University of Science and Technology", domain: "aust.edu", isVerified: true },
    { name: "Bangladesh University of Professionals", domain: "bup.edu.bd", isVerified: true },
    { name: "Islamic University of Technology", domain: "iutoic-dhaka.edu", isVerified: true },
    { name: "University of Liberal Arts Bangladesh", domain: "ulab.edu.bd", isVerified: true },
    { name: "Bangladesh University of Business and Technology", domain: "bubt.edu.bd", isVerified: true },
    { name: "International University of Business Agriculture and Technology", domain: "iubat.edu", isVerified: true },
    { name: "Southeast University, Bangladesh", domain: "seu.edu.bd", isVerified: true },
    { name: "Islamic Arabic University", domain: "iau.edu.bd", isVerified: true },
    { name: "Islamic University", domain: "iu.ac.bd", isVerified: true },
    { name: "University of Asia Pacific", domain: "uap-bd.edu", isVerified: true },
    { name: "Dhaka University of Engineering and Technology", domain: "duet.ac.bd", isVerified: true },
    { name: "Noakhali Science and Technology University", domain: "nstu.edu.bd", isVerified: true },
    { name: "International Islamic University, Chittagong", domain: "iiuc.ac.bd", isVerified: true },
    { name: "Gazipur Agricultural University", domain: "gazipuragriculturaluniversity.edu.bd", isVerified: false },
    { name: "Hajee Mohammad Danesh Science and Technology University", domain: "hstu.ac.bd", isVerified: true },
    { name: "Jashore University of Science and Technology", domain: "just.edu.bd", isVerified: true },
    { name: "Stamford University Bangladesh", domain: "stamforduniversity.edu.bd", isVerified: true },
    { name: "Bangladesh University of Textiles", domain: "butex.edu.bd", isVerified: true },
    { name: "Green University of Bangladesh", domain: "green.edu.bd", isVerified: true },
    { name: "Sher-e-Bangla Agricultural University", domain: "sau.edu.bd", isVerified: true },
    { name: "Patuakhali Science and Technology University", domain: "pstu.ac.bd", isVerified: true },
    { name: "Comilla University", domain: "cou.ac.bd", isVerified: true },
    { name: "Jatiya Kabi Kazi Nazrul Islam University", domain: "jkkniu.edu.bd", isVerified: true },
    { name: "Chittagong Veterinary and Animal Sciences University", domain: "cvasu.ac.bd", isVerified: true },
    { name: "Independent University, Bangladesh", domain: "iub.edu.bd", isVerified: true },
    { name: "Bangladesh Maritime University", domain: "bmu.edu.bd", isVerified: true },
    { name: "Uttara University", domain: "uttarauniversity.edu.bd", isVerified: true },
    { name: "BGMEA University of Fashion and Technology", domain: "buft.edu.bd", isVerified: true },
    { name: "Mawlana Bhashani Science and Technology University", domain: "mbstu.ac.bd", isVerified: true },
    { name: "University of Barisal", domain: "bu.ac.bd", isVerified: true },
    { name: "Sylhet Agricultural University", domain: "sau.ac.bd", isVerified: true },
    { name: "Begum Rokeya University, Rangpur", domain: "brur.ac.bd", isVerified: true },
    { name: "World University of Bangladesh", domain: "wub.edu.bd", isVerified: true },
    { name: "Dhaka International University", domain: "diu.edu.bd", isVerified: true },
    { name: "Varendra University", domain: "vu.edu.bd", isVerified: true },
    { name: "Pabna Science and Technology University", domain: "pu.ac.bd", isVerified: true },
    { name: "Leading University", domain: "lu.ac.bd", isVerified: true },
    { name: "Northern University of Bangladesh", domain: "nub.ac.bd", isVerified: true },
    { name: "Chittagong Independent University", domain: "ciu.edu.bd", isVerified: true },
    { name: "State University of Bangladesh", domain: "sub.edu.bd", isVerified: true },
    { name: "Gopalganj Science and Technology University", domain: "gstubd.edu.bd", isVerified: false },
    { name: "Primeasia University", domain: "primeasia.edu.bd", isVerified: true },
    { name: "Sonargaon University", domain: "su.edu.bd", isVerified: true },
    { name: "ASA University Bangladesh", domain: "asaub.edu.bd", isVerified: true },
    { name: "University of Science and Technology Chittagong", domain: "ustc.ac.bd", isVerified: true },
    { name: "Asian University of Bangladesh", domain: "aub.edu.bd", isVerified: true },
    { name: "City University", domain: "cityuniversity.edu.bd", isVerified: true },
    { name: "Eastern University, Bangladesh", domain: "easternuni.edu.bd", isVerified: true },
    { name: "University of Information Technology and Sciences", domain: "uits.edu.bd", isVerified: true },
    { name: "Manarat International University", domain: "manarat.ac.bd", isVerified: true },
    { name: "East Delta University", domain: "eastdelta.edu.bd", isVerified: true },
    { name: "Canadian University of Bangladesh", domain: "cubh.edu.bd", isVerified: true },
    { name: "European University of Bangladesh", domain: "eub.edu.bd", isVerified: true },
    { name: "Bangladesh University", domain: "bu.edu.bd", isVerified: true },
    { name: "Presidency University, Bangladesh", domain: "presidency.edu.bd", isVerified: true },
    { name: "Prime University", domain: "primeuniversity.edu.bd", isVerified: true },
    { name: "Notre Dame University Bangladesh", domain: "ndub.edu.bd", isVerified: true },
    { name: "Metropolitan University", domain: "metrouni.edu.bd", isVerified: true },
    { name: "Shanto Mariam University of Creative Technology", domain: "smuct.edu.bd", isVerified: true },
    { name: "Rajshahi Medical University", domain: "rmu.edu.bd", isVerified: true },
    { name: "Gono Bishwabidyalay", domain: "gub.edu.bd", isVerified: true },
    { name: "Southern University Bangladesh", domain: "southern.edu.bd", isVerified: true },
    { name: "University of Development Alternative", domain: "uoda.edu.bd", isVerified: true },
    { name: "Bangladesh Digital University", domain: "bdu.ac.bd", isVerified: true },
    { name: "Bangladesh University of Health Sciences", domain: "buhs.edu.bd", isVerified: true },
    { name: "Port City International University", domain: "pciu.edu.bd", isVerified: true },
    { name: "Premier University", domain: "premier.edu.bd", isVerified: true },
    { name: "Khwaja Yunus Ali University", domain: "kyu.edu.bd", isVerified: true },
    { name: "BGC Trust University Bangladesh", domain: "bgctub.edu.bd", isVerified: true },
    { name: "North Western University", domain: "nwu.edu.bd", isVerified: true },
    { name: "Bangladesh Islami University", domain: "biu.ac.bd", isVerified: true },
    { name: "Victoria University of Bangladesh", domain: "vub.edu.bd", isVerified: true },
    { name: "Fareast International University", domain: "faiu.edu.bd", isVerified: true },
    { name: "Aviation and Aerospace University, Bangladesh", domain: "aaub.edu.bd", isVerified: true },
    { name: "Rabindra University, Bangladesh", domain: "rabindrauniversity.edu.bd", isVerified: true },
    { name: "Sylhet International University", domain: "siu.edu.bd", isVerified: true },
    { name: "Khulna Khan Bahadur Ahsanullah University", domain: "kkbau.edu.bd", isVerified: true },
    { name: "Atish Dipankar University of Science and Technology", domain: "adust.edu.bd", isVerified: true },
    { name: "University of South Asia, Bangladesh", domain: "usa.edu.bd", isVerified: true },
    { name: "Chittagong Medical University", domain: "cmu.edu.bd", isVerified: true },
    { name: "The Millenium University", domain: "tmu.edu.bd", isVerified: true },
    { name: "Khulna Medical University", domain: "kmu.edu.bd", isVerified: true },
    { name: "Royal University of Dhaka", domain: "royal.edu.bd", isVerified: true },
    { name: "IBAIS University", domain: "ibaisuniv.edu.bd", isVerified: true },
    { name: "Kishoreganj University", domain: "kishoreganjuniv.edu.bd", isVerified: true },
    { name: "Jamalpur Science and Technology University", domain: "jstu.edu.bd", isVerified: true },
    { name: "North East University Bangladesh", domain: "neub.edu.bd", isVerified: true },
    { name: "Ranada Prasad Shaha University", domain: "rpsu.edu.bd", isVerified: true },
    { name: "Sheikh Fazilatunnesa Mujib University", domain: "sfmu.edu.bd", isVerified: true },
    { name: "International Standard University", domain: "isu.ac.bd", isVerified: true },
    { name: "Hamdard University of Bangladesh", domain: "hamdarduniversity.edu.bd", isVerified: true },
    { name: "Pirojpur Science and Technology University", domain: "pstu.edu.bd", isVerified: true },
    { name: "Central Women's University", domain: "cwu.edu.bd", isVerified: true },
    { name: "University of Global Village", domain: "ugv.edu.bd", isVerified: true },
    { name: "Khulna Agricultural University", domain: "kau.edu.bd", isVerified: true },
    { name: "The International University of Scholars", domain: "ius.edu.bd", isVerified: true },
    { name: "Feni University", domain: "feniuniversity.ac.bd", isVerified: true },
    { name: "Hobiganj Agricultural University", domain: "hau.edu.bd", isVerified: true },
    { name: "Rangamati Science and Technology University", domain: "rmstu.edu.bd", isVerified: true },
    { name: "German University Bangladesh", domain: "gub.edu.bd", isVerified: true },
    { name: "Netrokona University", domain: "netrokonauniversity.edu.bd", isVerified: true },
    { name: "Queens University", domain: "queens.edu.bd", isVerified: true },
    { name: "The People's University of Bangladesh", domain: "pub.edu.bd", isVerified: true },
    { name: "Ahsania Mission University of Science and Technology", domain: "amsu.edu.bd", isVerified: true },
    { name: "First Capital University of Bangladesh", domain: "fcu.edu.bd", isVerified: true },
    { name: "Chandpur Science and Technology University", domain: "cstu.edu.bd", isVerified: true },
    { name: "University of Skill Enrichment and Technology", domain: "uset.edu.bd", isVerified: true },
    { name: "Anwer Khan Modern University", domain: "akmu.edu.bd", isVerified: true },
    { name: "Northern University of Business and Technology, Khulna", domain: "nubt.edu.bd", isVerified: true },
    { name: "University of Creative Technology Chittagong", domain: "uctc.edu.bd", isVerified: true },
    { name: "Rabindra Maitree University", domain: "rmu.edu.bd", isVerified: true },
    { name: "Pundra University of Science and Technology", domain: "pust.edu.bd", isVerified: true },
    { name: "Kurigram Agricultural University", domain: null, isVerified: false },
    { name: "Rajshahi Science and Technology University", domain: "rstu.edu.bd", isVerified: true },
    { name: "Bangamata Sheikh Fazilatunnesa Mujib Medical University", domain: null, isVerified: false },
    { name: "University of Brahmanbaria", domain: null, isVerified: false },
    { name: "CCN University of Science and Technology", domain: "ccnust.edu.bd", isVerified: true },
    { name: "North Bengal International University", domain: "nbiu.edu.bd", isVerified: true },
    { name: "Sunamganj Science and Technology University", domain: "sstu.edu.bd", isVerified: true },
    { name: "Exim Bank Agricultural University of Bangladesh", domain: "ebaub.edu.bd", isVerified: true },
    { name: "Central University of Science and Technology", domain: "cust.edu.bd", isVerified: true },
    { name: "Ishakha International University, Bangladesh", domain: "iiub.edu.bd", isVerified: true },
    { name: "Chattogram BGMEA University of Fashion and Technology", domain: "cbgmeaft.edu.bd", isVerified: true },
    { name: "ZNRF University of Management Sciences", domain: "znrfums.edu.bd", isVerified: true },
    { name: "Times University of Bangladesh", domain: "tub.edu.bd", isVerified: true },
    { name: "N.P.I. University of Bangladesh", domain: "npiub.edu.bd", isVerified: true },
    { name: "Dr. Momtaz Begum University of Science and Technology", domain: null, isVerified: false },
    { name: "Trust University, Barishal", domain: "tub.ac.bd", isVerified: true },
    { name: "Tagore University of Creative Arts", domain: "tuca.edu.bd", isVerified: true },
    { name: "Bandarban University", domain: "bandarbanuniversity.edu.bd", isVerified: true },
    { name: "Cox's Bazar International University", domain: "cbiu.ac.bd", isVerified: true },
    { name: "Teesta University", domain: null, isVerified: false },
    { name: "Global University Bangladesh", domain: "globaluniversity.edu.bd", isVerified: true },
    { name: "Z.H. Sikder University of Science and Technology", domain: "zhsust.edu.bd", isVerified: true },
    { name: "Britannia University", domain: "britannia.edu.bd", isVerified: true },
    { name: "International Islami University of Science and Technology", domain: "iiust.edu.bd", isVerified: true },
    { name: "R.T.M. Al-Kabir Technical University", domain: "rtmaktu.edu.bd", isVerified: true },
    { name: "Meherpur University", domain: null, isVerified: false },
    { name: "Naogaon University", domain: null, isVerified: false },
]