import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Belarus_universities = [

    // Belarus

    { name: "Belarusian State University", domain: "bsu.by", isVerified: true },
    { name: "Belarusian National Technical University", domain: "bntu.by", isVerified: true },
    { name: "Belarusian State Medical University", domain: "bsmu.by", isVerified: true },
    { name: "Yanka Kupala State University of Grodno", domain: "grsu.by", isVerified: true },
    { name: "Belarusian State University of Informatics and Radioelectronics", domain: "bsuir.by", isVerified: true },
    { name: "Francisk Skorina Gomel State University", domain: "gsu.by", isVerified: true },
    { name: "Belarusian State Pedagogical University", domain: "bspu.by", isVerified: true },
    { name: "Vitebsk State University", domain: "vsu.by", isVerified: true },
    { name: "Belarusian State Economic University", domain: "bseu.by", isVerified: true },
    { name: "Belarusian State Technological University", domain: "belstu.by", isVerified: true },
    { name: "Polotsk State University", domain: "psu.by", isVerified: true },
    { name: "Grodno State Medical University", domain: "grsmu.by", isVerified: true },
    { name: "Brest State Technical University", domain: "brstu.by", isVerified: true },
    { name: "Vitebsk State Medical University", domain: "vsmu.by", isVerified: true },
    { name: "Vitebsk State Technological University", domain: "vstu.by", isVerified: true },
    { name: "Brest State University", domain: "brsu.by", isVerified: true },
    { name: "Baranovichi State University", domain: "baru.by", isVerified: true },
    { name: "Polessky State University", domain: "polessu.by", isVerified: true },
    { name: "Belarusian State Agricultural Academy", domain: "bsaa.by", isVerified: true },
    { name: "Academy of Public Administration under the President of Belarus", domain: "pac.by", isVerified: true },
    { name: "Minsk State Linguistic University", domain: "mslu.by", isVerified: true },
    { name: "Sukhoi State Technical University of Gomel", domain: "gstu.by", isVerified: true },
    { name: "Mogilev State A. Kuleshov University", domain: "msu.by", isVerified: true },
    { name: "Belarusian-Russian University", domain: "bru.by", isVerified: true },
    { name: "Gomel State Medical University", domain: "gsmu.by", isVerified: true },
    { name: "University of Civil Protection", domain: "ucp.by", isVerified: true },
    { name: "Belarusian State University of Culture and Arts", domain: "buk.by", isVerified: true },
    { name: "Vitebsk State Academy of Veterinary Medicine", domain: "vsavm.by", isVerified: true },
    { name: "Belarusian Trade and Economics University of Consumer Cooperatives", domain: "bteu.by", isVerified: true },
    { name: "Belarusian State Agrarian Technical University", domain: "bsatu.by", isVerified: true },
    { name: "Grodno State Agrarian University", domain: "ggau.by", isVerified: true },
    { name: "Belarusian State University of Physical Culture", domain: "sportedu.by", isVerified: true },
    { name: "Belarusian State University of Transport", domain: "bsut.by", isVerified: true },
    { name: "Academy of the Ministry of Internal Affairs", domain: "amia.by", isVerified: true },
    { name: "International University MITSO", domain: "mitso.by", isVerified: true },
    { name: "Mozyr State Pedagogical University", domain: "mspu.by", isVerified: true },
    { name: "Belarusian State Academy of Music", domain: "bgam.by", isVerified: true },
    { name: "Belarusian State Academy of Communications", domain: "bsac.by", isVerified: true },
    { name: "Belarusian State Academy of Aviation", domain: "bgaa.by", isVerified: true },
    { name: "Belarusian State University of Food and Chemical Technologies", domain: "bgut.by", isVerified: true },
    { name: "BIP – University of Law and Social and Information Technologies", domain: "bip-ip.by", isVerified: true },
    { name: "Belarusian State Academy of Arts", domain: "bdam.by", isVerified: true },
    { name: "University of the National Academy of Sciences of Belarus", domain: "unan.by", isVerified: true },
    { name: "Institute of Parliamentarism and Private Enterprise", domain: "ipp.by", isVerified: true },
    { name: "Institute of Management and Entrepreneurship", domain: "imb.by", isVerified: true },
    { name: "Institute of Modern Knowledge", domain: "isz.minsk.by", isVerified: true },
    { name: "International Humanities and Economics Institute", domain: "mgei.org", isVerified: true },
    { name: "Minsk Innovation University", domain: "miu.by", isVerified: true },
]