import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Belgium_universities = [

    // Belgium

    { name: "Katholieke Universiteit Leuven", domain: "kuleuven.be", isVerified: true },
    { name: "Universiteit Gent", domain: "ugent.be", isVerified: true },
    { name: "Université de Liège", domain: "uliege.be", isVerified: true },
    { name: "Université Catholique de Louvain", domain: "uclouvain.be", isVerified: true },
    { name: "Université Libre de Bruxelles", domain: "ulb.be", isVerified: true },
    { name: "Vrije Universiteit Brussel", domain: "vub.be", isVerified: true },
    { name: "Universiteit Antwerpen", domain: "uantwerpen.be", isVerified: true },
    { name: "Université de Namur", domain: "unamur.be", isVerified: true },
    { name: "Universiteit Hasselt", domain: "uhasselt.be", isVerified: true },
    { name: "Hogeschool Gent", domain: "hogent.be", isVerified: true },
    { name: "Université de Mons", domain: "umons.ac.be", isVerified: true },
    { name: "AP Hogeschool Antwerpen", domain: "ap.be", isVerified: true },
    { name: "Thomas More Hogeschool", domain: "thomasmore.be", isVerified: true },
    { name: "Collège d'Europe", domain: "coleurope.eu", isVerified: true },
    { name: "Instituut voor Tropische Geneeskunde", domain: "itg.be", isVerified: true },
    { name: "VIVES", domain: "vives.be", isVerified: true },
    { name: "Karel de Grote-Hogeschool", domain: "kdg.be", isVerified: true },
    { name: "Arteveldehogeschool", domain: "arteveldehogeschool.be", isVerified: true },
    { name: "Vlerick Business School", domain: "vlerick.com", isVerified: true },
    { name: "UC Leuven-Limburg", domain: "ucll.be", isVerified: true },
    { name: "Hogeschool PXL", domain: "pxl.be", isVerified: true },
    { name: "LUCA School of Arts", domain: "luca-arts.be", isVerified: true },
    { name: "Hogeschool West-Vlaanderen", domain: "howest.be", isVerified: true },
    { name: "Odisee", domain: "odisee.be", isVerified: true },
    { name: "Erasmushogeschool Brussel", domain: "ehb.be", isVerified: true },
    { name: "Université Saint-Louis - Bruxelles", domain: "usaintlouis.be", isVerified: true },
    { name: "Haute École Libre Mosane", domain: "helmo.be", isVerified: true },
    { name: "Conservatoire Royal de Bruxelles", domain: "crb.brussels", isVerified: true },
    { name: "Antwerp Management School", domain: "antwerpmanagementschool.be", isVerified: true },
    { name: "Haute École Léonard de Vinci", domain: "held.be", isVerified: true },
    { name: "Haute École Louvain en Hainaut", domain: "helha.be", isVerified: true },
    { name: "Haute École de Namur-Liège-Luxembourg", domain: "henallux.be", isVerified: true },
    { name: "École Nationale Supérieure des Arts Visuels de La Cambre", domain: "lacambre.be", isVerified: true },
    { name: "Brussels School of Governance", domain: "brussels-school.be", isVerified: true },
    { name: "Haute École Provinciale de Hainaut - Condorcet", domain: "condorcet.be", isVerified: true },
    { name: "Haute École EPHEC", domain: "ephec.be", isVerified: true },
    { name: "Institut Catholique des Hautes Études Commerciales", domain: "ichec.be", isVerified: true },
    { name: "Hogere Zeevaartschool Antwerpen", domain: "hzs.be", isVerified: true },
    { name: "Haute École Bruxelles-Brabant", domain: null, isVerified: false },
    { name: "Haute École Albert Jacquard", domain: "heaj.be", isVerified: true },
    { name: "École de Recherche Graphique", domain: "erg.be", isVerified: true },
    { name: "Haute École Robert Schuman", domain: null, isVerified: false },
    { name: "Evangelische Theologische Faculteit", domain: "evangelische-theologie.be", isVerified: true },
    { name: "ARTS² - École supérieure des Arts", domain: "arts2.be", isVerified: true },
    { name: "Haute École Libre de Bruxelles Ilya Prigogine", domain: "helbprig.be", isVerified: true },
    { name: "Haute École en Hainaut", domain: "heh.be", isVerified: true },
    { name: "Haute École Francisco Ferrer", domain: "ferrer.be", isVerified: true },
    { name: "Institut national supérieur des Arts du Spectacle et des Techniques de Diffusion", domain: "insas.be", isVerified: true },
    { name: "Haute École de la Province de Liège", domain: "hepl.be", isVerified: true },
    { name: "Conservatoire Royal de Liège", domain: "conservatoiredeliege.be", isVerified: true },
    { name: "École Supérieure des Arts Saint-Luc de Liège", domain: "esa-saintluc.be", isVerified: true },
    { name: "Institut des Arts de Diffusion", domain: "iad-artes.be", isVerified: true },
    { name: "Haute École Charlemagne", domain: "he-charlemagne.be", isVerified: true },
    { name: "Institut Supérieur de Musique et de Pédagogie", domain: "ismp.be", isVerified: true },
    { name: "Haute École Lucia de Brouckère", domain: "helb-luciadb.be", isVerified: true },
    { name: "Haute École de la Province de Namur", domain: "hepn.be", isVerified: true },
    { name: "Haute École de la Ville de Liège", domain: "he-vi.be", isVerified: true },
    { name: "Institut Supérieur de Formation Sociale et de Communication", domain: "isfsc.be", isVerified: true },
    { name: "Haute École Galilée", domain: "hegalilee.be", isVerified: true },
    { name: "Institut Saint-Luc Tournai", domain: "stluctournai.be", isVerified: true },
    { name: "Académie des Beaux-Arts de Tournai", domain: "academiedetournai.be", isVerified: true },
    { name: "Beaux-Arts de Liège", domain: "beauxartsdeliege.be", isVerified: true },
    { name: "Instituts Saint-Luc Bruxelles", domain: "institut-saint-luc.brussels", isVerified: true },
]