import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Bolivia_universities = [

   // Bolivia

   { name: "Universidad Mayor de San Simón", domain: "umss.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Mayor de San Andrés", domain: "umsa.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad San Francisco Xavier", domain: "usfx.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Católica Boliviana", domain: "ucb.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Autónoma Gabriel René Moreno", domain: "uagrm.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada Domingo Savio", domain: "upds.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada Boliviana", domain: "upb.edu", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Técnica de Oruro", domain: "uto.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada del Valle", domain: "univalle.edu", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Autónoma Tomás Frías", domain: "uatf.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Nur", domain: "nur.edu", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada de Santa Cruz de la Sierra", domain: "upsa.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Autónoma Juan Misael Saracho", domain: "uajms.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad de Aquino Bolivia", domain: "udabol.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Pública de El Alto", domain: "upea.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Salesiana de Bolivia", domain: "usalesiana.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada Franz Tamayo", domain: "unifranz.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Andina Simón Bolívar", domain: "uasb.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Escuela Militar de Ingeniería", domain: "emi.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Tecnológica Privada de Santa Cruz", domain: "utepsa.edu", region: "South America", country: "Bolivia", isVerified: true },  
   { name: "Universidad Adventista de Bolivia", domain: "uab.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada Abierta Latinoamericana", domain: "upal.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Autónoma del Beni", domain: "uabjb.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Tecnológica Boliviana", domain: "utb.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Cristiana de Bolivia", domain: "ucebol.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada de Ciencias Administrativas y Tecnologicas", domain: "ucatec.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Nuestra Señora de La Paz", domain: "unslp.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Central, Bolivia", domain: "unicen.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Loyola", domain: "loyola.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad La Salle, Bolivia", domain: "ulasalle.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad de los Andes, Bolivia", domain: "udelosandes.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Técnica Privada Cosmos", domain: "unitepc.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada Cumbre", domain: "cumbre.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Amazónica de Pando", domain: "uap.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad San Francisco de Asís", domain: "usfa.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Evangélica Boliviana", domain: "ueb.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Nacional Ecológica", domain: "uecologica.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad para el Desarrollo y la Innovación", domain: "udi.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Unión Bolivariana", domain: "ub.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Nacional de Siglo XX", domain: "unsxx.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Nacional del Oriente", domain: "uno.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Real", domain: "ureal.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Simón I. Patiño", domain: "usip.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad de la Cordillera", domain: "unica.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Bethesda", domain: "unibeth.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Latinoamericana", domain: "ulat.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada de Oruro", domain: "unior.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Boliviana de Informática", domain: "ubi.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Unidad", domain: "uunidad.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad de la Amazonía Boliviana", domain: "unab.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad para la Investigación Estratégica en Bolivia", domain: "upieb.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
   { name: "Universidad Privada del Chaco", domain: "unichaco.edu.bo", region: "South America", country: "Bolivia", isVerified: true },
]