import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Brazil_universities = [

    // Brazil
  
    { name: "Universidade de São Paulo", domain: "usp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Minas Gerais", domain: "ufmg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Campinas", domain: "unicamp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Rio Grande do Sul", domain: "ufrgs.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Rio de Janeiro", domain: "ufrj.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Santa Catarina", domain: "ufsc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual Paulista", domain: "unesp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Brasília", domain: "unb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado do Rio de Janeiro", domain: "uerj.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Paraná", domain: "ufpr.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal da Bahia", domain: "ufba.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica do Rio de Janeiro", domain: "puc‑rio.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Rio Grande do Norte", domain: "ufrn.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal Fluminense", domain: "uff.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Ceará", domain: "ufc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Pernambuco", domain: "ufpe.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Paulista", domain: "unip.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica do Rio Grande do Sul", domain: "pucrs.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal da Paraíba", domain: "ufpb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de São Carlos", domain: "ufscar.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Goiás", domain: "ufg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Uberlândia", domain: "ufu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de São Paulo", domain: "unifesp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Santa Maria", domain: "ufsm.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Espírito Santo", domain: "ufes.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Juiz de Fora", domain: "ufjf.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Maringá", domain: "uem.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Pelotas", domain: "ufpel.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Vale do Rio dos Sinos", domain: "unisinos.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Pará", domain: "ufpa.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica de São Paulo", domain: "pucsp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estácio de Sá", domain: "estacio.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica de Minas Gerais", domain: "pucminas.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Tecnológica Federal do Paraná", domain: "utfpr.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica do Paraná", domain: "pucpr.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Viçosa", domain: "ufv.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Presbiteriana Mackenzie", domain: "mackenzie.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Alagoas", domain: ".ufal.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Mato Grosso do Sul", domain: "ufms.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Norte do Paraná", domain: "unopar.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Maranhão", domain: "ufma.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Londrina", domain: "uel.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Cruzeiro do Sul", domain: "cruzeirodosul.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Nove de Julho", domain: "uninove.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Amazonas", domain: "ufam.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Evangélica de Goiás", domain: "ueg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Campina Grande", domain: "ufcg.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Lavras", domain: "ufla.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Mato Grosso", domain: "ufmt.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do ABC", domain: "ufabc.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Ouro Preto", domain: "ufop.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado de Santa Catarina", domain: "udesc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Sergipe", domain: "ufs.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Piauí", domain: "ufpi.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Ponta Grossa", domain: "uepg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Ceará", domain: "uece.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Rio Grande", domain: "furg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual da Paraíba", domain: "uepb.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal Rural do Rio de Janeiro", domain: "ufrrj.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Maranhão", domain: "uema.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado da Bahia", domain: "uneb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Estado do Rio de Janeiro", domain: "unirio.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Oeste do Paraná", domain: "unioeste.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Fortaleza", domain: "unifor.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica de Goiás", domain: "pucgoias.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Vale do Itajaí", domain: "univali.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de São João Del Rei", domain: "ufsj.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Santa Cruz do Sul", domain: "unisc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal Rural de Pernambuco", domain: "ufrpe.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Caxias do Sul", domain: "ucs.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Montes Claros", domain: "unimontes.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Acre", domain: "ufac.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Metodista de São Paulo", domain: "metodista.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Cesumar", domain: "unicesumar.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal Rural do Semi-Árido", domain: "ufersa.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal da Grande Dourados", domain: "ufgd.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado de Minas Gerais", domain: "uemg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Pontifícia Universidade Católica de Campinas", domain: "puc-campinas.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Passo Fundo", domain: "upf.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Roraima", domain: "ufrr.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Tocantins", domain: "uft.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Itajubá", domain: "unifei.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Feira de Santana", domain: "uefs.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Recôncavo da Bahia", domain: "ufrb.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Anhembi Morumbi", domain: "anhembi.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado do Pará", domain: "uepa.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Pernambuco", domain: "upe.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Sudoeste da Bahia", domain: "uesb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Uberaba", domain: "uniube.br", region: "South America", country: "Brazil", isVerified: true },         
    { name: "Universidade Federal dos Vales do Jequitinhonha e Mucuri", domain: "ufvjm.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Goiás", domain: "ueg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Amapá", domain: "unifap.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado de Mato Grosso", domain: "unemat.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica de Pernambuco", domain: "unicap.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade São Francisco", domain: "usf.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Pampa", domain: "unipampa.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Centro‑Oeste", domain: "uecg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado do Rio Grande do Norte", domain: "uern.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Santa Cruz", domain: "uesc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Regional de Blumenau", domain: "furb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica de Brasília", domain: "ucb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Rondônia", domain: "unir.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Oeste Paulista", domain: "unoeste.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Oeste de Santa Catarina", domain: "unoesc.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Santa Cecília", domain: "unisanta.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade da Amazônia", domain: "unama.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Vale do São Francisco", domain: "univasf.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal da Integração Latino-Americana", domain: "unila.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Sul de Santa Catarina", domain: "unisul.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal da Fronteira Sul", domain: "uffs.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado do Amazonas", domain: "uea.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Paraná", domain: "uepg.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Luterana do Brasil", domain: "ulbra.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Veiga de Almeida", domain: "uva.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Piauí", domain: "uespi.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Alfenas", domain: "unifal.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade La Salle", domain: "lasalle.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Salvador", domain: "unifacs.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Paranaense", domain: "unipar.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Oeste do Pará", domain: "ufopa.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Extremo Sul Catarinense", domain: "unesc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Vale do Taquari", domain: "univates.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Mato Grosso do Sul", domain: "uems.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal Rural da Amazônia", domain: "ufra.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Triângulo Mineiro", domain: "uftm.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Santo Amaro", domain: "unisa.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Vale do Paraíba", domain: "univap.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Tiradentes", domain: "unit.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Taubaté", domain: "unitau.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Feevale", domain: "feevale.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade São Judas Tadeu", domain: "usjt.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade da Integração Internacional da Lusofonia Afro-Brasileira", domain: "unilab.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Regional do Noroeste do Estado do Rio Grande do Sul", domain: "unijui.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica Dom Bosco", domain: "ucdb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Tocantins", domain: "unitins.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Cariri", domain: "ufca.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade FUMEC", domain: "fumec.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica de Santos", domain: "unisantos.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Comunitária da Região de Chapecó", domain: "unochapeco.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Vila Velha", domain: "uvv.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Norte do Paraná", domain: "uenp.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Sul e Sudeste do Pará", domain: "unifesspa.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Regional do Cariri", domain: "urca.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Norte Fluminense Darcy Ribeiro", domain: "uenf.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Marília", domain: "unimar.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Ciências da Saúde de Porto Alegre", domain: "ufcspa.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Municipal de São Caetano do Sul", domain: "uscs.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Sorocaba", domain: "uniso.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Cidade de São Paulo", domain: "unicid.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Positivo", domain: "up.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Universus Veritas Guarulhos", domain: "ung.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Regional Integrada do Alto Uruguai e das Missões", domain: "uri.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica do Salvador", domain: "ucsal.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Salgado de Oliveira", domain: "universo.edu.br", region: "South America", country: "Brazil", isVerified: true },                   
    { name: "Universidade Potiguar", domain: "unP.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Vassouras", domain: "univassouras.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Sul da Bahia", domain: "ufsb.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Ribeirão Preto", domain: "unaerp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Cuiabá", domain: "unic.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Oeste da Bahia", domain: "ufob.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade da Região de Joinville", domain: "univille.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Tuiuti do Paraná", domain: "utp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade José do Rosário Vellano", domain: "unifenas.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Metodista de Piracicaba", domain: "unimep.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual do Rio Grande do Sul", domain: "uers.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica de Pelotas", domain: "ucpel.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Franca", domain: "unifran.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual Vale do Acaraú", domain: "uva.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Contestado", domain: "unc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Católica de Petrópolis", domain: "ucp.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Cândido Mendes", domain: "ucam.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Franciscana", domain: "ufn.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Rio Verde", domain: "unirv.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Mogi das Cruzes", domain: "umc.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Gurupi", domain: "unirg.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Anhanguera-Uniderp", domain: "anhanguera.com", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Grande Rio", domain: "unigranrio.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Roraima", domain: "uerr.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Araraquara", domain: "uniara.com.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Ciências da Saúde de Alagoas", domain: "uncisal.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Ceuma", domain: "ceuma.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Estadual de Alagoas", domain: "uneal.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Rondonópolis", domain: "ufr.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade de Cruz Alta", domain: "unicruz.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Castelo Branco", domain: "ucb.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Metropolitana de Santos", domain: "unimes.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Alto Vale do Rio do Peixe", domain: "uniarp.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Planalto Catarinense", domain: "uniplac.net", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Agreste de Pernambuco", domain: "ufape.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Iguaçu", domain: "unig.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Vale do Sapucaí", domain: "univassouras.edu.br", region: "South America", country: "Brazil", isVerified: false },
    { name: "Universidade Estadual da Região Tocantina do Maranhão", domain: "uertm.edu.br", region: "South America", country: "Brazil", isVerified: false },
    { name: "Universidade Vale do Rio Doce", domain: "univale.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Brasil", domain: "universidadebrasil.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Ibirapuera", domain: "ibirapuera.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade do Estado do Amapá", domain: "ueap.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal do Delta do Parnaíba", domain: "ufdpb.edu.br", region: "South America", country: "Brazil", isVerified: false },
    { name: "Universidade de Itaúna", domain: "uit.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Nilton Lins", domain: "niltonlins.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Catalão", domain: "ufcat.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Santa Úrsula", domain: "usu.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Federal de Jataí", domain: "ufj.edu.br", region: "South America", country: "Brazil", isVerified: true },
    { name: "Universidade Anhanguera de São Paulo", domain: "anhanguera.com", region: "South America", country: "Brazil", isVerified: true },

]