import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Bulgaria_universities = [

    // Bulgaria

    { name: "Sofia University St. Kliment Ohridski", domain: "uni-sofia.bg", isVerified: true },
    { name: "New Bulgarian University", domain: "nbu.bg", isVerified: true },
    { name: "Technical University of Sofia", domain: "tu-sofia.bg", isVerified: true },
    { name: "Varna Free University \"Chernorizets Hrabar\"", domain: "vfu.bg", isVerified: true },
    { name: "University of Plovdiv Paisii Hilendarski", domain: "uni-plovdiv.bg", isVerified: true },
    { name: "Angel Kanchev University of Ruse", domain: "uni-ruse.bg", isVerified: true },
    { name: "St. Cyril and St. Methodius University of Veliko Tarnovo", domain: "uni-vt.bg", isVerified: true },
    { name: "American University in Bulgaria", domain: "aubg.edu", isVerified: true },
    { name: "University of National and World Economy", domain: "unwe.bg", isVerified: true },
    { name: "Medical University-Varna", domain: "mu-varna.bg", isVerified: true },
    { name: "University of Economics - Varna", domain: "ue-varna.bg", isVerified: true },
    { name: "South-West University \"Neofit Rilski\"", domain: "swu.bg", isVerified: true },
    { name: "Trakia University", domain: "uni-sz.bg", isVerified: true },
    { name: "D.A. Tsenov Academy of Economics", domain: "uni-svishtov.bg", isVerified: true },
    { name: "Medical University - Sofia", domain: "mu-sofia.bg", isVerified: true },
    { name: "University of Chemical Technology and Metallurgy", domain: "uctm.edu", isVerified: true },
    { name: "Technical University - Varna", domain: "tu-varna.bg", isVerified: true },
    { name: "University of Architecture, Civil Engineering and Geodesy", domain: "uacg.bg", isVerified: true },
    { name: "Konstantin Preslavsky University of Shumen", domain: "shu.bg", isVerified: true },
    { name: "Varna University of Management", domain: "vum.bg", isVerified: true },
    { name: "Medical University of Plovdiv", domain: "mu-plovdiv.bg", isVerified: true },
    { name: "Burgas Free University", domain: "bfu.bg", isVerified: true },
    { name: "University of Mining and Geology St Ivan Rilski", domain: "mgu.bg", isVerified: true },
    { name: "Technical University of Gabrovo", domain: "tugab.bg", isVerified: true },
    { name: "Agricultural University of Plovdiv", domain: "au-plovdiv.bg", isVerified: true },
    { name: "National Sports Academy Vasil Levski", domain: "nsa.bg", isVerified: true },
    { name: "National Academy of Arts", domain: "nhaa.bg", isVerified: true },
    { name: "Medical University - Pleven", domain: "mu-pleven.bg", isVerified: true },
    { name: "Nikola Vaptsarov Naval Academy", domain: "nvna.bg", isVerified: true },
    { name: "Higher School of Insurance and Finance", domain: "vuzf.bg", isVerified: true },
    { name: "University of Forestry", domain: "ltu.bg", isVerified: true },
    { name: "National Military University \"Vasil Levski\"", domain: "nvu.bg", isVerified: true },
    { name: "University of Food Technologies", domain: "uft-plovdiv.bg", isVerified: true },
    { name: "University of Library Studies and Information Technologies", domain: "unibit.bg", isVerified: true },
    { name: "University Prof. Dr. Assen Zlatarov", domain: "btu.bg", isVerified: true },
    { name: "Krastyo Sarafov National Academy for Theatre and Film Arts", domain: "natfiz.bg", isVerified: true },
    { name: "University of Transport Todor Kableshkov", domain: "vtu.bg", isVerified: true },
    { name: "National Academy of Music \"Pancho Vladigerov\"", domain: "nma.bg", isVerified: true },
    { name: "International Business School of Bulgaria", domain: "ibsedu.bg", isVerified: true },
    { name: "Academy of Music, Dance and Fine Arts", domain: "amdfa.bg", isVerified: true },
    { name: "Lyuben Karavelov University of Applied Sciences", domain: "vsu.bg", isVerified: true },
    { name: "University of Agribusiness and Rural Development", domain: "uard.bg", isVerified: true },
    { name: "University of Telecommunications and Post", domain: "utp.bg", isVerified: true },
    { name: "European Polytechnical University", domain: "epu.bg", isVerified: true },
    { name: "European Graduate School of Economics and Management", domain: null, isVerified: false },
    { name: "University of Security and Economics", domain: null, isVerified: false },
    { name: "MT&M College", domain: "mtmcollege.bg", isVerified: true },
    { name: "College of Tourism Blagoevgrad", domain: null, isVerified: false }, 
]