import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Cambodia_universities = [

    // Cambodia

    { name: "Royal University of Phnom Penh", domain: "rupp.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Institute of Technology of Cambodia", domain: "itc.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Paññāsāstra University of Cambodia", domain: "puc.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National University of Battambang", domain: "nub.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Paragon International University", domain: "paragoniu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Royal University of Agriculture", domain: "rua.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "The University of Cambodia", domain: "uc.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National University of Management", domain: "num.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Royal University of Fine Arts", domain: "rupa.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "University of Puthisastra", domain: "puthisastra.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Norton University", domain: "norton-u.com", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "American University of Phnom Penh", domain: "aupp.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Royal Academy of Cambodia", domain: "rac.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Royal University of Law and Economics", domain: "rule.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Université des Sciences de la Santé", domain: "uss.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Build Bright University", domain: "bbu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National Polytechnic Institute of Cambodia", domain: "npic.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Cambodian Mekong University", domain: "cmu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "CamEd Business School", domain: "cam-ed.com", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "International University", domain: "iu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Asia Euro University", domain: "aeu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Svay Rieng University", domain: "sru.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Phnom Penh International University", domain: "ppiu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "IIC University of Technology", domain: "iic.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "École Royale d'Administration", domain: "era.gov.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "University of Management and Economics", domain: "ume.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National Meanchey University", domain: "nmu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Angkor University", domain: "angkor.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "East Asia Management University", domain: "eamc.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National University of CheaSim Kamchaymear", domain: "nuck.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "University of Southeast Asia", domain: "usea.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National Institute of Education", domain: "nie.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Prek Leap National Institute of Agriculture", domain: "prekleap.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Cambodia University for Specialties", domain: "cus.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Life University, Cambodia", domain: "life.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Vanda Institute", domain: "vanda.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Dewey International University", domain: "diu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Human Resources University", domain: "hru.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Panha Chiet University", domain: "pcu.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Preah Sihanouk Raja Buddhist University", domain: "psrb.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Western University, Cambodia", domain: "western.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Chenla University", domain: "chenla.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "National Institute of Business", domain: "nib.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Economics and Finance Institute", domain: "efi.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Khemarak University", domain: "khemarak.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Kampong Cham National Institute of Agriculture", domain: "kcna.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Beltei International University", domain: "beltei.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Angkor Khemara University", domain: "aku.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },
    { name: "Limkokwing University of Creative Technology, Cambodia", domain: "limkokwing.edu.kh", region: "Asia", country: "Cambodia", isVerified: true },  
]