import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Canada_universities = [
    
 // Canada

 { name: "Memorial University of Newfoundland", domain: "mun.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Prince Edward Island", domain: "upei.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Acadia University", domain: "acadiau.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Acadia Divinity College", domain: "divinity.acadiau.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Atlantic School of Theology", domain: "astheology.ns.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Cape Breton University", domain: "capebreton.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Dalhousie University", domain: "dal.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of King's College", domain: "ukings.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Mount Saint Vincent University", domain: "msvu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Nova Scotia College of Art and Design University", domain: "nscad.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université Sainte-Anne", domain: "usainteanne.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "St. Francis Xavier University", domain: "stfx.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Saint Mary's University", domain: "smu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Mount Allison University", domain: "mountallison.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of New Brunswick", domain: "unb.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université de Moncton", domain: "umoncton.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "St. Thomas University", domain: "stu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Bishop's University", domain: "ubishops.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "McGill University", domain: "mcgill.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université de Montréal", domain: "umontreal.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Polytechnique Montréal", domain: "polymtl.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "École des hautes études commerciales", domain: "hec.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université Laval", domain: "ulaval.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université de Sherbrooke", domain: "usherbrooke.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Concordia University", domain: "concordia.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université du Québec à Chicoutimi", domain: "uqac.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université du Québec à Montréal", domain: "uqam.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université du Québec en Abitibi-Témiscamingue", domain: "uqat.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université du Québec à Trois-Rivières", domain: "uqtr.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université du Québec en Outaouais", domain: "uqo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "ENAP (Université du Québec)", domain: "enap.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "INRS (Université du Québec)", domain: "inrs.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université du Québec à Rimouski", domain: "uqar.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "ÉTS (Université du Québec)", domain: "etsmtl.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "TÉLUQ (Université du Québec)", domain: "teluq.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Brock University", domain: "brocku.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Concordia Lutheran Theological Seminary", domain: "clts.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Carleton University", domain: "carleton.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Dominican University College", domain: "duc.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Guelph", domain: "uoguelph.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Lakehead University", domain: "lakeheadu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Laurentian University", domain: "laurentian.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "McMaster University", domain: "mcmaster.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Nipissing University", domain: "nipissingu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Ottawa", domain: "uottawa.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Saint-Paul University", domain: "ustpaul.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Queen's University", domain: "queensu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Ryerson University", domain: "ryerson.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Toronto", domain: "utoronto.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "St. Augustine's Seminary", domain: "staugustines.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of St. Michael's College", domain: "smc.utoronto.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Trinity College", domain: "trinity.utoronto.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Victoria University", domain: "vic.utoronto.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Knox College", domain: "knox.utoronto.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Wycliffe College", domain: "wycliffe.utoronto.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Regis College", domain: "regiscollege.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Trent University", domain: "trentu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Waterloo", domain: "uwaterloo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "St. Jerome's University", domain: "sju.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Renison University College", domain: "renison.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Conrad Grebel University College", domain: "grebel.uwaterloo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Western Ontario", domain: "uwo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Brescia University College", domain: "brescia.uwo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Huron University College", domain: "huron.uwo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "King's University College", domain: "kings.uwo.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Wilfrid Laurier University", domain: "wlu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Windsor", domain: "uwindsor.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "York University", domain: "yorku.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Ontario College of Art and Design University", domain: "ocadu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Ontario Tech University", domain: "ontariotechu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Algoma University", domain: "algomau.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Sudbury", domain: "usudbury.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université de Hearst", domain: "uhearst.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Huntingdon University", domain: "huntingdonuniversity.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Thorneloe University", domain: "thorneloe.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Brandon University", domain: "brandonu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Canadian Mennonite University", domain: "cmu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Manitoba", domain: "umanitoba.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Université de Saint-Boniface", domain: "ustboniface.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Winnipeg", domain: "uwinnipeg.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Regina", domain: "uregina.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Campion College", domain: "campioncollege.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Luther College", domain: "luthercollege.edu", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Saskatchewan", domain: "usask.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "College of Emmanuel and St. Chad", domain: null, region: "North America", country: "Canada", isVerified: false },
 { name: "Lutheran Theological Seminary", domain: null, region: "North America", country: "Canada", isVerified: false },
 { name: "St. Andrew's College", domain: "standrews.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "St. Thomas More College", domain: "stmcollege.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Horizon College & Seminary", domain: null, region: "North America", country: "Canada", isVerified: false },
 { name: "University of Alberta", domain: "ualberta.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Athabasca University", domain: "athabascau.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Calgary", domain: "ucalgary.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Burman University", domain: "burmanu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Concordia University of Edmonton", domain: "concordia.ab.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Lethbridge", domain: "uleth.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "The King's University", domain: "kingsu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Ambrose University", domain: "ambrose.edu", region: "North America", country: "Canada", isVerified: true },
 { name: "MacEwan University", domain: "macewan.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Mount Royal University", domain: "mtroyal.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of British Columbia", domain: "ubc.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Northern British Columbia", domain: "unbc.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Royal Roads University", domain: "royalroads.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Simon Fraser University", domain: "sfu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Victoria", domain: "uvic.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Thompson Rivers University", domain: "tru.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Capilano University", domain: "capilanou.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Vancouver Island University", domain: "viu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Emily Carr University of Art and Design", domain: "ecuad.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Kwantlen Polytechnic University", domain: "kpu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of the Fraser Valley", domain: "ufv.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Yukon University", domain: "yukonu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Royal Military College of Canada", domain: "rmc-cmr.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Booth University College", domain: "boothuc.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Crandall University", domain: "crandallu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Kingswood University", domain: "kingswood.edu", region: "North America", country: "Canada", isVerified: true },
 { name: "Pacific Coast University for Workplace Health Sciences", domain: "pcu-whs.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Providence University College and Theological Seminary", domain: "providencecollege.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Redeemer University", domain: "redeemer.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "St. Stephen’s University", domain: "ssu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Trinity Western University", domain: "twu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Tyndale University", domain: "tyndale.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University Canada West", domain: "ucanwest.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Fredericton", domain: "universityfredericton.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University of Niagara Falls Canada", domain: "universityniagarafalls.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Yorkville University", domain: "yorkvilleu.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "University College of the North", domain: "ucn.ca", region: "North America", country: "Canada", isVerified: true },
 { name: "Collège universitaire de Saint-Boniface", domain: null, region: "North America", country: "Canada", isVerified: false },

]