import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Chile_universities = [

   // Chile

   { name: "Universidad de Chile", domain: "uchile.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Pontificia Universidad Católica de Chile", domain: "puc.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Concepción", domain: "udec.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Técnica Federico Santa María", domain: "usm.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Santiago de Chile", domain: "usach.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Pontificia Universidad Católica de Valparaíso", domain: "pucv.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Andrés Bello", domain: "unab.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Austral de Chile", domain: "uach.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Diego Portales", domain: "udp.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Talca", domain: "utalca.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad del Desarrollo", domain: "udd.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Adolfo Ibañez", domain: "uai.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de La Frontera", domain: "ufro.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Valparaíso", domain: "uv.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Tecnológica de Chile INACAP", domain: "inacap.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Católica del Norte", domain: "ucn.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad del Bío-Bío", domain: "ubb.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Alberto Hurtado", domain: "uahurtado.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Mayor", domain: "umayor.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Autónoma de Chile", domain: "uautonoma.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad San Sebastián", domain: "uss.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Católica de Temuco", domain: "uctemuco.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de los Andes, Chile", domain: "uandes.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Tarapacá", domain: "uta.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de los Lagos", domain: "ulagos.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Tecnológica Metropolitana", domain: "utem.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Central de Chile", domain: "ucentral.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Católica de la Santísima Concepción", domain: "ucsc.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Católica del Maule", domain: "ucm.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Finis Terrae", domain: "uft.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Playa Ancha de Ciencias de la Educacion", domain: "upla.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Magallanes", domain: "umag.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Las Américas", domain: "udla.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Metropolitana de Ciencias de la Educación", domain: "umce.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de La Serena", domain: "userena.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Antofagasta", domain: "uantof.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Atacama", domain: "uda.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Academia de Humanismo Cristiano", domain: "uahc.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Arturo Prat", domain: "unap.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Viña del Mar", domain: "uvm.cl", region: "South America", country: "Chile", isVerified: true },    
   { name: "Universidad Santo Tomás, Chile", domain: "ust.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Católica Silva Henriquez", domain: "ucsh.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Bernardo O'Higgins", domain: "ubo.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Gabriela Mistral", domain: "ugm.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Artes, Ciencias y Comunicación", domain: "arcis.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de O'Higgins", domain: "uoh.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Aysén", domain: "uaysen.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad del Alba", domain: null, region: "South America", country: "Chile", isVerified: false },
   { name: "Universidad Adventista de Chile", domain: "uach.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad SEK", domain: "sek.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad de Aconcagua", domain: "uac.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad La República", domain: "urep.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Bolivariana", domain: "ubolivariana.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Miguel de Cervantes", domain: "umc.cl", region: "South America", country: "Chile", isVerified: true },
   { name: "Universidad Los Leones", domain: "unileones.cl", region: "South America", country: "Chile", isVerified: true },  
]