import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const China_universities = [

    // China

    { name: "Peking University", domain: "pku.edu.cn", isVerified: true },
    { name: "Tsinghua University", domain: "tsinghua.edu.cn", isVerified: true },
    { name: "Zhejiang University", domain: "zju.edu.cn", isVerified: true },
    { name: "Shanghai Jiao Tong University", domain: "sjtu.edu.cn", isVerified: true },
    { name: "Fudan University", domain: "fudan.edu.cn", isVerified: true },
    { name: "University of Science and Technology of China", domain: "ustc.edu.cn", isVerified: true },
    { name: "Nanjing University", domain: "nju.edu.cn", isVerified: true },
    { name: "Wuhan University", domain: "whu.edu.cn", isVerified: true },
    { name: "Xiamen University", domain: "xmu.edu.cn", isVerified: true },
    { name: "Renmin University of China", domain: "ruc.edu.cn", isVerified: true },
    { name: "Shandong University", domain: "sdu.edu.cn", isVerified: true },
    { name: "Xi'an Jiaotong University", domain: "xjtu.edu.cn", isVerified: true },
    { name: "Huazhong University of Science and Technology", domain: "hust.edu.cn", isVerified: true },
    { name: "Tongji University", domain: "tongji.edu.cn", isVerified: true },
    { name: "Sun Yat-Sen University", domain: "sysu.edu.cn", isVerified: true },
    { name: "Beijing Normal University", domain: "bnu.edu.cn", isVerified: true },
    { name: "Beihang University", domain: "buaa.edu.cn", isVerified: true },
    { name: "Harbin Institute of Technology", domain: "hit.edu.cn", isVerified: true },
    { name: "Tianjin University", domain: "tju.edu.cn", isVerified: true },
    { name: "Southeast University", domain: "seu.edu.cn", isVerified: true },
    { name: "East China Normal University", domain: "ecnu.edu.cn", isVerified: true },
    { name: "Nankai University", domain: "nankai.edu.cn", isVerified: true },
    { name: "Jilin University", domain: "jlu.edu.cn", isVerified: true },
    { name: "Beijing Institute of Technology", domain: "bit.edu.cn", isVerified: true },
    { name: "Chongqing University", domain: "cqu.edu.cn", isVerified: true },
    { name: "Central South University", domain: "csu.edu.cn", isVerified: true },
    { name: "University of Electronic Science and Technology of China", domain: "uestc.edu.cn", isVerified: true },
    { name: "Sichuan University", domain: "scu.edu.cn", isVerified: true },
    { name: "Dalian University of Technology", domain: "dlut.edu.cn", isVerified: true },
    { name: "Lanzhou University", domain: "lzu.edu.cn", isVerified: true },
    { name: "Shenzhen University", domain: "szu.edu.cn", isVerified: true },
    { name: "Shanghai University", domain: "shu.edu.cn", isVerified: true },
    { name: "University of the Chinese Academy of Sciences", domain: "ucas.ac.cn", isVerified: true },
    { name: "Northwestern Polytechnical University", domain: "nwpu.edu.cn", isVerified: true },
    { name: "Beijing Jiaotong University", domain: "bjtu.edu.cn", isVerified: true },
    { name: "South China University of Technology", domain: "scut.edu.cn", isVerified: true },
    { name: "Xidian University", domain: "xidian.edu.cn", isVerified: true },
    { name: "China Agricultural University", domain: "cau.edu.cn", isVerified: true },
    { name: "Southwest Jiaotong University", domain: "swjtu.edu.cn", isVerified: true },
    { name: "Southern University of Science and Technology", domain: "sustech.edu.cn", isVerified: true },
    { name: "Zhengzhou University", domain: "zzu.edu.cn", isVerified: true },
    { name: "University of Science and Technology Beijing", domain: "ustb.edu.cn", isVerified: true },
    { name: "Soochow University", domain: "suda.edu.cn", isVerified: true },
    { name: "Shanghai University of Finance and Economics", domain: "shufe.edu.cn", isVerified: true },
    { name: "Hunan University", domain: "hnu.edu.cn", isVerified: true },
    { name: "Beijing Foreign Studies University", domain: "bfsu.edu.cn", isVerified: true },
    { name: "Jinan University", domain: "jnu.edu.cn", isVerified: true },
    { name: "Central China Normal University", domain: "ccnu.edu.cn", isVerified: true },
    { name: "Northeastern University", domain: "neu.edu.cn", isVerified: true },
    { name: "Nanjing University of Aeronautics and Astronautics", domain: "nuaa.edu.cn", isVerified: true },
    { name: "Hefei University of Technology", domain: "hfut.edu.cn", isVerified: true },
    { name: "East China University of Science and Technology", domain: "ecust.edu.cn", isVerified: true },
    { name: "Nanjing Agricultural University", domain: "njau.edu.cn", isVerified: true },
    { name: "South China Normal University", domain: "scnu.edu.cn", isVerified: true },
    { name: "Wuhan University of Technology", domain: "whut.edu.cn", isVerified: true },
    { name: "Southwestern University of Finance and Economics", domain: "swufe.edu.cn", isVerified: true },
    { name: "Shanghai International Studies University", domain: "shisu.edu.cn", isVerified: true },
    { name: "Southwest University", domain: "swu.edu.cn", isVerified: true },
    { name: "Xi'an Jiaotong-Liverpool University", domain: "xjtlu.edu.cn", isVerified: true },
    { name: "Beijing University of Posts and Telecommunications", domain: "bupt.edu.cn", isVerified: true },
    { name: "China University of Geosciences Wuhan", domain: "cug.edu.cn", isVerified: true },
    { name: "Northwest A&F University", domain: "nwafu.edu.cn", isVerified: true },
    { name: "Chang'an University", domain: "chd.edu.cn", isVerified: true },
    { name: "Donghua University", domain: "dhu.edu.cn", isVerified: true },
    { name: "Huazhong Agricultural University", domain: "hzau.edu.cn", isVerified: true },
    { name: "Communication University of China", domain: "cuc.edu.cn", isVerified: true },
    { name: "Ocean University of China", domain: "ouc.edu.cn", isVerified: true },
    { name: "Nanjing Normal University", domain: "njnu.edu.cn", isVerified: true },
    { name: "South China Agricultural University", domain: "scau.edu.cn", isVerified: true },
    { name: "China University of Political Science and Law", domain: "cupl.edu.cn", isVerified: true },
    { name: "University of Shanghai for Science and Technology", domain: "usst.edu.cn", isVerified: true },
    { name: "Fuzhou University", domain: "fzu.edu.cn", isVerified: true },
    { name: "China University of Mining and Technology", domain: "cumt.edu.cn", isVerified: true },        
    { name: "Hohai University", domain: "hhu.edu.cn", isVerified: true },
    { name: "Dongbei University of Finance and Economics", domain: "dufe.edu.cn", isVerified: true },
    { name: "Northeast Normal University", domain: "nenu.edu.cn", isVerified: true },
    { name: "Beijing University of Chemical Technology", domain: "buct.edu.cn", isVerified: true },
    { name: "Anhui University", domain: "ahu.edu.cn", isVerified: true },
    { name: "Harbin Engineering University", domain: "hrbeu.edu.cn", isVerified: true },
    { name: "Zhongnan University of Economics and Law", domain: "znufe.edu.cn", isVerified: true },
    { name: "Hunan Normal University", domain: "hunnu.edu.cn", isVerified: true },
    { name: "The Chinese University of Hong Kong, Shenzhen", domain: "cuhk.edu.cn", isVerified: true },
    { name: "Yunnan University", domain: "ynu.edu.cn", isVerified: true },
    { name: "Beijing Language and Culture University", domain: "blcu.edu.cn", isVerified: true },
    { name: "Northwest University", domain: "nwu.edu.cn", isVerified: true },
    { name: "Nanjing University of Science and Technology", domain: "njust.edu.cn", isVerified: true },
    { name: "Henan University", domain: "ha.edu.cn", isVerified: true },
    { name: "Guangdong University of Technology", domain: "gdut.edu.cn", isVerified: true },
    { name: "North China Electric Power University", domain: "ncepu.edu.cn", isVerified: true },
    { name: "Shanxi University", domain: "sxu.edu.cn", isVerified: true },
    { name: "Shaanxi Normal University", domain: "snnu.edu.cn", isVerified: true },
    { name: "Jiangsu University", domain: "ujs.edu.cn", isVerified: true },
    { name: "Qingdao University", domain: "qdu.edu.cn", isVerified: true },
    { name: "Guangdong University of Foreign Studies", domain: "gdufs.edu.cn", isVerified: true },
    { name: "ShanghaiTech University", domain: "shanghaitech.edu.cn", isVerified: true },
    { name: "Taiyuan University of Technology", domain: "tyut.edu.cn", isVerified: true },
    { name: "Beijing University of Technology", domain: "bjut.edu.cn", isVerified: true },
    { name: "Central University of Finance and Economics", domain: "cufe.edu.cn", isVerified: true },
    { name: "Zhejiang University of Technology", domain: "zjut.edu.cn", isVerified: true },
    { name: "University of International Business and Economics", domain: "uibe.edu.cn", isVerified: true },
    { name: "Huaqiao University", domain: "hqu.edu.cn", isVerified: true },
    { name: "Northeast Forestry University", domain: "nefu.edu.cn", isVerified: true },
    { name: "Jiangnan University", domain: "jiangnan.edu.cn", isVerified: true },
    { name: "Nanchang University", domain: "ncu.edu.cn", isVerified: true },
    { name: "Dalian Maritime University", domain: "dlmu.edu.cn", isVerified: true },
    { name: "China University of Petroleum", domain: "upc.edu.cn", isVerified: true },
    { name: "Nanjing Medical University", domain: "njmu.edu.cn", isVerified: true },
    { name: "Guangxi University", domain: "guet.edu.cn", isVerified: true },
    { name: "China Europe International Business School", domain: "ceibs.edu", isVerified: true },
    { name: "Hangzhou Dianzi University", domain: "hdu.edu.cn", isVerified: true },
    { name: "National University of Defense Technology", domain: "nudt.edu.cn", isVerified: true },
    { name: "Shanghai Normal University", domain: "shnu.edu.cn", isVerified: true },
    { name: "Capital Normal University", domain: "cnu.edu.cn", isVerified: true },
    { name: "Hainan University", domain: "hainan.edu.cn", isVerified: true },
    { name: "Guangzhou University", domain: "gzhu.edu.cn", isVerified: true },
    { name: "Yangzhou University", domain: "yzu.edu.cn", isVerified: true },
    { name: "Beijing University of Chinese Medicine", domain: "bucm.edu.cn", isVerified: true },
    { name: "Shantou University", domain: "stu.edu.cn", isVerified: true },
    { name: "Nanjing University of Information Science and Technology", domain: "nuist.edu.cn", isVerified: true },
    { name: "Anhui University of Science and Technology", domain: "aust.edu.cn", isVerified: true },
    { name: "Hebei Normal University", domain: "hebmu.edu.cn", isVerified: true },
    { name: "Central Conservatory of Music", domain: "ccom.edu.cn", isVerified: true },
    { name: "Liaoning University", domain: "lnu.edu.cn", isVerified: true },
    { name: "Inner Mongolia University", domain: "imu.edu.cn", isVerified: true },
    { name: "Beijing Forestry University", domain: "bjfu.edu.cn", isVerified: true },
    { name: "Guangxi University for Nationalities", domain: "gxun.edu.cn", isVerified: true },
    { name: "Nanjing University of Posts and Telecommunications", domain: "nupt.edu.cn", isVerified: true },
    { name: "Ningbo University", domain: "nbu.edu.cn", isVerified: true },
    { name: "Jiangxi University of Finance and Economics", domain: "jxufe.edu.cn", isVerified: true },
    { name: "China Central Academy of Fine Arts", domain: "cafa.edu.cn", isVerified: true },
    { name: "Nanjing Tech University", domain: "njtech.edu.cn", isVerified: true },
    { name: "Fujian Normal University", domain: "fjnu.edu.cn", isVerified: true },
    { name: "Hubei University", domain: "hubu.edu.cn", isVerified: true },
    { name: "Sichuan Agricultural University", domain: "scau.edu.cn", isVerified: true },
    { name: "China University of Petroleum (Beijing)", domain: "cup.edu.cn", isVerified: true },
    { name: "The University of Nottingham Ningbo, China", domain: "nottingham.edu.cn", isVerified: true },
    { name: "Shandong Normal University", domain: "sdnu.edu.cn", isVerified: true },
    { name: "Chongqing University of Posts and Telecommunications", domain: "cqupt.edu.cn", isVerified: true },
    { name: "Yangtze University", domain: "ytu.edu.cn", isVerified: true },
    { name: "Nanjing Forestry University", domain: "njfu.edu.cn", isVerified: true },
    { name: "Zhejiang Normal University", domain: "zjnu.edu.cn", isVerified: true },
    { name: "China University of Geosciences (Beijing)", domain: "cugb.edu.cn", isVerified: true },
    { name: "Xi'an University of Architecture and Technology", domain: "xauat.edu.cn", isVerified: true },
    { name: "Shandong University of Science and Technology", domain: "sdust.edu.cn", isVerified: true },
    { name: "Chengdu University of Technology", domain: "cdu.edu.cn", isVerified: true },
    { name: "Yanshan University", domain: "ysu.edu.cn", isVerified: true },
    { name: "Anhui University of Technology", domain: "ahut.edu.cn", isVerified: true },
    { name: "Guangxi Normal University", domain: "gxnu.edu.cn", isVerified: true },
    { name: "Shandong Agricultural University", domain: "sdau.edu.cn", isVerified: true },
    { name: "China Academy of Art", domain: "caa.edu.cn", isVerified: true },
    { name: "Jimei University", domain: "jmu.edu.cn", isVerified: true },
    { name: "Fujian Medical University", domain: "fjmu.edu.cn", isVerified: true },
    { name: "East China University of Political Science and Law", domain: "ecupl.edu.cn", isVerified: true },
    { name: "Fujian Agriculture and Forestry University", domain: "fafu.edu.cn", isVerified: true },
    { name: "XiangTan University", domain: "xtu.edu.cn", isVerified: true },
    { name: "Tianjin University of Technology", domain: "tjut.edu.cn", isVerified: true },
    { name: "Guizhou University", domain: "gzu.edu.cn", isVerified: true },
    { name: "Peking Union Medical College", domain: "pumc.edu.cn", isVerified: true },
    { name: "Tianjin Normal University", domain: "tjnu.edu.cn", isVerified: true },
    { name: "China Pharmaceutical University", domain: "cpu.edu.cn", isVerified: true },
    { name: "Kunming University of Science and Technology", domain: "kmust.edu.cn", isVerified: true },
    { name: "Capital University of Economics and Business", domain: "cueb.edu.cn", isVerified: true },
    { name: "Zhejiang Sci-Tech University", domain: "zstu.edu.cn", isVerified: true },
    { name: "Shanghai University of Engineering Science", domain: "sues.edu.cn", isVerified: true },
    { name: "Qingdao University of Science and Technology", domain: "qust.edu.cn", isVerified: true },
    { name: "Northwest Normal University", domain: "nwnu.edu.cn", isVerified: true },
    { name: "Anhui Agricultural University", domain: "ahau.edu.cn", isVerified: true },
    { name: "Nanjing Audit University", domain: "nau.edu.cn", isVerified: true },
    { name: "Xinjiang University", domain: "xinhuanet.edu.cn", isVerified: false },
    { name: "Ludong University", domain: "ludong.edu.cn", isVerified: true },
    { name: "Inner Mongolia Agricultural University", domain: "imau.edu.cn", isVerified: true },
    { name: "Xi'an University of Technology", domain: "xaut.edu.cn", isVerified: true },
    { name: "Changsha University of Science and Technology", domain: "csu.edu.cn", isVerified: true },
    { name: "Jiangxi Normal University", domain: "jxnu.edu.cn", isVerified: true },
    { name: "Hubei University of Technology", domain: "hubt.edu.cn", isVerified: true },
    { name: "University of Jinan", domain: "ujn.edu.cn", isVerified: true },
    { name: "Sichuan Normal University", domain: "scnu.edu.cn", isVerified: true },
    { name: "Chongqing Medical University", domain: "cqmu.edu.cn", isVerified: true },
    { name: "North University of China", domain: "nuc.edu.cn", isVerified: true },
    { name: "Hangzhou Normal University", domain: "hznu.edu.cn", isVerified: true },
    { name: "Shandong University of Finance and Economics", domain: "sdufe.edu.cn", isVerified: true },
    { name: "Harbin Medical University", domain: "hrbmu.edu.cn", isVerified: true },
    { name: "Shandong University of Technology", domain: "sdut.edu.cn", isVerified: true },
    { name: "Henan University of Science and Technology", domain: "haust.edu.cn", isVerified: true },
    { name: "Civil Aviation Flight University of China", domain: "cafuc.edu.cn", isVerified: true },
    { name: "Capital Medical University", domain: "ccmu.edu.cn", isVerified: true },
    { name: "Chongqing Normal University", domain: "cqnu.edu.cn", isVerified: true },
    { name: "Shanghai Maritime University", domain: "shmtu.edu.cn", isVerified: true },
    { name: "Zhejiang University of Finance and Economics", domain: "zufe.edu.cn", isVerified: true },
    { name: "Zhejiang Gongshang University", domain: "zjgsu.edu.cn", isVerified: true },
    { name: "Changzhou University", domain: "cczu.edu.cn", isVerified: true },
    { name: "Qilu University of Technology", domain: "qlu.edu.cn", isVerified: true },
    { name: "Yantai University", domain: "ytu.edu.cn", isVerified: true },
    { name: "China Medical University", domain: "cmu.edu.cn", isVerified: true },
    { name: "Yunnan Normal University", domain: "ynn.edu.cn", isVerified: true },
    { name: "Shanghai Ocean University", domain: "shou.edu.cn", isVerified: true },
    { name: "Wenzhou University", domain: "wzu.edu.cn", isVerified: true },
    { name: "Sichuan International Studies University", domain: "sisu.edu.cn", isVerified: true },
    { name: "Anhui Medical University", domain: "ahmu.edu.cn", isVerified: true },
    { name: "Guilin University of Electronic Technology", domain: "guet.edu.cn", isVerified: true },
    { name: "Hebei University of Technology", domain: "hebut.edu.cn", isVerified: true },
    { name: "Minzu University of China", domain: "muc.edu.cn", isVerified: true },
    { name: "Ningxia University", domain: "nxu.edu.cn", isVerified: true },
    { name: "Jiangsu Normal University", domain: "jsnu.edu.cn", isVerified: true },
    { name: "Henan Normal University", domain: "henu.edu.cn", isVerified: true },
    { name: "Anhui University of Science and Technology", domain: "aust.edu.cn", isVerified: true },
    { name: "North China University of Technology", domain: "ncut.edu.cn", isVerified: true },
    { name: "Henan Agricultural University", domain: "hau.edu.cn", isVerified: true },
    { name: "Southwest University of Political Science and Law", domain: "swupl.edu.cn", isVerified: true },
    { name: "Tianjin Foreign Studies University", domain: "tjfsu.edu.cn", isVerified: true },
    { name: "Henan Polytechnic University", domain: "hpu.edu.cn", isVerified: true },
    { name: "Chengdu University of Information Technology", domain: "cuit.edu.cn", isVerified: true },
    { name: "Southern Medical University", domain: "smu.edu.cn", isVerified: true },
    { name: "Nantong University", domain: "ntu.edu.cn", isVerified: true },
    { name: "South-Central University for Nationalities", domain: "scuec.edu.cn", isVerified: true },
    { name: "Beijing Sport University", domain: "bsu.edu.cn", isVerified: true },
    { name: "Heilongjiang University", domain: "heu.edu.cn", isVerified: true },
    { name: "Anhui Normal University", domain: "ahnu.edu.cn", isVerified: true },
    { name: "Wuhan University of Science and Technology", domain: "wust.edu.cn", isVerified: true },
    { name: "Jiangsu University of Science and Technology", domain: "just.edu.cn", isVerified: true },
    { name: "Hebei University", domain: "hebu.edu.cn", isVerified: true },
    { name: "Sichuan Fine Arts Institute", domain: "scfai.edu.cn", isVerified: true },
    { name: "Duke Kunshan University", domain: "dukekunshan.edu.cn", isVerified: true },
    { name: "Tianjin University of Finance and Economics", domain: "tjufe.edu.cn", isVerified: true },
    { name: "Southwest Petroleum University", domain: "swpu.edu.cn", isVerified: true },
    { name: "Qufu Normal University", domain: "qfnu.edu.cn", isVerified: true },
    { name: "Shenyang Agricultural University", domain: "syau.edu.cn", isVerified: true },
    { name: "Zhejiang University of Science and Technology", domain: "zust.edu.cn", isVerified: true },
    { name: "Hunan Agricultural University", domain: "hunau.edu.cn", isVerified: true },
    { name: "Beijing Film Academy", domain: "bfa.edu.cn", isVerified: true },
    { name: "Shenyang Pharmaceutical University", domain: "syphu.edu.cn", isVerified: true },
    { name: "Hebei Medical University", domain: "hbmu.edu.cn", isVerified: true },
    { name: "Shanghai University of Sport", domain: "sus.edu.cn", isVerified: true },
    { name: "Anhui University of Finance and Economics", domain: "aufe.edu.cn", isVerified: true },
    { name: "Guangdong University of Finance and Economics", domain: "gdufe.edu.cn", isVerified: true },
    { name: "China Jiliang University", domain: null, isVerified: false },
    { name: "Dalian University of Foreign Languages", domain: "dlufl.edu.cn", isVerified: true },
    { name: "Northeast Agricultural University", domain: "neau.edu.cn", isVerified: true },
    { name: "Tianjin University of Science and Technology", domain: "tjust.edu.cn", isVerified: true },
    { name: "Chengdu University", domain: "cdu.edu.cn", isVerified: true },
    { name: "China Three Gorges University", domain: "ctgu.edu.cn", isVerified: true },
    { name: "Southwest University of Science and Technology", domain: "swust.edu.cn", isVerified: true },
    { name: "Guangzhou Academy of Fine Arts", domain: "gzarts.edu.cn", isVerified: true },
    { name: "Hebei University of Science and Technology", domain: "hebust.edu.cn", isVerified: true },
    { name: "Changzhou Institute of Technology", domain: "czit.edu.cn", isVerified: true },
    { name: "Jishou University", domain: "jsu.edu.cn", isVerified: true },
    { name: "Xi'an International Studies University", domain: "xisu.edu.cn", isVerified: true },
    { name: "Tiangong University", domain: "tiangong.edu.cn", isVerified: true },
    { name: "Beijing International Studies University", domain: "bisu.edu.cn", isVerified: true },
    { name: "Zhejiang Forestry University", domain: "zjfu.edu.cn", isVerified: true },
    { name: "Shaanxi University of Science and Technology", domain: "snust.edu.cn", isVerified: true },
    { name: "Beijing University of Civil Engineering and Architecture", domain: "bucea.edu.cn", isVerified: true },
    { name: "Harbin Normal University", domain: "hrbnu.edu.cn", isVerified: true },
    { name: "Dongguan University of Technology", domain: "dgut.edu.cn", isVerified: true },
    { name: "University of South China", domain: "usc.edu.cn", isVerified: true },
    { name: "Hebei University of Engineering", domain: null, isVerified: false },
    { name: "Jiangxi Agricultural University", domain: "jxau.edu.cn", isVerified: true },
    { name: "Huaiyin Institute of Technology", domain: "hyit.edu.cn", isVerified: true },
    { name: "Agricultural University of Hebei", domain: null, isVerified: false },
    { name: "Yanbian University", domain: "ybu.edu.cn", isVerified: true },
    { name: "Henan University of Traditional Chinese Medicine", domain: "hntcm.edu.cn", isVerified: true },
    { name: "Liaoning Normal University", domain: "lnnu.edu.cn", isVerified: true },
    { name: "Xi'an University of Science and Technology", domain: "xust.edu.cn", isVerified: true },
    { name: "Beijing Technology and Business University", domain: "btbu.edu.cn", isVerified: true },
    { name: "Nanjing University of Finance and Economics", domain: "nufe.edu.cn", isVerified: true },
    { name: "Tianjin University of Commerce", domain: "tuc.edu.cn", isVerified: true },
    { name: "Hubei University of Chinese Medicine", domain: "hbucm.edu.cn", isVerified: true },
    { name: "Tianjin Academy of Fine Arts", domain: "tjarts.edu.cn", isVerified: true },
    { name: "Wenzhou Medical University", domain: "wmu.edu.cn", isVerified: true },
    { name: "Hunan University of Science and Technology", domain: "hnust.edu.cn", isVerified: true },
    { name: "Shenyang Institute of Engineering", domain: "syie.edu.cn", isVerified: true },
    { name: "Hubei University of Economics", domain: "hue.edu.cn", isVerified: true },
    { name: "Civil Aviation University of China", domain: "civilaviation.edu.cn", isVerified: true },
    { name: "Wuhan Textile University", domain: "wtu.edu.cn", isVerified: true },
    { name: "Xi'an University of Posts and Telecommunications", domain: "xupt.edu.cn", isVerified: true },
    { name: "Harbin University of Science and Technology", domain: "hrbust.edu.cn", isVerified: true },                                            
    { name: "Hebei University of Economics and Business", domain: "hueb.edu.cn", isVerified: true },
    { name: "Chongqing Jiaotong University", domain: null, isVerified: false },
    { name: "Inner Mongolia University of Technology", domain: "imut.edu.cn", isVerified: true },
    { name: "Hubei Normal University", domain: "hbnu.edu.cn", isVerified: true },
    { name: "Nanyang Institute of Technology", domain: "nyist.edu.cn", isVerified: true },
    { name: "Nanjing University of Chinese Medicine", domain: "njucm.edu.cn", isVerified: true },
    { name: "Shanghai University of International Business and Economics", domain: null, isVerified: false },
    { name: "Wuhan Polytechnic University", domain: "whpu.edu.cn", isVerified: true },
    { name: "Tianjin Medical University", domain: "tjmu.edu.cn", isVerified: true },
    { name: "Xi'an Academy of Fine Arts", domain: "xafa.edu.cn", isVerified: true },
    { name: "Chengdu University of Traditional Chinese Medicine", domain: "cdutcm.edu.cn", isVerified: true },
    { name: "Guizhou Normal University", domain: "gznu.edu.cn", isVerified: true },
    { name: "Hainan Normal University", domain: null, isVerified: false },
    { name: "Chongqing University of Technology", domain: "cqut.edu.cn", isVerified: true },
    { name: "The Central Academy of Drama", domain: null, isVerified: false },
    { name: "Anqing Normal University", domain: "aqnu.edu.cn", isVerified: true },
    { name: "China Conservatory of Music", domain: null, isVerified: false },
    { name: "Shihezi University", domain: "shzu.edu.cn", isVerified: true },
    { name: "Changchun University of Science and Technology", domain: "ccust.edu.cn", isVerified: true },
    { name: "North China University of Science and Technology", domain: "ncust.edu.cn", isVerified: true },
    { name: "Zhejiang Chinese Medical University", domain: "zcmu.edu.cn", isVerified: true },
    { name: "Yunnan Agricultural University", domain: "ynau.edu.cn", isVerified: true },
    { name: "Henan University of Technology", domain: "haut.edu.cn", isVerified: true },
    { name: "Guangdong Ocean University", domain: "gdou.edu.cn", isVerified: true },
    { name: "Zhengzhou University of Light Industry", domain: "zzuli.edu.cn", isVerified: true },
    { name: "Nanjing Institute of Technology", domain: "njit.edu.cn", isVerified: true },
    { name: "Chaohu University", domain: "chaohu.edu.cn", isVerified: true },
    { name: "Jianghan University", domain: "jhun.edu.cn", isVerified: true },
    { name: "Suzhou University of Science and Technology", domain: "sist.edu.cn", isVerified: true },
    { name: "Jiangxi University of Science and Technology", domain: "jxust.edu.cn", isVerified: true },
    { name: "Beijing Union University", domain: "buu.edu.cn", isVerified: true },
    { name: "United International College", domain: "uic.edu.cn", isVerified: true },
    { name: "Wuyi University", domain: "wuyi.edu.cn", isVerified: true },
    { name: "Central South University of Forestry and Technology", domain: "csuft.edu.cn", isVerified: true },
    { name: "Shanghai Conservatory of Music", domain: "shcmusic.edu.cn", isVerified: true },
    { name: "Inner Mongolia Normal University", domain: "imnu.edu.cn", isVerified: true },
    { name: "Xi'an Polytechnic University", domain: "xpu.edu.cn", isVerified: true },
    { name: "North China University of Water Resources and Electric Power", domain: "ncwu.edu.cn", isVerified: true },
    { name: "Shanghai University of Traditional Chinese Medicine", domain: "shutcm.edu.cn", isVerified: true },
    { name: "Guangzhou University of Chinese Medicine", domain: "gzucm.edu.cn", isVerified: true },
    { name: "Chongqing Technology and Business University", domain: "cqtbu.edu.cn", isVerified: true },
    { name: "Guilin University of Technology", domain: "glut.edu.cn", isVerified: true },
    { name: "Shanghai Lixin University of Accounting and Finance", domain: "sluaf.edu.cn", isVerified: true },
    { name: "Shanghai Theatre Academy", domain: "sta.edu.cn", isVerified: true },
    { name: "LuXun Academy of Fine Arts", domain: "lufa.edu.cn", isVerified: true },
    { name: "Anhui Jianzhu University", domain: "ahjzu.edu.cn", isVerified: true },
    { name: "Taiyuan University of Science and Technology", domain: "tyust.edu.cn", isVerified: true },
    { name: "Changchun University of Technology", domain: "ccut.edu.cn", isVerified: true },
    { name: "Hefei University", domain: "hefei.edu.cn", isVerified: true },
    { name: "Lanzhou Jiaotong University", domain: "lzjtu.edu.cn", isVerified: true },
    { name: "Zhongyuan University of Technology", domain: "zytu.edu.cn", isVerified: true },
    { name: "Shijiazhuang Tiedao University", domain: null, isVerified: false },
    { name: "Beijing Dance Academy", domain: "bda.edu.cn", isVerified: true },
    { name: "Shanxi Agricultural University", domain: "snau.edu.cn", isVerified: true },
    { name: "Hanshan Normal University", domain: "hanshan.edu.cn", isVerified: true },
    { name: "Foshan University", domain: "fosu.edu.cn", isVerified: true },
    { name: "Southwest University for Nationalities", domain: "swun.edu.cn", isVerified: true },
    { name: "Tianjin University of Traditional Chinese Medicine", domain: "tjtcm.edu.cn", isVerified: true },
    { name: "Anyang Normal University", domain: "ayang.ac.cn", isVerified: true },
    { name: "Shanghai University of Electric Power", domain: "shiep.edu.cn", isVerified: true },
    { name: "Inner Mongolia University of Science and Technology", domain: "imust.edu.cn", isVerified: true },
    { name: "Dalian Neusoft University of Information", domain: "neusoft.edu.cn", isVerified: true },
    { name: "Xuchang University", domain: "xcu.edu.cn", isVerified: true },
    { name: "Xiamen University of Technology", domain: "xmut.edu.cn", isVerified: true },
    { name: "Tianjin University of Technology and Education", domain: "tjute.edu.cn", isVerified: true },
    { name: "Shanghai Institute of Technology", domain: "sit.edu.cn", isVerified: true },
    { name: "Fujian University of Technology", domain: "fjut.edu.cn", isVerified: true },
    { name: "Qingdao University of Technology", domain: "qdut.edu.cn", isVerified: true },
    { name: "Shenyang Ligong University", domain: "syut.edu.cn", isVerified: true },
    { name: "East China Jiaotong University", domain: "ecjtu.edu.cn", isVerified: true },
    { name: "Anhui University of Chinese Medicine", domain: "ahutcm.edu.cn", isVerified: true },
    { name: "Hubei University of Automotive Technology", domain: "huat.edu.cn", isVerified: true },
    { name: "Beijing Institute of Graphic Communication", domain: "bignc.edu.cn", isVerified: true },
    { name: "Jinggangshan University", domain: "jgsu.edu.cn", isVerified: true },
    { name: "Shandong University of Arts", domain: "sduarts.edu.cn", isVerified: true },        
    { name: "Huaiyin Normal University", domain: "hyu.edu.cn", isVerified: true },
    { name: "Beijing Information Science and Technology University", domain: "bistu.edu.cn", isVerified: true },
    { name: "Qinghai Normal University", domain: "qhnu.edu.cn", isVerified: true },
    { name: "Taizhou University", domain: "tzc.edu.cn", isVerified: true },
    { name: "Jiangxi University of Traditional Chinese Medicine", domain: "jxtcm.edu.cn", isVerified: true },
    { name: "Xihua University", domain: "xhu.edu.cn", isVerified: true },
    { name: "Shanxi University of Finance and Economics", domain: "sxufe.edu.cn", isVerified: true },
    { name: "Henan Institute of Science and Technology", domain: "haust.edu.cn", isVerified: true },
    { name: "Chongqing University of Arts and Sciences", domain: "cqarts.edu.cn", isVerified: true },
    { name: "Gansu Agricultural University", domain: "gsau.edu.cn", isVerified: true },
    { name: "Henan University of Economics and Law", domain: "huel.edu.cn", isVerified: true },
    { name: "Shaoxing University", domain: "sxu.edu.cn", isVerified: true },
    { name: "Binzhou Medical University", domain: "bzmu.edu.cn", isVerified: true },
    { name: "Guizhou Medical University", domain: "gzhmu.edu.cn", isVerified: true },
    { name: "Shenyang Jianzhu University", domain: "sjzu.edu.cn", isVerified: true },
    { name: "Beijing Institute of Petrochemical Technology", domain: "bipt.edu.cn", isVerified: true },
    { name: "Henan Institute of Technology", domain: "hnit.edu.cn", isVerified: true },
    { name: "Xuzhou Institute of Technology", domain: "xzit.edu.cn", isVerified: true },
    { name: "Shandong Jiaotong University", domain: "sdjt.edu.cn", isVerified: true },
    { name: "Yan'an University", domain: "yanan.edu.cn", isVerified: true },
    { name: "Nanjing University of the Arts", domain: "njarts.edu.cn", isVerified: true },
    { name: "Northeast Electric Power University", domain: "neepu.edu.cn", isVerified: true },
    { name: "Yancheng Institute of Technology", domain: "ycit.edu.cn", isVerified: true },
    { name: "The National Academy of Chinese Theatre Arts", domain: "catc.edu.cn", isVerified: true },
    { name: "Jiaxing University", domain: "jxu.edu.cn", isVerified: true },
    { name: "Hunan University of Technology", domain: "hnut.edu.cn", isVerified: true },
    { name: "Liaocheng University", domain: "lcu.edu.cn", isVerified: true },
    { name: "Shenyang Normal University", domain: "synu.edu.cn", isVerified: true },
    { name: "Zhengzhou University of Aeronautics", domain: "zhua.edu.cn", isVerified: true },
    { name: "Zhongkai University of Agriculture and Engineering", domain: null, isVerified: false },
    { name: "Shanxi Normal University", domain: "sxnu.edu.cn", isVerified: true },
    { name: "Nanchang Institute of Technology", domain: "ncit.edu.cn", isVerified: true },
    { name: "Xinjiang Normal University", domain: "xjnu.edu.cn", isVerified: true },
    { name: "Shenyang Aerospace University", domain: "syau.edu.cn", isVerified: true },
    { name: "Yunnan University of Finance and Economics", domain: "ynufe.edu.cn", isVerified: true },
    { name: "Qinghai University", domain: "qhu.edu.cn", isVerified: true },
    { name: "Sichuan University of Science and Engineering", domain: null, isVerified: false },
    { name: "Hubei Institute of Fine Arts", domain: "hifa.edu.cn", isVerified: true },
    { name: "Lanzhou University of Technology", domain: "lut.edu.cn", isVerified: true },
    { name: "Beijing Institute of Fashion Technology", domain: "bift.edu.cn", isVerified: true },
    { name: "Nanchang Hangkong University", domain: "nchu.edu.cn", isVerified: true },
    { name: "Shenyang University of Chemical Technology", domain: "syuct.edu.cn", isVerified: true },
    { name: "Jinling Institute of Technology", domain: "jnit.edu.cn", isVerified: true },
    { name: "Dalian Medical University", domain: "dmu.edu.cn", isVerified: true },
    { name: "Liaoning University of Technology", domain: "lutech.edu.cn", isVerified: true },
    { name: "Liaoning Shihua University", domain: "lsu.edu.cn", isVerified: true },
    { name: "Huizhou University", domain: "hzu.edu.cn", isVerified: true },
    { name: "Guangdong Polytechnic Normal University", domain: "gdipnu.edu.cn", isVerified: true },
    { name: "Shenyang University of Technology", domain: "syut.edu.cn", isVerified: true },
    { name: "Shanghai University of Political Science and Law", domain: "shupl.edu.cn", isVerified: true },
    { name: "Northwest University of Politics and Law", domain: "nwpupl.edu.cn", isVerified: true },
    { name: "Fujian University of Traditional Chinese Medicine", domain: "fjtcm.edu.cn", isVerified: true },
    { name: "Qingdao Agricultural University", domain: "qau.edu.cn", isVerified: true },
    { name: "Linyi University", domain: "lyu.edu.cn", isVerified: true },
    { name: "Wuhan Institute of Technology", domain: "whit.edu.cn", isVerified: true },
    { name: "Yunnan Minzu University", domain: "ynni.edu.cn", isVerified: true },
    { name: "Shanghai Second Polytechnic University", domain: "sspu.edu.cn", isVerified: true },
    { name: "Guangzhou Medical University", domain: "gzhmu.edu.cn", isVerified: true },
    { name: "Guangxi Medical University", domain: "gxmu.edu.cn", isVerified: true },
    { name: "Wuhan Sports University", domain: "whsu.edu.cn", isVerified: true },
    { name: "Xi'an International University", domain: "xaiu.edu.cn", isVerified: true },
    { name: "Sichuan Conservatory of Music", domain: "sccmusic.edu.cn", isVerified: true },
    { name: "Dalian Nationalities University", domain: "dlnu.edu.cn", isVerified: true },
    { name: "Qingdao Binhai University", domain: "qdbhu.edu.cn", isVerified: true },
    { name: "Liaoning Technical University", domain: null, isVerified: false },
    { name: "China Women's University", domain: "cwu.edu.cn", isVerified: true },
    { name: "Huangshan University", domain: "hsu.edu.cn", isVerified: true },
    { name: "Dalian Polytechnic University", domain: "dlpu.edu.cn", isVerified: true },
    { name: "Xinjiang Agricultural University", domain: "xjau.edu.cn", isVerified: true },
    { name: "Northeast Petroleum University", domain: "nepu.edu.cn", isVerified: true },
    { name: "Hunan Institute of Engineering", domain: "hnie.edu.cn", isVerified: true },
    { name: "Ningbo University of Technology", domain: "nbut.edu.cn", isVerified: true },
    { name: "Jilin Agricultural University", domain: "jlau.edu.cn", isVerified: true },
    { name: "Zhejiang Ocean University", domain: "zjou.edu.cn", isVerified: true },
    { name: "Jilin Normal University", domain: "jlun.edu.cn", isVerified: true },        
    { name: "Xi'an Eurasia University", domain: "xeu.edu.cn", isVerified: true },
    { name: "Chongqing University of Science and Technology", domain: "cqust.edu.cn", isVerified: true },
    { name: "Minjiang University", domain: "minjiang.edu.cn", isVerified: true },
    { name: "Dalian University", domain: "dlu.edu.cn", isVerified: true },
    { name: "Xijing University", domain: "xiju.edu.cn", isVerified: true },
    { name: "Jiaying University", domain: "jiaying.edu.cn", isVerified: true },
    { name: "Jiangsu Ocean University", domain: "jsou.edu.cn", isVerified: true },
    { name: "Hunan Institute of Science and Technology", domain: "hnist.edu.cn", isVerified: true },
    { name: "Shenyang Sport University", domain: "syus.edu.cn", isVerified: true },
    { name: "Nanchang Institute of Technology", domain: "ncit.edu.cn", isVerified: true },
    { name: "Beihua University", domain: "bhu.edu.cn", isVerified: true },
    { name: "Guilin University of Aerospace Technology", domain: "guat.edu.cn", isVerified: true },
    { name: "Shanghai Business School", domain: null, isVerified: false },
    { name: "Shanghai Dianji University", domain: null, isVerified: false },
    { name: "Nanning Normal University", domain: "nnnu.edu.cn", isVerified: true },
    { name: "Beijing City University", domain: "bjcu.edu.cn", isVerified: true },
    { name: "Guilin Medical University", domain: "glm.edu.cn", isVerified: true },
    { name: "Guizhou University of Finance and Economics", domain: "gzufe.edu.cn", isVerified: true },
    { name: "China Foreign Affairs University", domain: "cfa.edu.cn", isVerified: true },
    { name: "Shaanxi University of Technology", domain: "snut.edu.cn", isVerified: true },
    { name: "Weifang University", domain: "wfu.edu.cn", isVerified: true },
    { name: "Huanghuai University", domain: "hhu.edu.cn", isVerified: true },
    { name: "Changsha University", domain: "csu.edu.cn", isVerified: true },
    { name: "Shandong University of Traditional Chinese Medicine", domain: "sdtcm.edu.cn", isVerified: true },
    { name: "Tianjin Chengjian University", domain: "tcu.edu.cn", isVerified: true },
    { name: "North Minzu University", domain: "nmu.edu.cn", isVerified: true },
    { name: "Shenyang University", domain: "syu.edu.cn", isVerified: true },
    { name: "Anhui Polytechnic University", domain: "ahpu.edu.cn", isVerified: true },
    { name: "Xinxiang Medical University", domain: "xxmu.edu.cn", isVerified: true },
    { name: "Beijing University of Agriculture", domain: "buagri.edu.cn", isVerified: true },
    { name: "Dalian Ocean University", domain: "dolu.edu.cn", isVerified: true },
    { name: "Zhejiang Wanli University", domain: "zwu.edu.cn", isVerified: true },
    { name: "Hefei Normal University", domain: "hfnu.edu.cn", isVerified: true },
    { name: "Hanjiang Normal University", domain: "hjnc.edu.cn", isVerified: true },
    { name: "Shaoguan University", domain: "sgu.edu.cn", isVerified: true },
    { name: "Jingdezhen Ceramic Institute", domain: "jdzu.edu.cn", isVerified: true },
    { name: "Shandong Technology and Business University", domain: "sdutb.edu.cn", isVerified: true },
    { name: "China West Normal University", domain: "cwnu.edu.cn", isVerified: true },
    { name: "Shandong Jianzhu University", domain: "sdjzu.edu.cn", isVerified: true },
    { name: "Changchun University", domain: "ccu.edu.cn", isVerified: true },
    { name: "Jinzhou Medical University", domain: "jzmu.edu.cn", isVerified: true },
    { name: "China Youth University for Political Sciences", domain: "cyu.edu.cn", isVerified: true },
    { name: "Hebei Normal University of Science and Technology", domain: "hebstu.edu.cn", isVerified: true },
    { name: "Heilongjiang University of Chinese Medicine", domain: "hljcimu.edu.cn", isVerified: true },
    { name: "Guizhou Education University", domain: "gzedu.edu.cn", isVerified: true },
    { name: "Wuzhou University", domain: "wzu.edu.cn", isVerified: true },
    { name: "Guangdong Medical University", domain: "gdm.edu.cn", isVerified: true },
    { name: "University of International Relations", domain: "uir.edu.cn", isVerified: true },
    { name: "Xi'an Technological University", domain: "xatu.edu.cn", isVerified: true },
    { name: "Changshu Institute of Technology", domain: "csit.edu.cn", isVerified: true },
    { name: "Tibet University", domain: "tub.edu.cn", isVerified: true },
    { name: "Wuchang University of Technology", domain: "wcut.edu.cn", isVerified: true },
    { name: "Shandong First Medical University", domain: "sfmu.edu.cn", isVerified: true },
    { name: "Guangdong Pharmaceutical University", domain: "gdpu.edu.cn", isVerified: true },
    { name: "Guizhou Minzu University", domain: "gzmu.edu.cn", isVerified: true },
    { name: "Shandong University of Art and Design", domain: "sduad.edu.cn", isVerified: true },
    { name: "Xi'an Physical Education University", domain: "xipeu.edu.cn", isVerified: true },
    { name: "Guangdong Technion Israel Institute of Technology", domain: "gtit.edu.cn", isVerified: true },
    { name: "West Anhui University", domain: "wahu.edu.cn", isVerified: true },
    { name: "Chuzhou University", domain: "czhu.edu.cn", isVerified: true },
    { name: "Shandong Yingcai University", domain: "sdyu.edu.cn", isVerified: true },
    { name: "Northwest University for Nationalities", domain: "nwuni.edu.cn", isVerified: true },
    { name: "Hebei GEO University", domain: "hgu.edu.cn", isVerified: true },
    { name: "Wannan Medical College", domain: "wnmc.edu.cn", isVerified: true },
    { name: "Huzhou University", domain: "hzu.edu.cn", isVerified: true },
    { name: "Inner Mongolia University for the Nationalities", domain: null, isVerified: false },
    { name: "Xinghai Conservatory of Music", domain: "xhcm.edu.cn", isVerified: true },
    { name: "Communication University of Zhejiang", domain: "cuz.edu.cn", isVerified: true },
    { name: "Zunyi Medical University", domain: "zymu.edu.cn", isVerified: true },
    { name: "Minnan Normal University", domain: "mnnu.edu.cn", isVerified: true },
    { name: "Huanghe Jiaotong University", domain: "hhjt.edu.cn", isVerified: true },
    { name: "Hainan Medical University", domain: null, isVerified: false },
    { name: "Taiyuan Institute of Technology", domain: "tyit.edu.cn", isVerified: true },
    { name: "Gansu University of Political Science and Law", domain: "gups.edu.cn", isVerified: true },
    { name: "Xuzhou Medical University", domain: "xzmu.edu.cn", isVerified: true },
    { name: "Qiqihar University", domain: "qqhru.edu.cn", isVerified: true },
    { name: "Heze University", domain: "hezeu.edu.cn", isVerified: true },
    { name: "Shenyang Conservatory of Music", domain: "sccmusic.edu.cn", isVerified: true },
    { name: "Anyang Institute of Technology", domain: "ayit.edu.cn", isVerified: true },
    { name: "Fujian Business University", domain: "fbu.edu.cn", isVerified: true },
    { name: "Henan University of Urban Construction", domain: "huuc.edu.cn", isVerified: true },        
    { name: "Chizhou University", domain: "czu.edu.cn", isVerified: true },
    { name: "Neijiang Normal University", domain: "njnu.edu.cn", isVerified: true },
    { name: "Chongqing Three Gorges University", domain: "cqtgu.edu.cn", isVerified: true },
    { name: "Huainan Normal University", domain: "hnnu.edu.cn", isVerified: true },
    { name: "Honghe University", domain: "hhu.edu.cn", isVerified: true },
    { name: "Tarim University", domain: "tru.edu.cn", isVerified: true },
    { name: "Xinyang Normal University", domain: "xynu.edu.cn", isVerified: true },
    { name: "Chengdu Medical College", domain: "cdmc.edu.cn", isVerified: true },
    { name: "Shanxi Medical University", domain: "sxmu.edu.cn", isVerified: true },
    { name: "Dalian Jiaotong University", domain: "dlju.edu.cn", isVerified: true },
    { name: "Beijing Wuzi University", domain: "bwu.edu.cn", isVerified: true },
    { name: "Tangshan College", domain: "tsc.edu.cn", isVerified: true },
    { name: "Liaoning University of Traditional Chinese Medicine", domain: "lutcm.edu.cn", isVerified: true },
    { name: "Xinjiang Medical University", domain: "xjmu.edu.cn", isVerified: true },
    { name: "Chengdu Technological University", domain: "cdtu.edu.cn", isVerified: true },
    { name: "Wuhan Conservatory of Music", domain: "whcm.edu.cn", isVerified: true },
    { name: "Hubei Polytechnic University", domain: "hbpu.edu.cn", isVerified: true },
    { name: "Hubei University of Medicine", domain: "hbmu.edu.cn", isVerified: true },
    { name: "Jiujiang University", domain: "jju.edu.cn", isVerified: true },
    { name: "Hunan University of Chinese Medicine", domain: "hucm.edu.cn", isVerified: true },
    { name: "Luoyang Institute of Science and Technology", domain: "luyit.edu.cn", isVerified: true },
    { name: "Huaibei Normal University", domain: "hbnu.edu.cn", isVerified: true },
    { name: "Chengde Medical University", domain: "cdmedu.edu.cn", isVerified: true },
    { name: "Hunan First Normal University", domain: "hnfnu.edu.cn", isVerified: true },
    { name: "Guangxi University of Science and Technology", domain: "gxust.edu.cn", isVerified: true },
    { name: "Zhejiang Shuren University", domain: "zjsr.edu.cn", isVerified: true },
    { name: "Dezhou University", domain: "dezu.edu.cn", isVerified: true },
    { name: "Xi'an University", domain: "xau.edu.cn", isVerified: true },
    { name: "Guangdong University of Finance", domain: "gduf.edu.cn", isVerified: true },
    { name: "North China Institute of Science and Technology", domain: "ncist.edu.cn", isVerified: true },
    { name: "People's Public Security University of China", domain: "psp.edu.cn", isVerified: true },
    { name: "Chengdu Sport University", domain: "cdsu.edu.cn", isVerified: true },
    { name: "Yangtze Normal University", domain: "yznnu.edu.cn", isVerified: true },
    { name: "Tongling University", domain: "tlu.edu.cn", isVerified: true },
    { name: "Guiyang University Traditional Chinese Medicine", domain: "gyutcm.edu.cn", isVerified: true },
    { name: "Guangxi University of Chinese Medicine", domain: "gxucm.edu.cn", isVerified: true },
    { name: "Hubei University of Education", domain: "hbue.edu.cn", isVerified: true },
    { name: "Bohai University", domain: "bhu.edu.cn", isVerified: true },
    { name: "Dali University", domain: "dali.edu.cn", isVerified: true },
    { name: "Tianjin Conservatory of Music", domain: "tjcm.edu.cn", isVerified: true },
    { name: "Shandong Sport University", domain: "sdsu.edu.cn", isVerified: true },
    { name: "Xinxiang University", domain: "xxu.edu.cn", isVerified: true },
    { name: "Xi'an University of Finance and Economics", domain: "xufe.edu.cn", isVerified: true },
    { name: "Fuyang Normal University", domain: "fynu.edu.cn", isVerified: true },
    { name: "Nanyang Normal University", domain: "nynu.edu.cn", isVerified: true },
    { name: "Qiannan Normal College for Nationalities", domain: "qnnc.edu.cn", isVerified: true },
    { name: "Daqing Normal University", domain: "dqnu.edu.cn", isVerified: true },
    { name: "Hechi University", domain: "hcu.edu.cn", isVerified: true },
    { name: "Taiyuan Normal University", domain: "tynu.edu.cn", isVerified: true },
    { name: "Shanxi Datong University", domain: "sxdtu.edu.cn", isVerified: true },
    { name: "Shanghai Jianqiao University", domain: "jqu.edu.cn", isVerified: true },
    { name: "Hunan University of Commerce", domain: "huce.edu.cn", isVerified: true },
    { name: "Yancheng Teachers University", domain: "yctu.edu.cn", isVerified: true },
    { name: "Huanghe Science and Technology College", domain: "hhstc.edu.cn", isVerified: true },
    { name: "Taishan University", domain: "tsu.edu.cn", isVerified: true },
    { name: "North Sichuan Medical College", domain: "nsmc.edu.cn", isVerified: true },
    { name: "Lanzhou University of Finance and Economics", domain: "lufe.edu.cn", isVerified: true },
    { name: "Zhaoqing University", domain: "zqu.edu.cn", isVerified: true },
    { name: "Wenzhou-Kean University", domain: "wz-kean.edu.cn", isVerified: true },
    { name: "Shaanxi University of Chinese Medicine", domain: "sxucm.edu.cn", isVerified: true },
    { name: "Southwest Medical University", domain: "swmu.edu.cn", isVerified: true },
    { name: "Shandong Second Medical University", domain: "sdsmu.edu.cn", isVerified: true },
    { name: "Xi'an Conservatory of Music", domain: "xacm.edu.cn", isVerified: true },
    { name: "Harbin University of Commerce", domain: "hrbuc.edu.cn", isVerified: true },
    { name: "Zhejiang Yuexiu University of Foreign Languages", domain: "zyufl.edu.cn", isVerified: true },
    { name: "Zaozhuang University", domain: "zzzc.edu.cn", isVerified: true },
    { name: "Hebei University of Architecture", domain: "hebau.edu.cn", isVerified: true },
    { name: "Shangqiu Normal University", domain: "sqnu.edu.cn", isVerified: true },
    { name: "Jining Medical University", domain: "jnmu.edu.cn", isVerified: true },
    { name: "Jiangxi Science and Technology Normal University", domain: "jxstnu.edu.cn", isVerified: true },
    { name: "Hexi University", domain: "hxu.edu.cn", isVerified: true },
    { name: "Kunming University", domain: "kmu.edu.cn", isVerified: true },
    { name: "Shaanxi Xueqian Normal University", domain: "sxnnu.edu.cn", isVerified: true },
    { name: "Zhejiang International Studies University", domain: "zisud.edu.cn", isVerified: true },
    { name: "Tianjin Agricultural University", domain: "tjau.edu.cn", isVerified: true },
    { name: "Guangdong Baiyun University", domain: "baiyun.edu.cn", isVerified: true },
    { name: "Lingnan Normal University", domain: "lnnu.edu.cn", isVerified: true },
    { name: "Yunnan Arts University", domain: "ynau.edu.cn", isVerified: true },
    { name: "China University of Labor Relations", domain: "culr.edu.cn", isVerified: true },
    { name: "Zhoukou Normal University", domain: "zhknu.edu.cn", isVerified: true },
    { name: "Zhengzhou Shengda University of Economics, Business and Management", domain: null, isVerified: false },
    { name: "Changchun Institute of Technology", domain: "ccit.edu.cn", isVerified: true },
    { name: "Guangzhou Sport University", domain: null, isVerified: false },
    { name: "Bengbu Medical College", domain: "bbmc.edu.cn", isVerified: true },
    { name: "Zunyi Normal College", domain: "znc.edu.cn", isVerified: true },
    { name: "Quanzhou Normal University", domain: "qznu.edu.cn", isVerified: true },
    { name: "Southwest Forestry University", domain: "swfu.edu.cn", isVerified: true },
    { name: "Suzhou University", domain: "suda.edu.cn", isVerified: true },
    { name: "Changchun Normal University", domain: "ccnu.edu.cn", isVerified: true },
    { name: "Anhui Xinhua University", domain: "ahxu.edu.cn", isVerified: true },
    { name: "Hunan City University", domain: "hcyu.edu.cn", isVerified: true },
    { name: "Zhejiang Conservatory of Music", domain: "zcm.edu.cn", isVerified: true },
    { name: "Jiangsu Teachers University of Technology", domain: "jsut.edu.cn", isVerified: true },
    { name: "Changchun University of Chinese Medicine", domain: "ccucm.edu.cn", isVerified: true },
    { name: "Weinan Normal University", domain: "wnu.edu.cn", isVerified: true },
    { name: "Guangxi Normal University for Nationalities", domain: "gxnnu.edu.cn", isVerified: true },
    { name: "Huaihua University", domain: "hhwu.edu.cn", isVerified: true },
    { name: "Hainan Tropical Ocean University", domain: null, isVerified: false },
    { name: "Capital University of Physical Education and Sports", domain: "chinasport.edu", isVerified: true },
    { name: "Zhejiang University of Water Resources and Electric Power", domain: null, isVerified: false },
    { name: "Hubei University of Arts and Science", domain: "hubas.edu.cn", isVerified: true },
    { name: "Qujing Normal University", domain: "qjnu.edu.cn", isVerified: true },
    { name: "Hunan University of Arts and Science", domain: "hunas.edu.cn", isVerified: true },
    { name: "Huanggang Normal University", domain: "hhnu.edu.cn", isVerified: true },
    { name: "Jilin Jianzhu University", domain: "jljz.edu.cn", isVerified: true },
    { name: "Shandong University of Political Science and Law", domain: "sdpsl.edu.cn", isVerified: true },
    { name: "Zhengzhou Institute of Technology", domain: "zzit.edu.cn", isVerified: true },
    { name: "Mudanjiang Normal University", domain: "mdjnu.edu.cn", isVerified: true },
    { name: "Nanjing Xiaozhuang University", domain: "nxzu.edu.cn", isVerified: true },
    { name: "Lanzhou City University", domain: "lzcu.edu.cn", isVerified: true },
    { name: "Hulunbeier University", domain: "hlbrc.edu.cn", isVerified: true },
    { name: "Hunan International Economics University", domain: "hiue.edu.cn", isVerified: true },
    { name: "Beibu Gulf University", domain: "bgu.edu.cn", isVerified: true },
    { name: "Harbin University", domain: "harbinu.edu.cn", isVerified: true },
    { name: "Jingchu University of Technology", domain: "jcut.edu.cn", isVerified: true },
    { name: "Ningxia Medical University", domain: "nxmu.edu.cn", isVerified: true },
    { name: "Lishui University", domain: "lishui.edu.cn", isVerified: true },
    { name: "Tianshui Normal University", domain: "tsnu.edu.cn", isVerified: true },
    { name: "Baoji University of Arts and Sciences", domain: "buaas.edu.cn", isVerified: true },
    { name: "Jiangsu University of Technology", domain: "just.edu.cn", isVerified: true },
    { name: "Hengyang Normal University", domain: "hyu.edu.cn", isVerified: true },
    { name: "Anshun University", domain: "ansu.edu.cn", isVerified: true },
    { name: "Guangdong University of Petrochemical Technology", domain: "gdpcu.edu.cn", isVerified: true },
    { name: "Pingdingshan University", domain: "pdsu.edu.cn", isVerified: true },
    { name: "Sanda University", domain: "sanda.edu.cn", isVerified: true },
    { name: "Anhui Sanlian University", domain: "anhsu.edu.cn", isVerified: true },
    { name: "Longyan University", domain: "lyu.edu.cn", isVerified: true },
    { name: "Yunnan University of Chinese Medicine", domain: "ynucm.edu.cn", isVerified: true },
    { name: "Luoyang Normal University", domain: "lynu.edu.cn", isVerified: true },
    { name: "Jilin Institute of Chemical Technology", domain: "jlict.edu.cn", isVerified: true },
    { name: "Guangxi University of Finance and Economics", domain: "gxufe.edu.cn", isVerified: true },
    { name: "Xi'an Peihua University", domain: "xpu.edu.cn", isVerified: true },
    { name: "Putian University", domain: "ptu.edu.cn", isVerified: true },
    { name: "Jilin International Studies University", domain: "jlisu.edu.cn", isVerified: true },
    { name: "Gansu University of Chinese Medicine", domain: "gucm.edu.cn", isVerified: true },
    { name: "Sanya University", domain: "sanya.edu.cn", isVerified: true },
    { name: "Kunming Medical University", domain: "kmu.edu.cn", isVerified: true },
    { name: "Yibin University", domain: "ybu.edu.cn", isVerified: true },
    { name: "Hubei University for Nationalities", domain: "hubu.edu.cn", isVerified: true },
    { name: "Zhengzhou Normal University", domain: "zznu.edu.cn", isVerified: true },
    { name: "Guangxi Arts University", domain: "gxarts.edu.cn", isVerified: true },
    { name: "Gannan Normal University", domain: "gnnu.edu.cn", isVerified: true },
    { name: "Ankang University", domain: "anku.edu.cn", isVerified: true },
    { name: "Tianjin University of Sport", domain: "tjus.edu.cn", isVerified: true },
    { name: "Xingtai University", domain: "xtu.edu.cn", isVerified: true },
    { name: "Nanjing Sport Institute", domain: "nsi.edu.cn", isVerified: true },
    { name: "Xi'an Siyuan University", domain: "xsru.edu.cn", isVerified: true },
    { name: "Chongqing College of Humanities, Science and Technology", domain: "cchst.edu.cn", isVerified: true },
    { name: "Fujian Jiangxia University", domain: "fjxu.edu.cn", isVerified: true },
    { name: "Ningxia Normal University", domain: "nxnu.edu.cn", isVerified: true },
    { name: "Xiangnan University", domain: "xnu.edu.cn", isVerified: true },
    { name: "Hubei University of Science and Technology", domain: "hubst.edu.cn", isVerified: true },
    { name: "University of Science and Technology Liaoning", domain: "ustl.edu.cn", isVerified: true },
    { name: "Hubei Engineering University", domain: "hbeng.edu.cn", isVerified: true },
    { name: "Shaoyang University", domain: "syu.edu.cn", isVerified: true },
    { name: "Hebei North University", domain: "hbnu.edu.cn", isVerified: true },
    { name: "Binzhou University", domain: "bzhu.edu.cn", isVerified: true },
    { name: "Baicheng Normal University", domain: "bcnnu.edu.cn", isVerified: true },
    { name: "East China University of Technology", domain: "ecut.edu.cn", isVerified: true },
    { name: "Quzhou University", domain: "qzu.edu.cn", isVerified: true },
    { name: "Hunan University of Science and Engineering", domain: "hnust.edu.cn", isVerified: true },
    { name: "Lanzhou Institute of Technology", domain: "lzit.edu.cn", isVerified: true },
    { name: "Kashi University", domain: "kashi.edu.cn", isVerified: true },
    { name: "Hebei University of Chinese Medicine", domain: "hbucm.edu.cn", isVerified: true },
    { name: "Guizhou Institute of Technology", domain: "gzit.edu.cn", isVerified: true },
    { name: "Xi'an Aeronautical University", domain: "xauat.edu.cn", isVerified: true },
    { name: "Xi'an Fanyi University", domain: "xfu.edu.cn", isVerified: true },
    { name: "Shaanxi Institute of International Trade and Commerce", domain: "siitc.edu.cn", isVerified: true },
    { name: "Qinghai University for Nationalities", domain: "qhnu.edu.cn", isVerified: true },
    { name: "Shougang Institute of Technology", domain: "sgit.edu.cn", isVerified: true },
    { name: "Qingdao Huanghai University", domain: "qhu.edu.cn", isVerified: true },
    { name: "Jilin University of Finance and Economics", domain: "jlufe.edu.cn", isVerified: true },
    { name: "Wenhua University", domain: "whu.edu.cn", isVerified: true },
    { name: "Shandong Women's University", domain: "sdwu.edu.cn", isVerified: true },
    { name: "Shanxi University of Traditional Chinese Medicine", domain: "sxutcm.edu.cn", isVerified: true },
    { name: "Ningxia Institute of Science and Technology", domain: "nxist.edu.cn", isVerified: true },
    { name: "Tangshan Normal University", domain: "tsnu.edu.cn", isVerified: true },
    { name: "Jilin Animation Institute", domain: "jlai.edu.cn", isVerified: true },
    { name: "Wuhan College", domain: "whcollege.edu.cn", isVerified: true },
    { name: "Jilin College of the Arts", domain: "jca.edu.cn", isVerified: true },
    { name: "Haikou College of Economics", domain: "hkue.edu.cn", isVerified: true },
    { name: "Jining University", domain: "jnu.edu.cn", isVerified: true },
    { name: "Hengshui University", domain: "hsu.edu.cn", isVerified: true },
    { name: "Yinchuan Energy College", domain: "yec.edu.cn", isVerified: true },
    { name: "Yulin Normal University", domain: "ylnu.edu.cn", isVerified: true },
    { name: "Shandong Youth University of Political Science", domain: "syups.edu.cn", isVerified: true },
    { name: "Inner Mongolia University of Finance and Economics", domain: "imu-fe.edu.cn", isVerified: true },
    { name: "Hunan University of Humanities, Science and Technology", domain: "huhst.edu.cn", isVerified: true },
    { name: "Baoding University", domain: "bdu.edu.cn", isVerified: true },
    { name: "Henan Finance University", domain: "hfu.edu.cn", isVerified: true },
    { name: "Chuxiong Normal University", domain: "cxnu.edu.cn", isVerified: true },
    { name: "Shenzhen MSU-BIT University", domain: "smbu.edu.cn", isVerified: true },
    { name: "Wuhan Donghu University", domain: "whdh.edu.cn", isVerified: true },
    { name: "Zhengzhou Institute of Finance and Economics", domain: "zzife.edu.cn", isVerified: true },
    { name: "Xi'an Medical University", domain: "xamu.edu.cn", isVerified: true },
    { name: "Ningbo University of Finance and Economics", domain: "nbufe.edu.cn", isVerified: true },
    { name: "Hebei University of Engineering", domain: "hebut.edu.cn", isVerified: true },
    { name: "Sichuan University of Arts and Science", domain: "scuas.edu.cn", isVerified: true },
    { name: "Inner Mongolia Medical University", domain: "immu.edu.cn", isVerified: true },
    { name: "Chifeng University", domain: "cfu.edu.cn", isVerified: true },
    { name: "North China Institute of Aerospace Engineering", domain: "nciae.edu.cn", isVerified: true },
    { name: "Xiamen Institute of Technology", domain: "xit.edu.cn", isVerified: true },
    { name: "Leshan Normal University", domain: "lsnu.edu.cn", isVerified: true },
    { name: "Sichuan University of Media and Communications", domain: "scmc.edu.cn", isVerified: true },
    { name: "Jiangxi University of Technology", domain: "jxut.edu.cn", isVerified: true },
    { name: "Qilu Normal University", domain: "qlnu.edu.cn", isVerified: true },
    { name: "Yuxi Normal University", domain: "yxnu.edu.cn", isVerified: true },
    { name: "Jinzhong University", domain: "jzu.edu.cn", isVerified: true },
    { name: "Panzhihua University", domain: "pzu.edu.cn", isVerified: true },
    { name: "Luliang University", domain: "llu.edu.cn", isVerified: true },
    { name: "Hebei Institute of Physical Education", domain: "hipe.edu.cn", isVerified: true },
    { name: "Hebei Institute of Communication", domain: "heic.edu.cn", isVerified: true },
    { name: "Shandong Agriculture and Engineering University", domain: null, isVerified: false },
    { name: "Xinjiang University of Finance and Economics", domain: "xufe.edu.cn", isVerified: true },
    { name: "Xizang Minzu University", domain: "xzmu.edu.cn", isVerified: true },
    { name: "Yantai Nanshan University", domain: null, isVerified: false },
    { name: "Lanzhou University of Arts and Science", domain: null, isVerified: false },
    { name: "Anshan Normal University", domain: "asnu.edu.cn", isVerified: true },
    { name: "Guiyang University", domain: "gyu.edu.cn", isVerified: true },
    { name: "Wuyi University", domain: "wuyi.edu.cn", isVerified: true },
    { name: "Changsha Medical University", domain: "csmu.edu.cn", isVerified: true },
    { name: "Yili Normal University", domain: "ylnu.edu.cn", isVerified: true },
    { name: "Xi'an Shiyou University", domain: "xasyu.edu.cn", isVerified: true },
    { name: "Shandong Xiehe University", domain: "sdxhu.edu.cn", isVerified: true },
    { name: "Yichun University", domain: "ycu.edu.cn", isVerified: true },
    { name: "Heilongjiang Institute of Technology", domain: "hljit.edu.cn", isVerified: true },
    { name: "Handan College", domain: "hdu.edu.cn", isVerified: true },
    { name: "Xiamen Huaxia University", domain: "xhxy.edu.cn", isVerified: true },
    { name: "Tonghua Normal University", domain: "thnu.edu.cn", isVerified: true },
    { name: "Heilongjiang Bayi Agricultural University", domain: "hljbyafu.edu.cn", isVerified: true },
    { name: "Xinjiang Arts University", domain: "xjau.edu.cn", isVerified: true },
    { name: "Shanghai University of Medicine and Health Sciences", domain: "shsmu.edu.cn", isVerified: true },
    { name: "Jiamusi University", domain: "jmu.edu.cn", isVerified: true },
    { name: "Shijiazhuang University", domain: "szu.edu.cn", isVerified: true },
    { name: "Jilin Engineering Normal University", domain: "jlenu.edu.cn", isVerified: true },
    { name: "Ningde Normal University", domain: "ndnu.edu.cn", isVerified: true },
    { name: "Mianyang Normal University", domain: "mynu.edu.cn", isVerified: true },
    { name: "Harbin Sport University", domain: "hbu.edu.cn", isVerified: false },
    { name: "Chongqing University of Education", domain: "cquedu.cn", isVerified: true },
    { name: "Yunnan College of Business Management", domain: "yncbm.edu.cn", isVerified: true },
    { name: "Xianyang Normal University", domain: "xynu.edu.cn", isVerified: true },
    { name: "Guangxi Science and Technology Normal University", domain: "gxstnu.edu.cn", isVerified: true },                                        
    { name: "Heihe University", domain: "hhu.edu.cn", isVerified: true },
    { name: "Shanghai Institute of Visual Art", domain: "siva.edu.cn", isVerified: true },
    { name: "Kaili University", domain: "klu.edu.cn", isVerified: true },
    { name: "Liaoning Institute of Science and Technology", domain: "nist.edu.cn", isVerified: true },
    { name: "Hunan Institute of Technology", domain: "hunati.edu.cn", isVerified: true },
    { name: "Qilu Medical University", domain: "qlmu.edu.cn", isVerified: true },
    { name: "Gannan Medical University", domain: "gnmu.edu.cn", isVerified: true },
    { name: "Shenyang Medical College", domain: "symc.edu.cn", isVerified: true },
    { name: "Wuhan University of Engineering Science", domain: "wues.edu.cn", isVerified: true },
    { name: "Zhengzhou University of Science and Technology", domain: "zzust.edu.cn", isVerified: true },
    { name: "Changsha Normal University", domain: "csnu.edu.cn", isVerified: true },
    { name: "Xichang College", domain: "xccollege.edu.cn", isVerified: true },
    { name: "Wuchang Institute of Technology", domain: "wuit.edu.cn", isVerified: true },
    { name: "Hankou University", domain: "huu.edu.cn", isVerified: true },
    { name: "Weifang University of Science and Technology", domain: "wfust.edu.cn", isVerified: true },
    { name: "Hunan Women's University", domain: "hnwu.edu.cn", isVerified: true },
    { name: "Guangxi University of Foreign Languages", domain: "gufl.edu.cn", isVerified: true },
    { name: "Wuhan Business University", domain: "wbu.edu.cn", isVerified: true },
    { name: "Dalian Art College", domain: "dac.edu.cn", isVerified: true },
    { name: "Wenzhou Business College", domain: "wbc.edu.cn", isVerified: true },    
    { name: "Guangzhou College of Commerce", domain: "gzc.edu.cn", isVerified: true },
    { name: "Yang-En University", domain: "yenu.edu.cn", isVerified: true },
    { name: "Bengbu University", domain: "bbu.edu.cn", isVerified: true },
    { name: "Wuchang Shouyi University", domain: "wsu.edu.cn", isVerified: true },
    { name: "Chengdu College of Arts and Sciences", domain: "ccas.edu.cn", isVerified: true },
    { name: "Hangzhou Medical College", domain: "hzmc.edu.cn", isVerified: true },
    { name: "Suqian University", domain: "squ.edu.cn", isVerified: true },
    { name: "Baise University", domain: "bsu.edu.cn", isVerified: true },
    { name: "Hebei Foreign Studies University", domain: "hfsu.edu.cn", isVerified: true },
    { name: "Zhengzhou University of Industrial Technology", domain: "zzuit.edu.cn", isVerified: true },
    { name: "Cangzhou Normal University", domain: "czu.edu.cn", isVerified: true },
    { name: "Wuhan Institute of Bioengineering", domain: "wib.edu.cn", isVerified: true },
    { name: "Jiangsu Second Normal University", domain: "js2nu.edu.cn", isVerified: true },
    { name: "Qingdao Hengxing University of Science and Technology", domain: "qhust.edu.cn", isVerified: true },
    { name: "Henan University of Animal Husbandry and Economy", domain: "huahe.edu.cn", isVerified: true },
    { name: "Sanjiang University", domain: "sju.edu.cn", isVerified: true },
    { name: "Hebei Finance University", domain: "hf-u.edu.cn", isVerified: true },
    { name: "Chengdu Normal University", domain: "cdnu.edu.cn", isVerified: true },
    { name: "Shandong Management University", domain: "sdmu.edu.cn", isVerified: true },
    { name: "Anhui Wonder University of Information Engineering", domain: null, isVerified: false },
    { name: "Sichuan University for Nationalities", domain: "scun.edu.cn", isVerified: true },
    { name: "Yulin University", domain: "yliu.edu.cn", isVerified: true },
    { name: "West Yunnan University", domain: "wnu.edu.cn", isVerified: true },
    { name: "Chongqing Institute of Engineering", domain: "cqie.edu.cn", isVerified: true },
    { name: "Hezhou University", domain: "hzu.edu.cn", isVerified: true },
    { name: "SanQuan Medical College", domain: null, isVerified: false },
    { name: "Xinyu University", domain: "xyu.edu.cn", isVerified: true },
    { name: "Inner Mongolia Arts University", domain: "imu.edu.cn", isVerified: false },
    { name: "Suihua University", domain: "shu.edu.cn", isVerified: true },
    { name: "Changzhi University", domain: "cznu.edu.cn", isVerified: true },
    { name: "Beijing Electronic Science and Technology Institute", domain: null, isVerified: false },
    { name: "Guangzhou Maritime University", domain: "gzm.edu.cn", isVerified: true },
    { name: "Sichuan University of Culture and Arts", domain: "scuac.edu.cn", isVerified: true },
    { name: "Qilu Institute of Technology", domain: "qlit.edu.cn", isVerified: true },
    { name: "Changzhi Medical College", domain: "czmc.edu.cn", isVerified: true },
    { name: "Changchun Guanghua University", domain: "ccghu.edu.cn", isVerified: true },    
    { name: "Taizhou University", domain: "tzc.edu.cn", isVerified: true },
    { name: "West Yunnan University of Applied Sciences", domain: null, isVerified: false },
    { name: "Hunan University of Finance and Economics", domain: "hufe.edu.cn", isVerified: true },
    { name: "Hetao College", domain: "hetaodaxue.com", isVerified: true },
    { name: "Gansu Normal University for Nationalities", domain: "gnun.edu.cn", isVerified: true },
    { name: "Liaodong University", domain: "ldxy.cn", isVerified: true },
    { name: "Qiqihar Medical University", domain: "qmu.edu.cn", isVerified: true },
    { name: "Hebei Academy of Fine Arts", domain: "hbafa.com", isVerified: true },
    { name: "Longdong University", domain: "ldxy.edu.cn", isVerified: true },
    { name: "Zhengzhou Technology and Business University", domain: "ztbu.edu.cn", isVerified: true },
    { name: "Xinyang Agriculture and Forestry University", domain: "xyafu.edu.cn", isVerified: true },
    { name: "Guilin Tourism University", domain: "gltu.edu.cn", isVerified: true },
    { name: "Wuhan College of Media and Communications", domain: "whmc.edu.cn", isVerified: true },
    { name: "Harbin Guangxia University", domain: "gsxy.cn", isVerified: true },
    { name: "Nanchang Institute of Science and Technology", domain: "nit.edu.cn", isVerified: true },
    { name: "Heilongjiang University of Science and Technology", domain: "usth.edu.cn", isVerified: true },
    { name: "Tongren University", domain: "gztrc.edu.cn", isVerified: true },
    { name: "Shandong Huayu University of Technology", domain: null, isVerified: false },
    { name: "Wuxi Taihu University", domain: null, isVerified: false },
    { name: "Qiongtai Normal University", domain: null, isVerified: false },
    { name: "Communication University of Shanxi", domain: null, isVerified: false },
    { name: "Hunan Institute of Traffic Engineering", domain: null, isVerified: false },
    { name: "Beihai College of Art and Design", domain: null, isVerified: false },
    { name: "Yanjing Institute of Technology", domain: null, isVerified: false },
    { name: "NanTong Institute of Technology", domain: null, isVerified: false },
    { name: "Shaanxi Fashion Engineering University", domain: null, isVerified: false },
    { name: "Baoshan University", domain: null, isVerified: false },
    { name: "Shangluo University", domain: null, isVerified: false },
    { name: "Hebei College of Science and Technology", domain: null, isVerified: false },
    { name: "Shandong Xiandai University", domain: null, isVerified: false },
    { name: "Sichuan Tourism University", domain: null, isVerified: false },
    { name: "Nanchang Normal University", domain: "ncsu.edu.cn", isVerified: true },
    { name: "Xinyang University", domain: null, isVerified: false },
    { name: "Jilin Business and Technology College", domain: null, isVerified: false },
    { name: "Zhengzhou Business School", domain: null, isVerified: false },
    { name: "Henan Institute of Technology", domain: "hait.edu.cn", isVerified: true },
    { name: "Tianjin Zhongde University of Applied Sciences", domain: null, isVerified: false },
    { name: "Hunan Institute of Information Technology", domain: null, isVerified: false },
    { name: "Heilongjiang University of Finance and Economics", domain: "hfu.edu.cn", isVerified: true },
    { name: "Wuhan Technology and Business University", domain: "wtbu.edu.cn", isVerified: true },
    { name: "Liaoning Communication University", domain: "lncu.edu.cn", isVerified: true },
    { name: "Jilin Agricultural Science and Technology College", domain: null, isVerified: false },
    { name: "Guangdong Peizheng College", domain: null, isVerified: false },
    { name: "Qingdao Institute of Technology", domain: null, isVerified: false },
    { name: "Inner Mongolia Nationality College", domain: null, isVerified: false },
    { name: "Yunnan Technology and Business University", domain: null, isVerified: false },
    { name: "Anhui International Studies University", domain: "aisu.edu.cn", isVerified: true },
    { name: "Jiangxi Institute of Fashion Technology", domain: null, isVerified: false },
    { name: "Shangqiu Institute of Technology", domain: null, isVerified: false },
    { name: "Anhui Institute of Information Technology", domain: null, isVerified: false },
    { name: "Xinzhou Teachers University", domain: null, isVerified: false },
    { name: "Hubei Business College", domain: null, isVerified: false },
    { name: "Jingdezhen University", domain: "jcu.edu.cn", isVerified: true },
    { name: "Hunan Applied Technology University", domain: "hnat.edu.cn", isVerified: true },
    { name: "Shangqiu University", domain: null, isVerified: false },
    { name: "Changchun Architecture and Civil Engineering College", domain: null, isVerified: false },
    { name: "Liaoning University of International Business and Economics", domain: null, isVerified: false },
    { name: "Guangdong Polytechnic College", domain: null, isVerified: false },
    { name: "Liupanshui Normal University", domain: null, isVerified: false },
    { name: "Hebei University of Environmental Engineering", domain: "hebeuei.edu.cn", isVerified: true },
    { name: "Chengdu Neusoft University", domain: "neusoft.edu.cn", isVerified: true },
    { name: "Anyang University", domain: "ayu.edu.cn", isVerified: true },
    { name: "Bozhou University", domain: null, isVerified: false },
    { name: "Nanning University", domain: "nnxy.edu.cn", isVerified: true },
    { name: "Puer University", domain: "puer.edu.cn", isVerified: true },
    { name: "Jilin Medical University", domain: null, isVerified: false },
    { name: "Neusoft Institute, Guangdong", domain: null, isVerified: false },
    { name: "Shenyang Institute of Technology", domain: "syit.edu.cn", isVerified: true },
    { name: "Shangrao Normal University", domain: null, isVerified: false },
    { name: "Harbin Cambridge University", domain: null, isVerified: false },
    { name: "Aba Teachers University", domain: null, isVerified: false },
    { name: "Hunan University of Medicine", domain: null, isVerified: false },
    { name: "Tibetan Traditional Medical College", domain: null, isVerified: false },
    { name: "Heilongjiang International University", domain: null, isVerified: false },
    { name: "Mudanjiang Medical University", domain: "mdjmu.edu.cn", isVerified: true },
    { name: "Shenyang Urban Construction University", domain: null, isVerified: false },
    { name: "Guizhou University of Commerce", domain: null, isVerified: false },
    { name: "Youjiang Medical University for Nationalities", domain: null, isVerified: false },
    { name: "Wuhan Huaxia Institute of Technology", domain: null, isVerified: false },
    { name: "Guizhou University of Engineering Science", domain: "guet.edu.cn", isVerified: true },
    { name: "Xingyi Normal University for Nationalities", domain: null, isVerified: false },
    { name: "Pingxiang University", domain: null, isVerified: false },
    { name: "Xinjiang Institute of Engineering", domain: null, isVerified: false },
    { name: "Langfang Normal University", domain: "lfsnu.cn", isVerified: true },
    { name: "Minnan University of Science and Technology", domain: "must.edu.cn", isVerified: true },
    { name: "Sichuan Institute of Industrial Technology", domain: null, isVerified: false },
    { name: "Changchun University of Science and Technology", domain: "cjust.edu.cn", isVerified: true },
    { name: "Ordos Institute of Technology", domain: null, isVerified: false },
    { name: "Qiqihar Institute of Engineering", domain: null, isVerified: false },
    { name: "Guangdong University of Science and Technology", domain: null, isVerified: false },
    { name: "Wuhan Qingchuan University", domain: null, isVerified: false },
    { name: "Taiyuan University", domain: null, isVerified: false },
    { name: "Fuzhou Institute of Technology", domain: "fit.edu.cn", isVerified: true },
    { name: "Wuhan Institute of Design and Sciences", domain: null, isVerified: false },
    { name: "Tianjin Tianshi College", domain: null, isVerified: false },
    { name: "Zhaotong University", domain: null, isVerified: false },
    { name: "Yuzhang Normal University", domain: "yznu.edu.cn", isVerified: true },
    { name: "He University", domain: null, isVerified: false },
    { name: "Xi'an Traffic Engineering Institute", domain: null, isVerified: false },
    { name: "Harbin Conservatory of Music", domain: null, isVerified: false },
    { name: "Hebei Normal University for Nationalities", domain: null, isVerified: false },
    { name: "Liaoning Institute of Science and Engineering", domain: null, isVerified: false },
    { name: "Dalian University of Finance and Economics", domain: "dafe.edu.cn", isVerified: true },
    { name: "Harbin Institute of Petroleum", domain: null, isVerified: false },
    { name: "Harbin Finance University", domain: "hrfu.edu.cn", isVerified: true },
    { name: "Sichuan Film and Television University", domain: null, isVerified: false },
    { name: "Shanghai Xingwei College", domain: null, isVerified: false },
    { name: "Moutai Institute", domain: null, isVerified: false },
    { name: "Shanxi Technology and Business College", domain: null, isVerified: false },
    { name: "Gansu Medical College", domain: null, isVerified: false },
    { name: "Harbin Institute of Information Technology", domain: null, isVerified: false },
    { name: "Shanxi Institute of Technology", domain: null, isVerified: false },
    { name: "Heilongjiang University of Technology", domain: null, isVerified: false },
    { name: "Shenyang City University", domain: null, isVerified: false },
    { name: "Yingkou Institute of Technology", domain: null, isVerified: false },
    { name: "Liaoning University of Finance and Trade", domain: "lufist.edu.cn", isVerified: true },
    { name: "Harbin Huade University", domain: null, isVerified: false },
    { name: "Shanxi Institute of Energy", domain: null, isVerified: false },
    { name: "Quanzhou Institute of Information Engineering", domain: null, isVerified: false },
    { name: "Heilongjiang University of Business and Technology", domain: null, isVerified: false },
    { name: "Harbin Far East Institute of Technology", domain: null, isVerified: false },
    { name: "Changchun University of Finance and Economics", domain: "ccufe.edu.cn", isVerified: true },
    { name: "Shanxi College of Applied Science and Technology", domain: null, isVerified: false },
    { name: "Dalian University of Science and Technology", domain: null, isVerified: false },
    { name: "Shenyang Institute of Science and Technology", domain: null, isVerified: false },
    { name: "Jining Normal University", domain: "jnnu.edu.cn", isVerified: true },
    { name: "Hebei Oriental University", domain: null, isVerified: false },
    { name: "Sanming University", domain: null, isVerified: false },
    { name: "Beijing Geely University", domain: null, isVerified: false },
    { name: "Guangdong University of Education", domain: null, isVerified: false },
    { name: "Zhangjiakou University", domain: null, isVerified: false },
    { name: "Wenshan University", domain: null, isVerified: false },
    { name: "Changji University", domain: null, isVerified: false },
    { name: "Yuncheng University", domain: null, isVerified: false }, 
]