import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Colombia_universities = [

   // Colombia

   { name: "Universidad de los Andes, Colombia", domain: "uniandes.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Nacional de Colombia", domain: "unal.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Pontificia Universidad Javeriana", domain: "javeriana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Antioquía", domain: "udea.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Rosario", domain: "urosario.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Valle", domain: "univalle.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Distrital Francisco José de Caldas", domain: "udistrital.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad EAFIT", domain: "eafit.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Industrial de Santander", domain: "uis.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Pontificia Bolivariana", domain: "upb.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Externado de Colombia", domain: "externado.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Minuto de Dios", domain: "uniminuto.edu", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Norte", domain: "uninorte.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de La Sabana", domain: "unisabana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad ICESI", domain: "icesi.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Cooperativa de Colombia", domain: "ucc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Magdalena", domain: "unimagdalena.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Pedagógica y Tecnológica de Colombia", domain: "uptc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Politécnico Grancolombiano", domain: "poligran.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Militar Nueva Granada", domain: "umng.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Santo Tomás", domain: "usantotomas.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Libre", domain: "unilibre.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de La Salle", domain: "lasalle.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Tecnológica de Pereira", domain: "utp.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Bogotá Jorge Tadeo Lozano", domain: "utadeo.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Cauca", domain: "unicauca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad El Bosque", domain: "unbosque.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Nariño", domain: "udenar.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Caldas", domain: "ucaldas.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Pedagógica Nacional", domain: "upn.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Simón Bolívar", domain: "unisimon.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Sergio Arboleda", domain: "universidadsergioarboleda.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Medellín", domain: "udem.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma de Bucaramanga", domain: "unab.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad EAN", domain: "universidadean.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Católica de Colombia", domain: "ucatolica.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Escuela Superior de Administración Pública", domain: "esap.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Instituto Tecnológico Metropolitano", domain: "itm.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria de la Costa", domain: "cuc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Cartagena", domain: "unicartagena.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria del Area Andina", domain: "areandina.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad CES", domain: "ces.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Tecnológica de Bolívar", domain: "utb.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Santander", domain: "udes.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Quindío", domain: "uniquindio.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Pamplona", domain: "unipamplona.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Antonio Nariño", domain: "uan.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Iberoamericana", domain: "ibero.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Tolima", domain: "ut.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Atlántico", domain: "uniatlantico.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Central", domain: "ucentral.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Católica Luis Amigó", domain: "funlam.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Santiago de Cali", domain: "usc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Católica del Norte", domain: "ucn.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma de Occidente", domain: "uao.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Francisco de Paula Santander", domain: "ufps.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad EIA", domain: "eia.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Cundinamarca", domain: "ucundinamarca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Konrad Lorenz", domain: "konradlorenz.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Tecnológico de Antioquia", domain: "tdea.edu.co", region: "South America", country: "Colombia", isVerified: true },    
   { name: "Universidad de Córdoba", domain: "unicordoba.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Manizales", domain: "umanizales.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Piloto de Colombia", domain: "unipiloto.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Ciencias Aplicadas y Ambientales", domain: "udca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Remington", domain: "remington.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma del Caribe", domain: "uac.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Escuela Colombiana de Ingeniería Julio Garavito", domain: "escuelaing.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma de Manizales", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Universidad La Gran Colombia", domain: "ulagrancolombia.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Instituto Caro y Cuervo", domain: "caroycuervo.gov.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria de Envigado", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Colegio de Estudios Superiores de Administración", domain: "cesa.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Compensar", domain: "compensar.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Colegio Mayor de Cundinamarca", domain: "unicolmayor.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Popular del Cesar", domain: "unicesar.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de los Llanos", domain: "unillanos.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de San Buenaventura", domain: "usb.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad ECCI", domain: "ecci.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de la Amazonia", domain: "uamazonica.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Mariana", domain: "umariana.edu.co", region: "South America", country: "Colombia", isVerified: true },    
   { name: "Universidad de Boyacá", domain: "uniboyaca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria de Ciencias de la Salud", domain: "fucsalud.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Surcolombiana", domain: "usco.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Colegio Mayor de Antioquia", domain: "colegiomayor.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de América", domain: "uam.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Instituto Tecnológico Pascual Bravo", domain: "itpascualbravo.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Ibagué", domain: "unibague.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma Latinoamericana", domain: "unila.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Católica de Pereira", domain: "ucp.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Católica de Oriente", domain: "uco.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Rafael Núñez", domain: "curn.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de Sucre", domain: "unisucre.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Americana", domain: "americana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Manuela Beltrán", domain: "umb.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria del Caribe", domain: "unicaribe.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universitaria Agustiniana", domain: "uagustiniana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad CESMAG", domain: "cesmag.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Católica de Manizales", domain: "ucm.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad de La Guajira", domain: "uniguajira.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Politécnico Colombiano Jaime Isaza Cadavid", domain: "politecnicojic.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria CEIPA", domain: "ceipa.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Adventista", domain: "unac.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Colegio Mayor del Cauca", domain: "colmayor.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Los Libertadores", domain: "ulibertadores.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Antonio José Camacho", domain: "uajc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria San Mateo", domain: "usam.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Juan N. Corpas", domain: "corpas.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universidad de Investigación y Desarrollo", domain: "unid.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Unilasallista Corporación Universitaria", domain: "unilasallista.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria de Barranquilla", domain: "unibac.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria San Martín", domain: "fusm.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad INCCA de Colombia", domain: "incca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Católica Lumen Gentium", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Universidad del Sinú", domain: "unisinu.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Juan de Castellanos", domain: "juandecastellanos.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Escuela Tecnológica Instituto Técnico Central", domain: "itc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Antonio José de Sucre", domain: "unisucre.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Claretiana", domain: "claretiana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Tecnológico Comfenalco - Cartagena", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Fundación Universitaria Autónoma de Las Américas", domain: "uam.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad del Pacífico", domain: "unipacifico.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria UNITEC", domain: "unitec.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Tecnológica del Chocó", domain: "utch.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Unidad Central del Valle del Cauca", domain: "uceva.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Sanitas", domain: "unisanitas.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Para el Desarrollo Humano", domain: "uninpahu.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Maria Cano", domain: "mariacano.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma de Colombia", domain: "fuac.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Republicana", domain: "urepublicana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Agraria de Colombia", domain: "uniagraria.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Esumer", domain: "esumer.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Cafam", domain: "unicafam.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Instituto Universitario de La Paz", domain: "unipaz.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Escuela Colombiana de Rehabilitación", domain: "ecr.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Metropolitana, Colombia", domain: "unimetro.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria de San Gil", domain: "unisangil.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria de Popayán", domain: "fup.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Internacional de Colombia", domain: "unincol.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria del Meta", domain: "unimeta.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Colegios de Colombia", domain: "unicoc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Antonio de Arévalo", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Universitaria Comfacauca", domain: "comfacauca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Latinoamericana", domain: "culat.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Empresarial Alexander Von Humboldt", domain: "humboldt.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Autónoma del Cauca", domain: "unica.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Monserrate", domain: "monserrate.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Empresarial de la Cámara de Comercio de Bogotá", domain: "fecbbogota.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Universitaria de Asturias", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Escuela Nacional del Deporte", domain: "ensedep.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Internacional del Trópico Americano", domain: "fuitropico.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Colegiatura Colombiana", domain: "colcolegiatura.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Bellas Artes", domain: "fuba.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Instituto Departamental de Bellas Artes", domain: "idba.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Navarra", domain: "navarra.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria EAM", domain: "eam.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria del Huila", domain: "unihuila.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Cervantes San Agustín", domain: "cervantes.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Taller Cinco", domain: "tallercinco.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Luis G. Páez", domain: "flgpaez.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria de Colombia - Universitaria de Colombia", domain: "uni.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Fundación Escuela Colombiana de Mercadotecnia", domain: "fesc.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Institución Universitaria Salazar y Herrera", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Universitaria de Ciencia y Desarrollo", domain: "uciencia.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Internacional de la Rioja", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Institución Universitaria Colombo Americana", domain: "colomboamericana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Marco Fidel Suárez", domain: "mf-suarez.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Institución Universitaria Mayor de Cartagena", domain: "unimayor.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Bellas Artes y Ciencias de Bolívar", domain: "ibb.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Fundación Universitaria Colombo Internacional", domain: "colombointernacional.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Universitaria de Sabaneta", domain: "unisabaneta.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Autónoma de Nariño", domain: "unan.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universidad Autónoma Indígena Intercultural", domain: "uniai.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Conservatorio del Tolima", domain: "contolima.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Universitaria Reformada", domain: "unireformada.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria de Santa Rosa de Cabal", domain: "unisarc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Horizonte", domain: "horizonte.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Institución Universitaria Latina", domain: "latina.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación de Estudios Superiores Monseñor Abraham Escudero Montoya", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Escuela Tecnológica del Oriente", domain: "cetorientil.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporación Escuela de Artes y Letras", domain: "artesletras.edu.co", region: "South America", country: "Colombia", isVerified: false },
   { name: "Corporacion Universitaria de Cataluña", domain: "ucatalunya.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria CENDA", domain: "cenda.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporacion Universitaria de Ciencias Empresariales, Educacion y Salud", domain: "corsalud.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria San Alfonso", domain: "sanalfonso.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Colombo Germana", domain: "unigermana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria San Pablo", domain: "unisanpablo.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporacion Universitaria U de Colombia", domain: "udecolombia.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación de Estudios Superiores Universitarios de Urabá Antonio Roldán Betancur", domain: "fesu.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Comfenalco Santander", domain: "unc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Salesiana", domain: "salesiana.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Empresarial de Salamanca", domain: "unisalamanca.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Centro Superior", domain: "unicuces.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Escuela Superior de Empresa, Ingeniería y Tecnología", domain: "eseit.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Comfamiliar Risaralda", domain: "uc.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria CIEO", domain: "unicieo.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Misión Paz", domain: "unimisionpaz.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Escuela Tecnológica de Neiva Jesús Oviedo Pérez", domain: "fet.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria de Colombia IDEAS", domain: "ideas.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Universitaria del Chicamocha", domain: "unich.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Regional del Caribe", domain: "iafic.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Católica del Sur", domain: "unicatolicadelsur.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Centro Universitario de Bienestar Rural", domain: null, region: "South America", country: "Colombia", isVerified: false },
   { name: "Fundación Universitaria Patricio Symes", domain: "unisymes.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria FCV", domain: "funiversitariafcv.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Fundación Universitaria Católica del Caribe", domain: "unicatolicadelcaribe.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Corporación Universitaria Autónoma del Norte", domain: "uanorte.edu.co", region: "South America", country: "Colombia", isVerified: true },
   { name: "Institución Universitaria Conocimiento e Innovación para la Justicia", domain: null, region: "South America", country: "Colombia", isVerified: false },
]