import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Costa_Rica_universities = [

   // Costa Rica

   { name: "Universidad de Costa Rica", domain: "ucr.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Nacional", domain: "una.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Instituto Tecnológico de Costa Rica", domain: "itcr.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "INCAE Business School, Costa Rica", domain: "incae.edu", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Latina de Costa Rica", domain: "ulatina.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad EARTH", domain: "earth.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Latinoamericana de Ciencia y Tecnología", domain: "ulacit.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Técnica Nacional", domain: "utn.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Internacional de las Américas", domain: "uniamericas.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Hispanoamericana", domain: "usah.edu.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Fidélitas", domain: "ufidelitas.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad LCI VERITAS", domain: "veritas.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Autónoma de Centro América", domain: "uaca.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad para la Cooperación Internacional", domain: "uci.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de Cartago Florencio del Castillo", domain: "ucr.ac.cr/cartago", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Central, Costa Rica", domain: "ucentral.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Cenfotec", domain: "cenfotec.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Americana, Costa Rica", domain: "uam.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad San Marcos", domain: "usam.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de Iberoamérica", domain: "ibero.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },  
   { name: "Universidad Politécnica Internacional", domain: "upi.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de Ciencias Médicas, Costa Rica", domain: "ucimed.com", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "LEAD University", domain: "ulead.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Libre de Costa Rica", domain: "ulicori.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Bíblica Latinoamericana", domain: "ubl.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Católica de Costa Rica", domain: "ucatolica.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de la Salle Costa Rica", domain: "ulasalle.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de las Ciencias y el Arte de Costa Rica", domain: "udelascienciasyelarte.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Fundepos Alma Mater", domain: "fundepos.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Creativa", domain: "ucreativa.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Castro Carazo", domain: "castrocarazo.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Santa Paula", domain: "usantapaula.com", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Federada San Judas Tadeo", domain: "usanjudas.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Adventista de Centro América", domain: "unadeca.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad del Turismo", domain: "utur.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Internacional San Isidro Labrador", domain: "uisil.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Empresarial de Costa Rica", domain: "unem.international", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad San Juan de la Cruz", domain: "universidadsanjuan.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Invenio", domain: "invenio.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de Ciencias Empresariales", domain: "ucem.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Isaac Newton", domain: "uin.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Escuela Libre de Derecho", domain: "uescuelalibre.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Magister", domain: "umagister.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Tecnológica Costarricense", domain: "utc.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Santa Lucía", domain: "usl.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Juan Pablo II", domain: "ujpii.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Panamericana, Costa Rica", domain: "upanamericana.net", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Centroamericana de Ciencias Sociales", domain: "ucacis.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Independiente de Costa Rica", domain: "uindependiente.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Continental de las Ciencias y las Artes", domain: "uccart.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad de San José", domain: "usj.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Braulio Carrillo", domain: "ubcarrillo.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Evangélica de las Américas", domain: "unela.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Neotropical", domain: "uneotropical.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
   { name: "Universidad Metodista de Costa Rica", domain: "umetodista.ac.cr", region: "North America", country: "Costa Rica", isVerified: true },
]