import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Cuba_universities = [

   // Cuba

   { name: "Universidad de La Habana", domain: "uh.cu", region: "North America", country: "Cuba", isVerified: true },                  
   { name: "Universidad Central Marta Abreu de Las Villas", domain: "uclv.edu.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Universidad Tecnológica de la Habana José Antonio Echeverría", domain: "cujae.edu.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Universidad de las Ciencias Informáticas", domain: "uci.cu", region: "North America", country: "Cuba", isVerified: true },     
   { name: "Universidad de Cienfuegos Carlos Rafael Rodríguez", domain: "ucf.edu.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Universidad de Pinar del Río Hermanos Saíz Montes de Oca", domain: "upr.edu.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Universidad de Oriente", domain: "uo.edu.cu", region: "North America", country: "Cuba", isVerified: true },                   
   { name: "Universidad de Granma", domain: "udg.edu.cu", region: "North America", country: "Cuba", isVerified: true },                   
   { name: "Universidad de Sancti Spíritus José Martí Pérez", domain: "suss.co.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Instituto Superior de Diseño", domain: "isdi.co.cu", region: "North America", country: "Cuba", isVerified: true },            
   { name: "Universidad de Holguín", domain: "uho.edu.cu", region: "North America", country: "Cuba", isVerified: true },                  
   { name: "Universidad de Las Tunas", domain: "ult.edu.cu", region: "North America", country: "Cuba", isVerified: true },                
   { name: "Universidad de Matanzas", domain: "umcc.cu", region: "North America", country: "Cuba", isVerified: true },                    
   { name: "Universidad de Ciego de Ávila Máximo Gómez Báez", domain: "unica.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Universidad de Moa Dr Antonio Núñez Jiménez", domain: "ismm.edu.cu", region: "North America", country: "Cuba", isVerified: true },    
   { name: "Universidad Agraria de La Habana Fructuoso Rodríguez Pérez", domain: "unah.edu.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Instituto Superior de Relaciones Internacionales Raúl Roa García", domain: "isri.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "Instituto Nacional de Ciencias Agrícolas", domain: "inca.edu.cu", region: "North America", country: "Cuba", isVerified: true },   
   { name: "Universidad de Ciencias de la Cultura Física y el Deporte Manuel Fajardo", domain: "uccfd.cu", region: "North America", country: "Cuba", isVerified: true },  
   { name: "ISA, Universidad de las Artes", domain: "isa.cult.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Artemisa", domain: "ua.uart.edu.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Matanzas", domain: "ucm.mtz.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas, Cienfuegos", domain: "ucm.cfg.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Villa Clara", domain: "ucm.vcl.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Sancti Spíritus", domain: "ucmss.ssp.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Ciego de Ávila", domain: "universidad.cav.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Camagüey", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Médicas de Holguín", domain: "ucmho.hlg.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Granma", domain: "ucm.grm.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Guantánamo", domain: "ucm.gtm.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Santiago de Cuba", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Médicas de Las Tunas", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Instituto Superior de Tecnologías y Ciencias Aplicadas", domain: "instec.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de Pinar del Río", domain: "ucm.pri.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Pedagógicas Félix Varela Morales", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Pedagógicas José de la Luz y Caballero", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Pedagógicas Enrique José Varona", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Pedagógicas Frank País García", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Pedagógicas Pepito Tey", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Ciencias Pedagógicas Héctor Alfredo Pineda Zaldívar", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Instituto de Ciencia Animal", domain: "ica.inf.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de la Isla de la Juventud Jesús Montané Oropesa", domain: "uij.edu.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Escuela Latinoamericana de Medicina", domain: null, region: "North America", country: "Cuba", isVerified: false },
   { name: "Universidad de Guantánamo", domain: "cug.co.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Ciencias Médicas de La Habana", domain: "ucmh.sld.cu", region: "North America", country: "Cuba", isVerified: true },
   { name: "Universidad de Camagüey Ignacio Agramonte Loynaz", domain: "reduc.edu.cu", region: "North America", country: "Cuba", isVerified: true },
]