import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Cyrus_universities = [

   // Cyprus

   { name: "University of Cyprus", domain: "ucy.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "University of Nicosia", domain: "unic.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Dogu Akdeniz Üniversitesi", domain: "emu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "European University Cyprus", domain: "euc.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Cyprus University of Technology", domain: "cut.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Yakin Dogu Üniversitesi", domain: "neu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Uluslararası Kibris Üniversitesi", domain: "ciu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "The Cyprus Institute", domain: "cyi.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Frederick University", domain: "frederick.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Girne Amerikan Üniversitesi", domain: "gau.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Neapolis University Pafos", domain: "nup.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "University of Limassol", domain: "uol.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "University of Central Lancashire, Cyprus", domain: "uclancyprus.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Lefke Avrupa Üniversitesi", domain: "eul.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Girne Üniversitesi", domain: "kyrenia.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Uluslararasi Final Üniversitesi", domain: "final.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Cyprus College", domain: "cycollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Orta Dogu Teknik Universitesi Kuzey Kibris Kampusu", domain: "metu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "American College", domain: "ac.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "CIM-Cyprus Business School", domain: "cim.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Intercollege", domain: "intercollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Kibris İlim Üniversitesi", domain: "kiu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Kibris Sağlik ve Toplum Bilimleri Üniversitesi", domain: "kstbu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Arkin Yaratici Sanatlar ve Tasarim Üniversitesi", domain: "arusat.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Kibris Amerikan Üniversitesi", domain: "ciu.edu.tr", region: "Europe", country: "Cyprus", isVerified: false },
   { name: "Akdeniz Karpaz Üniversitesi", domain: "akun.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "P.A. College", domain: "pacollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "The CTL Eurocollege", domain: "ctleuro.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Alexander College", domain: "alexander.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Bahçeşehir Kibris Üniversitesi", domain: "bau.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "College of Tourism and Hotel Management", domain: "cth.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Casa College", domain: "casacollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "KES College", domain: "kes.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "City Unity College Nicosia", domain: "cityu.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Kibris Bati Üniversitesi", domain: "wcu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Rauf Denktaş Üniversitesi", domain: "rdu.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Mediterranean Institute of Management", domain: "mim.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "The Philips College", domain: "philips.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "C.D.A. College", domain: "cdacollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Global College", domain: "globalcollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Ada Kent Üniversitesi", domain: "adakent.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "The Limassol College", domain: "limassolcollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Onbeş Kasim Kibris Üniversitesi", domain: "15kasim.edu.tr", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Larnaca College", domain: "larnacacollege.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "InterNapa College", domain: "internapa.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Atlantis College", domain: "atlantiscollege.com.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Mesoyios College", domain: "mesoyios.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "Ledra College", domain: "ledra.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "ARTE Music Academy", domain: "arte-music.com", region: "Europe", country: "Cyprus", isVerified: true },
   { name: "The Cyprus Institute of Neurology and Genetics", domain: "cing.ac.cy", region: "Europe", country: "Cyprus", isVerified: true },
]