import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Czech_Republic_universities = [

    // Czech Republic
  
    { name: "Univerzita Karlova", domain: "cuni.cz", isVerified: true },
    { name: "Masarykova univerzita", domain: "muni.cz", isVerified: true },
    { name: "České vysoké učení technické v Praze", domain: "cvut.cz", isVerified: true },
    { name: "Vysoké učení technické v Brně", domain: "vut.cz", isVerified: true },
    { name: "Univerzita Palackého v Olomouci", domain: "upol.cz", isVerified: true },
    { name: "Západoceská Univerzita v Plzni", domain: "zcu.cz", isVerified: true },
    { name: "Vysoká škola ekonomická v Praze", domain: "vse.cz", isVerified: true },
    { name: "VŠB - Technická univerzita Ostrava", domain: "vsb.cz", isVerified: true },
    { name: "Česká zemědělská univerzita v Praze", domain: "czu.cz", isVerified: true },
    { name: "Jihočeská univerzita v Českých Budějovicích", domain: "jcu.cz", isVerified: true },
    { name: "Mendelova univerzita v Brně", domain: "mendelu.cz", isVerified: true },
    { name: "Ostravská univerzita", domain: "osu.cz", isVerified: true },
    { name: "Vysoká škola chemicko-technologická v Praze", domain: "vscht.cz", isVerified: true },
    { name: "Technická Univerzita v Liberci", domain: "tul.cz", isVerified: true },
    { name: "Univerzita Pardubice", domain: "upce.cz", isVerified: true },
    { name: "Univerzita Jana Evangelisty Purkyně v Ústí nad Labem", domain: "ujep.cz", isVerified: true },
    { name: "Univerzita Tomáše Bati ve Zlíně", domain: "utb.cz", isVerified: true },
    { name: "Slezská univerzita v Opavě", domain: "slu.cz", isVerified: true },
    { name: "Univerzita Hradec Králové", domain: "uhk.cz", isVerified: true },
    { name: "Veterinární univerzita Brno", domain: "vfu.cz", isVerified: true },
    { name: "Vysoká škola umeleckoprumyslová v Praze", domain: "umprum.cz", isVerified: true },
    { name: "Vysoká škola Ambis", domain: "ambis.cz", isVerified: true },
    { name: "Vysoká škola finanční a správní", domain: "vsfs.cz", isVerified: true },
    { name: "Janáčkova akademie múzických umění", domain: "jamu.cz", isVerified: true },
    { name: "Akademie výtvarných umění v Praze", domain: "avu.cz", isVerified: true },
    { name: "University of New York in Prague", domain: "unyp.cz", isVerified: true },
    { name: "Vysoká škola CEVRO", domain: "cevroinstitut.cz", isVerified: true },
    { name: "Akademie múzických umění v Praze", domain: "amu.cz", isVerified: true },
    { name: "Panevropská univerzita", domain: "paneurouni.com", isVerified: true },
    { name: "Metropolitní univerzita v Praze", domain: "mup.cz", isVerified: true },
    { name: "Anglo-americká vysoká škola", domain: "aauni.cz", isVerified: true },
    { name: "Vysoká škola technická a ekonomická v Českých Budějovicích", domain: "vste.cz", isVerified: true },
    { name: "Vysoká škola polytechnická Jihlava", domain: "vspj.cz", isVerified: true },
    { name: "Škoda Auto Vysoká škola", domain: "skoda-auto-university.com", isVerified: true },
    { name: "Unicorn University", domain: "unicornuniversity.net", isVerified: true },
    { name: "Vysoká škola ekonomie a managementu", domain: "vsem.cz", isVerified: true },
    { name: "Prague City University", domain: "praguecityuniversity.cz", isVerified: true },
    { name: "Newton University", domain: "newtonuniversity.eu", isVerified: true },
    { name: "University College Prague", domain: "ucp.cz", isVerified: true },
    { name: "Moravská vysoká škola Olomouc", domain: "mvs.cz", isVerified: true },
    { name: "Univerzita Jana Amose Komenského Praha", domain: "ujak.cz", isVerified: true },
    { name: "Vysoká škola hotelová a ekonomická", domain: "vshe.cz", isVerified: true },
    { name: "Vysoká škola telesné výchovy a sportu Palestra", domain: "palestra.cz", isVerified: true },
    { name: "Vysoká škola logistiky", domain: "vslg.cz", isVerified: true },
    { name: "Architectural Institute in Prague", domain: null, isVerified: false },
    { name: "Vysoká škola evropských a regionálních studií", domain: "vsevs.cz", isVerified: true },
    { name: "Vysoká škola zdravotnická", domain: "vsz.cz", isVerified: true },
    { name: "Pražská vysoká škola psychosociálních studií", domain: "pvpps.cz", isVerified: true },
    { name: "Vysoká škola kreativní komunikace", domain: "vskk.cz", isVerified: true },
    { name: "European Research University", domain: "eru.cz", isVerified: true },
    { name: "Vysoká škola Sting", domain: "sting.cz", isVerified: true },
    { name: "Filmová akademie Miroslava Ondříčka v Písku", domain: null, isVerified: false },
    { name: "Akademie HUSPOL", domain: "huspol.cz", isVerified: true },
    { name: "Vysoká škola obchodní a hotelová", domain: "vsoh.cz", isVerified: true },
    { name: "Vysoká škola aplikované psychologie", domain: "vsap.cz", isVerified: true },
    { name: "Art and Design Institut", domain: null, isVerified: false },
    { name: "Københavns Universitet", domain: "ku.dk", isVerified: true },
    { name: "Aarhus Universitet", domain: "au.dk", isVerified: true },
    { name: "Danmarks Tekniske Universitet", domain: "dtu.dk", isVerified: true },
    { name: "Aalborg Universitet", domain: "aau.dk", isVerified: true },
    { name: "Syddansk Universitet", domain: "sdu.dk", isVerified: true },
    { name: "Handelshøjskolen i København", domain: "cbs.dk", isVerified: true },
    { name: "Roskilde Universitet", domain: "ruc.dk", isVerified: true },
    { name: "IT-Universitetet i København", domain: "itu.dk", isVerified: true },
    { name: "University College Lillebaelt", domain: "ucl.dk", isVerified: true },
    { name: "Det Kongelige Akademi - Arkitektur, Design, Konservering", domain: "kadk.dk", isVerified: true },
    { name: "Københavns Erhvervsakademi", domain: "kea.dk", isVerified: true },
    { name: "Danmarks Medie- og journalisthøjskole", domain: "dmjx.dk", isVerified: true },
    { name: "Designskolen Kolding", domain: "designskolenkolding.dk", isVerified: true },
    { name: "Arkitektskolen Aarhus", domain: "aarch.dk", isVerified: true },
    { name: "Det Kongelige Danske Musikkonservatorium", domain: "dkdm.dk", isVerified: true },
    { name: "Erhvervsakademi Aarhus", domain: "eaaa.dk", isVerified: true },
    { name: "Erhvervsakademi Sjælland", domain: "zealand.dk", isVerified: true },
    { name: "Det Kongelige Danske Kunstakademi, Billedkunstskolerne", domain: "kunstakademiet.dk", isVerified: true },
    { name: "Erhvervsakademiet Copenhagen Business", domain: "cphbusiness.dk", isVerified: true },
    { name: "IBA Erhvervsakademi Kolding", domain: "iba.dk", isVerified: true },
    { name: "Det Jyske Musikkonservatorium", domain: "musikkons.dk", isVerified: true },
    { name: "Erhvervsakademi Dania", domain: "eadania.dk", isVerified: true },
    { name: "Den Danske Scenekunstskole", domain: "ddsks.dk", isVerified: true },
    { name: "Syddansk Musikkonservatorium", domain: "sdmk.dk", isVerified: true },
    { name: "Erhvervsakademi SydVest", domain: "easv.dk", isVerified: true },
    { name: "Erhvervsakademi Midtvest", domain: "eamv.dk", isVerified: true },
]