import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Dominican_Republic_universities = [

   // Dominican Republic

   { name: "Universidad Autónoma de Santo Domingo", domain: "uasd.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Tecnológica de Santiago", domain: "utesa.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Pontificia Universidad Católica Madre y Maestra", domain: "pucmm.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Instituto Tecnológico de Santo Domingo", domain: "intec.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Iberoamericana", domain: "unibe.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad del Caribe", domain: "unicaribe.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Instituto Superior de Formación Docente Salomé Ureña", domain: "isfodosu.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Instituto Tecnológico de Las Américas", domain: "itla.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Nacional Pedro Henríquez Ureña", domain: "unphu.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad APEC", domain: "unapec.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Central del Este", domain: "uce.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Escuela Nacional de la Judicatura", domain: "enj.org", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Católica Santo Domingo", domain: "ucsd.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Dominicana O&M", domain: "udoym.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Instituto Técnico Superior Comunitario", domain: "itsc.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Instituto Politécnico Loyola", domain: "ipl.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Católica Nordestana", domain: "ucne.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Tecnológica del Cibao Oriental", domain: "uteco.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Federico Henríquez y Carvajal", domain: "ufhec.edu.do", region: "North America", country: "Dominican Republic", isVerified: true }, 
   { name: "Universidad Católica del Cibao", domain: "ucateci.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Católica Tecnológica de Barahona", domain: "ucateba.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Barna Business School", domain: "barna.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Nacional Evangélica", domain: "unev.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Adventista Dominicana", domain: "unad.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto Superior Pedro Francisco Bonó", domain: "bono.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad ISA", domain: "isa.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Agroforestal Fernando Arturo de Meriño", domain: "uafam.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Eugenio María de Hostos", domain: "uniremhos.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Nacional Tecnológica", domain: "unnatec.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Tecnológica del Sur", domain: "utesur.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Domínico-Americana", domain: "unicda.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto Global de Altos Estudios en Ciencias Sociales", domain: "iglobal.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad INCE", domain: "ince.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto de Educación Superior en Formación Diplomática y Consular", domain: "inesdyc.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Experimental Felix Adam", domain: "unefa.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Católica del Este", domain: "ucade.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Psicología Industrial Dominicana", domain: "upid.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto Especializado de Investigación y Formación en Ciencias Jurídicas", domain: "iomg.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto Técnico Superior Mercy Jácquez", domain: "mercyjacquez.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Universidad Odontológica Dominicana", domain: "uod.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto Superior de Estudios Especializados en Ciencias Sociales y Humanidades", domain: "ies-lhb.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
   { name: "Instituto Dominicano de Tecnología", domain: "idt.edu.do", region: "North America", country: "Dominican Republic", isVerified: true },
]