import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const DRC_universities = [

    // Democratic Republic of the Congo

    { name: "Université Adventiste de Goma", domain: "uagom.com", isVerified: true },
    { name: "Université Officielle de Bukavu", domain: "uob.ac.cd", isVerified: true },
    { name: "Université de Kikwit", domain: "unikik.ac.cd", isVerified: true },
    { name: "Université Protestante de Lubumbashi", domain: "upl-univ.ac", isVerified: true },
    { name: "Université Pédagogique Nationale", domain: "upnrdc.net", isVerified: true },
    { name: "Université de Kolwezi", domain: "unikol.ac.cd", isVerified: true },
    { name: "Université de Kinshasa", domain: "unikin.ac.cd", isVerified: true },
    { name: "Université Saint Augustin de Kinshasa", domain: "usakin.ac.cd", isVerified: true },
    { name: "Université de Lubumbashi", domain: "unilu.ac.cd", isVerified: true },
    { name: "Université catholique du Congo", domain: null, isVerified: false },
    { name: "Université Catholique de Bukavu", domain: "ucbukavu.ac.cd", isVerified: true },
    { name: "Université Libre des Pays des Grands Lacs", domain: "ulpgl.net", isVerified: true },
    { name: "Université Protestante du Congo", domain: "upc.ac.cd", isVerified: true },
    { name: "Université Evangélique en Afrique", domain: "uea.ac.cd", isVerified: true },
    { name: "Université Shalom de Bunia", domain: "unishabunia.org", isVerified: true },
    { name: "Université de Kisangani", domain: "unikis.ac.cd", isVerified: true },
    { name: "Université de Mbuji Mayi", domain: "um.ac.cd", isVerified: true },
    { name: "Université Notre Dame du Kasayi", domain: "uka.ac.cd", isVerified: true },
    { name: "Université de Goma", domain: "unigom.ac.cd", isVerified: true },
    { name: "Adventist University of Lukanga", domain: "uniluk.org", isVerified: true },  
    { name: "Université Officielle de Ruwenzori", domain: null, isVerified: false },
    { name: "Université Loyola du Congo", domain: "uloco.ac.cd", isVerified: true },
    { name: "Université Libre de Kinshasa", domain: "ulk.ac.cd", isVerified: true },
    { name: "Université Technologique Bel Campus", domain: "utbc.ac.cd", isVerified: true },
    { name: "Université Catholique du Graben", domain: "ucg.ac.cd", isVerified: true },
    { name: "Université de l'Uélé", domain: "uele-univ.ac.cd", isVerified: true },
    { name: "Université de Kalemie", domain: "unikalemie.ac.cd", isVerified: true },
    { name: "Université Kongo", domain: "unkongo.ac.cd", isVerified: true },
    { name: "Université Simon Kimbangu", domain: "usk.ac.cd", isVerified: true },
    { name: "Université de Lisala", domain: "unilisala.ac.cd", isVerified: true },
    { name: "Université de Kindu", domain: "unkindu.ac.cd", isVerified: true },
    { name: "Université William Booth", domain: "uwb.ac.cd", isVerified: true },
    { name: "Université Anglicane du Congo", domain: "uac.ac.cd", isVerified: true },
    { name: "Université de Likasi", domain: "unilikasi.ac.cd", isVerified: true },
    { name: "Université de Kamina", domain: "unikamina.ac.cd", isVerified: true },
    { name: "Université Officielle de Mweka", domain: null, isVerified: false },
    { name: "Université de Conservation de la Nature et de Développement", domain: "ucnd.org.cd", isVerified: true },
    { name: "Université Sainte-Croix de Mulo", domain: null, isVerified: false },
    { name: "Université de Mwene-Ditu", domain: "unimd.ac.cd", isVerified: true },
    { name: "Université Joseph Kasa-Vubu", domain: "ujkb.ac.cd", isVerified: true },
    { name: "Université Officielle de Mbujimayi", domain: "uombuj.ac.cd", isVerified: true },
    { name: "Université Pédagogique de Kananga", domain: "upk.ac.cd", isVerified: true },
    { name: "Université du Kwango", domain: "unikwango.ac.cd", isVerified: true },
    { name: "Université de Lodja", domain: "unilodja.ac.cd", isVerified: true },
    { name: "Université Patrice Emery Lumumba", domain: "upel.ac.cd", isVerified: true },
    { name: "Université Protestante de Kimpese", domain: "upkimpese.ac.cd", isVerified: true },
    { name: "Université de Bunia", domain: "unibunia.ac.cd", isVerified: true },
    { name: "Université Notre Dame de Lomami", domain: "undl.ac.cd", isVerified: true },
    { name: "Université des Sciences et Technologies de Lodja", domain: "ustl.ac.cd", isVerified: true },
    { name: "Université de Kananga", domain: "unikanga.ac.cd", isVerified: true },
    { name: "Université de Kabinda", domain: "unikabinda.ac.cd", isVerified: true },
    { name: "Université de Gbadolite", domain: "unigbadolite.ac.cd", isVerified: true },
    { name: "Université Officielle de Semuliki", domain: null, isVerified: false },
    { name: "Université du Cinquantenaire de Lwiro", domain: null, isVerified: false },
    { name: "Université Notre Dame de Tshumbe", domain: "undt.ac.cd", isVerified: true },
    { name: "Université du Moyen Lualaba de Kalima au Maniema", domain: null, isVerified: false },
    { name: "Université de Malemba Nkulu", domain: null, isVerified: false },
    { name: "Université Catholique Don Peti", domain: null, isVerified: false },
    { name: "Université Divina Gloria", domain: null, isVerified: false },
    { name: "Université du Cepromad", domain: null, isVerified: false },
    { name: "Université Libre de Luozi", domain: null, isVerified: false },
    { name: "Université de Mbandaka", domain: "unimbanda.ac.cd", isVerified: true },
    { name: "Université Méthodiste au Katanga", domain: null, isVerified: false },
    { name: "Université Chrétienne de Kinshasa", domain: "uck.ac.cd", isVerified: true },
    { name: "Université de Bandundu", domain: "unibandundu.ac.cd", isVerified: true },
    { name: "Université Chrétienne Cardinal Malula", domain: null, isVerified: false },
]