import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Ecuador_universities = [

   // Ecuador

   { name: "Universidad Central del Ecuador", domain: "uce.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Politécnica Salesiana", domain: "ups.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad San Francisco de Quito", domain: "usfq.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Escuela Superior Politécnica del Litoral", domain: "espol.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Guayaquil", domain: "ug.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica Particular de Loja", domain: "utpl.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Escuela Politécnica Nacional", domain: "epn.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Estatal de Milagro", domain: "unemi.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Cuenca", domain: "ucuenca.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Pontificia Universidad Católica del Ecuador", domain: "puce.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Las Américas", domain: "udla.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Escuela Superior Politécnica de Chimborazo", domain: "espoch.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Andina Simón Bolívar, Ecuador", domain: "uasb.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Nacional de Loja", domain: "unl.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica de Ambato", domain: "uta.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica de Manabí", domain: "utm.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Nacional de Chimborazo", domain: "unach.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad del Azuay", domain: "uazuay.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Tecnológica Equinoccial", domain: "ute.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Católica de Santiago de Guayaquil", domain: "ucsg.edu.ec", region: "South America", country: "Ecuador", isVerified: true },  
   { name: "Universidad Tecnica de Machala", domain: "utmachala.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica del Norte", domain: "utn.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica Estatal de Quevedo", domain: "uteq.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Laica Eloy Alfaro de Manabi", domain: "uleam.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Catolica de Cuenca", domain: "ucacue.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Especialidades del Espíritu Santo", domain: "uees.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Facultad Latinoamericana de Ciencias Sociales, Ecuador", domain: "flacso.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica de Babahoyo", domain: "utb.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Estatal Amazonica", domain: "uea.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Internacional del Ecuador", domain: "uide.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Estatal Península de Santa Elena", domain: "upse.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Técnica de Cotopaxi", domain: "utc.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Estatal de Bolívar", domain: "ueb.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Estatal del Sur de Manabi", domain: "unesum.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Indoamérica", domain: "indoamerica.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Nacional de Educación", domain: "unae.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Regional Autonoma de los Andes", domain: "uniandes.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Instituto de Altos Estudios Nacionales", domain: "iaen.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Particular San Gregorio de Portoviejo", domain: "sangregorio.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Ecotec", domain: "ecotec.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Politecnica Estatal del Carchi", domain: "upec.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Laica Vicente Rocafuerte de Guayaquil", domain: "ulvr.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Internacional SEK", domain: "uisek.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Israel", domain: "uisrael.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Los Hemisferios", domain: "uhemisferios.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Yachay Tech", domain: "yachaytech.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Casa Grande", domain: "casagrande.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Regional Amazónica IKIAM", domain: "ikiam.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de las Artes", domain: "uartes.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Agraria del Ecuador", domain: "uagraria.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Metropolitana, Ecuador", domain: "umet.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad del Pacifico, Ecuador", domain: "upacifico.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Escuela Superior Politecnica Agropecuaria de Manabi", domain: "espam.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Iberoamericana del Ecuador", domain: "unibe.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Tecnica Luis Vargas Torres", domain: "utelvt.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Tecnológica Empresarial de Guayaquil", domain: "uteg.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Otavalo", domain: "uotavalo.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad de Especialidades Turísticas", domain: "ueturistica.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
   { name: "Universidad Santa María Campus Guayaquil", domain: "usm.edu.ec", region: "South America", country: "Ecuador", isVerified: true },
]