import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Egypt_universities = [

    // Egypt

    { name: "The American University in Cairo", domain: "auc.edu.eg", isVerified: true },
    { name: "Mansoura University", domain: "mans.edu.eg", isVerified: true },
    { name: "Cairo University", domain: "cu.edu.eg", isVerified: true },
    { name: "Ain Shams University", domain: "asu.edu.eg", isVerified: true },
    { name: "Future University in Egypt", domain: "fue.edu.eg", isVerified: true },
    { name: "Alexandria University", domain: "alexu.edu.eg", isVerified: true },
    { name: "Al-Azhar University", domain: "azhar.edu.eg", isVerified: true },
    { name: "Arab Academy for Science, Technology and Maritime Transport", domain: "aast.edu", isVerified: true },
    { name: "Helwan University", domain: "hu.edu.eg", isVerified: true },
    { name: "Tanta University", domain: "tanta.edu.eg", isVerified: true },
    { name: "Zagazig University", domain: "zu.edu.eg", isVerified: true },
    { name: "Assiut University", domain: "aun.edu.eg", isVerified: true },
    { name: "The German University in Cairo", domain: "guc.edu.eg", isVerified: true },
    { name: "Benha University", domain: "bu.edu.eg", isVerified: true },
    { name: "Misr University for Science and Technology", domain: "must.edu.eg", isVerified: true },
    { name: "Suez Canal University", domain: "scu.edu.eg", isVerified: true },
    { name: "Nile University", domain: "nu.edu.eg", isVerified: true },
    { name: "Minia University", domain: "minia.edu.eg", isVerified: true },
    { name: "Egypt-Japan University of Science and Technology", domain: "ejust.edu.eg", isVerified: true },
    { name: "Modern Sciences and Arts University", domain: "msa.edu.eg", isVerified: true },  
    { name: "The British University in Egypt", domain: "bue.edu.eg", isVerified: true },
    { name: "Pharos University in Alexandria", domain: "pharos.edu.eg", isVerified: true },
    { name: "South Valley University", domain: "svu.edu.eg", isVerified: true },
    { name: "Sohag University", domain: "sohag-univ.edu.eg", isVerified: true },
    { name: "Kafrelsheikh University", domain: "kfs.edu.eg", isVerified: true },
    { name: "October 6 University", domain: "o6u.edu.eg", isVerified: true },
    { name: "Menoufia University", domain: null, isVerified: false },
    { name: "Nahda University", domain: "nahdauniversity.com", isVerified: true },
    { name: "University of Science and Technology at Zewail City", domain: "zewailcity.edu.eg", isVerified: true },
    { name: "Beni-Suef University", domain: "bsu.edu.eg", isVerified: true },
    { name: "Fayoum University", domain: "fayoum.edu.eg", isVerified: true },
    { name: "Mansoura University", domain: "mans.edu.eg", isVerified: true },
    { name: "The Arab Academy for Management, Banking and Financial Sciences", domain: "aambfs.edu.eg", isVerified: true },
    { name: "Misr International University", domain: "miu.edu.eg", isVerified: true },
    { name: "Aswan University", domain: "aswu.edu.eg", isVerified: true },
    { name: "Delta University for Science and Technology", domain: "dust.edu.eg", isVerified: true },
    { name: "Modern University for Technology and Information", domain: "mti.edu.eg", isVerified: true },
    { name: "Damanhour University", domain: "damanhour.edu.eg", isVerified: true },
    { name: "Egyptian Chinese University", domain: "ecu.edu.eg", isVerified: true },
    { name: "Heliopolis University", domain: "heliopolisuniversity.edu.eg", isVerified: true },  
    { name: "Damietta University", domain: "damietta.edu.eg", isVerified: true },
    { name: "Sinai University", domain: "sinaiuniv.edu.eg", isVerified: true },
    { name: "King Salman International University", domain: "ksiu.edu.eg", isVerified: true },
    { name: "Badr University in Cairo", domain: null, isVerified: false },
    { name: "Port Said University", domain: "psu.edu.eg", isVerified: true },
    { name: "Université Française d'Égypte", domain: "ufe.edu.eg", isVerified: true },
    { name: "University of Sadat City", domain: null, isVerified: false },
    { name: "Sphinx University", domain: "sphinxuniversity.edu.eg", isVerified: true },
    { name: "New Giza University", domain: "newgiza.edu.eg", isVerified: true },
    { name: "Ahram Canadian University", domain: "acu.edu.eg", isVerified: true },
    { name: "Galala University", domain: "galala.edu.eg", isVerified: true },
    { name: "Al Alamein International University", domain: "aiu.edu.eg", isVerified: true },
    { name: "New Valley University", domain: "nvu.edu.eg", isVerified: true },
    { name: "Egyptian Russian University", domain: "eru.edu.eg", isVerified: true },
    { name: "Deraya University", domain: "deraya.edu.eg", isVerified: true },
    { name: "Suez University", domain: "suez.edu.eg", isVerified: true },
    { name: "Arish University", domain: "arish.edu.eg", isVerified: true },
    { name: "Egypt University of Informatics", domain: "eui.edu.eg", isVerified: true },
    { name: "Luxor University", domain: "luxor.edu.eg", isVerified: true },
    { name: "Matrouh University", domain: "matrouh.edu.eg", isVerified: true },
]