import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Ethiopia_universities = [

    // Ethiopia

    { name: "Addis Ababa University", domain: "aau.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Jimma University", domain: "ju.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Bahir Dar University", domain: "bdu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "University of Gondar", domain: "uog.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Hawassa University", domain: "hawassauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Mekelle University", domain: "mu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Haramaya University", domain: "haramaya.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Adama Science and Technology University", domain: "astu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Arba Minch University", domain: "amu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Jigjiga University", domain: "jigjigauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Addis Ababa Science and Technology University", domain: "aastu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Ambo University", domain: "ambo.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Dilla University", domain: "dillau.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Unity University", domain: "unityuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Debre Berhan University", domain: "dbu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Wollo University", domain: "wollo.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Debre Markos University", domain: "dmu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Wolaita Sodo University", domain: "wolaitasodo.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Madda Walabu University", domain: "madawalabu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Werabe University", domain: "werabe.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Wachamo University", domain: "wachamouniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Debre Tabor University", domain: "debretaboruniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Wolkite University", domain: "wolkiteuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Ethiopian Civil Service University", domain: "ecsu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Arsi University", domain: "arsiuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Samara University", domain: "samarauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Assosa University", domain: "assosauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Dire Dawa University", domain: "ddu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Wollega University", domain: "wollegauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Mattu University", domain: "mattuuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Mizan-Tepi University", domain: "mizantepiuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Kotebe Education University", domain: "keu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Adigrat University", domain: "adigratuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Woldia University", domain: "woldiauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Oromia State University", domain: "osu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Bule Hora University", domain: "bulehorauuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: false },
    { name: "Aksum University", domain: "aksumuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Bonga University", domain: "bongauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: false },
    { name: "Rift Valley University", domain: "rvu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Oda Bultum University", domain: "odabultumuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: false },
    { name: "Raya University", domain: "ru.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Injibara University", domain: "iju.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Selale University", domain: "slu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Debark University", domain: "debarkuniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: false },
    { name: "Kebri Dehar University", domain: "kdu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Gambella University", domain: "gu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Mekdela Amba University", domain: "mau.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Dembi Dolo University", domain: "ddu.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Jinka University", domain: "jku.edu.et", region: "Africa", country: "Ethiopia", isVerified: true },
    { name: "Borena University", domain: "borenauniversity.edu.et", region: "Africa", country: "Ethiopia", isVerified: false },
    { name: "Ethiopian Police University", domain: null, region: "Africa", country: "Ethiopia", isVerified: false },
]