import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const France_universities = [

    // France

    { name: "3iL École d'ingénieurs", domain: "3il-ingenieurs.fr", isVerified: true },
    { name: "AgroParisTech", domain: "agroparistech.fr", isVerified: true },
    { name: "Aix-Marseille Université", domain: "univ-amu.fr", isVerified: true },
    { name: "Arts et Métiers ParisTech", domain: "arts-et-metiers.fr", isVerified: true },
    { name: "Audencia Business School", domain: "audencia.com", isVerified: true },
    { name: "Avignon Université", domain: "univ-avignon.fr", isVerified: true },
    { name: "Bordeaux INP", domain: "bordeaux-inp.fr", isVerified: true },
    { name: "Brest Business School", domain: "brest-bs.com", isVerified: true },
    { name: "BUILDERS École d'ingénieurs", domain: "builders-ecole.com", isVerified: true },
    { name: "Burgundy School of Business", domain: "bsb-education.com", isVerified: true },
    { name: "Campus Adventiste du Salève", domain: "campus-adventiste.com", isVerified: true },
    { name: "Centrale Lille", domain: "centrale-lille.fr", isVerified: true },
    { name: "Centrale Méditerranée", domain: "centralemediterranee.fr", isVerified: true },
    { name: "CentraleSupélec", domain: "centralesupelec.fr", isVerified: true },
    { name: "CESI École d'Ingénieurs", domain: "cesi.fr", isVerified: true },
    { name: "CY Cergy Paris Université", domain: "cyu.fr", isVerified: true },
    { name: "CY Tech", domain: "cytech.fr", isVerified: true },
    { name: "ECAM Lyon", domain: "ecam.fr", isVerified: true },
    { name: "ECAM Rennes Louis de Broglie", domain: "ecam-rennes.fr", isVerified: true },
    { name: "ECAM Strasbourg-Europe", domain: "ecam-strasbourg.eu", isVerified: true },
    { name: "ECAM-EPMI", domain: "epmi.fr", isVerified: true },
    { name: "ECE Paris", domain: "ece.fr", isVerified: true },
    { name: "École Centrale de Lyon", domain: "ec-lyon.fr", isVerified: true },
    { name: "École Centrale de Nantes", domain: "ec-nantes.fr", isVerified: true },
    { name: "École de Biologie Industrielle", domain: "ebi-ingenieurs.com", isVerified: true },
    { name: "École de Commerce de Valence", domain: null, isVerified: false },
    { name: "École de Gestion et de Commerce d'Occitanie", domain: null, isVerified: false },
    { name: "École de Management de Normandie", domain: "em-normandie.fr", isVerified: true },
    { name: "École de Management Léonard de Vinci", domain: "emlv.fr", isVerified: true },
    { name: "École des Dirigeants et Créateurs d'entreprise", domain: "edcparis.edu", isVerified: true },
    { name: "École des Hautes Études Commerciales de Paris", domain: "hec.edu", isVerified: true },
    { name: "École des Hautes Études Commerciales du Nord", domain: "edhec.edu", isVerified: true },
    { name: "École des Hautes Études en Santé Publique", domain: "ehesp.fr", isVerified: true },
    { name: "École des Hautes Études en Sciences Sociales", domain: "ehess.fr", isVerified: true },
    { name: "École des Ingénieurs de la Ville de Paris", domain: "eivp-paris.fr", isVerified: true },
    { name: "École des Ponts ParisTech", domain: "enpc.fr", isVerified: true },
    { name: "École d'ingénieur généraliste en informatique et technologies du numérique", domain: null, isVerified: false },
    { name: "École d'Ingénieurs de Purpan", domain: "purpan.fr", isVerified: true },
    { name: "École d'Ingénieurs Généralistes La Rochelle", domain: "ei-lr.fr", isVerified: true },
    { name: "École d'ingénieurs SIGMA Clermont", domain: "sigma-clermont.fr", isVerified: true },
    { name: "École Européenne de Management", domain: null, isVerified: false },
    { name: "École Nationale de la Météorologie", domain: null, isVerified: false },
    { name: "École Nationale de la Statistique et de l'Analyse de l'information", domain: "ensai.fr", isVerified: true },
    { name: "École Nationale de l'Aviation Civile", domain: "enac.fr", isVerified: true },
    { name: "École Nationale des Sciences Géographiques", domain: "ensg.eu", isVerified: true },
    { name: "École Nationale des Travaux Publics de l'État", domain: "entpe.fr", isVerified: true },
    { name: "École Nationale d'Ingénieurs de Brest", domain: "enib.fr", isVerified: true },
    { name: "École Nationale d'Ingénieurs de Saint-Étienne", domain: "enise.fr", isVerified: true },
    { name: "École Nationale d'Ingénieurs de Tarbes", domain: "enit.fr", isVerified: true },
    { name: "École Nationale Supérieure Agronomique de Toulouse", domain: "ensat.fr", isVerified: true },
    { name: "École Nationale Supérieure d'Architecture de Nancy", domain: "ensan.fr", isVerified: true },
    { name: "École Nationale Supérieure de Chimie de Lille", domain: "ensc-lille.fr", isVerified: true },
    { name: "École Nationale Supérieure de Chimie de Montpellier", domain: "enscm.fr", isVerified: true },
    { name: "École Nationale Supérieure de Chimie de Paris", domain: "chimieparistech.psl.eu", isVerified: true },
    { name: "École Nationale Supérieure de Chimie de Rennes", domain: "ensc-rennes.fr", isVerified: true },
    { name: "École Nationale Supérieure de l'Électronique et de ses Applications", domain: "ensea.fr", isVerified: true },
    { name: "École Nationale Supérieure de Mécanique et d'Aérotechnique", domain: "ensma.fr", isVerified: true },
    { name: "École Nationale Supérieure de Mécanique et des Microtechniques", domain: "ens2m.fr", isVerified: true },
    { name: "École Nationale Supérieure de Techniques Avancées Bretagne", domain: "ensta-bretagne.fr", isVerified: true },
    { name: "École Nationale Supérieure des Arts et Industries Textiles", domain: "ensait.fr", isVerified: true },
    { name: "École Nationale Supérieure des Mines de St-Étienne", domain: "emse.fr", isVerified: true },
    { name: "École nationale supérieure des sciences agronomiques de Bordeaux Aquitaine", domain: "agrobordeaux.fr", isVerified: true },
    { name: "École Nationale Supérieure des Sciences de l'Information et des Bibliothèques", domain: "enssib.fr", isVerified: true },
    { name: "École Nationale Supérieure d'Informatique pour l'Industrie et l'Entreprise", domain: "ensiie.fr", isVerified: true },
    { name: "École Nationale Supérieure d'Ingénieurs de Caen", domain: "ensicaen.fr", isVerified: true },
    { name: "École Nationale Vétérinaire d'Alfort", domain: "vet-alfort.fr", isVerified: true },
    { name: "École Nationale Vétérinaire de Toulouse", domain: "envt.fr", isVerified: true },
    { name: "École Nationale Vétérinaire, Agroalimentaire et de l'alimentation de Nantes-Atlantique", domain: "oniris-nantes.fr", isVerified: true },
    { name: "École Normale Supérieure", domain: "ens.psl.eu", isVerified: true },
    { name: "École Normale Supérieure de Lyon", domain: "ens-lyon.fr", isVerified: true },
    { name: "École Normale Supérieure de Rennes", domain: "ens-rennes.fr", isVerified: true },
    { name: "École Normale Supérieure Paris-Saclay", domain: "ens-paris-saclay.fr", isVerified: true },
    { name: "École Polytechnique", domain: "polytechnique.edu", isVerified: true },
    { name: "École pour l'Informatique et les Techniques Avancées", domain: "epita.fr", isVerified: true },
    { name: "École Spéciale des Travaux Publics, du Bâtiment et de l'Industrie", domain: "estp.fr", isVerified: true },
    { name: "École Supérieure d'Agriculture d'Angers", domain: "esa-angers.fr", isVerified: true },
    { name: "École Supérieure d'Agro-développement International", domain: "esai.fr", isVerified: true },
    { name: "École Supérieure de Chimie Organique et Minérale", domain: "escom.fr", isVerified: true },
    { name: "École Supérieure de Chimie Physique Électronique de Lyon", domain: "cpe.fr", isVerified: true },
    { name: "École Supérieure de Commerce d'Amiens", domain: "essca.fr", isVerified: true },
    { name: "École Supérieure de Commerce et de Développement 3A", domain: "3a.fr", isVerified: true },
    { name: "École Supérieure de Fonderie et de Forge", domain: null, isVerified: false },
    { name: "École supérieure de physique et de chimie industrielles de la Ville de Paris", domain: "espci.fr", isVerified: true },
    { name: "École Supérieure d'Électronique de l'Ouest", domain: "eseo.fr", isVerified: true },
    { name: "École Supérieure des Sciences Économiques et Commerciales", domain: "essec.edu", isVerified: true },
    { name: "École Supérieure des Techniques Aéronautiques et de Construction Automobile", domain: "estaca.fr", isVerified: true },
    { name: "École supérieure des technologies et des affaires de Belfort", domain: "estb.fr", isVerified: true },
    { name: "École Supérieure des Technologies Industrielles Avancées", domain: "estia.fr", isVerified: true },
    { name: "École Supérieure d'Informatique, Électronique, Automatique", domain: null, isVerified: false },
    { name: "École Supérieure d'Ingénieurs des Travaux de la Construction de Metz", domain: null, isVerified: false },
    { name: "École Supérieure d'Ingénieurs des Travaux de la Construction de Paris", domain: null, isVerified: false },
    { name: "École Supérieure d'Ingénieurs en Génie Électrique", domain: "esigelec.fr", isVerified: true },
    { name: "École Supérieure d'Ingénieurs Léonard de Vinci", domain: "devinci.fr", isVerified: true },
    { name: "École Supérieure du Bois", domain: "esb-campus.fr", isVerified: true },
    { name: "École Supérieure du Commerce Extérieur", domain: "esce.fr", isVerified: true },
    { name: "Eklore-ed School of Management", domain: null, isVerified: false },
    { name: "EMLYON Business School", domain: "emlyon.com", isVerified: true },
    { name: "ENSAE Paris", domain: "ensae.fr", isVerified: true },
    { name: "ENSTA Paris", domain: "ensta-paris.fr", isVerified: true },
    { name: "EPF École d'Ingénieurs", domain: "epf.fr", isVerified: true },
    { name: "ESAIP École d'Ingénieurs", domain: "esaip.org", isVerified: true },
    { name: "ESCP Business School", domain: "escpeurope.eu", isVerified: true },
    { name: "ESIEE Paris", domain: "esiee.fr", isVerified: true },
    { name: "ESME Sudria", domain: "esme.fr", isVerified: true },
    { name: "ESSCA School of Management", domain: "essca.fr", isVerified: true },
    { name: "Eurecom", domain: "eurecom.fr", isVerified: true },
    { name: "Excelia", domain: "excelia-group.fr", isVerified: true },
    { name: "Grenoble École de Management", domain: "grenoble-em.com", isVerified: true },
    { name: "Grenoble INP", domain: "grenoble-inp.fr", isVerified: true },
    { name: "ICAM - Institut Catholiques d'Arts et Métiers", domain: "icam.fr", isVerified: true },
    { name: "ICN Business School", domain: "icn-artem.com", isVerified: true },
    { name: "IÉSEG School of Management", domain: "ieseg.fr", isVerified: true },
    { name: "IFP School", domain: "ifp-school.com", isVerified: true },
    { name: "IMT Atlantique", domain: "imt-atlantique.fr", isVerified: true },
    { name: "IMT Mines Albi", domain: "mines-albi.fr", isVerified: true },
    { name: "IMT Mines Alès", domain: "mines-ales.fr", isVerified: true },
    { name: "IMT Nord Europe", domain: "imt-nord-europe.fr", isVerified: true },
    { name: "INSEEC Alpes-Savoie", domain: "inseec.com", isVerified: true },
    { name: "Institut Agro Dijon", domain: "institut-agro-dijon.fr", isVerified: true },
    { name: "Institut Agro Rennes-Angers", domain: "institut-agro-rennes-angers.fr", isVerified: true },
    { name: "Institut Catholique de Paris", domain: "icp.fr", isVerified: true },
    { name: "Institut Catholique de Toulouse", domain: "ict-toulouse.fr", isVerified: true },
    { name: "Institut d'Études Politiques de Paris", domain: "sciencespo.fr", isVerified: true },
    { name: "Institut d'Optique Graduate School", domain: "institutoptique.fr", isVerified: true },
    { name: "Institut International du Commerce et du Développement", domain: "ecole-iicd.com", isVerified: true },
    { name: "Institut National des Langues et Civilisations Orientales", domain: "inalco.fr", isVerified: true },
    { name: "Institut National des Sciences Appliquées Centre Val de Loire", domain: "insa-centrevaldeloire.fr", isVerified: true },
    { name: "Institut National des Sciences Appliquées de Lyon", domain: "insa-lyon.fr", isVerified: true },
    { name: "Institut National des Sciences Appliquées de Rennes", domain: "insa-rennes.fr", isVerified: true },
    { name: "Institut National des Sciences Appliquées de Rouen", domain: "insa-rouen.fr", isVerified: true },
    { name: "Institut National des Sciences Appliquées de Strasbourg", domain: "insa-strasbourg.fr", isVerified: true },
    { name: "Institut National des Sciences Appliquées de Toulouse", domain: "insa-toulouse.fr", isVerified: true },
    { name: "Institut national du service public", domain: "insp.gouv.fr", isVerified: true },
    { name: "Institut National Polytechnique de Toulouse", domain: "toulouse-inp.fr", isVerified: true },
    { name: "Institut National Universitaire Champollion", domain: "champollion.fr", isVerified: true },
    { name: "Institut Polytechnique des Sciences Avancées", domain: "ipsa.fr", isVerified: true },
    { name: "Institut Supérieur d'Agriculture et d'Agroalimentaire Rhône-Alpes", domain: "isara.fr", isVerified: true },
    { name: "Institut Supérieur de Gestion", domain: "isg.fr", isVerified: true },
    { name: "Institut Supérieur de l'Aéronautique et de l'Espace", domain: "isae-supaero.fr", isVerified: true },
    { name: "Institut Supérieur d'Électronique de Paris", domain: "isep.fr", isVerified: true },
    { name: "Institut Supérieur des Biotechnologies de Paris", domain: "isbp.fr", isVerified: true },
    { name: "Institut Supérieur des Matériaux et Mécaniques Avancés du Mans", domain: null, isVerified: false },
    { name: "Institut Supérieur du Bâtiment et des Travaux Publics", domain: "estp.fr", isVerified: true },
    { name: "Institute of Intercultural Management and Communication", domain: null, isVerified: false },
    { name: "IPAG Business School", domain: "ipag.edu", isVerified: true },
    { name: "ISC Paris Business School", domain: "iscparis.com", isVerified: true },
    { name: "ITECH Institut Textile et Chimique de Lyon", domain: "itech.fr", isVerified: true },
    { name: "Junia", domain: "junia.com", isVerified: true },
    { name: "KEDGE Business School", domain: "kedge.edu", isVerified: true },
    { name: "La Rochelle Université", domain: "univ-lr.fr", isVerified: true },
    { name: "Le Mans Université", domain: "univ-lemans.fr", isVerified: true },
    { name: "L'École de design Nantes Atlantique", domain: "design-nantes.fr", isVerified: true },
    { name: "Mines Paris", domain: "minesparistech.psl.eu", isVerified: true },
    { name: "Montpellier Business School", domain: "montpellier-bs.com", isVerified: true },
    { name: "Montpellier SupAgro", domain: "supagro.fr", isVerified: true },
    { name: "Nantes Université", domain: "univ-nantes.fr", isVerified: true },
    { name: "NEOMA Business School", domain: "neoma-bs.com", isVerified: true },
    { name: "Rennes School of Business", domain: "rennes-sb.com", isVerified: true },
    { name: "SKEMA Business School", domain: "skema.edu", isVerified: true },
    { name: "Sorbonne Université", domain: "sorbonne-universite.fr", isVerified: true },
    { name: "South Champagne Business School", domain: null, isVerified: false },
    { name: "Strate École de Design", domain: "strate.design", isVerified: true },
    { name: "Supméca - Institut Supérieur de Mécanique", domain: "supmeca.fr", isVerified: true },
    { name: "Télécom Paris", domain: "telecom-paris.fr", isVerified: true },
    { name: "Télécom SudParis", domain: "telecom-sudparis.eu", isVerified: true },
    { name: "The American University of Paris", domain: "aup.edu", isVerified: true },
    { name: "Toulouse Business School", domain: "tbs-education.fr", isVerified: true },
    { name: "UniLaSalle", domain: "unilasalle.fr", isVerified: true },
    { name: "Université Bordeaux Montaigne", domain: "u-bordeaux-montaigne.fr", isVerified: true },
    { name: "Université Bourgogne-Europe", domain: "u-bourgogne.fr", isVerified: true },
    { name: "Université Bretagne Sud", domain: "univ-ubs.fr", isVerified: true },
    { name: "Université Catholique de Lille", domain: "catholille.fr", isVerified: true },
    { name: "Université Catholique de l'Ouest", domain: "uco.fr", isVerified: true },
    { name: "Université Catholique de Lyon", domain: "ucly.fr", isVerified: true },
    { name: "Université Claude Bernard Lyon 1", domain: "univ-lyon1.fr", isVerified: true },
    { name: "Université Clermont Auvergne", domain: "uca.fr", isVerified: true },
    { name: "Université Côte d'Azur", domain: "universite-cotedazur.fr", isVerified: true },
    { name: "Université d'Angers", domain: "univ-angers.fr", isVerified: true },
    { name: "Université d'Artois", domain: "univ-artois.fr", isVerified: true },
    { name: "Université de Bordeaux", domain: "u-bordeaux.fr", isVerified: true },
    { name: "Université de Bretagne Occidentale", domain: "univ-brest.fr", isVerified: true },
    { name: "Université de Caen Normandie", domain: "unicaen.fr", isVerified: true },
    { name: "Université de Corse Pasquale Paoli", domain: "univ-corse.fr", isVerified: true },
    { name: "Université de Franche-Comté", domain: "univ-fcomte.fr", isVerified: true },
    { name: "Université de Haute-Alsace", domain: "uha.fr", isVerified: true },
    { name: "Université de Lille", domain: "univ-lille.fr", isVerified: true },
    { name: "Université de Limoges", domain: "unilim.fr", isVerified: true },
    { name: "Université de Lorraine", domain: "univ-lorraine.fr", isVerified: true },
    { name: "Université de Montpellier", domain: "umontpellier.fr", isVerified: true },
    { name: "Université de Nîmes", domain: "unimes.fr", isVerified: true },
    { name: "Université de Paris", domain: "u-paris.fr", isVerified: true },
    { name: "Université de Pau et des Pays de l'Adour", domain: "univ-pau.fr", isVerified: true },
    { name: "Université de Perpignan Via Domitia", domain: "univ-perp.fr", isVerified: true },
    { name: "Université de Picardie Jules Verne", domain: "u-picardie.fr", isVerified: true },
    { name: "Université de Poitiers", domain: "univ-poitiers.fr", isVerified: true },
    { name: "Université de Reims Champagne-Ardenne", domain: "univ-reims.fr", isVerified: true },
    { name: "Université de Rennes", domain: "univ-rennes.fr", isVerified: true },
    { name: "Université de Rouen Normandie", domain: "univ-rouen.fr", isVerified: true },
    { name: "Université de Strasbourg", domain: "unistra.fr", isVerified: true },
    { name: "Université de Technologie de Belfort-Montbéliard", domain: "utbm.fr", isVerified: true },
    { name: "Université de Technologie de Compiègne", domain: "utc.fr", isVerified: true },
    { name: "Université de Technologie de Troyes", domain: "utt.fr", isVerified: true },
    { name: "Université de Toulon", domain: "univ-tln.fr", isVerified: true },
    { name: "Université de Tours", domain: "univ-tours.fr", isVerified: true },
    { name: "Université de Versailles Saint-Quentin-en-Yvelines", domain: "uvsq.fr", isVerified: true },
    { name: "Université d'Évry-Val d'Essonne", domain: "univ-evry.fr", isVerified: true },
    { name: "Université d'Orléans", domain: "univ-orleans.fr", isVerified: true },
    { name: "Université du Littoral Côte d'Opale", domain: "univ-littoral.fr", isVerified: true },
    { name: "Université Grenoble Alpes", domain: "univ-grenoble-alpes.fr", isVerified: true },
    { name: "Université Gustave Eiffel", domain: "univ-gustave-eiffel.fr", isVerified: true },
    { name: "Université Jean Monnet", domain: "univ-st-etienne.fr", isVerified: true },
    { name: "Université Jean Moulin Lyon 3", domain: "univ-lyon3.fr", isVerified: true },
    { name: "Université Le Havre Normandie", domain: "univ-lehavre.fr", isVerified: true },
    { name: "Université Lumière Lyon 2", domain: "univ-lyon2.fr", isVerified: true },
    { name: "Université Paris 1 Panthéon-Sorbonne", domain: "univ-paris1.fr", isVerified: true },
    { name: "Université Paris 8 Vincennes-Saint-Denis", domain: "univ-paris8.fr", isVerified: true },
    { name: "Université Paris Nanterre", domain: "u-paris10.fr", isVerified: true },
    { name: "Université Paris-Dauphine", domain: "dauphine.psl.eu", isVerified: true },
    { name: "Université Paris-Est Créteil Val de Marne", domain: "u-pec.fr", isVerified: true },
    { name: "Université Paris-Panthéon-Assas", domain: "u-paris2.fr", isVerified: true },
    { name: "Université Paris-Saclay", domain: "universite-paris-saclay.fr", isVerified: true },
    { name: "Université Paul Valéry Montpellier 3", domain: "univ-montp3.fr", isVerified: true },
    { name: "Université Polytechnique Hauts-de-France", domain: "uphf.fr", isVerified: true },
    { name: "Université Rennes 2", domain: "univ-rennes2.fr", isVerified: true },
    { name: "Université Savoie Mont Blanc", domain: "univ-smb.fr", isVerified: true },
    { name: "Université Sorbonne Nouvelle - Paris 3", domain: "sorbonne-nouvelle.fr", isVerified: true },
    { name: "Université Sorbonne Paris Nord", domain: "univ-paris13.fr", isVerified: true },
    { name: "Université Toulouse - Jean Jaurès", domain: "univ-tlse2.fr", isVerified: true },
    { name: "Université Toulouse Capitole", domain: "ut-capitole.fr", isVerified: true },
    { name: "Université Toulouse III - Paul Sabatier", domain: "univ-tlse3.fr", isVerified: true },
    { name: "VetAgro Sup", domain: "vetagro-sup.fr", isVerified: true },

]