import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Georgia_universities = [

    // Georgia

    { name: "Ivane Javakhishvili Tbilisi State University", domain: "tsu.edu.ge", isVerified: true },
    { name: "Ilia State University", domain: "iliauni.edu.ge", isVerified: true },
    { name: "The University of Georgia", domain: "uog.edu.ge", isVerified: true },
    { name: "Georgian Technical University", domain: "gtu.edu.ge", isVerified: true },
    { name: "Business and Technology University", domain: "btu.edu.ge", isVerified: true },
    { name: "Caucasus University", domain: "caucasus.edu.ge", isVerified: true },
    { name: "Tbilisi State Medical University", domain: "tsmu.edu.ge", isVerified: true },
    { name: "International Black Sea University", domain: "ibsu.edu.ge", isVerified: true },
    { name: "Akaki Tsereteli State University", domain: "atsu.edu.ge", isVerified: true },
    { name: "Batumi Shota Rustaveli State University", domain: "bsru.edu.ge", isVerified: true },
    { name: "Georgian National University SEU", domain: "seu.edu.ge", isVerified: true },
    { name: "Free University of Tbilisi", domain: "freeuni.edu.ge", isVerified: true },
    { name: "Georgian Institute of Public Affairs", domain: "gipa.ge", isVerified: true },
    { name: "David Tvildiani Medical University", domain: "dtmu.edu.ge", isVerified: true },
    { name: "Caucasus International University", domain: "ciu.edu.ge", isVerified: true },
    { name: "European University", domain: "eu.edu.ge", isVerified: true },
    { name: "Sokhumi State University", domain: "ssu.edu.ge", isVerified: true },
    { name: "Iakob Gogebashvili Telavi State University", domain: "telavi.edu.ge", isVerified: true },
    { name: "Georgian American University", domain: "gau.edu.ge", isVerified: true },
    { name: "Saint Andrew the First-Called Georgian University", domain: "sagu.edu.ge", isVerified: true },
    { name: "Sulkhan-Saba Orbeliani Teaching University", domain: "ssotu.edu.ge", isVerified: true },
    { name: "V. Sarajishvili Tbilisi State Conservatoire", domain: "tsconcert.edu.ge", isVerified: true },
    { name: "Agricultural University of Georgia", domain: "agu.edu.ge", isVerified: true },
    { name: "Grigol Robakidze University", domain: "gru.edu.ge", isVerified: true },
    { name: "New Vision University", domain: "nvu.edu.ge", isVerified: true },
    { name: "Tbilisi State Academy of Arts", domain: "tsa.edu.ge", isVerified: true },
    { name: "Batumi State Maritime Academy", domain: "bsma.edu.ge", isVerified: true },
    { name: "Alte University", domain: "alte.edu.ge", isVerified: true },
    { name: "Central European University", domain: "ceu.edu.ge", isVerified: true },
    { name: "Petre Shotadze Tbilisi Medical Academy", domain: "psta.edu.ge", isVerified: true },
    { name: "Gori State Teaching University", domain: "gstu.edu.ge", isVerified: true },
    { name: "Teaching University Geomedi", domain: "geomedi.edu.ge", isVerified: true },
    { name: "East European University, Georgia", domain: "eeu.edu.ge", isVerified: true },
    { name: "Shota Rustaveli Theatre and Film Georgian State University", domain: "srtc.edu.ge", isVerified: true },
    { name: "Shota Meskhia State Teaching University", domain: "smstu.edu.ge", isVerified: true },
    { name: "BAU International University, Batumi", domain: "bau.edu.ge", isVerified: true },
    { name: "Samtskhe-Javakheti State University", domain: "sjsu.edu.ge", isVerified: true },
    { name: "Batumi Navigation Teaching University", domain: "bntu.edu.ge", isVerified: true },
    { name: "David Aghmashenebeli University of Georgia", domain: "dau.edu.ge", isVerified: true },
    { name: "Georgian International University", domain: "giu.edu.ge", isVerified: true },
    { name: "Georgian Aviation University", domain: "avu.edu.ge", isVerified: true },
    { name: "Batumi Art Teaching University", domain: "batuaftu.edu.ge", isVerified: true },
    { name: "Tbilisi Humanitarian Teaching University", domain: "thtu.edu.ge", isVerified: true },
    { name: "St. King Tamar University of Patriarchate of Georgia", domain: "stkge.edu.ge", isVerified: true },
    { name: "Georgian State Teaching University of Physical Education and Sport", domain: "gspsu.edu.ge", isVerified: true },
    { name: "Avicenna Batumi Medical University", domain: "abmu.edu.ge", isVerified: true },
    { name: "Tbel Abuserisdze Teaching University of Georgian Patriarchate", domain: "tabu.edu.ge", isVerified: true },
    { name: "Bank of Georgia University", domain: "bgu.edu.ge", isVerified: true }, 
]