import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Germany_universities = [

 // Germany

    { name: "GISMA University of Applied Sciences", domain: "gisma.com", isVerified: true },
    { name: "University of Europe for Applied Sciences", domain: "ue-germany.com", isVerified: true },
    { name: "Berlin School of Business of Innovation", domain: "bsbi.edu", isVerified: true },
    { name: "IU International University of Applied Sciences", domain: "iu.org", isVerified: true },
    { name: "Rheinisch-Westfälische Technische Hochschule Aachen", domain: "rwth-aachen.de", isVerified: true },
    { name: "Universität Augsburg", domain: "uni-augsburg.de", isVerified: true },
    { name: "Otto-Friedrich-Universität Bamberg", domain: "uni-bamberg.de", isVerified: true },
    { name: "Universität Bayreuth", domain: "uni-bayreuth.de", isVerified: true },
    { name: "Bard College Berlin, A Liberal Arts University", domain: "berlin.bard.edu", isVerified: true },
    { name: "ESCP Europe Wirtschaftshochschule Berlin e.V.", domain: "escp.eu", isVerified: true },
    { name: "ESMT European School of Management and Technology", domain: "esmt.org", isVerified: true },
    { name: "Freie Universität Berlin", domain: "fu-berlin.de", isVerified: true },
    { name: "Hertie School", domain: "hertie-school.org", isVerified: true },
    { name: "Humboldt-Universität zu Berlin", domain: "hu-berlin.de", isVerified: true },
    { name: "International Psychoanalytic University Berlin", domain: "ipu-berlin.de", isVerified: true },
    { name: "Psychologische Hochschule Berlin (PHB)", domain: "phb-berlin.de", isVerified: true },
    { name: "Technische Universität Berlin", domain: "tu-berlin.de", isVerified: true },
    { name: "Universität Bielefeld", domain: "uni-bielefeld.de", isVerified: true },
    { name: "Ruhr-Universität Bochum", domain: "rub.de", isVerified: true },
    { name: "Rheinische Friedrich-Wilhelms-Universität Bonn", domain: "uni-bonn.de", isVerified: true },
    { name: "Technische Universität Carolo-Wilhelmina zu Braunschweig", domain: "tu-braunschweig.de", isVerified: true },
    { name: "Constructor University", domain: "constructor.university", isVerified: true },
    { name: "Universität Bremen", domain: "uni-bremen.de", isVerified: true },
    { name: "Technische Universität Chemnitz", domain: "tu-chemnitz.de", isVerified: true },
    { name: "Technische Universität Clausthal", domain: "tu-clausthal.de", isVerified: true },
    { name: "Brandenburgische Technische Universität Cottbus-Senftenberg", domain: "b-tu.de", isVerified: true },
    { name: "Technische Universität Darmstadt", domain: "tu-darmstadt.de", isVerified: true },
    { name: "Technische Universität Dortmund", domain: "tu-dortmund.de", isVerified: true },
    { name: "DIU - Dresden International University GmbH", domain: "di-uni.de", isVerified: true },
    { name: "Technische Universität Dresden", domain: "tu-dresden.de", isVerified: true },
    { name: "Heinrich-Heine-Universität Düsseldorf", domain: "uni-duesseldorf.de", isVerified: true },
    { name: "Katholische Universität Eichstätt – Ingolstadt", domain: "ku.de", isVerified: true },
    { name: "Universität Erfurt", domain: "uni-erfurt.de", isVerified: true },
    { name: "Friedrich-Alexander-Universität Erlangen-Nürnberg", domain: "fau.de", isVerified: true },
    { name: "Universität Duisburg-Essen", domain: "uni-due.de", isVerified: true },
    { name: "Europa-Universität Flensburg", domain: "uni-flensburg.de", isVerified: true },
    { name: "Frankfurt School of Finance & Management", domain: "fs.de", isVerified: true },
    { name: "Johann Wolfgang Goethe-Universität Frankfurt am Main", domain: "uni-frankfurt.de", isVerified: true },
    { name: "Philosophisch-Theologische Hochschule Sankt Georgen Frankfurt am Main", domain: "pthg-frankfurt.de", isVerified: true },
    { name: "Europa-Universität Viadrina Frankfurt (Oder)", domain: "europa-uni.de", isVerified: true },
    { name: "Technische Universität Bergakademie Freiberg", domain: "tu-freiberg.de", isVerified: true },
    { name: "Albert-Ludwigs-Universität Freiburg", domain: "uni-freiburg.de", isVerified: true },
    { name: "Pädagogische Hochschule Freiburg", domain: "ph-freiburg.de", isVerified: true },
    { name: "Theologische Hochschule Friedensau", domain: "thh-friedensau.de", isVerified: true },
    { name: "Zeppelin Universität", domain: "zu.de", isVerified: true },
    { name: "Theologische Fakultät Fulda", domain: "tfh-fulda.de", isVerified: true },
    { name: "Justus-Liebig-Universität Gießen", domain: "uni-giessen.de", isVerified: true },
    { name: "Georg-August-Universität Göttingen", domain: "uni-goettingen.de", isVerified: true },
    { name: "Universität Greifswald", domain: "uni-greifswald.de", isVerified: true },
    { name: "FernUniversität in Hagen", domain: "fernuni-hagen.de", isVerified: true },
    { name: "Martin-Luther-Universität Halle-Wittenberg", domain: "uni-halle.de", isVerified: true },
    { name: "Bucerius Law School", domain: "bucerius.de", isVerified: true },
    { name: "HafenCity Universität Hamburg", domain: "hcu-hamburg.de", isVerified: true },
    { name: "Helmut-Schmidt-Universität/Universität der Bundeswehr Hamburg", domain: "hsuhh.de", isVerified: true },
    { name: "Kühne Logistics University", domain: "the-klu.org", isVerified: true },
    { name: "Technische Universität Hamburg", domain: "tuhh.de", isVerified: true },
    { name: "Universität Hamburg", domain: "uni-hamburg.de", isVerified: true },
    { name: "Gottfried Wilhelm Leibniz Universität Hannover", domain: "uni-hannover.de", isVerified: true },
    { name: "Medizinische Hochschule Hannover", domain: "mhhannover.de", isVerified: true },
    { name: "Stiftung Tierärztliche Hochschule Hannover", domain: "tiho-hannover.de", isVerified: true },
    { name: "Hochschule für Jüdische Studien Heidelberg", domain: "hfjw.org", isVerified: true },
    { name: "Pädagogische Hochschule Heidelberg", domain: "ph-heidelberg.de", isVerified: true },
    { name: "Ruprecht-Karls-Universität Heidelberg", domain: "uni-heidelberg.de", isVerified: true },
    { name: "Universität Hildesheim", domain: "uni-hildesheim.de", isVerified: true },
    { name: "Technische Universität Ilmenau", domain: "tu-ilmenau.de", isVerified: true },
    { name: "Friedrich-Schiller-Universität Jena", domain: "uni-jena.de", isVerified: true },
    { name: "Rheinland-Pfälzische Technische Universität Kaiserslautern-Landau", domain: "tu-kl.de", isVerified: true },
    { name: "Karlsruher Institut für Technologie", domain: "kit.edu", isVerified: true },
    { name: "Pädagogische Hochschule Karlsruhe", domain: "ph-karlsruhe.de", isVerified: true },
    { name: "Universität Kassel", domain: "uni-kassel.de", isVerified: true },
    { name: "Christian-Albrechts-Universität zu Kiel", domain: "uni-kiel.de", isVerified: true },
    { name: "Universität Koblenz", domain: "uni-koblenz-landau.de", isVerified: true },
    { name: "Deutsche Sporthochschule Köln", domain: "dshs-koeln.de", isVerified: true },
    { name: "Kölner Hochschule für Katholische Theologie (KHKT)", domain: "khkt.de", isVerified: true },
    { name: "Universität zu Köln", domain: "uni-koeln.de", isVerified: true },
    { name: "Universität Konstanz", domain: "uni-konstanz.de", isVerified: true },
    { name: "HHL Leipzig Graduate School of Management", domain: "hhl.de", isVerified: true },
    { name: "Universität Leipzig", domain: "uni-leipzig.de", isVerified: true },
    { name: "Universität zu Lübeck", domain: "uni-luebeck.de", isVerified: true },
    { name: "Pädagogische Hochschule Ludwigsburg", domain: "ph-ludwigsburg.de", isVerified: true },
    { name: "Leuphana Universität Lüneburg", domain: "leuphana.de", isVerified: true },
    { name: "Otto-von-Guericke-Universität Magdeburg", domain: "ovgu.de", isVerified: true },
    { name: "Johannes Gutenberg-Universität Mainz", domain: "uni-mainz.de", isVerified: true },
    { name: "Universität Mannheim", domain: "uni-mannheim.de", isVerified: true },
    { name: "Philipps-Universität Marburg", domain: "uni-marburg.de", isVerified: true },
    { name: "Hochschule für Philosophie München", domain: "hfp-muenchen.de", isVerified: true },
    { name: "Ludwig-Maximilians-Universität München", domain: "lmu.de", isVerified: true },
    { name: "Technische Universität München", domain: "tum.de", isVerified: true },
    { name: "Philosophisch-Theologische Hochschule Münster", domain: "pth-muenster.de", isVerified: true },
    { name: "Universität Münster", domain: "uni-muenster.de", isVerified: true },
    { name: "Universität der Bundeswehr München", domain: "unibw.de", isVerified: true },
    { name: "Augustana-Hochschule Neuendettelsau", domain: "augustana-hochschule.de", isVerified: true },
    { name: "Medizinische Hochschule Brandenburg Theodor Fontane", domain: "mhb-fontane.de", isVerified: true },
    { name: "Lutherische Theologische Hochschule Oberursel", domain: null, isVerified: true },
    { name: "Carl von Ossietzky Universität Oldenburg", domain: "uni-oldenburg.de", isVerified: true },
    { name: "Universität Osnabrück", domain: "uni-osnabrueck.de", isVerified: true },
    { name: "Theologische Fakultät Paderborn", domain: null, isVerified: true },
    { name: "Universität Paderborn", domain: "uni-paderborn.de", isVerified: true },
    { name: "Universität Passau", domain: "uni-passau.de", isVerified: true },
    { name: "Universität Potsdam", domain: "uni-potsdam.de", isVerified: true },
    { name: "Universität Regensburg", domain: "uni-regensburg.de", isVerified: true },
    { name: "Universität Rostock", domain: "uni-rostock.de", isVerified: true },
    { name: "Universität des Saarlandes", domain: "uni-saarland.de", isVerified: true },
    { name: "Pädagogische Hochschule Schwäbisch Gmünd", domain: "ph-gmuend.de", isVerified: true },
    { name: "Universität Siegen", domain: "uni-siegen.de", isVerified: true },
    { name: "Deutsche Universität für Verwaltungswissenschaften Speyer", domain: "uni-speyer.de", isVerified: true },
    { name: "Freie Hochschule Stuttgart - Seminar für Waldorfpädagogik", domain: "freie-hochschule-stuttgart.de", isVerified: true },
    { name: "Universität Stuttgart", domain: "uni-stuttgart.de", isVerified: true },
    { name: "Universität Hohenheim", domain: "uni-hohenheim.de", isVerified: true },
    { name: "Theologische Fakultät Trier", domain: null, isVerified: true },
    { name: "Universität Trier", domain: "uni-trier.de", isVerified: true },
    { name: "Eberhard Karls Universität Tübingen", domain: "uni-tuebingen.de", isVerified: true },
    { name: "Universität Ulm", domain: "uni-ulm.de", isVerified: true },
    { name: "Vinzenz Pallotti University", domain: null, isVerified: true },
    { name: "WHU – Otto Beisheim School of Management", domain: "whu.edu", isVerified: true },
    { name: "Universität Vechta", domain: "uni-vechta.de", isVerified: true },
    { name: "Bauhaus-Universität Weimar", domain: "uni-weimar.de", isVerified: true },
    { name: "Pädagogische Hochschule Weingarten", domain: "ph-weingarten.de", isVerified: true },
    { name: "Charlotte Fresenius Hochschule", domain: null, isVerified: true },
    { name: "EBS Universität für Wirtschaft und Recht", domain: "ebs.edu", isVerified: true },
    { name: "Private Universität Witten/Herdecke gGmbH", domain: "witten-herdecke.de", isVerified: true },
    { name: "Bergische Universität Wuppertal", domain: "uni-wuppertal.de", isVerified: true },
    { name: "Kirchliche Hochschule Wuppertal", domain: "kh-wuppertal.de", isVerified: true },
    { name: "Julius-Maximilians-Universität Würzburg", domain: "uni-wuerzburg.de", isVerified: true },
    { name: "Fachhochschule Aachen", domain: "fh-aachen.de", isVerified: true },
    { name: "Hochschule Aalen - Technik und Wirtschaft", domain: "htw-aalen.de", isVerified: true },
    { name: "Ostbayerische Technische Hochschule Amberg-Weiden", domain: "oth-aw.de", isVerified: true },
    { name: "Hochschule für angewandte Wissenschaften Ansbach", domain: "fh-ansbach.de", isVerified: true },
    { name: "Technische Hochschule Aschaffenburg", domain: "th-aschaffenburg.de", isVerified: true },
    { name: "Technische Hochschule Augsburg", domain: "thi.de", isVerified: true },
    { name: "EHIP – Europäische Hochschule für Innovation und Perspektive", domain: "ehip.de", isVerified: true },
    { name: "accadis Hochschule Bad Homburg", domain: "accadis.com", isVerified: true },
    { name: "Internationale Hochschule Liebenzell (IHL)", domain: "ihl.de", isVerified: true },
    { name: "DIPLOMA Hochschule - Private Fachhochschule Nordhessen", domain: "diploma-hochschule.de", isVerified: true },
    { name: "Akkon-Hochschule", domain: "akkon-hochschule.de", isVerified: true },
    { name: "Alice Salomon Hochschule Berlin", domain: "alice-salomon-hochschule.de", isVerified: true },
    { name: "bbw Hochschule", domain: "bbw-hochschule.de", isVerified: true },
    { name: "Berliner Hochschule für Technik", domain: "bht-berlin.de", isVerified: true },
    { name: "Berlin International University of Applied Sciences", domain: "berlin-international.de", isVerified: true },
    { name: "BSP Business and Law School – Hochschule für Management und Recht", domain: "bsp-businessschool.de", isVerified: true },
    { name: "CODE University of Applied Sciences", domain: "code.berlin", isVerified: true },
    { name: "DHGS Deutsche Hochschule für Gesundheit und Sport", domain: "dhgs.de", isVerified: true },
    { name: "Digital Business University of Applied Sciences", domain: "digital-business-school.de", isVerified: true },
    { name: "Evangelische Hochschule Berlin", domain: "evh-berlin.de", isVerified: true },
    { name: "HMKW Hochschule für Medien, Kommunikation und Wirtschaft", domain: "hmkw.de", isVerified: true },
    { name: "Hochschule für Soziale Arbeit und Pädagogik (HSAP)", domain: "hsap.de", isVerified: true },
    { name: "Hochschule für Technik und Wirtschaft Berlin", domain: "htw-berlin.de", isVerified: true },
    { name: "Hochschule für Wirtschaft und Recht Berlin", domain: "hwr-berlin.de", isVerified: true },
    { name: "IB Hochschule für Gesundheit und Soziales", domain: "ib-hochschule.de", isVerified: true },
    { name: "Katholische Hochschule für Sozialwesen Berlin (KHSB)", domain: "khsb-berlin.de", isVerified: true },
    { name: "Mediadesign Hochschule für Design und Informatik", domain: "mediadesign-hochschule.de", isVerified: true },
    { name: "Medical School Berlin – Hochschule für Gesundheit und Medizin (MSB)", domain: "msb-berlin.de", isVerified: true },
    { name: "Quadriga Hochschule Berlin", domain: "quadriga-hochschule.com", isVerified: true },
    { name: "SRH Berlin University of Applied Sciences", domain: "berlin.srh-hochschule.de", isVerified: true },
    { name: "Touro College Berlin", domain: "touro-college.de", isVerified: true },
    { name: "VICTORIA Internationale Hochschule", domain: "victoria-internationale-hochschule.de", isVerified: true },
    { name: "Hochschule Biberach", domain: "fh-biberach.de", isVerified: true },
    { name: "Fachhochschule der Diakonie – Diaconia", domain: "diakonie-hs.de", isVerified: true },
    { name: "Fachhochschule des Mittelstands (FHM)", domain: "fhm.edu", isVerified: true },
    { name: "Hochschule Bielefeld – University of Applied Sciences and Arts", domain: "hs-bielefeld.de", isVerified: true },
    { name: "Technische Hochschule Bingen", domain: "th-bingen.de", isVerified: true },
    { name: "EBZ Business School – University of Applied Sciences", domain: "ebz-bs.de", isVerified: true },
    { name: "Evangelische Hochschule Rheinland-Westfalen-Lippe", domain: "ehrwl.de", isVerified: true },
    { name: "Hochschule Bochum – University of Applied Sciences", domain: "hs-bochum.de", isVerified: true },
    { name: "Hochschule für Gesundheit – University of Applied Sciences", domain: "hs-gesundheit.de", isVerified: true },
    { name: "Technische Hochschule Georg Agricola", domain: "thga.de", isVerified: true },
    { name: "Hochschule für Finanzwirtschaft & Management", domain: null, isVerified: true },
    { name: "Technische Hochschule Brandenburg", domain: "th-brandenburg.de", isVerified: true },
    { name: "APOLLON Hochschule der Gesundheitswirtschaft", domain: "apollon-hochschule.de", isVerified: true },
    { name: "Hochschule Bremen – City University of Applied Sciences", domain: "hs-bremen.de", isVerified: true },
    { name: "Hochschule Bremerhaven – University of Applied Sciences", domain: "hs-bremerhaven.de", isVerified: true },
    { name: "Europäische Fachhochschule Rhein/Erft", domain: "efh-rhein-erft.de", isVerified: true },
    { name: "Hochschule 21", domain: "hs21.de", isVerified: true },
    { name: "Hochschule Coburg – University of Applied Sciences", domain: "fh-coburg.de", isVerified: true },
    { name: "Evangelische Hochschule Darmstadt", domain: "evh-darmstadt.de", isVerified: true },
    { name: "Hochschule Darmstadt – University of Applied Sciences", domain: "h-da.de", isVerified: true },
    { name: "Wilhelm Büchner Hochschule – Private Fernhochschule Darmstadt", domain: "wilhelmbuechner.de", isVerified: true },
    { name: "Technische Hochschule Deggendorf", domain: "th-deggendorf.de", isVerified: true },
    { name: "Theologisches Hochschule Ewersbach", domain: null, isVerified: true },
    { name: "Fachhochschule Dortmund – University of Applied Sciences", domain: "fh-dortmund.de", isVerified: true },
    { name: "International School of Management", domain: "ism.de", isVerified: true },
    { name: "Evangelische Hochschule Dresden", domain: "evh-dresden.de", isVerified: true },
    { name: "Fachhochschule Dresden", domain: "fh-dresden.de", isVerified: true },
    { name: "Hochschule für Technik und Wirtschaft Dresden", domain: "htw-dresden.de", isVerified: true },
    { name: "Fliedner Fachhochschule Düsseldorf", domain: "fliedner-fh.de", isVerified: true },
    { name: "Hochschule Düsseldorf", domain: "hs-duesseldorf.de", isVerified: true },
    { name: "IST-Hochschule für Management", domain: "ist-hochschule.de", isVerified: true },
    { name: "Hochschule für nachhaltige Entwicklung Eberswalde", domain: "hnee.de", isVerified: true },
    { name: "NORDAKADEMIE Hochschule der Wirtschaft", domain: "nordakademie.de", isVerified: true },
    { name: "Theologische Hochschule Elstal", domain: null, isVerified: false },
    { name: "Hochschule Emden/Leer", domain: "hs-emden-leer.de", isVerified: true },
    { name: "Fachhochschule Erfurt", domain: "fh-erfurt.de", isVerified: true },
    { name: "FOM Hochschule für Oekonomie & Management", domain: "fom.de", isVerified: true },
    { name: "Hochschule Esslingen", domain: "hs-esslingen.de", isVerified: true },
    { name: "Hochschule Flensburg", domain: "hs-flensburg.de", isVerified: true },
    { name: "Frankfurt University of Applied Sciences", domain: "frankfurt-university.de", isVerified: true },
    { name: "Provadis School of International Management and Technology", domain: "provadis-hochschule.de", isVerified: true },
    { name: "Tomorrow University of Applied Sciences", domain: null, isVerified: false },
    { name: "University of Labour", domain: null, isVerified: false },
    { name: "Evangelische Hochschule Freiburg", domain: "evh-freiburg.de", isVerified: true },
    { name: "Katholische Hochschule Freiburg", domain: "khf.de", isVerified: true },
    { name: "Hochschule für angewandte Wissenschaften Weihenstephan-Triesdorf", domain: "hswt.de", isVerified: true },
    { name: "Hochschule Fulda", domain: "fh-fulda.de", isVerified: true },
    { name: "SRH Wilhelm Löhe Hochschule", domain: "wilhelm-loehe-hochschule.de", isVerified: true },
    { name: "Hochschule Furtwangen", domain: "hs-furtwangen.de", isVerified: true },
    { name: "Westfälische Hochschule Gelsenkirchen, Bocholt, Recklinghausen", domain: "whs.de", isVerified: true },
    { name: "SRH Hochschule für Gesundheit", domain: "srh-hochschule-gesundheit.de", isVerified: true },
    { name: "Freie Theologische Hochschule Gießen", domain: "fthg.de", isVerified: true },
    { name: "Technische Hochschule Mittelhessen", domain: "thm.de", isVerified: true },
    { name: "PFH – Private Hochschule Göttingen", domain: "pfh.de", isVerified: true },
    { name: "Brand University of Applied Sciences", domain: null, isVerified: false },
    { name: "Europäische Fernhochschule Hamburg", domain: "efh.de", isVerified: true },
    { name: "Evangelische Hochschule für Soziale Arbeit & Diakonie", domain: null, isVerified: false },
    { name: "Hamburger Fern-Hochschule", domain: "hfh.de", isVerified: true },
    { name: "Hochschule für Angewandte Wissenschaften Hamburg", domain: "haw-hamburg.de", isVerified: true },
    { name: "HSBA Hamburg School of Business Administration", domain: "hsba.de", isVerified: true },
    { name: "NBS Northern Business School", domain: "nbs.de", isVerified: true },
    { name: "Hochschule Weserbergland", domain: "hs-wes.de", isVerified: true },
    { name: "Hochschule Hamm-Lippstadt", domain: "hshl.de", isVerified: true },
    { name: "SRH Hochschule in Nordrhein-Westfalen", domain: "nrwhochschule.de", isVerified: true },
    { name: "Fachhochschule für die Wirtschaft Hannover", domain: "fww-hannover.de", isVerified: true },
    { name: "Hochschule Hannover", domain: "hs-hannover.de", isVerified: true },
    { name: "Leibniz-Fachhochschule", domain: "leibniz-fh.de", isVerified: true },
    { name: "Fachhochschule Westküste", domain: "fh-westkueste.de", isVerified: true },
    { name: "Hochschule Fresenius Heidelberg", domain: "fresenius-university.de", isVerified: true },
    { name: "SRH Hochschule Heidelberg", domain: "srh-hochschule-heidelberg.de", isVerified: true },
    { name: "Hochschule Heilbronn", domain: "hs-heilbronn.de", isVerified: true },
    { name: "Fachhochschule für Interkulturelle Theologie Hermannsburg", domain: null, isVerified: false },
    { name: "HAWK Hochschule für angewandte Wissenschaft und Kunst Hildesheim/Holzminden/Göttingen", domain: "hawk.de", isVerified: true },
    { name: "Hochschule für angewandte Wissenschaften Hof", domain: null, isVerified: false },
    { name: "Hochschule Fresenius Idstein", domain: "fresenius-university.de", isVerified: true },
    { name: "Technische Hochschule Ingolstadt", domain: "thi.de", isVerified: true },
    { name: "Fachhochschule Südwestfalen", domain: "fh-swf.de", isVerified: true },
    { name: "Hochschule für angewandtes Management", domain: null, isVerified: false },
    { name: "Ernst-Abbe-Hochschule Jena", domain: "eah-jena.de", isVerified: true },
    { name: "Hochschule Kaiserslautern", domain: "hs-kl.de", isVerified: true },
    { name: "Hochschule Karlsruhe – Technik und Wirtschaft", domain: "h-ka.de", isVerified: true },
    { name: "Karlshochschule International University", domain: "karlshochschule.de", isVerified: true },
    { name: "CVJM-Hochschule", domain: "cvjm-hochschule.de", isVerified: true },
    { name: "Hochschule für angewandte Wissenschaften Kempten", domain: "hs-kempten.de", isVerified: true },
    { name: "Duale Hochschule Schleswig-Holstein", domain: "dhsh.de", isVerified: true },
    { name: "Fachhochschule Kiel", domain: "fh-kiel.de", isVerified: true },
    { name: "Hochschule Rhein-Waal", domain: "hochschule-rhein-waal.de", isVerified: true },
    { name: "Hochschule Koblenz", domain: "hs-koblenz.de", isVerified: true },
    { name: "CBS International Business School", domain: "cbs.de", isVerified: true },
    { name: "INU – Innovative Hochschule für angewandte Wissenschaften", domain: "inu.de", isVerified: true },
    { name: "Katholische Hochschule Nordrhein-Westfalen", domain: "kh-nrw.de", isVerified: true },
    { name: "Kolping Hochschule", domain: "kolping-uni.de", isVerified: true },
    { name: "Rheinische Fachhochschule Köln", domain: "rheinische-fachhochschule.de", isVerified: true },
    { name: "Technische Hochschule Köln", domain: "th-koeln.de", isVerified: true },
    { name: "Allensbach Hochschule Konstanz", domain: "allensbach-hochschule.de", isVerified: true },
    { name: "Hochschule Konstanz Technik, Wirtschaft und Gestaltung", domain: "hftg-konstanz.de", isVerified: true },
    { name: "Hochschule Anhalt", domain: "hs-anhalt.de", isVerified: true },
    { name: "Hochschule Niederrhein", domain: "hs-niederrhein.de", isVerified: true },
    { name: "Hochschule Landshut", domain: "haw-landshut.de", isVerified: true },
    { name: "Hochschule für Technik, Wirtschaft und Kultur Leipzig", domain: "htwk-leipzig.de", isVerified: true },
    { name: "Technische Hochschule Ostwestfalen-Lippe", domain: "th-owl.de", isVerified: true },
    { name: "Technische Hochschule Lübeck", domain: "th-luebeck.de", isVerified: true },
    { name: "Evangelische Hochschule Ludwigsburg", domain: "evh-ludwigsburg.de", isVerified: true },
    { name: "Hochschule für Wirtschaft und Gesellschaft Ludwigshafen", domain: "hwg-lu.de", isVerified: true },
    { name: "Hochschule Magdeburg-Stendal", domain: "hs-magdeburg-stendal.de", isVerified: true },
    { name: "Steinbeis Hochschule", domain: "steinbeis-hochschule.de", isVerified: true },
    { name: "Hochschule Mainz", domain: "hs-mainz.de", isVerified: true },
    { name: "Katholische Hochschule Mainz", domain: "khm-mainz.de", isVerified: true },
    { name: "Hochschule der Wirtschaft für Management", domain: "hswm-mannheim.de", isVerified: true },
    { name: "Hochschule Mannheim", domain: "hs-mannheim.de", isVerified: true },
    { name: "Evangelische Hochschule Tabor", domain: "evh-tabor.de", isVerified: true },
    { name: "Hochschule Merseburg", domain: "hochschule-merseburg.de", isVerified: true },
    { name: "Hochschule Mittweida, University of Applied Sciences", domain: "hs-mittweida.de", isVerified: true },
    { name: "Hochschule Ruhr West – University of Applied Sciences", domain: "hrw.de", isVerified: true },
    { name: "Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften - HDBW", domain: "hdbw.de", isVerified: true },
    { name: "Hochschule für angewandte Wissenschaften München", domain: "hm.edu", isVerified: true },
    { name: "Internationale Hochschule SDI München", domain: "sdi-muenchen.de", isVerified: true },
    { name: "Katholische Stiftungshochschule München", domain: "ksh-muenchen.de", isVerified: true },
    { name: "Munich Business School", domain: "munich-business-school.de", isVerified: true },
    { name: "FH Münster University of Applied Sciences", domain: "fh-muenster.de", isVerified: true },
    { name: "Hochschule Neubrandenburg", domain: "hs-nb.de", isVerified: true },
    { name: "Hochschule für angewandte Wissenschaften Neu-Ulm", domain: "hnu.de", isVerified: true },
    { name: "Hochschule Nordhausen", domain: "hs-nordhausen.de", isVerified: true },
    { name: "Evangelische Hochschule Nürnberg", domain: "ehn.de", isVerified: true },
    { name: "Technische Hochschule Nürnberg Georg Simon Ohm", domain: "ohm-uni.de", isVerified: true },
    { name: "Hochschule Nürtingen-Geislingen", domain: "hs-nuertingen-geislingen.de", isVerified: true },
    { name: "Hochschule Offenburg", domain: "hs-offenburg.de", isVerified: true },
    { name: "Hochschule Osnabrück", domain: "hs-osnabrueck.de", isVerified: true },
    { name: "Hochschule für Künste im Sozialen, Ottersberg", domain: null, isVerified: false },
    { name: "Fachhochschule der Wirtschaft", domain: "fhdw.de", isVerified: true },
    { name: "Hochschule Pforzheim", domain: "hs-pforzheim.de", isVerified: true },
    { name: "Fachhochschule für Sport und Management Potsdam", domain: null, isVerified: false },
    { name: "Fachhochschule Potsdam", domain: "fh-potsdam.de", isVerified: true },
    { name: "GU Deutsche Hochschule", domain: null, isVerified: false },
    { name: "Hochschule Clara Hoffbauer (HCHP)", domain: "hchp.de", isVerified: true },
    { name: "Hochschule Döpfer", domain: null, isVerified: false },
    { name: "XU Exponential University", domain: "xuex.de", isVerified: true },
    { name: "Ostbayerische Technische Hochschule Regensburg", domain: "oth-regensburg.de", isVerified: true },
    { name: "Hochschule Reutlingen", domain: "hs-reutlingen.de", isVerified: true },
    { name: "Theologische Hochschule Reutlingen", domain: null, isVerified: false },
    { name: "SRH Fernhochschule", domain: "srh-fernhochschule.de", isVerified: true },
    { name: "Technische Hochschule Rosenheim", domain: "th-rosenheim.de", isVerified: true },
    { name: "Hochschule für Forstwirtschaft Rottenburg", domain: "fh-rottenburg.de", isVerified: true },
    { name: "Deutsche Hochschule für Prävention und Gesundheitsmanagement", domain: "dhfpg.de", isVerified: true },
    { name: "Hochschule für Technik und Wirtschaft des Saarlandes", domain: "htw-saarland.de", isVerified: true },
    { name: "Hochschule Bonn-Rhein-Sieg", domain: "h-brs.de", isVerified: true },
    { name: "Hochschule Schmalkalden", domain: "fh-schmalkalden.de", isVerified: true },
    { name: "Hochschule für Gestaltung Schwäbisch Gmünd", domain: "hfg-gmuend.de", isVerified: true },
    { name: "Hochschule Albstadt-Sigmaringen", domain: "hs-albsig.de", isVerified: true },
    { name: "Hochschule Stralsund", domain: "hochschule-stralsund.de", isVerified: true },
    { name: "AKAD Hochschule Stuttgart", domain: "akad.de", isVerified: true },
    { name: "Hochschule der Medien Stuttgart", domain: "hdm-stuttgart.de", isVerified: true },
    { name: "Hochschule für Kommunikation und Gestaltung", domain: "hfg-stuttgart.de", isVerified: true },
    { name: "Hochschule für Technik Stuttgart", domain: "hft-stuttgart.de", isVerified: true },
    { name: "Hochschule Macromedia Stuttgart", domain: "macromedia-fachhochschule.de", isVerified: true },
    { name: "media Akademie – Hochschule Stuttgart", domain: "media-akademie.de", isVerified: true },
    { name: "Merz Akademie Stuttgart", domain: "merz-akademie.de", isVerified: true },
    { name: "VWA-Hochschule für berufsbegleitendes Studium", domain: "vwa-hochschule.de", isVerified: true },
    { name: "Hochschule Trier", domain: "hochschule-trier.de", isVerified: true },
    { name: "Technische Hochschule Ulm", domain: "th-ulm.de", isVerified: true },
    { name: "Private Hochschule für Wirtschaft und Technik Vechta/Diepholz", domain: "phwt.de", isVerified: true },
    { name: "Fachhochschule Wedel", domain: "fh-wedel.de", isVerified: true },
    { name: "Hochschule Ravensburg-Weingarten", domain: "hs-weingarten.de", isVerified: true },
    { name: "Hochschule Harz", domain: "hs-harz.de", isVerified: true },
    { name: "Hochschule RheinMain", domain: "hs-rm.de", isVerified: true },
    { name: "Technische Hochschule Wildau", domain: "th-wildau.de", isVerified: true },
    { name: "Jade Hochschule", domain: "jade-hs.de", isVerified: true },
    { name: "Hochschule Wismar", domain: "hs-wismar.de", isVerified: true },
    { name: "Hochschule Braunschweig/Wolfenbüttel, Ostfalia", domain: "ostfalia.de", isVerified: true },
    { name: "Hochschule Worms", domain: "hs-worms.de", isVerified: true },
    { name: "Technische Hochschule Würzburg-Schweinfurt", domain: "thws.de", isVerified: true },
    { name: "Hochschule Zittau/Görlitz", domain: "hszg.de", isVerified: true },
    { name: "Westsächsische Hochschule Zwickau", domain: "fh-zwickau.de", isVerified: true },
    { name: "Alanus Hochschule für Kunst und Gesellschaft", domain: "alanus.edu", isVerified: true },
    { name: "Hochschule für evangelische Kirchenmusik Bayreuth", domain: "hfk-bayreuth.de", isVerified: true },
    { name: "Barenboim-Said Akademie", domain: "barenboim-said.de", isVerified: true },
    { name: "Hochschule für Musik \"Hanns Eisler\" Berlin", domain: "hfm-berlin.de", isVerified: true },
    { name: "Hochschule für Schauspielkunst Ernst Busch", domain: "hfs-berlin.de", isVerified: true },
    { name: "Universität der Künste Berlin", domain: "udk-berlin.de", isVerified: true },
    { name: "weißensee kunsthochschule berlin", domain: "kh-berlin.de", isVerified: true },
    { name: "Hochschule für Bildende Künste Braunschweig", domain: "hbk-bs.de", isVerified: true },
    { name: "Hochschule für Künste Bremen", domain: "hfk-bremen.de", isVerified: true },
    { name: "Hochschule für Musik Detmold", domain: "hfm-detmold.de", isVerified: true },
    { name: "Hochschule für Bildende Künste Dresden", domain: "hfbk-dresden.de", isVerified: true },
    { name: "Hochschule für Kirchenmusik der Evangelisch-Lutherischen Landeskirche Sachsens", domain: null, isVerified: true },
    { name: "Hochschule für Musik Carl Maria von Weber Dresden", domain: "hfmdd.de", isVerified: true },
    { name: "Palucca Hochschule für Tanz Dresden", domain: "palucca.eu", isVerified: true },
    { name: "Kunstakademie Düsseldorf", domain: "kunstakademie-duesseldorf.de", isVerified: true },
    { name: "Robert-Schumann-Hochschule Düsseldorf", domain: "rsh-duesseldorf.de", isVerified: true },
    { name: "Folkwang Universität der Künste", domain: "folkwang-uni.de", isVerified: true },
    { name: "Hochschule der bildenden Künste Essen", domain: "hbk-essen.de", isVerified: true },
    { name: "Hochschule für Bildende Künste (Städelschule)", domain: "staedelschule.de", isVerified: true },
    { name: "Hochschule für Musik und Darstellende Kunst Frankfurt am Main", domain: "hfmdk-frankfurt.de", isVerified: true },
    { name: "Hochschule für Musik Freiburg", domain: "hfm-freiburg.de", isVerified: true },
    { name: "Burg Giebichenstein Kunsthochschule Halle", domain: "burg-halle.de", isVerified: true },
    { name: "Evangelische Hochschule für Kirchenmusik Halle", domain: null, isVerified: true },
    { name: "Hochschule für Bildende Künste Hamburg", domain: "hfbk-hamburg.de", isVerified: true },
    { name: "Hochschule für Musik und Theater Hamburg", domain: "hfmt-hamburg.de", isVerified: true },
    { name: "Hochschule für Musik, Theater und Medien Hannover", domain: "hmtm-hannover.de", isVerified: true },
    { name: "Hochschule für Kirchenmusik der Evangelischen Landeskirche in Baden", domain: null, isVerified: true },
    { name: "Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen", domain: null, isVerified: true },
    { name: "Hochschule für Musik Karlsruhe", domain: "hfm-karlsruhe.de", isVerified: true },
    { name: "Staatliche Akademie der Bildenden Künste Karlsruhe", domain: "abk-karlsruhe.de", isVerified: true },
    { name: "Staatliche Hochschule für Gestaltung Karlsruhe", domain: "hfg-karlsruhe.de", isVerified: true },
    { name: "Muthesius Kunsthochschule", domain: "muthesius-kunsthochschule.de", isVerified: true },
    { name: "Hochschule für Musik und Tanz Köln", domain: "hfmt-koeln.de", isVerified: true },
    { name: "Kunsthochschule für Medien Köln", domain: "khm.de", isVerified: true },
    { name: "Hochschule für Grafik und Buchkunst Leipzig", domain: "hgb-leipzig.de", isVerified: true },
    { name: "Hochschule für Musik und Theater \"Felix Mendelssohn Bartholdy\" Leipzig", domain: "hmt-leipzig.de", isVerified: true },
    { name: "Musikhochschule Lübeck", domain: "musikhochschule-luebeck.de", isVerified: true },
    { name: "Staatliche Hochschule für Musik und Darstellende Kunst Mannheim", domain: "musikhochschule-mannheim.de", isVerified: true },
    { name: "Akademie der Bildenden Künste München", domain: "adbk.de", isVerified: true },
    { name: "Hochschule für Fernsehen und Film München", domain: "hff-muc.de", isVerified: true },
    { name: "Hochschule für Musik und Theater München", domain: "hmtm.de", isVerified: true },
    { name: "Kunstakademie Münster, Hochschule für Bildende Künste", domain: null, isVerified: true },
    { name: "Akademie der Bildenden Künste Nürnberg", domain: "adbk-nuernberg.de", isVerified: true },
    { name: "Hochschule für Musik Nürnberg", domain: "hfm-nuernberg.de", isVerified: true },
    { name: "Hochschule für Gestaltung Offenbach", domain: "hfg-offenbach.de", isVerified: true },
    { name: "Filmuniversität Babelsberg Konrad Wolf", domain: "filmuniversitaet.de", isVerified: true },
    { name: "Hochschule für Katholische Kirchenmusik und Musikpädagogik Regensburg", domain: null, isVerified: true },
    { name: "Hochschule für Musik und Theater Rostock", domain: "hmt-rostock.de", isVerified: true },
    { name: "Hochschule für Kirchenmusik der Diözese Rottenburg-Stuttgart", domain: null, isVerified: true },
    { name: "Hochschule der Bildenden Künste Saar", domain: "hbksaar.de", isVerified: true },
    { name: "Hochschule für Musik Saar", domain: "hfm-saar.de", isVerified: true },
    { name: "Staatliche Akademie der Bildenden Künste Stuttgart", domain: "abk-stuttgart.de", isVerified: true },
    { name: "Staatliche Hochschule für Musik und Darstellende Kunst Stuttgart", domain: "hmdk-stuttgart.de", isVerified: true },
    { name: "Staatliche Hochschule für Musik Trossingen", domain: "musikhochschule-trossingen.de", isVerified: true },
    { name: "Hochschule für Kirchenmusik der Evangelischen Landeskirche in Württemberg", domain: null, isVerified: true },
    { name: "Hochschule für Musik Franz Liszt Weimar", domain: "hfm-weimar.de", isVerified: true },
    { name: "Hochschule für Musik Würzburg", domain: "hfm-wuerzburg.de", isVerified: true },
    { name: "Fachhochschule für Verwaltung und Dienstleistung", domain: "fh-vd-sh.de", isVerified: true },
    { name: "Fachhochschule Polizei Sachsen-Anhalt", domain: "fh-polizei.de", isVerified: true },
    { name: "Steuerakademie Niedersachsen", domain: null, isVerified: true },
    { name: "Fachhochschule für Rechtspflege Nordrhein-Westfalen", domain: "fh-rechtspflege.de", isVerified: true },
    { name: "Hochschule für Öffentliche Verwaltung Bremen", domain: "hfv-bremen.de", isVerified: true },
    { name: "Hochschule des Bundes für öffentliche Verwaltung", domain: "hsbund.de", isVerified: true },
    { name: "Hochschule der Polizei Rheinland-Pfalz", domain: "fh-polizei-rlp.de", isVerified: true },
    { name: "Hochschule für Finanzen Rheinland-Pfalz", domain: "hfrp.de", isVerified: true },
    { name: "Hochschule für Polizei und öffentliche Verwaltung Nordrhein-Westfalen", domain: "hspv.nrw.de", isVerified: true },
    { name: "Thüringer Fachhochschule für öffentliche Verwaltung", domain: null, isVerified: true },
    { name: "Fachhochschule für öffentliche Verwaltung, Polizei und Rechtspflege Mecklenburg-Vorpommern", domain: null, isVerified: true },
    { name: "Hochschule der Deutschen Bundesbank", domain: null, isVerified: true },
    { name: "Akademie der Polizei Hamburg", domain: "polizeiakademie.hamburg.de", isVerified: true },
    { name: "Norddeutsche Akademie für Finanzen und Steuerrecht", domain: null, isVerified: true },
    { name: "Kommunale Hochschule für Verwaltung in Niedersachsen", domain: null, isVerified: true },
    { name: "Norddeutsche Hochschule für Rechtspflege", domain: null, isVerified: true },
    { name: "Hochschule für öffentliche Verwaltung Kehl", domain: "hs-kehl.de", isVerified: true },
    { name: "Fachhochschule für Finanzen Brandenburg", domain: null, isVerified: true },
    { name: "Hochschule für öffentliche Verwaltung und Finanzen Ludwigsburg", domain: null, isVerified: true },
    { name: "Hochschule der Bundesagentur für Arbeit", domain: null, isVerified: true },
    { name: "Archivschule Marburg", domain: "archivschule-marburg.de", isVerified: true },
    { name: "Hochschule für öffentliche Verwaltung Rheinland-Pfalz", domain: "hfv-rlp.de", isVerified: true },
    { name: "Hochschule für öffentliche Verwaltung und Rechtspflege Sachsen", domain: null, isVerified: true },
    { name: "Hochschule für den öffentlichen Dienst in Bayern", domain: null, isVerified: true },
    { name: "Deutsche Hochschule der Polizei", domain: "dh-polizei.de", isVerified: true },
    { name: "Polizeiakademie Niedersachsen", domain: "polizeiakademie.niedersachsen.de", isVerified: true },
    { name: "Hochschule für Finanzen NRW", domain: "fhfnrw.nrw.de", isVerified: true },
    { name: "Fachhochschule der Polizei Brandenburg", domain: "fhpolbb.de", isVerified: true },
    { name: "Hessische Hochschule für Finanzen und Rechtspflege", domain: null, isVerified: true },
    { name: "Hochschule der Sächsischen Polizei", domain: null, isVerified: true },
    { name: "Fachhochschule der Verwaltung des Saarlandes", domain: null, isVerified: true },
    { name: "Hochschule für Rechtspflege Schwetzingen", domain: null, isVerified: true },
    { name: "Hochschule für Polizei Baden-Württemberg", domain: null, isVerified: true },
    { name: "Hessische Hochschule für öffentliches Management und Sicherheit", domain: null, isVerified: true },
    { name: "HMU Health and Medical University Erfurt", domain: "health-and-medical-university-erfurt.de", isVerified: true },
    { name: "Hochschule Geisenheim University", domain: "hs-geisenheim.de", isVerified: true },
    { name: "Duale Hochschule Gera-Eisenach", domain: "dhge.de", isVerified: true },
    { name: "Berufliche Hochschule Hamburg (BHH)", domain: "bhh.hamburg.de", isVerified: true },
    { name: "MSH Medical School Hamburg", domain: "medicalschool-hamburg.de", isVerified: true },
    { name: "Hochschule für Gesellschaftsgestaltung", domain: "hfgg.de", isVerified: true },
    { name: "Duale Hochschule Baden-Württemberg", domain: "dhbw.de", isVerified: true },

]