import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Ghana_universities = [

   // Ghana

   { name: "University of Ghana", domain: "ug.edu.gh", isVerified: true },
   { name: "Kwame Nkrumah University of Science and Technology", domain: "knust.edu.gh", isVerified: true },
   { name: "University of Cape Coast", domain: "ucc.edu.gh", isVerified: true },
   { name: "Ashesi University", domain: "ashesi.edu.gh", isVerified: true },
   { name: "University of Education, Winneba", domain: "uew.edu.gh", isVerified: true },
   { name: "University for Development Studies", domain: "uds.edu.gh", isVerified: true },
   { name: "Ghana Communication Technology University", domain: "gctu.edu.gh", isVerified: true },
   { name: "Ghana Institute of Management and Public Administration", domain: "gimpa.edu.gh", isVerified: true },
   { name: "University of Energy and Natural Resources", domain: "uenr.edu.gh", isVerified: true },
   { name: "Valley View University", domain: "vvu.edu.gh", isVerified: true },
   { name: "Accra Technical University", domain: "atu.edu.gh", isVerified: true },
   { name: "Knutsford University College", domain: "knutsford.edu.gh", isVerified: true },
   { name: "University of Health and Allied Sciences", domain: "uhas.edu.gh", isVerified: true },
   { name: "University of Media, Arts and Communication", domain: "unimac.edu.gh", isVerified: true },
   { name: "Tamale Technical University", domain: "tatu.edu.gh", isVerified: true },
   { name: "Central University", domain: "central.edu.gh", isVerified: true },
   { name: "University of Mines and Technology", domain: "umat.edu.gh", isVerified: true },
   { name: "Kumasi Technical University", domain: "kstu.edu.gh", isVerified: true },
   { name: "Wisconsin International University College", domain: "wiuc-ghana.edu.gh", isVerified: true },
   { name: "University of Professional Studies, Accra", domain: "upsa.edu.gh", isVerified: true },
   { name: "Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development", domain: "aamusted.edu.gh", isVerified: true },
   { name: "Lancaster University, Ghana", domain: "lancaster.edu.gh", isVerified: true },
   { name: "Takoradi Technical University", domain: "ttu.edu.gh", isVerified: true },
   { name: "Pentecost University", domain: "pu.edu.gh", isVerified: true },
   { name: "Academic City University College", domain: "acu.edu.gh", isVerified: true },
   { name: "All Nations University", domain: "anu.edu.gh", isVerified: true },
   { name: "Sunyani Technical University", domain: "stu.edu.gh", isVerified: true },
   { name: "Regent University College of Science and Technology", domain: "regent.edu.gh", isVerified: true },
   { name: "Koforidua Technical University", domain: "ktuc.edu.gh", isVerified: true },
   { name: "KAAF University College", domain: "kaaf.edu.gh", isVerified: true },
   { name: "Ho Technical University", domain: "hotu.edu.gh", isVerified: true },
   { name: "Presbyterian University, Ghana", domain: "pug.edu.gh", isVerified: true },
   { name: "Regional Maritime University", domain: "rmu.edu.gh", isVerified: true },
   { name: "Accra Institute of Technology", domain: "ait.edu.gh", isVerified: true },
   { name: "Dominion University College", domain: "duc.edu.gh", isVerified: true },
   { name: "Ghana Christian University College", domain: "gcuc.edu.gh", isVerified: true },
   { name: "Catholic University of Ghana", domain: "cug.edu.gh", isVerified: true },
   { name: "Christian Service University College", domain: "csuc.edu.gh", isVerified: true },
   { name: "Garden City University College", domain: null, isVerified: false },
   { name: "BlueCrest College", domain: "bluecrest.edu.gh", isVerified: true },
   { name: "Cape Coast Technical University", domain: "cctu.edu.gh", isVerified: true },
   { name: "Maranatha University College", domain: "muc-gh.com", isVerified: true },
   { name: "Methodist University", domain: "mug.edu.gh", isVerified: true },
   { name: "Mountcrest University College", domain: "mountcrestuniversity.edu.gh", isVerified: true },
   { name: "African University College of Communications", domain: "aucc.edu.gh", isVerified: true },
   { name: "Simon Diedong Dombo University of Business and Integrated Development Studies", domain: "ubids.edu.gh", isVerified: true },
   { name: "University of Environment and Sustainable Development", domain: "uesd.edu.gh", isVerified: true },
   { name: "Zenith University College", domain: "zucghana.org", isVerified: true },
   { name: "C.K. Tedam University of Technology and Applied Sciences", domain: "cktutas.edu.gh", isVerified: true },
   { name: "Islamic University College, Ghana", domain: "iug.edu.gh", isVerified: true },
   { name: "Data Link Institute of Business and Technology", domain: "datalink.edu.gh", isVerified: true },
   { name: "Anglican University College of Technology", domain: "angutech.edu.gh", isVerified: true },
   { name: "Christ Apostolic University College", domain: "cauc.edu.gh", isVerified: true },
   { name: "West End University College", domain: "weuc.edu.gh", isVerified: true },
   { name: "Bolgatanga Technical University", domain: "bolgatu.edu.gh", isVerified: true },
   { name: "Kings University College", domain: "kuc.edu.gh", isVerified: true },
   { name: "Jayee University College", domain: "juc.edu.gh", isVerified: true },
   { name: "Radford University College", domain: "ruc.edu.gh", isVerified: true },
   { name: "Marshalls University College", domain: "marshalls.edu.gh", isVerified: true },
   { name: "Ghana Baptist University College", domain: "gbuc.edu.gh", isVerified: true },
   { name: "Kessben University College", domain: "kc.edu.gh", isVerified: true },
   { name: "Palm University College", domain: "palm.edu.gh", isVerified: true },
   { name: "Evangelical Presbyterian University College", domain: "epuc.edu.gh", isVerified: true },
   { name: "Spiritan University College", domain: "suc.edu.gh", isVerified: true },
   { name: "Catholic Institute of Business and Technology", domain: "cibt.edu.gh", isVerified: true },
   { name: "Dr. Hilla Limann Technical University", domain: "dhltu.edu.gh", isVerified: true },
   { name: "University College of Agriculture and Environmental Studies", domain: "environmentuniversity.edu.gh", isVerified: true },
   { name: "Perez University College", domain: "perez.edu.gh", isVerified: true },
   { name: "University College of Management Studies", domain: "ucoms.edu.gh", isVerified: true },
]