import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Hungary_universities = [

    // Hungary

    { name: "Eötvös Loránd Tudományegyetem", domain: "elte.hu", isVerified: true },
    { name: "Budapesti Műszaki és Gazdaságtudományi Egyetem", domain: "bme.hu", isVerified: true },
    { name: "Közép-Európai Egyetem", domain: "ceu.edu", isVerified: true },
    { name: "Szegedi Tudományegyetem", domain: "u-szeged.hu", isVerified: true },
    { name: "Pécsi Tudományegyetem", domain: "pte.hu", isVerified: true },
    { name: "Debreceni Egyetem", domain: "unideb.hu", isVerified: true },
    { name: "Semmelweis Egyetem", domain: "semmelweis.hu", isVerified: true },
    { name: "Budapesti Corvinus Egyetem", domain: "uni-corvinus.hu", isVerified: true },
    { name: "Miskolci Egyetem", domain: "uni-miskolc.hu", isVerified: true },
    { name: "Magyar Agrár- és Élettudományi Egyetem", domain: "uni-mate.hu", isVerified: true },
    { name: "Óbudai Egyetem", domain: "uni-obuda.hu", isVerified: true },
    { name: "Nemzeti Közszolgálati Egyetem", domain: "nke.hu", isVerified: true },
    { name: "Pázmány Péter Katolikus Egyetem", domain: "ppke.hu", isVerified: true },
    { name: "Eszterházy Károly Egyetem", domain: "uni-eszterhazy.hu", isVerified: true },
    { name: "Pannon Egyetem", domain: "uni-pannon.hu", isVerified: true },
    { name: "Budapesti Gazdasági Egyetem", domain: "bge.hu", isVerified: true },
    { name: "Liszt Ferenc Zeneművészeti Egyetem", domain: "lfze.hu", isVerified: true },
    { name: "Moholy-Nagy Művészeti Egyetem", domain: "mome.hu", isVerified: true },
    { name: "Soproni Egyetem", domain: "uni-sopron.hu", isVerified: true },
    { name: "Károli Gáspár Református Egyetem", domain: "kre.hu", isVerified: true },
    { name: "Budapesti Metropolitan Egyetem", domain: "metropolitan.hu", isVerified: true },
    { name: "Nyíregyházi Egyetem", domain: "nye.hu", isVerified: true },
    { name: "Kodolányi János Egyetem", domain: "kodolanyi.hu", isVerified: true },
    { name: "Széchényi István Egyetem", domain: "sze.hu", isVerified: true },
    { name: "Magyar Képzőművészeti Egyetem", domain: "mke.hu", isVerified: true },
    { name: "Andrássy Universität Budapest", domain: "andrassyuni.hu", isVerified: true },
    { name: "Neumann János Egyetem", domain: "nje.hu", isVerified: true },
    { name: "Dunaújvárosi Egyetem", domain: "uniduna.hu", isVerified: true },
    { name: "International Business School", domain: "ibs-b.hu", isVerified: true },
    { name: "Színház- és Filmművészeti Egyetem", domain: "szfe.hu", isVerified: true },
    { name: "Milton Friedman Egyetem", domain: "milton.hu", isVerified: true },
    { name: "Edutus Egyetem", domain: "edutus.hu", isVerified: true },
    { name: "Magyar Táncművészeti Egyetem", domain: "mte.hu", isVerified: true },
    { name: "Gábor Dénes Egyetem", domain: "gdf.hu", isVerified: true },
    { name: "Eötvös József Foiskola", domain: "ejf.hu", isVerified: true },
    { name: "Debreceni Református Hittudományi Egyetem", domain: "drhe.hu", isVerified: true },
    { name: "Wesley János Lelkészképző Főiskola", domain: "wjlf.hu", isVerified: true },
    { name: "Tomori Pál Főiskola", domain: "tpfk.hu", isVerified: true },
    { name: "Wekerle Sándor Üzleti Foiskola", domain: "wsu.hu", isVerified: true },
    { name: "Adventista Teológiai Fõiskola", domain: "atf.hu", isVerified: true },
    { name: "Esztergomi Hittudományi Fõiskola", domain: "ehtf.hu", isVerified: true },
]