import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const India_universities = [

    // India

    { name: "Indian Institute of Technology Bombay", domain: "iitb.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Madras", domain: "iitm.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Kanpur", domain: "iitk.ac.in", isVerified: true },
    { name: "University of Delhi", domain: "du.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Kharagpur", domain: "iitkgp.ac.in", isVerified: true },
    { name: "Manipal Academy of Higher Education", domain: "manipal.edu", isVerified: true },
    { name: "Indian Institute of Technology Roorkee", domain: "iitr.ac.in", isVerified: true },
    { name: "Vellore Institute of Technology", domain: "vit.ac.in", isVerified: true },
    { name: "Savitribai Phule Pune University", domain: "unipune.ac.in", isVerified: true },
    { name: "Tata Institute of Fundamental Research", domain: "tifr.res.in", isVerified: true },
    { name: "Birla Institute of Technology and Science", domain: "bits-pilani.ac.in", isVerified: true },
    { name: "Indian Institute of Science", domain: "iisc.ac.in", isVerified: true },
    { name: "Lovely Professional University", domain: "lpu.in", isVerified: true },
    { name: "Amrita Vishwa Vidyapeetham", domain: "amrita.edu", isVerified: true },
    { name: "SRM Institute of Science and Technology", domain: "srmist.edu.in", isVerified: true },
    { name: "International Institute of Information Technology, Hyderabad", domain: "iiit.ac.in", isVerified: true },
    { name: "Jawaharlal Nehru University", domain: "jnu.ac.in", isVerified: true },
    { name: "Tata Institute of Social Sciences", domain: "tiss.edu", isVerified: true },
    { name: "Indian Institute of Technology Guwahati", domain: "iitg.ac.in", isVerified: true },
    { name: "Anna University", domain: "annauniv.edu", isVerified: true },
    { name: "Amity University", domain: "amity.edu", isVerified: true },
    { name: "Dr. A.P.J. Abdul Kalam Technical University", domain: "aktu.ac.in", isVerified: true },
    { name: "Indian Statistical Institute", domain: "isical.ac.in", isVerified: true },
    { name: "All India Institute of Medical Sciences Delhi", domain: "aiims.edu", isVerified: true },
    { name: "University of Calicut", domain: "uoc.ac.in", isVerified: true },
    { name: "Narsee Monjee Institute of Management and Higher Studies", domain: "nmims.edu", isVerified: true },
    { name: "Indian Institute of Technology Hyderabad", domain: "iith.ac.in", isVerified: true },
    { name: "University of Petroleum and Energy Studies", domain: "upes.ac.in", isVerified: true },
    { name: "Parul University", domain: "paruluniversity.ac.in", isVerified: true },
    { name: "Christ University", domain: "christuniversity.in", isVerified: true },
    { name: "Banaras Hindu University", domain: "bhu.ac.in", isVerified: true },
    { name: "Aligarh Muslim University", domain: "amu.ac.in", isVerified: true },
    { name: "Ashoka University", domain: "ashoka.edu.in", isVerified: true },
    { name: "Cochin University of Science and Technology", domain: "cusat.ac.in", isVerified: true },
    { name: "Chandigarh University", domain: "cumohali.ac.in", isVerified: true },
    { name: "Visvesvaraya Technological University", domain: "vtu.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Gandhinagar", domain: "iitgn.ac.in", isVerified: true },
    { name: "University of Mumbai", domain: "mu.ac.in", isVerified: true },
    { name: "Panjab University", domain: "pu.ac.in", isVerified: true },
    { name: "Tamil Nadu Agricultural University", domain: "tnau.ac.in", isVerified: true },
    { name: "Gujarat Technological University", domain: "gtu.ac.in", isVerified: true },
    { name: "Mahatma Gandhi University", domain: "mgu.ac.in", isVerified: true },
    { name: "Osmania University", domain: "osmania.ac.in", isVerified: true },
    { name: "National Institute of Technology, Rourkela", domain: "nitrkl.ac.in", isVerified: true },
    { name: "Jamia Millia Islamia", domain: "jmi.ac.in", isVerified: true },
    { name: "APJ Abdul Kalam Technological University", domain: "ktu.edu.in", isVerified: true },
    { name: "O.P. Jindal Global University", domain: "jgu.edu.in", isVerified: true },
    { name: "Azim Premji University", domain: "azimpremjiuniversity.edu.in", isVerified: true },
    { name: "University of Hyderabad", domain: "uohyd.ac.in", isVerified: true },
    { name: "Indian Institute of Science Education and Research, Pune", domain: "iiserpune.ac.in", isVerified: true },
    { name: "University of Calcutta", domain: "caluniv.ac.in", isVerified: true },
    { name: "National Institute of Technology, Tiruchirappalli", domain: "nitt.edu", isVerified: true },
    { name: "Gandhi Institute of Technology and Management", domain: "gitam.edu", isVerified: true },
    { name: "University of Madras", domain: "unom.ac.in", isVerified: true },
    { name: "KIIT University", domain: "kiit.ac.in", isVerified: true },
    { name: "Thapar Institute of Engineering and Technology", domain: "thapar.edu", isVerified: true },
    { name: "Jawaharlal Nehru Technological University", domain: "jntuh.ac.in", isVerified: true },
    { name: "National Institute of Technology, Karnataka", domain: "nitk.ac.in", isVerified: true },
    { name: "National Institute of Technology, Calicut", domain: "nitc.ac.in", isVerified: true },
    { name: "National Institute of Design", domain: "nid.edu", isVerified: true },
    { name: "Shiv Nadar University", domain: "snu.edu.in", isVerified: true },
    { name: "University of Lucknow", domain: "lkouniv.ac.in", isVerified: true },
    { name: "Chitkara University, Punjab", domain: "chitkara.edu.in", isVerified: true },
    { name: "Guru Gobind Singh Indraprastha University", domain: "ggsipu.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Delhi", domain: "iitd.ac.in", isVerified: true },
    { name: "Sharda University", domain: "sharda.ac.in", isVerified: true },
    { name: "National Institute of Mental Health and Neuro Sciences", domain: "nimhans.ac.in", isVerified: true },
    { name: "Maulana Abul Kalam Azad University of Technology, West Bengal", domain: "makautwb.ac.in", isVerified: true },
    { name: "Indian Institute of Foreign Trade", domain: "iift.ac.in", isVerified: true },
    { name: "University of Kerala", domain: "keralauniversity.ac.in", isVerified: true },
    { name: "Delhi Technological University", domain: "dtu.ac.in", isVerified: true },
    { name: "Chennai Mathematical Institute", domain: "cmi.ac.in", isVerified: true },
    { name: "International Institute of Information Technology Bangalore", domain: "iiitb.ac.in", isVerified: true },
    { name: "National Law School of India University", domain: "nls.ac.in", isVerified: true },
    { name: "Chaudhary Charan Singh University", domain: "ccsuniversity.ac.in", isVerified: true },
    { name: "Indian Institute of Technology, BHU", domain: "iitbhu.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Jodhpur", domain: "iitj.ac.in", isVerified: true },
    { name: "Andhra University", domain: "andhrauniversity.edu.in", isVerified: true },
    { name: "Indian Institute of Technology Patna", domain: "iitp.ac.in", isVerified: true },
    { name: "Post Graduate Institute of Medical Education and Research", domain: "pgimer.edu.in", isVerified: true },
    { name: "University of Rajasthan", domain: "uniraj.ac.in", isVerified: true },
    { name: "National Institute of Fashion Technology", domain: "nift.ac.in", isVerified: true },
    { name: "Jadavpur University", domain: "jadavpuruniversity.ac.in", isVerified: true },
    { name: "Jawaharlal Institute of Postgraduate Medical Education & Research", domain: "jipmer.edu.in", isVerified: true },
    { name: "Kurukshetra University", domain: "kuk.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Mandi", domain: "iitmandi.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Indore", domain: "iiti.ac.in", isVerified: true },
    { name: "Indraprastha Institute of Information Technology", domain: "iiitd.ac.in", isVerified: true },
    { name: "Pondicherry University", domain: "pondiuni.edu.in", isVerified: true },
    { name: "Maharashtra University of Health Sciences", domain: "muhs.ac.in", isVerified: true },
    { name: "Rajiv Gandhi University of Health Sciences", domain: "rguhs.ac.in", isVerified: true },
    { name: "Bharathidasan University", domain: "bharathidasanuniversity.ac.in", isVerified: true },
    { name: "Guru Nanak Dev University", domain: "gndu.ac.in", isVerified: true },
    { name: "The Maharaja Sayajirao University of Baroda", domain: "msubaroda.ac.in", isVerified: true },
    { name: "University of Allahabad", domain: "allduniv.ac.in", isVerified: true },
    { name: "K L University", domain: "kluniversity.in", isVerified: true },
    { name: "Indian Institute of Technology Bhubaneswar", domain: "iitbbs.ac.in", isVerified: true },
    { name: "Devi Ahilya Vishwavidyalaya", domain: "dauniv.ac.in", isVerified: true },
    { name: "Indian Agricultural Research Institute", domain: "iari.res.in", isVerified: true },
    { name: "Indian Institute of Information Technology Allahabad", domain: "iiita.ac.in", isVerified: true },
    { name: "Indian School of Mines", domain: "iitism.ac.in", isVerified: true },
    { name: "Rajiv Gandhi Proudyogiki Vishwavidyalaya", domain: "rgpv.ac.in", isVerified: true },
    { name: "Indian Institute of Science Education and Research, Kolkata", domain: "iiserkol.ac.in", isVerified: true },
    { name: "Gujarat University", domain: "gujaratuniversity.ac.in", isVerified: true },
    { name: "Jawaharlal Nehru Centre for Advanced Scientific Research", domain: "jncasr.ac.in", isVerified: true },
    { name: "University of Kashmir", domain: "kashmiruniversity.ac.in", isVerified: true },
    { name: "Chhatrapati Shahu Ji Maharaj University", domain: "csjmu.ac.in", isVerified: true },
    { name: "Kannur University", domain: "kannuruniversity.ac.in", isVerified: true },
    { name: "Shivaji University", domain: "unishivaji.ac.in", isVerified: true },
    { name: "Indian Institute of Science Education and Research, Bhopal", domain: "iiserb.ac.in", isVerified: true },
    { name: "National Institute of Technology, Warangal", domain: "nitw.ac.in", isVerified: true },
    { name: "Kerala Agricultural University", domain: "kau.in", isVerified: true },
    { name: "SASTRA University", domain: "sastra.edu", isVerified: true },
    { name: "University of Engineering and Management, Kolkata", domain: "uem.edu.in", isVerified: true },
    { name: "Visva-Bharati University", domain: "visva-bharati.ac.in", isVerified: true },
    { name: "Indira Gandhi Institute of Development Research", domain: "igidr.ac.in", isVerified: true },
    { name: "Ahmedabad University", domain: "ahduni.edu.in", isVerified: true },
    { name: "Teerthanker Mahaveer University", domain: "tmu.ac.in", isVerified: true },
    { name: "Rajasthan University of Health Sciences", domain: "ruhs.ac.in", isVerified: true },
    { name: "Annamalai University", domain: "annamalaiuniversity.ac.in", isVerified: true },
    { name: "Motilal Nehru National Institute of Technology Allahabad", domain: "mnnit.ac.in", isVerified: true },
    { name: "Indian Institute of Space Science and Technology", domain: "iist.ac.in", isVerified: true },
    { name: "King George's Medical University", domain: "kgmu.org", isVerified: true },
    { name: "Symbiosis International University", domain: "siu.edu.in", isVerified: true },
    { name: "PES University", domain: "pesu.ac.in", isVerified: true },
    { name: "Jain University", domain: "jainuniversity.ac.in", isVerified: true },
    { name: "Birla Institute of Technology", domain: "bitmesra.ac.in", isVerified: true },
    { name: "NALSAR University of Law", domain: "nalsar.ac.in", isVerified: true },
    { name: "Malaviya National Institute of Technology, Jaipur", domain: "mnit.ac.in", isVerified: true },
    { name: "Sanjay Gandhi Post Graduate Institute of Medical Sciences", domain: "sgpgims.org", isVerified: true },
    { name: "Nirma University", domain: "nirmauni.ac.in", isVerified: true },
    { name: "Indian Institute of Technology Ropar", domain: "iitrpr.ac.in", isVerified: true },
    { name: "Dr. B R Ambedkar National Institute of Technology Jalandhar", domain: "nitj.ac.in", isVerified: true },
    { name: "Jiwaji University", domain: "jiwaji.edu", isVerified: true },
    { name: "CEPT University", domain: "cept.ac.in", isVerified: true },
    { name: "University of Mysore", domain: "uom.ac.in", isVerified: true },
    { name: "Tezpur University", domain: "tezu.ac.in", isVerified: true },
    { name: "Sathyabama Institute of Science and Technology", domain: "sathyabama.ac.in", isVerified: true },
    { name: "Indian Institute of Engineering Science and Technology, Shibpur", domain: "iiest.ac.in", isVerified: true },
    { name: "Bennett University", domain: "bennett.edu.in", isVerified: true },
    { name: "West Bengal University of Health Sciences", domain: "wbuhs.ac.in", isVerified: true },
    { name: "National Institute of Educational Planning and Administration", domain: "niepa.ac.in", isVerified: true },
    { name: "Pandit Ravishankar Shukla University", domain: "prsu.ac.in", isVerified: true },
    { name: "North Eastern Hill University", domain: "nehu.ac.in", isVerified: true },
    { name: "Sardar Vallabhbhai National Institute of Technology, Surat", domain: "svnitsurat.ac.in", isVerified: true },
    { name: "Gauhati University", domain: "gauhati.ac.in", isVerified: true },
    { name: "Dr. D.Y. Patil Vidyapeeth", domain: "dpu.edu.in", isVerified: true },
    { name: "Flame University", domain: "flame.edu.in", isVerified: true },
    { name: "Dr. Vishwanath Karad MIT World Peace University", domain: "mitwpu.edu.in", isVerified: true },
    { name: "NITTE University", domain: "nitte.edu.in", isVerified: true },
    { name: "Karunya Institute of Technology and Sciences", domain: "karunya.edu", isVerified: true },
    { name: "Madurai Kamaraj University", domain: "mkuniversity.ac.in", isVerified: true },
    { name: "Bharati Vidyapeeth Deemed University", domain: "bvuniversity.edu.in", isVerified: true },
    { name: "Bharathiar University", domain: "bharathiaruniversity.ac.in", isVerified: true },
    { name: "Swami Vivekananda Yoga Anusandhana Samsthana", domain: "svyasa.org", isVerified: true },
    { name: "Saurashtra University", domain: "saurashtrauniversity.edu.in", isVerified: true },
    { name: "Dhirubhai Ambani Institute of Information and Communication Technology", domain: "daiict.ac.in", isVerified: true },
    { name: "Kavayitri Bahinabai Chaudhari North Maharashtra University", domain: "nmu.ac.in", isVerified: true },
    { name: "Saveetha Institute of Medical and Technical Sciences", domain: "saveetha.ac.in", isVerified: true },
    { name: "Mohanlal Sukhadia University", domain: "mlsu.ac.in", isVerified: true },
    { name: "Indian Institute of Science Education and Research, Thiruvananthapuram", domain: "iisertvm.ac.in", isVerified: true },
    { name: "Alagappa University", domain: "alagappauniversity.ac.in", isVerified: true },
    { name: "University of Burdwan", domain: "burdwanuniv.ac.in", isVerified: true },
    { name: "National Institute of Technology, Durgapur", domain: "nitdgp.ac.in", isVerified: true },
    { name: "All India Institute of Medical Sciences Jodhpur", domain: "aiimsjodhpur.edu.in", isVerified: true },
    { name: "Alliance University", domain: "alliance.edu.in", isVerified: true },
    { name: "Veer Narmad South Gujarat University", domain: "vnsgu.ac.in", isVerified: true },
    { name: "Maulana Azad National Institute of Technology", domain: "manit.ac.in", isVerified: true },
    { name: "Punjabi University Patiala", domain: "punjabiuniversity.ac.in", isVerified: true },
    { name: "Babasaheb Bhimrao Ambedkar University", domain: "bbau.ac.in", isVerified: true },
    { name: "National Law University, Delhi", domain: "nludelhi.ac.in", isVerified: true },
    { name: "National Institute of Technology, Silchar", domain: "nits.ac.in", isVerified: true },
    { name: "Punjab Agricultural University", domain: "pau.edu", isVerified: true },
    { name: "Lalit Narayan Mithila University", domain: "lnmu.ac.in", isVerified: true },
    { name: "Tamil Nadu Dr. M.G.R. Medical University", domain: "tnmgrmu.ac.in", isVerified: true },
    { name: "Bundelkhand University", domain: "bujhansi.ac.in", isVerified: true },
    { name: "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology", domain: "veltech.edu.in", isVerified: true },
    { name: "Dibrugarh University", domain: "dibru.ac.in", isVerified: true },
    { name: "Sri Ramachandra Institute of Higher Education and Research", domain: "sriramachandra.edu.in", isVerified: true },
    { name: "National Institute of Technology, Jamshedpur", domain: "nitjsr.ac.in", isVerified: true },
    { name: "Himachal Pradesh University", domain: "hpuniv.ac.in", isVerified: true },
    { name: "Graphic Era University", domain: "geu.ac.in", isVerified: true },
    { name: "Jaypee University of Information Technology", domain: "juit.ac.in", isVerified: true },
    { name: "Visvesvaraya National Institute of Technology", domain: "vnit.ac.in", isVerified: true },
    { name: "All India Institute of Medical Sciences Rishikesh", domain: "aiimsrishikesh.edu.in", isVerified: true },
    { name: "BML Munjal University", domain: "bmu.edu.in", isVerified: true },
    { name: "Dr. Ram Manohar Lohia Avadh University", domain: "rmlau.ac.in", isVerified: true },
    { name: "Dr. Babasaheb Ambedkar Marathwada University", domain: "bamu.ac.in", isVerified: true },
    { name: "Graphic Era Hill University", domain: "gehu.ac.in", isVerified: true },
    { name: "Maharishi Markandeshwar University, Mullana", domain: "mmumullana.ac.in", isVerified: true },
    { name: "University of Jammu", domain: "jammuuniversity.ac.in", isVerified: true },
    { name: "National Forensic Sciences University", domain: "nfsu.ac.in", isVerified: true },
    { name: "University of North Bengal", domain: "northbengaluniversity.ac.in", isVerified: true },
    { name: "All India Institute of Medical Sciences Raipur", domain: "aiimsraipur.edu.in", isVerified: true },
    { name: "Indian Institute of Science Education and Research, Mohali", domain: "iisermohali.ac.in", isVerified: true },
    { name: "Jamia Hamdard", domain: "jamiahamdard.ac.in", isVerified: true },
    { name: "South Asian University", domain: "sau.int", isVerified: true },
    { name: "All India Institute of Medical Sciences Patna", domain: "aiimspatna.edu.in", isVerified: true },
    { name: "International Institute for Population Sciences", domain: "iipsindia.ac.in", isVerified: true },
    { name: "Uttaranchal University", domain: null, isVerified: false },
    { name: "M.J.P. Rohilkhand University", domain: "mjpru.ac.in", isVerified: true },
    { name: "Goa University", domain: "unigoa.ac.in", isVerified: true },
    { name: "Deen Dayal Upadhyay Gorakhpur University", domain: "ddugorakhpur.ac.in", isVerified: true },
    { name: "Hindustan Institute of Technology and Science", domain: "hindustanuniv.ac.in", isVerified: true },
    { name: "National Institute of Technology, Hamirpur", domain: "nith.ac.in", isVerified: true },
    { name: "Biju Patnaik University of Technology", domain: "bput.ac.in", isVerified: true },
    { name: "Govind Ballabh Pant University of Agriculture and Technology", domain: "gbpuat.ac.in", isVerified: true },
    { name: "Sree Chitra Thirunal Institute of Medical Sciences and Technology", domain: "sctimst.ac.in", isVerified: true },
    { name: "ITM University Raipur", domain: null, isVerified: false },
    { name: "Punjab Technical University", domain: "ptu.ac.in", isVerified: true },
    { name: "Jaypee Institute of Information Technology", domain: "jiit.ac.in", isVerified: true },
    { name: "Siksha 'O' Anusandhan", domain: "soauniversity.ac.in", isVerified: true },
    { name: "National Institute of Technology, Kurukshetra", domain: "nitkkr.ac.in", isVerified: true },
    { name: "JSS Academy of Higher Education and Research", domain: "jssuni.edu.in", isVerified: true },
    { name: "Dr. B. R. Ambedkar University Delhi", domain: "aud.ac.in", isVerified: true },
    { name: "Presidency University", domain: "presidencyuniversity.in", isVerified: true },
    { name: "Centurion University of Technology and Management", domain: "cutm.ac.in", isVerified: true },
    { name: "Assam University", domain: "aus.ac.in", isVerified: true },
    { name: "Galgotias University", domain: "galgotiasuniversity.edu.in", isVerified: true },
    { name: "Tilka Manjhi Bhagalpur University", domain: "tmbuniv.ac.in", isVerified: true },
    { name: "Kerala University of Health Sciences", domain: "kuhs.ac.in", isVerified: true },
    { name: "Sardar Patel University", domain: "spu.ac.in", isVerified: true },
    { name: "Rashtriya Sanskrit Sansthan University", domain: "rashtriyasanskrit.edu.in", isVerified: true },
    { name: "All India Institute of Medical Sciences Bhopal", domain: "aiimsbhopal.edu.in", isVerified: true },
    { name: "Manav Rachna University", domain: "mru.edu.in", isVerified: true },
    { name: "Maulana Azad National Urdu University", domain: "manuu.ac.in", isVerified: true },
    { name: "Hemchandracharya North Gujarat University", domain: "ngu.ac.in", isVerified: true },
    { name: "Acharya Nagarjuna University", domain: "nagarjunauniversity.ac.in", isVerified: true },
    { name: "Gokhale Institute of Politics and Economics", domain: "gipe.ac.in", isVerified: true },
    { name: "Swami Ramanand Teerth Marathwada University", domain: "srtmun.ac.in", isVerified: true },
    { name: "Ranchi University", domain: "ranchiuniversity.ac.in", isVerified: true },
    { name: "National Institute of Technology, Raipur", domain: "nitrr.ac.in", isVerified: true },
    { name: "University of Agricultural Sciences, Bangalore", domain: "uasbangalore.edu.in", isVerified: true },
    { name: "Hemwati Nandan Bahuguna Garhwal University", domain: "hnbgu.ac.in", isVerified: true },
    { name: "Babasaheb Bhimrao Ambedkar Bihar University", domain: "brabu.ac.in", isVerified: true },
    { name: "University of Kalyani", domain: "klyuniv.ac.in", isVerified: true },
    { name: "Shoolini University of Biotechnology and Management Sciences", domain: "shooliniuniversity.ac.in", isVerified: true },
    { name: "Pandit Deendayal Petroleum University", domain: "pdpu.ac.in", isVerified: true },
    { name: "Barkatullah University", domain: "barkatullahuniversity.ac.in", isVerified: true },
    { name: "Manonmaniam Sundaranar University", domain: "msuniv.ac.in", isVerified: true },
    { name: "Mizoram University", domain: "mizoramuniversity.ac.in", isVerified: true },
    { name: "Institute of Chemical Technology", domain: "ictmumbai.edu.in", isVerified: true },
    { name: "Dr. Harisingh Gour Vishwavidyalaya Sagar", domain: "dhsgsu.ac.in", isVerified: true },
    { name: "Anand Agricultural University", domain: "aau.in", isVerified: true },
    { name: "Vidyasagar University", domain: "vidyasagar.ac.in", isVerified: true },
    { name: "Indian Institute of Information Technology and Management Gwalior", domain: "iiitm.ac.in", isVerified: true },
    { name: "Mangalayatan University", domain: "mangalayatanuniversity.ac.in", isVerified: true },
    { name: "Tripura University", domain: "tripurauniv.ac.in", isVerified: true },
    { name: "Rabindra Bharati University", domain: "rbu.ac.in", isVerified: true },
    { name: "XIM University", domain: "xim.edu.in", isVerified: true },
    { name: "Sant Gadge Baba Amravati University", domain: "sgbau.ac.in", isVerified: true },
    { name: "Chhattisgarh Swami Vivekananda Technical University", domain: "csvtu.ac.in", isVerified: true },
    { name: "PDPM Indian Institute of Information Technology, Design and Manufacturing", domain: "iiitdmj.ac.in", isVerified: true },
    { name: "Sikkim Manipal University", domain: "smu.edu.in", isVerified: true },
    { name: "Dayalbagh Educational Institute", domain: "dei.ac.in", isVerified: true },
    { name: "Maharishi Dayanand University", domain: "mdu.ac.in", isVerified: true },
    { name: "REVA University", domain: "reva.edu.in", isVerified: true },
    { name: "Banasthali Vidyapith", domain: "banasthali.org", isVerified: true },
    { name: "Assam Agricultural University", domain: "aau.ac.in", isVerified: true },
    { name: "Swami Vivekanand Subharti University", domain: "subharti.org", isVerified: true },
    { name: "Periyar University", domain: "periyaruniversity.ac.in", isVerified: true },
    { name: "PEC University of Technology", domain: "pec.ac.in", isVerified: true },
    { name: "Central University of Haryana", domain: "cuh.ac.in", isVerified: true },
    { name: "Acharya N.G. Ranga Agricultural University", domain: "angrau.ac.in", isVerified: true },
    { name: "All India Institute of Medical Sciences Bhubaneswar", domain: "aiimsbhubaneswar.edu.in", isVerified: true },
    { name: "The English and Foreign Languages University", domain: "efluniversity.ac.in", isVerified: true },
    { name: "NIIT University", domain: "niituniversity.in", isVerified: true },
    { name: "Assam Don Bosco University", domain: "dbuniversity.ac.in", isVerified: true },
    { name: "Guru Ghasidas Vishwavidyalaya", domain: "ggu.ac.in", isVerified: true },
    { name: "Dr. Babasaheb Ambedkar Technological University", domain: "dbatu.ac.in", isVerified: true },
    { name: "Padmashree Dr. D.Y. Patil Vidyapith", domain: "dypvp.edu.in", isVerified: true },
    { name: "Mangalore University", domain: "mangaloreuniversity.ac.in", isVerified: true },
    { name: "The LNM Institute of Information Technology", domain: "lnmiit.ac.in", isVerified: true },
    { name: "Tamil Nadu Teacher Education University", domain: "tnteu.ac.in", isVerified: true },
    { name: "University of Kota", domain: "univkota.ac.in", isVerified: true },
    { name: "Gujarat Ayurved University", domain: "gau.in", isVerified: true },
    { name: "Utkal University", domain: "utkaluniversity.ac.in", isVerified: true },
    { name: "Baba Farid University of Health Sciences", domain: "bfuhs.ac.in", isVerified: true },
    { name: "Veer Surendra Sai University of Technology", domain: "vssut.ac.in", isVerified: true },
    { name: "The West Bengal National University of Juridical Sciences", domain: "wbnujs.ac.in", isVerified: true },
    { name: "National Institute of Technology, Patna", domain: "nitp.ac.in", isVerified: true },
    { name: "Central University of Rajasthan", domain: "curaj.ac.in", isVerified: true },
    { name: "Maharaja Chhatrasal Bundelkhand University", domain: null, isVerified: false },
    { name: "Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya", domain: "mcrpv.ac.in", isVerified: true },
    { name: "Atal Bihari Vajpayee Vishwavidyalaya", domain: null, isVerified: false },
    { name: "K.R. Mangalam University", domain: "krmangalam.edu.in", isVerified: true },
    { name: "Rajiv Gandhi University", domain: "rgu.ac.in", isVerified: true },
    { name: "Veer Bahadur Singh Purvanchal University", domain: "vbspu.ac.in", isVerified: true },
    { name: "National Institute of Technology, Agartala", domain: "nitagartala.ac.in", isVerified: true },
    { name: "Shri Ramswaroop Memorial University", domain: "srmu.ac.in", isVerified: true },
    { name: "Jaipur National University", domain: null, isVerified: false },
    { name: "School of Planning and Architecture, Delhi", domain: "spa.ac.in", isVerified: true },
    { name: "Islamic University of Science and Technology", domain: "iust.ac.in", isVerified: true },
    { name: "Indian Veterinary Research Institute", domain: "ivri.nic.in", isVerified: true },
    { name: "Gujarat National Law University", domain: "gnlu.ac.in", isVerified: true },
    { name: "Manipur University", domain: "manipuruniv.ac.in", isVerified: true },
    { name: "Adamas University", domain: "adamasuniversity.ac.in", isVerified: true },
    { name: "TERI School of Advanced Studies", domain: "terisas.ac.in", isVerified: true },
    { name: "Rashtrasant Tukadoji Maharaj Nagpur University", domain: "nagpuruniversity.ac.in", isVerified: true },
    { name: "Yenepoya University", domain: "yenepoya.edu.in", isVerified: true },
    { name: "DIT University", domain: "dituniversity.edu.in", isVerified: true },
    { name: "CMR University", domain: "cmr.edu.in", isVerified: true },
    { name: "Mahatma Gandhi Kashi Vidyapeeth", domain: "mgkvp.ac.in", isVerified: true },
    { name: "Vinayaka Mission's Research Foundation", domain: "vmrf.edu.in", isVerified: true },
    { name: "Integral University", domain: "integraluniversity.ac.in", isVerified: true },
    { name: "VIT Bhopal University", domain: "vitbhopal.ac.in", isVerified: true },
    { name: "DAV University", domain: "davuniversity.org", isVerified: true },
    { name: "Vels University", domain: "velsuniversity.edu.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Kottayam", domain: "iiitkottayam.ac.in", isVerified: true },
    { name: "Bangalore University", domain: "bangaloreuniversity.ac.in", isVerified: true },
    { name: "Dr. Bhimrao Ambedkar University", domain: "dbrau.ac.in", isVerified: true },
    { name: "Tamil Nadu Veterinary and Animal Sciences University", domain: "tanuvas.ac.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Design and Manufacturing", domain: "iiitdmch.ac.in", isVerified: true },
    { name: "Central University of Kerala", domain: "cukerala.ac.in", isVerified: true },
    { name: "Ravenshaw University", domain: "ravenshawuniversity.ac.in", isVerified: true },
    { name: "Uttarakhand Technical University", domain: null, isVerified: false },
    { name: "National Institute of Technology, Srinagar", domain: "nitkashmir.ac.in", isVerified: true },
    { name: "Rani Durgavati Vishwavidyalaya", domain: "rdvv.ac.in", isVerified: true },
    { name: "Bharath Institute of Higher Education and Research", domain: "bharathuniv.ac.in", isVerified: true },
    { name: "Central University of South Bihar", domain: "cub.ac.in", isVerified: true },
    { name: "National Institute of Technology, Meghalaya", domain: null, isVerified: false },
    { name: "Ganpat University", domain: "ganpatuniversity.ac.in", isVerified: true },
    { name: "National Law University, Jodhpur", domain: "nlujodhpur.ac.in", isVerified: true },
    { name: "Ramaiah University of Applied Sciences", domain: "ramaiahuniversity.ac.in", isVerified: true },
    { name: "IFHE Hyderabad", domain: "ifheindia.org", isVerified: true },
    { name: "Central University of Punjab", domain: "cup.ac.in", isVerified: true },
    { name: "Central University of Kashmir", domain: "cuc.ac.in", isVerified: true },
    { name: "Central University of Jharkhand", domain: "cuj.ac.in", isVerified: true },
    { name: "Karnatak University", domain: "karnatakuniversity.edu", isVerified: true },
    { name: "Sri Venkateswara University", domain: "svuniversity.ac.in", isVerified: true },
    { name: "Rishihood University", domain: "rishihood.edu.in", isVerified: true },
    { name: "Noida International University", domain: "niu.edu.in", isVerified: true },
    { name: "Vinoba Bhave University", domain: "vinobabhaveuniversity.ac.in", isVerified: true },
    { name: "Suresh Gyan Vihar University", domain: "sgvuniversity.ac.in", isVerified: true },
    { name: "Invertis University", domain: "invertisuniversity.ac.in", isVerified: true },
    { name: "Pandit Deendayal Upadhyaya Shekhawati University", domain: "pddsu.ac.in", isVerified: true },
    { name: "Dr. Rajendra Prasad Central Agricultural University", domain: "rpcau.ac.in", isVerified: true },
    { name: "Shreemati Nathibai Damodar Thackersey Women's University", domain: "sndt.ac.in", isVerified: true },
    { name: "The Northcap University", domain: "ncuindia.edu", isVerified: true },
    { name: "The Indian Law Institute", domain: "ili.ac.in", isVerified: true },
    { name: "Guru Jambheshwar University of Science and Technology", domain: "gjusbt.ac.in", isVerified: true },
    { name: "Vignan University", domain: "vignanuniversity.ac.in", isVerified: true },
    { name: "Prof. Rajendra Singh (Rajju Bhaiya) University", domain: "prsuniv.ac.in", isVerified: true },
    { name: "Rajiv Gandhi Institute of Petroleum Technology", domain: "rgipt.ac.in", isVerified: true },
    { name: "Central University of Himachal Pradesh", domain: "hpcu.ac.in", isVerified: true },
    { name: "GLA University", domain: "gla.ac.in", isVerified: true },
    { name: "Nalanda University", domain: "nalandauniv.edu.in", isVerified: true },
    { name: "Pt. Bhagwat Dayal Sharma University of Health Sciences", domain: "uhsr.ac.in", isVerified: true },
    { name: "The Gandhigram Rural Institute", domain: "ruraluniv.ac.in", isVerified: true },
    { name: "Shri Mata Vaishno Devi University", domain: "smvdu.ac.in", isVerified: true },
    { name: "Jawaharlal Nehru Technological University, Kakinada", domain: "jntuk.edu.in", isVerified: true },
    { name: "Jai Narain Vyas University", domain: "jnvu.edu.in", isVerified: true },
    { name: "Maharaja Krishnakumarsinhji Bhavnagar University", domain: "bhavnagaruniversity.ac.in", isVerified: true },
    { name: "Jawaharlal Nehru Technological University, Anantapur", domain: "jntua.ac.in", isVerified: true },
    { name: "Sri Sathya Sai Institute of Higher Learning", domain: "sssihl.edu.in", isVerified: true },
    { name: "Dr. N.T.R. University of Health Sciences", domain: "ntruhs.ap.nic.in", isVerified: true },
    { name: "Dev Sanskriti Vishwavidyalaya", domain: "devsanskriti.ac.in", isVerified: true },
    { name: "Sambalpur University", domain: "suniv.ac.in", isVerified: true },
    { name: "Kakatiya University", domain: "kakatiya.ac.in", isVerified: true },
    { name: "Indira Gandhi Krishi Vishwavidyalaya", domain: "igkv.ac.in", isVerified: true },
    { name: "Central University of Tamil Nadu", domain: "cutn.ac.in", isVerified: true },
    { name: "Marwadi University", domain: "marwadiuniversity.ac.in", isVerified: true },
    { name: "National Institute of Pharmaceutical Education and Research, S.A.S. Nagar", domain: "niper.gov.in", isVerified: true },
    { name: "Kalasalingam Academy of Research and Education", domain: null, isVerified: false },
    { name: "Junagadh Agricultural University", domain: "jau.in", isVerified: true },
    { name: "Navsari Agricultural University", domain: "nau.in", isVerified: true },
    { name: "Rajasthan University of Veterinary and Animal Sciences", domain: null, isVerified: false },
    { name: "GD Goenka University", domain: "gdgoenkauniversity.com", isVerified: true },
    { name: "Patna University", domain: "patnauniversity.ac.in", isVerified: true },
    { name: "National Institute of Technology, Puducherry", domain: "nitpy.ac.in", isVerified: true },
    { name: "CSK Himachal Pradesh Krishi Vishvavidyalaya", domain: null, isVerified: false },
    { name: "The National University of Advanced Legal Studies", domain: "nuals.ac.in", isVerified: true },
    { name: "National Institute of Food Technology Entrepreneurship and Management", domain: "niftem.ac.in", isVerified: true },
    { name: "Sikkim University", domain: "sikkimuniversity.ac.in", isVerified: true },
    { name: "Rajiv Gandhi University of Knowledge Technologies", domain: "rgukt.in", isVerified: true },
    { name: "National Dairy Research Institute", domain: "ndri.res.in", isVerified: true },
    { name: "Gautam Buddha University", domain: "gbu.ac.in", isVerified: true },
    { name: "Doon University", domain: "doonuniversity.ac.in", isVerified: true },
    { name: "Maharaja Ganga Singh University", domain: "mgsu.ac.in", isVerified: true },
    { name: "Rajasthan Technical University Kota", domain: "rtu.ac.in", isVerified: true },
    { name: "Chaudhary Charan Singh Haryana Agricultural University", domain: "hau.ac.in", isVerified: true },
    { name: "Brainware University", domain: "brainwareuniversity.ac.in", isVerified: true },
    { name: "Dayananda Sagar University", domain: "dayanandasagar.edu", isVerified: true },
    { name: "ITM University Gwalior", domain: "itmuniversity.ac.in", isVerified: true },
    { name: "Maharshi Dayanand Saraswati University", domain: "mdsuajmer.ac.in", isVerified: true },
    { name: "National Institute of Technology Delhi", domain: "nitdelhi.ac.in", isVerified: true },
    { name: "Kuvempu University", domain: "kuvempuuniversity.ac.in", isVerified: true },
    { name: "University of Agricultural Sciences, Dharwad", domain: "uasd.edu.in", isVerified: true },
    { name: "Kumaun University", domain: "kumauniversity.ac.in", isVerified: true },
    { name: "KLE Technological University", domain: "kletech.ac.in", isVerified: true },
    { name: "Gujarat Vidyapith", domain: "gujaratvidyapith.org", isVerified: true },
    { name: "Sido Kanhu Murmu University", domain: "skmu.ac.in", isVerified: true },
    { name: "Professor Jayashankar Telangana State Agricultural University", domain: "pjtsau.ac.in", isVerified: true },
    { name: "National Law Institute University", domain: "nliu.ac.in", isVerified: true },
    { name: "B.S. Abdur Rahman Crescent Institute of Science and Technology", domain: "crescent.education", isVerified: true },
    { name: "Madan Mohan Malaviya University of Technology", domain: "mmmut.ac.in", isVerified: true },
    { name: "Rama University", domain: "ramauniversity.ac.in", isVerified: true },
    { name: "Harcourt Butler Technical University", domain: "hbtu.ac.in", isVerified: true },
    { name: "Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir", domain: "skuastkashmir.ac.in", isVerified: true },
    { name: "Garden City University", domain: "gardencity.university", isVerified: true },
    { name: "Motherhood University", domain: "motherhooduniversity.edu.in", isVerified: true },
    { name: "Medi-Caps University", domain: "medicaps.ac.in", isVerified: true },
    { name: "Thiruvalluvar University", domain: "tvu.ac.in", isVerified: true },
    { name: "Homi Bhabha National Institute", domain: "hbni.ac.in", isVerified: true },
    { name: "Pravara Institute of Medical Sciences", domain: null, isVerified: false },
    { name: "Magadh University", domain: "magadhuniversity.ac.in", isVerified: true },
    { name: "Rani Channamma University, Belagavi", domain: "rcub.ac.in", isVerified: true },
    { name: "Ramakrishna Mission Vivekananda Educational and Research Institute", domain: "rkmvu.ac.in", isVerified: true },
    { name: "IIHMR University", domain: "iihmr.edu.in", isVerified: true },
    { name: "Janardan Rai Nagar Rajasthan Vidhyapeeth University", domain: "jnrvu.edu.in", isVerified: true },
    { name: "Nagaland University", domain: "nagalanduniversity.ac.in", isVerified: true },
    { name: "National Institute of Technology, Arunachal Pradesh", domain: "nitap.ac.in", isVerified: true },
    { name: "Srimanta Sankaradeva University of Health Sciences", domain: "ssuahs.in", isVerified: true },
    { name: "National Institute of Technology, Goa", domain: "nitgoa.ac.in", isVerified: true },
    { name: "Shree Guru Gobind Singh Tricentenary University", domain: "sgtsu.ac.in", isVerified: true },
    { name: "West Bengal University of Teachers' Training, Education Planning and Administration", domain: "wbuttepa.ac.in", isVerified: true },
    { name: "Awadhesh Pratap Singh University", domain: "apsu.ac.in", isVerified: true },
    { name: "Central University of Gujarat", domain: "cug.ac.in", isVerified: true },
    { name: "Kalinga University", domain: "kalingauniversity.ac.in", isVerified: true },
    { name: "Jawaharlal Nehru Krishi Vishwavidyalaya", domain: "jnkvv.edu.in", isVerified: true },
    { name: "The IIS University", domain: "iisuniv.ac.in", isVerified: true },
    { name: "Central University of Karnataka", domain: "cuk.ac.in", isVerified: true },
    { name: "JK Lakshmipat University", domain: "jklu.edu.in", isVerified: true },
    { name: "Bidhan Chandra Krishi Viswavidyalaya", domain: "bckv.edu.in", isVerified: true },
    { name: "Berhampur University", domain: "buodisha.edu.in", isVerified: true },
    { name: "Aryabhatta Knowledge University", domain: "aku.ac.in", isVerified: true },
    { name: "Presidency University", domain: "presidencyuniversity.in", isVerified: true },
    { name: "National Institute of Technology Sikkim", domain: "nitsikkim.ac.in", isVerified: true },
    { name: "Dr. Y.S. Parmar University of Horticulture and Forestry", domain: "yspuniversity.ac.in", isVerified: true },
    { name: "Poornima University", domain: "poornima.org", isVerified: true },
    { name: "Sri Sri University", domain: "srisriuniversity.edu.in", isVerified: true },
    { name: "Sant Longowal Institute of Engineering and Technology", domain: "sliet.ac.in", isVerified: true },
    { name: "Odisha University of Agriculture and Technology", domain: "ouat.ac.in", isVerified: true },
    { name: "Central University of Jammu", domain: "cujammu.edu.in", isVerified: true },
    { name: "Kerala Veterinary and Animal Sciences University", domain: "kvau.ac.in", isVerified: true },
    { name: "Swami Vivekanand University", domain: "svu.ac.in", isVerified: true },
    { name: "Nizam's Institute of Medical Sciences", domain: "nims.edu", isVerified: true },
    { name: "Shri Venkateshwara University", domain: "svu.edu.in", isVerified: true },
    { name: "Adikavi Nannaya University", domain: null, isVerified: false },
    { name: "North Eastern Regional Institute of Science and Technology", domain: "nerist.ac.in", isVerified: true },
    { name: "Hidayatullah National Law University", domain: "hnlu.ac.in", isVerified: true },
    { name: "Bhakta Kavi Narsinh Mehta University", domain: "bknmu.edu.in", isVerified: true },
    { name: "Assam Science and Technology University", domain: "astu.ac.in", isVerified: true },
    { name: "NIMS University", domain: "nimsuniversity.ac.in", isVerified: true },
    { name: "Cotton University", domain: "cottonuniversity.ac.in", isVerified: true },
    { name: "Sarguja University", domain: "su.ac.in", isVerified: true },
    { name: "Dr. M.G.R. Educational and Research Institute", domain: "drmgrdu.ac.in", isVerified: true },
    { name: "Indira Gandhi Delhi Technical University for Women", domain: "igdtuw.ac.in", isVerified: true },
    { name: "Sher-i-Kashmir Institute of Medical Sciences", domain: "skims.ac.in", isVerified: true },
    { name: "Aliah University", domain: "aliah.ac.in", isVerified: true },
    { name: "Karpagam Academy of Higher Education", domain: "karpagam.ac.in", isVerified: true },
    { name: "National Law University Odisha", domain: "nluo.ac.in", isVerified: true },
    { name: "Dr. Panjabrao Deshmukh Krishi Vidyapeeth", domain: "pdkv.ac.in", isVerified: true },
    { name: "Gurukul Kangri Vishwavidyalaya", domain: "gkv.ac.in", isVerified: true },
    { name: "Indian Maritime University", domain: "imu.edu.in", isVerified: true },
    { name: "Raj Rishi Bharthari Matsya University", domain: null, isVerified: false },
    { name: "Utkal University of Culture", domain: null, isVerified: false },
    { name: "Mahatma Phule Krishi Vidyapeeth", domain: "mpkv.ac.in", isVerified: true },
    { name: "Malwanchal University", domain: "malwanchaluniversity.edu.in", isVerified: true },
    { name: "Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu", domain: null, isVerified: false },
    { name: "University of Gour Banga", domain: "ugb.ac.in", isVerified: true },
    { name: "Vikram University", domain: "vikramuniv.ac.in", isVerified: true },
    { name: "Deenbandhu Chhotu Ram University of Science and Technology", domain: "dcrustm.ac.in", isVerified: true },
    { name: "Tamil Nadu Dr Ambedkar Law University", domain: "tndalu.ac.in", isVerified: true },
    { name: "National Institute of Pharmaceutical Education and Research, Hyderabad", domain: "niperhyd.ac.in", isVerified: true },
    { name: "Guru Angad Dev Veterinary and Animal Sciences University", domain: "gadvasu.in", isVerified: true },
    { name: "Anant National University", domain: "anant.edu", isVerified: true },
    { name: "National Institute of Technology Mizoram", domain: "nitmz.ac.in", isVerified: true },
    { name: "Mody University of Science and Technology", domain: "modyuniversity.ac.in", isVerified: true },
    { name: "Indira Gandhi National Tribal University", domain: "igntu.ac.in", isVerified: true },
    { name: "SRM University Haryana", domain: "srmh.ac.in", isVerified: true },
    { name: "Quantum University", domain: "quantumuniversity.ac.in", isVerified: true },
    { name: "Himachal Pradesh Technical University", domain: "hptu.ac.in", isVerified: true },
    { name: "Glocal University", domain: "glocaluniversity.ac.in", isVerified: true },
    { name: "Central University of Odisha", domain: "cuo.ac.in", isVerified: true },
    { name: "Rajiv Gandhi National University of Law", domain: "rgnul.ac.in", isVerified: true },
    { name: "Dharmsinh Desai University", domain: "ddu.ac.in", isVerified: true },
    { name: "Shobhit Institute of Engineering and Technology", domain: "shobhituniversity.ac.in", isVerified: true },
    { name: "RK University", domain: "rku.ac.in", isVerified: true },
    { name: "Datta Meghe Institute of Higher Education & Research", domain: "dmimsdu.edu.in", isVerified: true },
    { name: "Uttar Pradesh University of Medical Sciences", domain: "upums.ac.in", isVerified: true },
    { name: "Sage University", domain: "sageuniversity.in", isVerified: true },
    { name: "Raiganj University", domain: "raiganjuniversity.ac.in", isVerified: true },
    { name: "Charotar University of Science and Technology", domain: "charusat.ac.in", isVerified: true },
    { name: "Veer Kunwar Singh University", domain: "vksu.ac.in", isVerified: true },
    { name: "Sri Balaji Vidyapeeth", domain: "sbvu.ac.in", isVerified: true },
    { name: "Mahatma Gandhi Central University, Motihari", domain: "mgcub.ac.in", isVerified: true },
    { name: "Central Institute of Higher Tibetan Studies", domain: null, isVerified: false },
    { name: "School of Planning and Architecture, Vijayawada", domain: "spav.ac.in", isVerified: true },
    { name: "Nanaji Deshmukh Veterinary Science University", domain: null, isVerified: false },
    { name: "Rashtriya Raksha University", domain: "rru.ac.in", isVerified: true },
    { name: "Central Institute of Fisheries Education", domain: "cife.edu.in", isVerified: true },
    { name: "Singhania University", domain: "singhaniauniversity.ac.in", isVerified: true },
    { name: "Mewar University", domain: "mewaruniversity.ac.in", isVerified: true },
    { name: "Tilak Maharashtra Vidyapeeth", domain: "tmv.edu.in", isVerified: true },
    { name: "School of Planning and Architecture, Bhopal", domain: null, isVerified: false },
    { name: "Gangadhar Meher University", domain: "gmuniversity.ac.in", isVerified: true },
    { name: "J.C. Bose University of Science and Technology, YMCA Faridabad", domain: "ymcabc.ac.in", isVerified: true },
    { name: "Cooch Behar Panchanan Barma University", domain: "cbpbu.ac.in", isVerified: true },
    { name: "National Institute of Technology, Uttarakhand", domain: "nituk.ac.in", isVerified: true },
    { name: "Assam Down Town University", domain: "adt.ac.in", isVerified: true },
    { name: "Kerala University of Fisheries and Ocean Studies", domain: "kufos.ac.in", isVerified: true },
    { name: "Chaudhary Devi Lal University", domain: "cdlu.ac.in", isVerified: true },
    { name: "Chandra Shekhar Azad University of Agriculture and Technology", domain: "csauat.ac.in", isVerified: true },
    { name: "Jharkhand Rai University", domain: "jru.edu.in", isVerified: true },
    { name: "Sandip University", domain: "sandipuniversity.edu.in", isVerified: true },
    { name: "IMS Unison University", domain: "imsunison.ac.in", isVerified: true },
    { name: "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya", domain: null, isVerified: false },
    { name: "National Sanskrit University", domain: "nsu.ac.in", isVerified: true },
    { name: "JECRC University", domain: "jecrcuniversity.edu.in", isVerified: true },
    { name: "Vivekananda Global University", domain: "vgu.ac.in", isVerified: true },
    { name: "Krantiguru Shyamji Krishna Verma Kachchh University", domain: null, isVerified: false },
    { name: "Birsa Agricultural University", domain: "bau.edu.in", isVerified: true },
    { name: "Avantika University", domain: "avantikauniversity.edu.in", isVerified: true },
    { name: "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya", domain: "sssvm.edu.in", isVerified: true },
    { name: "Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth", domain: "dbskkv.org.in", isVerified: true },
    { name: "Vishwakarma University", domain: "vupune.edu.in", isVerified: true },
    { name: "Lingaya's University", domain: "lingayasuniversity.edu.in", isVerified: true },
    { name: "Ajeenkya D.Y. Patil University", domain: "adypu.edu.in", isVerified: true },
    { name: "Bihar Agricultural University", domain: "bau-bhagalpur.ac.in", isVerified: true },
    { name: "Sam Higginbottom Institute of Agriculture, Technology and Sciences", domain: "shiats.edu.in", isVerified: true },
    { name: "Techno India University", domain: "technoindiauniversity.ac.in", isVerified: true },
    { name: "National Institute of Technology, Manipur", domain: "nitmanipur.ac.in", isVerified: true },
    { name: "Lakshmibai National Institute of Physical Education", domain: "lnipe.edu.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Vadodara", domain: "iiitvadodara.ac.in", isVerified: true },
    { name: "National University of Study and Research in Law", domain: "nusrl.ac.in", isVerified: true },
    { name: "Rajiv Gandhi National Institute of Youth Development", domain: "rgnuyd.gov.in", isVerified: true },
    { name: "Arunachal University of Studies", domain: null, isVerified: false },
    { name: "Maharana Pratap University of Agriculture and Technology", domain: "mpuat.ac.in", isVerified: true },
    { name: "Sardarkrushinagar Dantiwada Agricultural University", domain: "sdau.edu.in", isVerified: true },
    { name: "Indira Gandhi University", domain: "igu.ac.in", isVerified: true },
    { name: "Govind Guru Tribal University", domain: "ggtu.ac.in", isVerified: true },
    { name: "Sree Sankaracharya University of Sanskrit", domain: "ssus.ac.in", isVerified: true },
    { name: "National Law University and Judicial Academy", domain: "nluassam.ac.in", isVerified: true },
    { name: "Sunrise University", domain: "sunriseuniversity.edu.in", isVerified: true },
    { name: "Dr. Ram Manohar Lohiya National Law University", domain: "rmlnlu.ac.in", isVerified: true },
    { name: "Mahatma Gandhi University, Nalgonda", domain: null, isVerified: false },
    { name: "Uka Tarsadia University", domain: null, isVerified: false },
    { name: "Chanakya National Law University", domain: "cnlu.ac.in", isVerified: true },
    { name: "LNCT University", domain: "lnctu.edu.in", isVerified: true },
    { name: "ICFAI University, Tripura", domain: "iutripura.edu.in", isVerified: true },
    { name: "IEC University", domain: "iec.ac.in", isVerified: true },
    { name: "Dr. C.V. Raman University", domain: "cvru.ac.in", isVerified: true },
    { name: "Chaudhary Ranbir Singh University", domain: "crsu.ac.in", isVerified: true },
    { name: "Kazi Nazrul University", domain: "knu.ac.in", isVerified: true },
    { name: "Maharashtra Animal and Fishery Sciences University", domain: "mafsu.in", isVerified: true },
    { name: "Karnavati University", domain: "karnavatiuniversity.edu.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Guwahati", domain: "iiitg.ac.in", isVerified: true },
    { name: "Bhagat Phool Singh Mahila Vishwavidyalaya", domain: "bpsmv.ac.in", isVerified: true },
    { name: "Karnataka State Law University", domain: "kslu.ac.in", isVerified: true },
    { name: "Lala Lajpat Rai University of Veterinary and Animal Sciences", domain: "llruvas.ac.in", isVerified: true },
    { name: "Sir Padampat Singhania University", domain: "spsu.ac.in", isVerified: true },
    { name: "Siddharth University", domain: null, isVerified: false },
    { name: "Krishna Vishwa Vidyapeeth", domain: null, isVerified: false },
    { name: "University of Trans-Disciplinary Health Sciences and Technology", domain: null, isVerified: false },
    { name: "Sri Padmavati Mahila Visvavidyalayam", domain: "spmv.ac.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Sri City", domain: "iiits.ac.in", isVerified: true },
    { name: "Tamil University", domain: "tamiluniversity.ac.in", isVerified: true },
    { name: "Swami Rama Himalayan University", domain: "srhu.edu.in", isVerified: true },
    { name: "National Institute of Technology, Nagaland", domain: "nitnagaland.ac.in", isVerified: true },
    { name: "Indira Gandhi Institute of Medical Sciences", domain: "igims.org", isVerified: true },
    { name: "Periyar Maniammai Institute of Science and Technology", domain: null, isVerified: false },
    { name: "Avinashilingam Institute for Home Science and Higher Education for Women", domain: "avinashilingam.ac.in", isVerified: true },
    { name: "Sidho Kanho Birsha University", domain: "skbu.ac.in", isVerified: true },
    { name: "Jaypee University of Engineering and Technology", domain: "juet.ac.in", isVerified: true },
    { name: "St. Xavier's University", domain: "sxuk.edu.in", isVerified: true },
    { name: "Sushant University", domain: "sushantuniversity.edu.in", isVerified: true },
    { name: "IIMT University", domain: "iimt.ac.in", isVerified: true },
    { name: "Sri Dev Suman Uttarakhand University", domain: "sdsuvt.org.in", isVerified: true },
    { name: "Fakir Mohan University", domain: "fmu.ac.in", isVerified: true },
    { name: "MIT Art Design and Technology University", domain: "mituniversity.edu.in", isVerified: true },
    { name: "Vasantrao Naik Marathwada Krishi Vidyapeeth", domain: "vnmkv.ac.in", isVerified: true },
    { name: "MGM Institute of Health Sciences", domain: "mgmuhs.ac.in", isVerified: true },
    { name: "Sarvepalli Radhakrishnan University", domain: "srru.ac.in", isVerified: true },
    { name: "Gulbarga University", domain: null, isVerified: false },
    { name: "Atmiya University", domain: "atmiyauni.ac.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Lucknow", domain: "iiitl.ac.in", isVerified: true },
    { name: "MATS University", domain: "matsuniversity.ac.in", isVerified: true },
    { name: "Bankura University", domain: "bankurauniv.ac.in", isVerified: true },
    { name: "Binod Bihari Mahto Koyalanchal University", domain: "bbmku.ac.in", isVerified: true },
    { name: "Krishna University", domain: null, isVerified: false },
    { name: "Mother Teresa Women's University", domain: "mtwu.ac.in", isVerified: true },
    { name: "GNA University", domain: "gnauniversity.edu.in", isVerified: true },
    { name: "Jawaharlal Nehru Architecture and Fine Arts University", domain: "jnafau.ac.in", isVerified: true },
    { name: "GSFC University", domain: "gsfcuniversity.ac.in", isVerified: true },
    { name: "AKS University", domain: "aksuniversity.ac.in", isVerified: true },
    { name: "Himalayan University", domain: null, isVerified: false },
    { name: "Tamil Nadu Dr. J. Jayalalithaa Fisheries University", domain: "tnjfuf.ac.in", isVerified: true },
    { name: "Sangam University", domain: "sangamuniversity.ac.in", isVerified: true },
    { name: "Kerala Kalamandalam", domain: "kalamandalam.ac.in", isVerified: true },
    { name: "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya", domain: "rvskvv.in", isVerified: true },
    { name: "Tumkur University", domain: "tumkuruniversity.ac.in", isVerified: true },
    { name: "Rayalaseema University", domain: "ru.ac.in", isVerified: true },
    { name: "Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha", domain: "slbsrv.ac.in", isVerified: true },
    { name: "Mahatma Gandhi University of Medical Sciences and Technology", domain: "mgumst.org", isVerified: true },
    { name: "Karnataka Veterinary, Animal and Fisheries Sciences University", domain: "kvafsu.karnataka.gov.in", isVerified: true },
    { name: "Gondwana University", domain: "gondwana.university", isVerified: true },
    { name: "Kolhan University", domain: "kolhanuniversity.ac.in", isVerified: true },
    { name: "Chitkara University, Himachal Pradesh", domain: "chitkara.edu.in", isVerified: true },
    { name: "Sri Krishnadevaraya University", domain: "skuniversity.ac.in", isVerified: true },
    { name: "G.L.S. University", domain: "glsuniversity.ac.in", isVerified: true },
    { name: "Bhupendra Narayan Mandal University", domain: "bnmu.ac.in", isVerified: true },
    { name: "Sardar Vallabhbhai Patel University of Agriculture and Technology", domain: "svpuat.edu.in", isVerified: true },
    { name: "Indian Institute of Public Health", domain: "iiphg.edu.in", isVerified: true },
    { name: "Jagannath University", domain: "jagannathuniversity.org", isVerified: true },
    { name: "JIS University", domain: "jisuniversity.ac.in", isVerified: true },
    { name: "Institute of Infrastructure, Technology, Research and Management", domain: "iitram.ac.in", isVerified: true },
    { name: "West Bengal University of Animal and Fishery Sciences", domain: "wbuafsc.edu.in", isVerified: true },
    { name: "Rayat-Bahra University", domain: "rayatbahrauniversity.edu.in", isVerified: true },
    { name: "Indus University", domain: "indusuni.ac.in", isVerified: true },
    { name: "Cluster University of Jammu", domain: "clujammu.ac.in", isVerified: true },
    { name: "Deccan College Post-Graduate and Research Institute", domain: "dcpune.ac.in", isVerified: true },
    { name: "AURO University", domain: "aurouniversity.edu.in", isVerified: true },
    { name: "Indian Institute of Information Technology, Una", domain: "iiitu.ac.in", isVerified: true },
    { name: "Yogi Vemana University", domain: "yogivemanauniversity.ac.in", isVerified: true },
    { name: "Desh Bhagat University", domain: "deshbhagatuniversity.in", isVerified: true },
    { name: "Jain Vishva Bharati Institute", domain: "jvbi.ac.in", isVerified: true },
    { name: "Maharashtra National Law University, Nagpur", domain: "nlunagpur.ac.in", isVerified: true },
    { name: "Forest Research Institute", domain: "fridu.edu.in", isVerified: true },
    { name: "Maharaja Ranjit Singh Punjab Technical University", domain: "mrsptu.ac.in", isVerified: true },
    { name: "Shri Vaishnav Vidyapeeth Vishwavidyalaya", domain: "svvv.edu.in", isVerified: true },
    { name: "Symbiosis University of Applied Sciences", domain: "suas.ac.in", isVerified: true },
    { name: "Uttar Banga Krishi Viswavidyalaya", domain: "ubkv.ac.in", isVerified: true },
    { name: "Navrachana University", domain: "nuv.ac.in", isVerified: true },
    { name: "International Institute of Information Technology, Bhubaneswar", domain: "iiit-bh.ac.in", isVerified: true },
    { name: "Swami Keshwanand Rajasthan Agricultural University", domain: "raubikaner.org", isVerified: true },
    { name: "RKDF University", domain: "rkdf.ac.in", isVerified: true },
    { name: "Babu Banarasi Das University", domain: "bbdu.ac.in", isVerified: true },
    { name: "KLE University", domain: "kledeemeduniversity.edu.in", isVerified: true },
    { name: "Jayoti Vidyapeeth Women's University", domain: "jvwu.ac.in", isVerified: true },
    { name: "Maharaja Agrasen Himalayan Garhwal University", domain: "hgu.ac.in", isVerified: true },                                        
    { name: "Central Agricultural University", domain: "cau.ac.in", isVerified: true },
    { name: "Maharashtra National Law University Mumbai", domain: "mnlumumbai.edu.in", isVerified: true },
    { name: "Chaudhary Bansi Lal University", domain: "cblu.ac.in", isVerified: true },
    { name: "Sanskriti University", domain: "sanskriti.edu.in", isVerified: true },
    { name: "Rai University", domain: "raiuniversity.edu", isVerified: true },
    { name: "Madhav University", domain: "madhavuniversity.edu.in", isVerified: true },
    { name: "Rabindranath Tagore University", domain: "rntu.ac.in", isVerified: true },
    { name: "Punyashlok Ahilyadevi Holkar Solapur University", domain: "su.digitaluniversity.ac", isVerified: true },
    { name: "Maharaja Surajmal Brij University", domain: "msbrijuniversity.ac.in", isVerified: true },
    { name: "Career Point University", domain: "cpur.in", isVerified: true },
    { name: "Indian Institute of Teacher Education", domain: "iite.ac.in", isVerified: true },
    { name: "Potti Sreeramulu Telugu University", domain: "teluguuniversity.ac.in", isVerified: true },
    { name: "Davangere University", domain: "davangereuniversity.ac.in", isVerified: true },
    { name: "People's University", domain: "peoplesuniversity.edu.in", isVerified: true },
    { name: "Nava Nalanda Mahavihara", domain: "nnm.ac.in", isVerified: true },
    { name: "National Institute of Pharmaceutical Education and Research, Guwahati", domain: "niperhyd.ac.in", isVerified: true },
    { name: "Shri Govind Guru University", domain: "sggu.ac.in", isVerified: true },
    { name: "Jagran Lakecity University", domain: "jlu.edu.in", isVerified: true },
    { name: "MIT University", domain: "mits.ac.in", isVerified: true },
    { name: "Institute of Advanced Studies in Education", domain: "iaseuniversity.org.in", isVerified: true },
    { name: "Kaziranga University", domain: "kazirangauniversity.in", isVerified: true },
    { name: "Maharishi University", domain: "maharishiuniversity.ac.in", isVerified: true },
    { name: "National Institute of Pharmaceutical Education and Research, Ahmedabad", domain: "niperahm.ac.in", isVerified: true },
    { name: "Hemwati Nandan Bahuguna Uttarakhand Medical Education University", domain: "hnbumu.ac.in", isVerified: true },
    { name: "Satavahana University", domain: "satavahana.ac.in", isVerified: true },
    { name: "JS University", domain: "jsu.edu.in", isVerified: true },
    { name: "RIMT University", domain: "rimt.ac.in", isVerified: true },
    { name: "Vikrama Simhapuri University", domain: "svuniversity.edu.in", isVerified: true },
    { name: "Tamil Nadu Physical Education and Sports University", domain: "tnpesu.org", isVerified: true },
    { name: "The Assam Royal Global University", domain: "rgu.ac", isVerified: true },
    { name: "Acharya Narendra Deva University of Agriculture & Technology", domain: "anduatu.ac.in", isVerified: true },
    { name: "GIET University", domain: "giet.edu", isVerified: true },
    { name: "P P Savani University", domain: "ppsu.ac.in", isVerified: true },
    { name: "Guru Kashi University", domain: "gku.ac.in", isVerified: true },
    { name: "Vijayanagara Sri Krishnadevaraya University", domain: "vskub.ac.in", isVerified: true },
    { name: "Sabarmati University", domain: "sabarmatiuniversity.edu.in", isVerified: true },
    { name: "Dravidian University", domain: "dravidianuniversity.ac.in", isVerified: true },
    { name: "Bodoland University", domain: "buniv.edu.in", isVerified: true },
    { name: "Dr K.N. Modi University", domain: "dknmu.org", isVerified: true },
    { name: "Shri Guru Ram Rai University", domain: "sgrru.ac.in", isVerified: true },
    { name: "University of Horticultural Sciences, Bagalkot", domain: "uhsbagalkot.karnataka.gov.in", isVerified: true },
    { name: "U.P. Pt. Deen Dayal Upadhyaya Veterinary Science University and Cattle Research Institute", domain: "upvetuniv.edu.in", isVerified: true },
    { name: "University of Science and Technology, Meghalaya", domain: "ustm.ac.in", isVerified: true },
    { name: "Kadi Sarva Vishwavidyalaya", domain: "ksvuniversity.org.in", isVerified: true },
    { name: "Martin Luther Christian University", domain: "mlcuniv.in", isVerified: true },
    { name: "International Institute of Information Technology, Naya Raipur", domain: "iiitnr.ac.in", isVerified: true },
    { name: "Shaheed Mahendra Karma Vishwavidyalaya", domain: "bvvjdp.ac.in", isVerified: true },
    { name: "Monad University", domain: "monad.edu.in", isVerified: true },
    { name: "Damodaram Sanjivayya National Law University", domain: "dsnlu.ac.in", isVerified: true },
    { name: "Murshidabad University", domain: null, isVerified: false },
    { name: "Telangana University", domain: null, isVerified: false },
    { name: "Delhi Pharmaceutical Sciences and Research University", domain: null, isVerified: false },
    { name: "Sri Guru Granth Sahib World University", domain: null, isVerified: false },
    { name: "Alakh Prakash Goyal Shimla University", domain: null, isVerified: false },
    { name: "IFTM University", domain: null, isVerified: false },
    { name: "Sri Guru Ram Das University of Health Sciences", domain: null, isVerified: false },
    { name: "BLDE University", domain: null, isVerified: false },
    { name: "ISBM University", domain: null, isVerified: false },
    { name: "Jananayak Chandrashekhar University", domain: null, isVerified: false },
    { name: "North Orissa University", domain: "nou.nic.in", isVerified: true },
    { name: "Guru Ravidas Ayurved University", domain: "graupunjab.org", isVerified: true },
    { name: "Oriental University", domain: null, isVerified: false },
    { name: "West Bengal State University", domain: "wbsu.ac.in", isVerified: true },
    { name: "ICFAI University, Dehradun", domain: "iudehradun.edu.in", isVerified: true },
    { name: "Indira Kala Sangeet Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Assam Women's University", domain: null, isVerified: false },
    { name: "O.P. Jindal University", domain: null, isVerified: false },
    { name: "Al‑Falah University", domain: null, isVerified: false },
    { name: "Karnataka State Akkamahadevi Women's University", domain: null, isVerified: false },
    { name: "Indian Institute of Information Technology, Kalyani", domain: null, isVerified: false },
    { name: "EIILM University", domain: null, isVerified: false },
    { name: "Jodhpur National University", domain: null, isVerified: false },
    { name: "Pacific University, India", domain: null, isVerified: false },
    { name: "ITM Vocational University", domain: null, isVerified: false },
    { name: "Indian Institute of Information Technology, Pune", domain: null, isVerified: false },
    { name: "Arka Jain University", domain: null, isVerified: false },
    { name: "Sri Satya Sai University of Technology and Medical Sciences", domain: null, isVerified: false },
    { name: "Era University", domain: null, isVerified: false },
    { name: "Mahatma Gandhi University, Meghalaya", domain: "mgu.edu.in", isVerified: true },
    { name: "Shri Guru Ram Rai Education Mission", domain: "sgrru.ac.in", isVerified: true },
    { name: "Sri Venkateswara Veterinary University", domain: "svvu.edu.in", isVerified: true },
    { name: "Sri Venkateswara Institute of Medical Sciences", domain: null, isVerified: false },
    { name: "Maharishi Markandeshwar University, Solan", domain: null, isVerified: false },
    { name: "Usha Martin University", domain: null, isVerified: false },
    { name: "Thunchath Ezhuthachan Malayalam University", domain: null, isVerified: false },
    { name: "Santosh University", domain: null, isVerified: false },
    { name: "Bhagwant University", domain: null, isVerified: false },
    { name: "Banda University of Agriculture and Technology", domain: null, isVerified: false },
    { name: "Adesh University", domain: null, isVerified: false },
    { name: "Dr. B.R. Ambedkar University", domain: null, isVerified: false },
    { name: "Meenakshi Academy of Higher Education and Research", domain: "maher.ac.in", isVerified: true },
    { name: "Shri Vishwakarma Skill University", domain: "svsu.ac.in", isVerified: true },
    { name: "National Institute of Pharmaceutical Education and Research, Raebareli", domain: null, isVerified: false },
    { name: "Mahatma Jyoti Rao Phoole University", domain: null, isVerified: false },
    { name: "Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya", domain: null, isVerified: false },
    { name: "JSS Science and Technology University", domain: null, isVerified: false },
    { name: "Kannada University", domain: null, isVerified: false },
    { name: "Shree Somnath Sanskrit University", domain: null, isVerified: false },
    { name: "Geetanjali University", domain: "geetanjaliuniversity.com", isVerified: true },
    { name: "Karnataka Samskrit University", domain: null, isVerified: false },
    { name: "Maharishi Mahesh Yogi Vedic Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Palamuru University", domain: null, isVerified: false },
    { name: "Rajiv Gandhi National Aviation University", domain: "rgnau.ac.in", isVerified: true },
    { name: "University of Agricultural and Horticultural Sciences, Shivamogga", domain: null, isVerified: false },
    { name: "Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry", domain: null, isVerified: false },
    { name: "Nilamber‑Pitamber University", domain: null, isVerified: false },
    { name: "Jagadguru Ramanandacharya Rajasthan Sanskrit University", domain: null, isVerified: false },
    { name: "University of Patanjali", domain: null, isVerified: false },
    { name: "Kameshwar Singh Darbhanga Sanskrit University", domain: null, isVerified: false },
    { name: "Sardar Patel University of Police, Security and Criminal Justice", domain: null, isVerified: false },
    { name: "Sampurnanand Sanskrit Vishvavidyalaya", domain: null, isVerified: false },
    { name: "National Institute of Pharmaceutical Education and Research, Kolkata", domain: null, isVerified: false },
    { name: "Shridhar University", domain: null, isVerified: false },
    { name: "Rani Lakshmi Bai Central Agricultural University", domain: null, isVerified: false },
    { name: "Maharashtra National Law University, Aurangabad", domain: null, isVerified: false },
    { name: "Suamandeep Vidyapeeth", domain: null, isVerified: false },
    { name: "The Sanskrit College and University", domain: null, isVerified: false },
    { name: "Seacom Skills University", domain: "seacomskillsuniversity.ac.in", isVerified: true },
    { name: "Srinivas University", domain: "srinivasuniversity.edu.in", isVerified: true },
    { name: "Manipur Technical University", domain: "mtu.ac.in", isVerified: true },
    { name: "ICFAI University, Jaipur", domain: null, isVerified: false },
    { name: "Ayush and Health Sciences University of Chhattisgarh", domain: null, isVerified: false },
    { name: "Himgiri ZEE University", domain: null, isVerified: false },
    { name: "Nehru Gram Bharati Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Ponnaiyan Ramajayam Institute of Science and Technology", domain: null, isVerified: false },
    { name: "Tamil Nadu National Law University", domain: null, isVerified: false },
    { name: "Baddi University of Emerging Sciences and Technologies", domain: null, isVerified: false },
    { name: "Haridwar University", domain: null, isVerified: false },
    { name: "Sanchi University of Buddhist-Indic Studies", domain: null, isVerified: false },
    { name: "Indian Institute of Information Technology, Manipur", domain: null, isVerified: false },
    { name: "Baba Ghulam Shah Badhshah University", domain: null, isVerified: false },
    { name: "Sri Siddhartha Academy of Higher Education", domain: null, isVerified: false },
    { name: "Jai Prakash Vishwavidyalaya", domain: null, isVerified: false },
    { name: "University of Technology", domain: null, isVerified: false },
    { name: "St. Peter's Institute of Higher Education and Research", domain: null, isVerified: false },
    { name: "North East Frontier Technical University", domain: null, isVerified: false },
    { name: "Maulana Mazharul Haque Arabic and Persian University", domain: "mmhapu.ac.in", isVerified: true },
    { name: "Maharishi Markandeshwar University, Sadopur", domain: null, isVerified: false },
    { name: "Dakshina Bharat Hindi Prachar Sabha", domain: null, isVerified: false },
    { name: "Atal Bihari Vajpayee Hindi Vishwavidyalaya", domain: null, isVerified: false },
    { name: "SRM University, Sikkim", domain: null, isVerified: false },
    { name: "ICFAI University, Himachal Pradesh", domain: null, isVerified: false },
    { name: "ICFAI University, Jharkhand", domain: null, isVerified: false },
    { name: "Khwaja Moinuddin Chishti Language University", domain: null, isVerified: false },
    { name: "Dr. Shakuntala Misra National Rehabilitation University", domain: null, isVerified: false },
    { name: "OPJS University", domain: null, isVerified: false },
    { name: "Dr. Y.S.R. Horticultural University", domain: null, isVerified: false },
    { name: "Sarala Birla University", domain: null, isVerified: false },
    { name: "Uttarakhand Ayurved University", domain: null, isVerified: false },
    { name: "The Neotia University", domain: null, isVerified: false },
    { name: "Sankalchand Patel University", domain: null, isVerified: false },
    { name: "Bhatkhande Sanskriti Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Tantia University", domain: null, isVerified: false },
    { name: "Diamond Harbour Women’s University", domain: null, isVerified: false },
    { name: "Sri Sai University", domain: "srisaiuniversity.org", isVerified: true },
    { name: "PDM University", domain: "pdm.ac.in", isVerified: true },
    { name: "Shri Jagannath Sanskrit Vishvavidyalaya", domain: null, isVerified: false },
    { name: "Arni University", domain: null, isVerified: false },
    { name: "Sai Nath University", domain: null, isVerified: false },
    { name: "Madhyanchal Professional University", domain: null, isVerified: false },
    { name: "Dr. A.P.J Abdul Kalam University", domain: null, isVerified: false },
    { name: "ICFAI University, Sikkim", domain: null, isVerified: false },
    { name: "MVN University", domain: null, isVerified: false },
    { name: "National Institute of Pharmaceutical Education and Research, Hajipur", domain: null, isVerified: false },
    { name: "G.H. Raisoni University", domain: null, isVerified: false },
    { name: "University of Agricultural Sciences, Raichur", domain: null, isVerified: false },
    { name: "Eternal University", domain: null, isVerified: false },
    { name: "Mandsaur University", domain: null, isVerified: false },
    { name: "Shri Jagdishprasad Jhabrmal Tibrewala University", domain: null, isVerified: false },
    { name: "Maharaja Agrasen University", domain: null, isVerified: false },
    { name: "Uttarakhand Sanskrit University", domain: null, isVerified: false },
    { name: "Mahapurusha Srimanta Sankaradeva Viswavidyalaya", domain: null, isVerified: false },
    { name: "Apeejay Stya University", domain: null, isVerified: false },
    { name: "Pragyan International University", domain: "pragyaninternationaluniversity.ac.in", isVerified: true },
    { name: "Maharshi Panini Sanskrit Vishwavidyalaya", domain: "mpsvv.ac.in", isVerified: true },
    { name: "National Sports University", domain: "nsu.ac.in", isVerified: true },
    { name: "Maharishi Panini Sanskrit Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Manav Bharti University", domain: null, isVerified: false },
    { name: "National Sports University, Imphal", domain: null, isVerified: false },
    { name: "Maharishi Arvind University, Jaipur", domain: null, isVerified: false },
    { name: "Central University of Andhra Pradesh", domain: null, isVerified: false },
    { name: "BAHRA University", domain: null, isVerified: false },
    { name: "ICFAI University, Raipur", domain: null, isVerified: false },
    { name: "Abhilashi University", domain: null, isVerified: false },
    { name: "Bhupal Nobles University", domain: null, isVerified: false },
    { name: "Raffles University", domain: null, isVerified: false },
    { name: "Kamdhenu University", domain: null, isVerified: false },
    { name: "Bengaluru North University", domain: null, isVerified: false },
    { name: "Swarnim Startup and Innovation University", domain: null, isVerified: false },
    { name: "Spicer Adventist University", domain: null, isVerified: false },
    { name: "Jagan Nath University", domain: null, isVerified: false },
    { name: "Children's University", domain: null, isVerified: false },
    { name: "Raja Mansingh Tomar Music and Arts University", domain: null, isVerified: false },
    { name: "Dr. B.R. Ambedkar University of Social Sciences", domain: "brauss.in", isVerified: true },
    { name: "Apex University", domain: "apexuniversityjaipur.ac.in", isVerified: true },
    { name: "Akal University", domain: null, isVerified: false },
    { name: "Mohammad Ali Jauhar University", domain: "jauharuniversity.edu.in", isVerified: true },
    { name: "Sant Baba Bhag Singh University", domain: null, isVerified: false },
    { name: "Sanjay Ghodawat University", domain: null, isVerified: false },
    { name: "Sri Konda Laxman Telangana State Horticultural University", domain: null, isVerified: false },
    { name: "Apex Professional University", domain: null, isVerified: false },
    { name: "Baba Mastnath University", domain: null, isVerified: false },
    { name: "Manipur University of Culture", domain: null, isVerified: false },
    { name: "NIILM University", domain: null, isVerified: false },
    { name: "Maharishi University of Management and Technology", domain: null, isVerified: false },
    { name: "Bhartiya Skill Development University", domain: null, isVerified: false },
    { name: "Jagadguru Rambhadracharya Handicapped University", domain: null, isVerified: false },
    { name: "P.K. University", domain: null, isVerified: false },
    { name: "Kushabhau Thakre Patrakarita Avam Jansanchar University", domain: null, isVerified: false },
    { name: "Indrashil University", domain: null, isVerified: false },
    { name: "Pratap University", domain: null, isVerified: false },
    { name: "William Carey University, Shillong", domain: null, isVerified: false },
    { name: "Bareilly International University", domain: "biu.edu.in", isVerified: true },
    { name: "Institute of Advanced Research", domain: "iar.ac.in", isVerified: true },
    { name: "Sri Venkateswara Vedic University", domain: null, isVerified: false },
    { name: "Karnataka State Rural Development and Panchayat Raj University", domain: null, isVerified: false },
    { name: "YBN University", domain: null, isVerified: false },
    { name: "Gujarat University of Transplantation Sciences", domain: null, isVerified: false },
    { name: "Starex University", domain: null, isVerified: false },
    { name: "K.K. University", domain: null, isVerified: false },
    { name: "Dr. Sarvepalli Radhakrishnan Rajasthan Ayurved University", domain: null, isVerified: false },
    { name: "ICFAI University, Meghalaya", domain: null, isVerified: false },
    { name: "Rai Technology University", domain: null, isVerified: false },
    { name: "Jaypee University Anoopshahr", domain: null, isVerified: false },
    { name: "Indus International University", domain: null, isVerified: false },
    { name: "Sangai International University", domain: null, isVerified: false },
    { name: "Sri Devaraj Urs Academy of Higher Education and Research", domain: null, isVerified: false },
    { name: "Plastindia International University", domain: null, isVerified: false },
    { name: "Swarnim Gujarat Sports University", domain: "sgsu.gujarat.gov.in", isVerified: true },
    { name: "CMJ University", domain: null, isVerified: false },
    { name: "Sharnbasva University", domain: null, isVerified: false },
    { name: "TeamLease Skills University", domain: "teamleaseuniversity.ac.in", isVerified: true },
    { name: "KSGH Music and Performing Arts University", domain: null, isVerified: false },
    { name: "Lakulish Yoga University", domain: null, isVerified: false },
    { name: "Manipur International University", domain: null, isVerified: false },
    { name: "Arunodaya University", domain: null, isVerified: false },
    { name: "Maharaja Bir Bikram University", domain: "mbbuni.ac.in", isVerified: true },
    { name: "Haridev Joshi University of Journalism and Mass Communication", domain: null, isVerified: false },
    { name: "Jharkhand Raksha Shakti University", domain: null, isVerified: false },
    { name: "Kumar Bhaskar Varma Sanskrit and Ancient Studies University", domain: null, isVerified: false },
    { name: "Karnataka Janapada Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Dada Lakhmi Chand State University of Performing and Visual Arts", domain: null, isVerified: false },
    { name: "C.U. Shah University", domain: "cushahuniversity.org", isVerified: true },
    { name: "Assam Rajiv Gandhi University of Cooperative Management", domain: null, isVerified: false },
    { name: "St. Joseph University", domain: "stjosephuniv.edu.in", isVerified: true },
    { name: "Vinayaka Missions Sikkim University", domain: "vmsuniversity.in", isVerified: true },
    { name: "Rama Devi Women's University", domain: "rdwu.ac.in", isVerified: true },
    { name: "Bhabha University", domain: "bhabhauniversity.edu.in", isVerified: true },
    { name: "ICFAI University, Nagaland", domain: "iunagaland.edu.in", isVerified: true },
    { name: "Sai Tirupati University", domain: null, isVerified: false },
    { name: "Indira Gandhi Technological and Medical Sciences University", domain: null, isVerified: false },
    { name: "SKIPS University", domain: null, isVerified: false },
    { name: "Maulana Azad University, Jodhpur", domain: null, isVerified: false },
    { name: "ICFAI University, Mizoram", domain: "iumizoram.edu.in", isVerified: true },
    { name: "Ras Bihari Bose Subharti University", domain: null, isVerified: false },
    { name: "Dr YSR Architecture and Fine Arts University", domain: null, isVerified: false },
    { name: "Tamil Nadu Dr.J Jayalalithaa Music and Fine Arts University", domain: null, isVerified: false },
    { name: "Pacific Medical University", domain: null, isVerified: false },
    { name: "Lokbharati University for Rural Innovation", domain: null, isVerified: false },
    { name: "Sandip University, Sijoul", domain: null, isVerified: false },
    { name: "Babu Dinesh Singh University", domain: null, isVerified: false },
    { name: "Uttarakhand Aawasiya Vishwavidyalaya, Almora", domain: null, isVerified: false },
    { name: "Chhattisgarh Kamdhenu Vishwavidyalaya", domain: null, isVerified: false },
    { name: "Manav Rachna International Institute of Research and Studies", domain: null, isVerified: false },

]