import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Indonesia_universities = [

    // Indonesia

    { name: "Universitas Indonesia", domain: "ui.ac.id", isVerified: true },
    { name: "Universitas Gadjah Mada", domain: "ugm.ac.id", isVerified: true },
    { name: "Universitas Telkom", domain: "telkomuniversity.ac.id", isVerified: true },
    { name: "Institut Teknologi Bandung", domain: "itb.ac.id", isVerified: true },
    { name: "Universitas Airlangga", domain: "unair.ac.id", isVerified: true },
    { name: "Universitas Bina Nusantara", domain: "binus.ac.id", isVerified: true },
    { name: "Universitas Brawijaya", domain: "ub.ac.id", isVerified: true },
    { name: "Universitas Diponegoro", domain: "undip.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Sumatera Utara", domain: "umsu.ac.id", isVerified: true },
    { name: "Universitas Sebelas Maret", domain: "uns.ac.id", isVerified: true },
    { name: "Universitas Lampung", domain: "unila.ac.id", isVerified: true },
    { name: "Institut Pertanian Bogor", domain: "ipb.ac.id", isVerified: true },
    { name: "Universitas Teknokrat Indonesia", domain: "teknokrat.ac.id", isVerified: true },
    { name: "Institut Teknologi Sepuluh Nopember", domain: "its.ac.id", isVerified: true },
    { name: "Universitas Padjadjaran", domain: "unpad.ac.id", isVerified: true },
    { name: "Universitas Gunadarma", domain: "gunadarma.ac.id", isVerified: true },
    { name: "Universitas Medan Area", domain: "uma.ac.id", isVerified: true },
    { name: "Universitas Syiah Kuala", domain: "unsyiah.ac.id", isVerified: true },
    { name: "Universitas Pendidikan Indonesia", domain: "upi.edu", isVerified: true },
    { name: "Universitas Budi Luhur", domain: "budiluhur.ac.id", isVerified: true },
    { name: "Universitas Negeri Malang", domain: "um.ac.id", isVerified: true },
    { name: "Universitas Andalas", domain: "unand.ac.id", isVerified: true },
    { name: "Universitas Islam Indonesia", domain: "uii.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sunan Ampel Surabaya", domain: "uinsby.ac.id", isVerified: true },
    { name: "Universitas Hasanuddin", domain: "unhas.ac.id", isVerified: true },
    { name: "Universitas Sains dan Teknologi Komputer", domain: "stekom.ac.id", isVerified: true },
    { name: "Universitas Negeri Semarang", domain: "unnes.ac.id", isVerified: true },
    { name: "Universitas Sumatera Utara", domain: "usu.ac.id", isVerified: true },
    { name: "Universitas Negeri Yogyakarta", domain: "uny.ac.id", isVerified: true },
    { name: "Universitas Jenderal Soedirman", domain: "unsoed.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Jakarta", domain: "umj.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Maulana Malik Ibrahim Malang", domain: "uin-malang.ac.id", isVerified: true },
    { name: "Universitas Jember", domain: "unej.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Yogyakarta", domain: "umy.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Malang", domain: "umm.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Surakarta", domain: "ums.ac.id", isVerified: true },
    { name: "Universitas Riau", domain: "unri.ac.id", isVerified: true },
    { name: "Universitas Udayana", domain: "unud.ac.id", isVerified: true },
    { name: "Universitas Negeri Padang", domain: "unp.ac.id", isVerified: true },
    { name: "Universitas Negeri Surabaya", domain: "unesa.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sunan Kalijaga Yogyakarta", domain: "uin-suka.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sunan Gunung Djati", domain: "uinsgd.ac.id", isVerified: true },
    { name: "Universitas Lambung Mangkurat", domain: "ulm.ac.id", isVerified: true },
    { name: "Universitas Sriwijaya", domain: "unsri.ac.id", isVerified: true },
    { name: "Universitas Kristen Petra", domain: "petra.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Syarif Hidayatullah Jakarta", domain: "uinjkt.ac.id", isVerified: true },
    { name: "Universitas Esa Unggul", domain: "esaunggul.ac.id", isVerified: true },
    { name: "Universitas Ahmad Dahlan", domain: "uad.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Prof. Dr. Hamka", domain: "uhamka.ac.id", isVerified: true },
    { name: "Universitas Pelita Harapan", domain: "uph.edu", isVerified: true },
    { name: "Universitas Mataram", domain: "unram.ac.id", isVerified: true },
    { name: "Universitas Mercu Buana", domain: "mercubuana.ac.id", isVerified: true },
    { name: "Universitas Sultan Ageng Tirtayasa", domain: "untirta.ac.id", isVerified: true },
    { name: "Universitas Halu Oleo", domain: "uho.ac.id", isVerified: true },
    { name: "Universitas Negeri Jakarta", domain: "unj.ac.id", isVerified: true },
    { name: "Universitas Pembangunan Nasional Veteran Jakarta", domain: "upnvj.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Raden Intan Lampung", domain: "radenintan.ac.id", isVerified: true },
    { name: "Universitas Tadulako", domain: "untad.ac.id", isVerified: true },
    { name: "Universitas Mulawarman", domain: "unmul.ac.id", isVerified: true },
    { name: "Universitas Bengkulu", domain: "unib.ac.id", isVerified: true },   
    { name: "Universitas Dian Nuswantoro", domain: "dinus.ac.id", isVerified: true },
    { name: "Universitas Tanjungpura", domain: "untan.ac.id", isVerified: true },
    { name: "Universitas Atma Jaya Yogyakarta", domain: "uajy.ac.id", isVerified: true },
    { name: "Universitas Negeri Makassar", domain: "unm.ac.id", isVerified: true },
    { name: "Universitas Jambi", domain: "unja.ac.id", isVerified: true },
    { name: "Universitas Sam Ratulangi", domain: "unsrat.ac.id", isVerified: true },
    { name: "Universitas Islam Sultan Agung", domain: "unisulla.ac.id", isVerified: true },
    { name: "Universitas Multimedia Nusantara", domain: "umn.ac.id", isVerified: true },
    { name: "Universitas Palangka Raya", domain: "upr.ac.id", isVerified: true },
    { name: "Universitas Islam Bandung", domain: "unisba.ac.id", isVerified: true },
    { name: "Universitas Tarumanagara", domain: "untar.ac.id", isVerified: true },
    { name: "Universitas Pamulang", domain: "unpam.ac.id", isVerified: true },
    { name: "Universitas Pembangunan Nasional Veteran Yogyakarta", domain: "upnyk.ac.id", isVerified: true },
    { name: "Universitas Kristen Satya Wacana", domain: "uksw.edu", isVerified: true },
    { name: "Universitas Muhammadiyah Surabaya", domain: "um-surabaya.ac.id", isVerified: true },
    { name: "Universitas Bakrie", domain: "bakrie.ac.id", isVerified: true },
    { name: "Universitas Katolik Soegijapranata", domain: "unikas.ac.id", isVerified: true },
    { name: "Universitas Negeri Medan", domain: "unimed.ac.id", isVerified: true },
    { name: "Universitas Pendidikan Ganesha", domain: "undiksha.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sultan Syarif Kasim Riau", domain: "uin-suska.ac.id", isVerified: true },
    { name: "Universitas Pasundan", domain: "unpas.ac.id", isVerified: true },
    { name: "Universitas Katolik Parahyangan", domain: "unpar.ac.id", isVerified: true },
    { name: "Universitas Islam Malang", domain: "unisma.ac.id", isVerified: true },
    { name: "Universitas Pertamina", domain: "universitaspertamina.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Kendari", domain: "umkendari.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Ar-Raniry", domain: "ar-raniry.ac.id", isVerified: true },
    { name: "Universitas Bina Sarana Informatika", domain: "bsi.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Purworejo", domain: "umpwr.ac.id", isVerified: true },
    { name: "Universitas Sanata Dharma", domain: "usd.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Alauddin Makassar", domain: "uin-alauddin.ac.id", isVerified: true },
    { name: "Universitas Surabaya", domain: "ubaya.ac.id", isVerified: true },
    { name: "Universitas Trisakti", domain: "trisakti.ac.id", isVerified: true },
    { name: "Universitas Jenderal Achmad Yani", domain: "unjani.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Walisongo", domain: "walisongo.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sulthan Thaha Saifuddin Jambi", domain: "uinjambi.ac.id", isVerified: true },
    { name: "Universitas Alma Ata", domain: "almaata.ac.id", isVerified: true },
    { name: "Universitas Pembangunan Nasional Veteran Jawa Timur", domain: "upnjatim.ac.id", isVerified: true },
    { name: "Universitas Ibn Khaldun", domain: "uika-bogor.ac.id", isVerified: true },
    { name: "Universitas Katolik Indonesia Atma Jaya", domain: "atmajaya.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Ponorogo", domain: "umpo.ac.id", isVerified: true }, 
    { name: "Universitas Muhammadiyah Semarang", domain: "unimus.ac.id", isVerified: true },
    { name: "Universitas Komputer Indonesia", domain: "unikom.ac.id", isVerified: true },
    { name: "Universitas Mercu Buana Yogyakarta", domain: "mercubuana-yogya.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Makassar", domain: "unismuh.ac.id", isVerified: true },
    { name: "Universitas Pakuan", domain: "unpak.ac.id", isVerified: true },
    { name: "Universitas Kristen Duta Wacana", domain: "ukdw.ac.id", isVerified: true },
    { name: "Universitas Negeri Gorontalo", domain: "ung.ac.id", isVerified: true },
    { name: "Universitas Tidar", domain: "untidar.ac.id", isVerified: true },
    { name: "Universitas Kristen Maranatha", domain: "maranatha.edu", isVerified: true },
    { name: "Universitas Muhammadiyah Sidoarjo", domain: "umsida.ac.id", isVerified: true },
    { name: "Institut Teknologi Nasional", domain: "itenas.ac.id", isVerified: true },
    { name: "Universitas Pattimura", domain: "unpatti.ac.id", isVerified: true },
    { name: "Universitas Katolik Widya Mandala Surabaya", domain: "ukwms.ac.id", isVerified: true },
    { name: "Universitas Trunojoyo Madura", domain: "trunojoyo.ac.id", isVerified: true },
    { name: "Universitas Kristen Indonesia", domain: "uki.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Purwokerto", domain: "ump.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Raden Fatah", domain: "radenfatah.ac.id", isVerified: true },
    { name: "Institut Seni Indonesia Surakarta", domain: "isi-ska.ac.id", isVerified: true },
    { name: "Universitas Islam Sumatera Utara", domain: "uinsu.ac.id", isVerified: true },
    { name: "Universitas Khairun", domain: "unkhair.ac.id", isVerified: true },
    { name: "Universitas Sarjanawiyata Tamansiswa", domain: "ustjogja.ac.id", isVerified: true },
    { name: "Universitas Presiden", domain: "president.ac.id", isVerified: true },
    { name: "Universitas Muria Kudus", domain: "umk.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sumatera Utara", domain: "uinsu.ac.id", isVerified: true },
    { name: "Universitas Islam Riau", domain: "uir.ac.id", isVerified: true },
    { name: "Universitas Ciputra", domain: "ciputra.ac.id", isVerified: true },
    { name: "Universitas Pancasila", domain: "unpancasila.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Surabaya", domain: "unusa.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Jember", domain: "unmuhjember.ac.id", isVerified: true },
    { name: "Universitas Semarang", domain: "usm.ac.id", isVerified: true },
    { name: "Universitas Muslim Indonesia", domain: "umi.ac.id", isVerified: true },
    { name: "Universitas Malikussaleh", domain: "unimal.ac.id", isVerified: true },
    { name: "Universitas Garut", domain: "uniga.ac.id", isVerified: true },
    { name: "Universitas Widyatama", domain: "widyatama.ac.id", isVerified: true },
    { name: "Institut Seni Indonesia Yogyakarta", domain: "isi.ac.id", isVerified: true },
    { name: "Universitas Prasetiya Mulya", domain: "prasetiyamulya.ac.id", isVerified: true },
    { name: "Universitas Merdeka Malang", domain: "unmer.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Mataram", domain: "uinmataram.ac.id", isVerified: true },
    { name: "Universitas 17 Agustus 1945 Surabaya", domain: "untag-sby.ac.id", isVerified: true },
    { name: "Universitas Narotama", domain: "narotama.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Mataram", domain: "ummat.ac.id", isVerified: true },
    { name: "Universitas PGRI Madiun", domain: "unipma.ac.id", isVerified: true },
    { name: "Universitas Dr. Soetomo", domain: "unitomo.ac.id", isVerified: true },
    { name: "Universitas Islam Darul Ulum Lamongan", domain: "unisdal.ac.id", isVerified: true },
    { name: "Universitas Nusa Cendana", domain: "undana.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sultan Maulana Hasanuddin Banten", domain: "uinsmhb.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Magelang", domain: "ummgl.ac.id", isVerified: true },
    { name: "Universitas PGRI Semarang", domain: "upgris.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Riau", domain: "umri.ac.id", isVerified: true },
    { name: "Universitas AMIKOM Yogyakarta", domain: "amikom.ac.id", isVerified: true },
    { name: "Universitas Advent Indonesia", domain: "unai.edu", isVerified: true },
    { name: "Universitas Nasional", domain: "unas.ac.id", isVerified: true },
    { name: "Universitas Bina Darma", domain: "binadarma.ac.id", isVerified: true },
    { name: "Universitas Cenderawasih", domain: "uncen.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Sayyid Ali Rahmatullah Tulungagung", domain: "uinsatu.ac.id", isVerified: true },
    { name: "Universitas Pancasakti", domain: "upstegal.ac.id", isVerified: true },
    { name: "Universitas Islam Kalimantan Muhammad Arsyad Al Banjari", domain: "uniska-bjm.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Tasikmalaya", domain: "umtas.ac.id", isVerified: true },
    { name: "Universitas Siliwangi", domain: "unsil.ac.id", isVerified: true },
    { name: "Universitas Sangga Buana", domain: "usbypkp.ac.id", isVerified: true },
    { name: "Universitas Wijaya Kusuma Surabaya", domain: "uwks.ac.id", isVerified: true },
    { name: "Universitas Negeri Manado", domain: "unima.ac.id", isVerified: true },
    { name: "Universitas 17 Agustus 1945 Semarang", domain: "untagsmg.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Antasari Banjarmasin", domain: "uin-antasari.ac.id", isVerified: true },
    { name: "Universitas Labuhanbatu", domain: "ulb.ac.id", isVerified: true },
    { name: "Universitas Pasir Pengaraian", domain: "upp.ac.id", isVerified: true },
    { name: "Universitas HKBP Nommensen", domain: "uhn.ac.id", isVerified: true },
    { name: "Universitas Sulawesi Barat", domain: "unsulbar.ac.id", isVerified: true },
    { name: "Universitas YARSI", domain: "yarsi.ac.id", isVerified: true },
    { name: "Universitas Hamzanwadi", domain: "hamzanwadi.ac.id", isVerified: true },
    { name: "Universitas Indraprasta PGRI", domain: "unindra.ac.id", isVerified: true },
    { name: "Universitas Singaperbangsa Karawang", domain: "unsika.ac.id", isVerified: true },
    { name: "Universitas Al Azhar Indonesia", domain: "uai.ac.id", isVerified: true },
    { name: "Institut Teknologi Nasional Malang", domain: "itn.ac.id", isVerified: true },
    { name: "Universitas Lancang Kuning", domain: "unilak.ac.id", isVerified: true },
    { name: "Universitas 17 Agustus 1945 Samarinda", domain: "untag-smd.ac.id", isVerified: true },
    { name: "Universitas Malahayati", domain: "malahayati.ac.id", isVerified: true },
    { name: "Universitas Islam Nusantara", domain: "uninus.ac.id", isVerified: true },
    { name: "Universitas Maritim Raja Ali Haji", domain: "umrah.ac.id", isVerified: true },
    { name: "Institut Seni Indonesia Denpasar", domain: "isi-dps.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Metro", domain: "ummetro.ac.id", isVerified: true },
    { name: "Universitas Siber Asia", domain: "unsia.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Raden Mas Said Surakarta", domain: "uinsaid.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Tangerang", domain: "umt.ac.id", isVerified: true },
    { name: "Universitas Nusa Putra", domain: "nusaputra.ac.id", isVerified: true },
    { name: "Universitas Potensi Utama", domain: "potensi-utama.ac.id", isVerified: true },
    { name: "Universitas Bung Hatta", domain: "bunghatta.ac.id", isVerified: true },
    { name: "Universitas Nusantara PGRI Kediri", domain: "unpkediri.ac.id", isVerified: true },
    { name: "Universitas Paramadina", domain: "paramadina.ac.id", isVerified: true },
    { name: "Universitas Djuanda", domain: "unida.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Lampung", domain: "unula.ac.id", isVerified: true },
    { name: "Universitas Pahlawan Tuanku Tambusai", domain: "universitaspahlawan.ac.id", isVerified: true },
    { name: "Universitas Majalengka", domain: "unma.ac.id", isVerified: true },
    { name: "Universitas PGRI Palembang", domain: "univpgri-palembang.ac.id", isVerified: true },
    { name: "Universitas Islam Lamongan", domain: "unisla.ac.id", isVerified: true },
    { name: "Universitas Wahid Hasyim", domain: "wahidhasyim.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Imam Bonjol", domain: "uinib.ac.id", isVerified: true },
    { name: "Universitas Sampoerna", domain: "sampoernauniversity.ac.id", isVerified: true },
    { name: "Universitas Stikubank", domain: "unstik.ac.id", isVerified: true },
    { name: "Universitas Kuningan", domain: "uniku.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Palangkaraya", domain: "ump.ac.id", isVerified: true },
    { name: "Universitas Swadaya Gunung Jati", domain: "ugj.ac.id", isVerified: true },
    { name: "Universitas Aisyiyah Yogyakarta", domain: "unisayogya.ac.id", isVerified: true },
    { name: "Universitas Dinamika", domain: "dinamika.ac.id", isVerified: true },
    { name: "Universitas Bunda Mulia", domain: "bundamulia.ac.id", isVerified: true },
    { name: "Universitas Bangka Belitung", domain: "ubb.ac.id", isVerified: true },
    { name: "Universitas PGRI Yogyakarta", domain: "upy.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Kalimantan Timur", domain: "umkt.ac.id", isVerified: true },
    { name: "Universitas Serambi Mekkah", domain: "serambimekkah.ac.id", isVerified: true },
    { name: "Universitas Buana Perjuangan Karawang", domain: "ubpkarawang.ac.id", isVerified: true },
    { name: "Universitas Internasional Batam", domain: "uib.ac.id", isVerified: true },
    { name: "Universitas Teuku Umar", domain: "utu.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Palembang", domain: "umpalembang.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Gresik", domain: "umg.ac.id", isVerified: true },
    { name: "Universitas Islam Nahdlatul Ulama", domain: "uninajepara.ac.id", isVerified: true },
    { name: "Universitas Dian Nusantara", domain: "undira.ac.id", isVerified: true },
    { name: "Universitas Pembangunan Jaya", domain: "upj.ac.id", isVerified: true },
    { name: "Universitas Pesantren Tinggi Darul 'Ulum", domain: "unipdu.ac.id", isVerified: true },
    { name: "Universitas PGRI Adi Buana", domain: "unipasby.ac.id", isVerified: true },
    { name: "Universitas Bandar Lampung", domain: "ubl.ac.id", isVerified: true },
    { name: "Universitas Bhayangkara Surabaya", domain: "ubhara.ac.id", isVerified: true },
    { name: "Universitas Mahasaraswati Denpasar", domain: "unmas.ac.id", isVerified: true },
    { name: "Universitas Tribhuwana Tungga Dewi", domain: "unitri.ac.id", isVerified: true },
    { name: "Universitas Nusa Mandiri", domain: "nusamandiri.ac.id", isVerified: true },
    { name: "Universitas Al Muslim", domain: "umuslim.ac.id", isVerified: true },
    { name: "Universitas Kanjuruhan Malang", domain: "unikama.ac.id", isVerified: true },
    { name: "Universitas Warmadewa", domain: "warmadewa.ac.id", isVerified: true },
    { name: "Universitas Kristen Krida Wacana", domain: "ukrida.ac.id", isVerified: true },
    { name: "Universitas Hang Tuah", domain: "hangtuah.ac.id", isVerified: true },
    { name: "Universitas Darma Persada", domain: "unsada.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Sumatera Barat", domain: "umsb.ac.id", isVerified: true },
    { name: "Universitas Teknologi Yogyakarta", domain: "uty.ac.id", isVerified: true },
    { name: "Universitas Abdurrab", domain: "univrab.ac.id", isVerified: true },
    { name: "Universitas Tomakaka", domain: "untika.ac.id", isVerified: true },
    { name: "Universitas Balikpapan", domain: "uniba-bpn.ac.id", isVerified: true },
    { name: "Universitas Borneo Tarakan", domain: "ubt.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Aceh", domain: "unmuha.ac.id", isVerified: true },
    { name: "Universitas Bhayangkara Jakarta Raya", domain: "ubharajaya.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Bengkulu", domain: "umb.ac.id", isVerified: true },
    { name: "Universitas Kristen Indonesia Toraja", domain: "ukitoraja.ac.id", isVerified: true },
    { name: "Universitas Kadiri", domain: "unik-kediri.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Cirebon", domain: "umc.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Palu", domain: "unismuhpalu.ac.id", isVerified: true },
    { name: "Universitas Prima Indonesia", domain: "unprimdn.ac.id", isVerified: true },
    { name: "Universitas Wiralodra", domain: "unwir.ac.id", isVerified: true },
    { name: "Universitas Teknologi Sumbawa", domain: "uts.ac.id", isVerified: true },
    { name: "Universitas 17 Agustus 1945", domain: "uta45jakarta.ac.id", isVerified: true },
    { name: "Universitas Samudra Langsa", domain: "unsam.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Lamongan", domain: "uml.ac.id", isVerified: true },
    { name: "Universitas Pendidikan Nasional", domain: "undiknas.ac.id", isVerified: true },
    { name: "Universitas Islam Kadiri", domain: "uniska-kediri.ac.id", isVerified: true },
    { name: "Universitas Jayabaya", domain: "jayabaya.ac.id", isVerified: true },
    { name: "Universitas Putera Batam", domain: "puterabatam.ac.id", isVerified: true },
    { name: "Universitas Maarif Hasyim Latif", domain: "umaha.ac.id", isVerified: true },
    { name: "Universitas Putra Indonesia YPTK Padang", domain: "upi-yptk.ac.id", isVerified: true },
    { name: "Universitas Pembangunan Panca Budi", domain: "dosen.pancabudi.ac.id", isVerified: true },
    { name: "Universitas Swiss German", domain: "sgu.ac.id", isVerified: true },
    { name: "Universitas Trilogi", domain: "trilogi.ac.id", isVerified: true },
    { name: "Universitas Palembang", domain: "unpal.ac.id", isVerified: true },
    { name: "Universitas Prof. Dr. Moestopo", domain: "moestopo.ac.id", isVerified: true },
    { name: "Universitas Multi Data Palembang", domain: "mdp.ac.id", isVerified: true },
    { name: "Universitas Darunnajah", domain: "darunnajah.ac.id", isVerified: true },
    { name: "Universitas Papua", domain: "unipa.ac.id", isVerified: true },
    { name: "Universitas Pekalongan", domain: "unikal.ac.id", isVerified: true },
    { name: "Universitas Dehasen Bengkulu", domain: "unived.ac.id", isVerified: true },
    { name: "Universitas Galuh Ciamis", domain: "unigal.ac.id", isVerified: true },
    { name: "Universitas Slamet Riyadi", domain: "unisri.ac.id", isVerified: true },
    { name: "Universitas Sains Al-Qur'an", domain: "unsiq.ac.id", isVerified: true },
    { name: "Universitas 'Aisyiyah Surakarta", domain: "aisyiyah.ac.id", isVerified: true },
    { name: "Universitas Setia Budi Surakarta", domain: "setiabudi.ac.id", isVerified: true },
    { name: "Universitas Merdeka Pasuruan", domain: "unmerpas.ac.id", isVerified: true },
    { name: "Universitas Persada Indonesia YAI", domain: "yai.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Sidoarjo", domain: "unusida.ac.id", isVerified: true },
    { name: "Universitas Janabadra", domain: "janabadra.ac.id", isVerified: true },
    { name: "Universitas Musamus", domain: "unmus.ac.id", isVerified: true },
    { name: "Universitas Graha Nusantara Padangsidimpuan", domain: "ugn.ac.id", isVerified: true },
    { name: "Universitas Batanghari", domain: "unbari.ac.id", isVerified: true },
    { name: "Universitas Islam Raden Rahmat", domain: "unira.ac.id", isVerified: true },
    { name: "Universitas Katolik Santo Thomas", domain: "ust.ac.id", isVerified: true },
    { name: "Universitas Wisnuwardhana", domain: "uws.ac.id", isVerified: true },
    { name: "Universitas PGRI Sumatera Barat", domain: "upgrisba.ac.id", isVerified: true },
    { name: "Universitas Duta Bangsa Surakarta", domain: "udb.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Al Ghazali", domain: "unugha.ac.id", isVerified: true },
    { name: "Universitas Krisnadwipayana", domain: "unkris.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Kudus", domain: "umkudus.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Sunan Giri", domain: "unsuri.ac.id", isVerified: true },
    { name: "Universitas AKI", domain: "unaki.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Sukabumi", domain: "ummi.ac.id", isVerified: true },
    { name: "Universitas Islam Madura Pamekasan", domain: "uim.ac.id", isVerified: true },
    { name: "Universitas Bina Bangsa Getsempena", domain: "ubbg.ac.id", isVerified: true },
    { name: "Universitas Sari Mutiara Indonesia", domain: "usm.ac.id", isVerified: true },
    { name: "Universitas Indo Global Mandiri", domain: "uigm.ac.id", isVerified: true },
    { name: "Universitas Respati Yogyakarta", domain: "respati.ac.id", isVerified: true },
    { name: "Universitas Islam As-Syafiiyah", domain: "uias.ac.id", isVerified: true },
    { name: "Universitas Darussalam Gontor", domain: "unida.gontor.ac.id", isVerified: true },
    { name: "Universitas Adhirajasa Reswara Sanjaya", domain: "unars.ac.id", isVerified: true },
    { name: "Universitas Veteran Bangun Nusantara", domain: "uvbn.ac.id", isVerified: true },
    { name: "Universitas Abdurachman Saleh", domain: "unars.ac.id", isVerified: true },
    { name: "Universitas Ngudi Waluyo", domain: "unw.ac.id", isVerified: true },
    { name: "Universitas Yudharta Pasuruan", domain: "yudharta.ac.id", isVerified: true },
    { name: "Universitas Ma Chung", domain: "machung.ac.id", isVerified: true },
    { name: "Universitas Bung Karno", domain: "ubk.ac.id", isVerified: true },
    { name: "Universitas Islam Internasional Indonesia", domain: "uiii.ac.id", isVerified: true },
    { name: "Universitas Peradaban Bumiayu", domain: "peradaban.ac.id", isVerified: true },
    { name: "Universitas Islam 45 Bekasi", domain: "unisma.ac.id", isVerified: true },
    { name: "Universitas Islam Majapahit", domain: "unisla.ac.id", isVerified: true },
    { name: "Universitas Muhadi Setiabudi", domain: "umus.ac.id", isVerified: true },
    { name: "Universitas Mohammad Husni Thamrin", domain: "thamrin.ac.id", isVerified: true },
    { name: "Universitas Hindu Indonesia", domain: "uhi.ac.id", isVerified: true },
    { name: "Universitas Islam Syekh-Yusuf", domain: "unis.ac.id", isVerified: true },
    { name: "Universitas Islam Negeri Datokarama Palu", domain: "uin-dk.ac.id", isVerified: true },
    { name: "Universitas Nurul Jadid", domain: "unuja.ac.id", isVerified: true },
    { name: "Universitas Katolik Widya Mandira", domain: "unwira.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Kupang", domain: "umk.ac.id", isVerified: true },
    { name: "Universitas Katolik Musi Charitas", domain: "ukmc.ac.id", isVerified: true },
    { name: "Universitas Klabat", domain: "unklab.ac.id", isVerified: true },
    { name: "Universitas Sembilanbelas November Kolaka", domain: "usnkolaka.ac.id", isVerified: true },
    { name: "Universitas Dharma Andalas", domain: "unidha.ac.id", isVerified: true },
    { name: "Universitas Indonesia Timur", domain: "uit.ac.id", isVerified: true },
    { name: "Universitas Pandanaran", domain: "unpand.ac.id", isVerified: true },
    { name: "Universitas Katolik Widya Mandala Madiun", domain: "wmm.ac.id", isVerified: true },
    { name: "Universitas Fajar", domain: "unifa.ac.id", isVerified: true },
    { name: "Universitas Islam Al-azhar Mataram", domain: "uia.ac.id", isVerified: true },
    { name: "Universitas Indonesia Membangun", domain: "uinm.ac.id", isVerified: true },
    { name: "Universitas Tanri Abeng", domain: "tau.ac.id", isVerified: true },
    { name: "Universitas KH. A. Wahab Hasbullah", domain: "unwaha.ac.id", isVerified: true },
    { name: "Universitas Harapan Bangsa", domain: "uhb.ac.id", isVerified: true },
    { name: "Universitas Tunas Pembangunan", domain: "utp.ac.id", isVerified: true },
    { name: "Universitas Tulang Bawang", domain: "utb.ac.id", isVerified: true },
    { name: "Universitas Buddhi Dharma", domain: "ubd.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Sorong", domain: "um-sorong.ac.id", isVerified: true },
    { name: "Universitas Langlangbuana", domain: "unla.ac.id", isVerified: true },
    { name: "Universitas Borobudur", domain: "borobudur.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Pontianak", domain: "ump.ac.id", isVerified: true },
    { name: "Universitas Islam Kuantan Singingi", domain: "uniks.ac.id", isVerified: true },
    { name: "Universitas Dinamika Bangsa", domain: "genesis.ac.id", isVerified: true },
    { name: "Universitas Cokroaminoto Palopo", domain: "uncp.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Palopo", domain: "umpalopo.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Buton", domain: "umbuton.ac.id", isVerified: true },
    { name: "Universitas Sahid", domain: "usahid.ac.id", isVerified: true },
    { name: "Universitas Andi Djemma", domain: "unanda.ac.id", isVerified: true },
    { name: "Universitas Teknologi Digital Indonesia", domain: "utdi.ac.id", isVerified: true },
    { name: "Universitas Abulyatama", domain: "abulyatama.ac.id", isVerified: true },
    { name: "Universitas Darussalam Ambon", domain: "unidar.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Tapanuli Selatan", domain: "umts.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Blitar", domain: "unublitar.ac.id", isVerified: true },
    { name: "Universitas Bosowa", domain: "unibos.ac.id", isVerified: true },
    { name: "Universitas Kristen Wira Wacana Sumba", domain: "ukwms.ac.id", isVerified: true },
    { name: "Universitas Islam Jember", domain: "uihj.ac.id", isVerified: true },
    { name: "Universitas Gresik", domain: "unigres.ac.id", isVerified: true },
    { name: "Universitas Kutai Kartanegara", domain: "unkarta.ac.id", isVerified: true },
    { name: "Universitas Cokroaminoto Yogyakarta", domain: "ucy.ac.id", isVerified: true },
    { name: "Universitas Riau Kepulauan", domain: "unrika.ac.id", isVerified: true },
    { name: "Universitas Subang", domain: "unsub.ac.id", isVerified: true },
    { name: "Universitas Respati Indonesia", domain: "urindo.ac.id", isVerified: true },
    { name: "Universitas Nurtanio", domain: "uninurtanio.ac.id", isVerified: true },
    { name: "Universitas Dirgantara Marsekal Suryadarma", domain: "unsurya.ac.id", isVerified: true },
    { name: "Universitas WR Supratman", domain: "uwrs.ac.id", isVerified: true },
    { name: "Universitas Internasional Semen Indonesia", domain: "uisi.ac.id", isVerified: true },
    { name: "Universitas Ubudiyah Indonesia", domain: "uui.ac.id", isVerified: true },
    { name: "Universitas Flores", domain: "uniflor.ac.id", isVerified: true },
    { name: "Universitas Matana", domain: "matana.ac.id", isVerified: true },
    { name: "Universitas Proklamasi 45", domain: "up45.ac.id", isVerified: true },
    { name: "Universitas PGRI Banyuwangi", domain: "unibabwi.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Banjarmasin", domain: "umbjm.ac.id", isVerified: true },
    { name: "Universitas Atma Jaya Makassar", domain: "uajm.ac.id", isVerified: true },
    { name: "Universitas Winaya Mukti", domain: "unwim.ac.id", isVerified: true },
    { name: "Universitas Muslim Nusantara Al-Washliyah", domain: "umnaw.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Bandung", domain: "umbandung.ac.id", isVerified: true },
    { name: "Universitas Ma'arif Nahdlatul Ulama", domain: "umma.ac.id", isVerified: true },
    { name: "Universitas Darul 'ulum", domain: "unud.ac.id", isVerified: true },
    { name: "Univesitas Islam Negeri Sjech M. Djamil Djambek Bukittinggi", domain: "uinbukittinggi.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Gorontalo", domain: "umgo.ac.id", isVerified: true },
    { name: "Universitas Kristen Immanuel", domain: "uki.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Luwuk Banggai", domain: "umlu.ac.id", isVerified: true },
    { name: "Universitas Bale Bandung", domain: "unibba.ac.id", isVerified: true },
    { name: "Universitas Widya Dharma", domain: "uwd.ac.id", isVerified: true },
    { name: "Universitas Dharmawangsa", domain: "dharmawangsa.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Purwokerto", domain: "unup.ac.id", isVerified: true },
    { name: "Institut Seni Indonesia Padang Panjang", domain: "isipadangpanjang.ac.id", isVerified: true },
    { name: "Universitas Widya Gama", domain: "widyagama.ac.id", isVerified: true },
    { name: "Universitas Ekasakti", domain: "ekasakti.ac.id", isVerified: true },
    { name: "Universitas Mikroskil", domain: "mikroskil.ac.id", isVerified: true },
    { name: "Universitas Kahuripan Kediri", domain: "kahuripan.ac.id", isVerified: true },
    { name: "Universitas Dhyana Pura", domain: "undhirabali.ac.id", isVerified: true },
    { name: "Universitas Suryakancana", domain: "unsur.ac.id", isVerified: true },
    { name: "Universitas Kebangsaan", domain: "uk.ac.id", isVerified: true },
    { name: "Universitas Wijaya Putra", domain: "uwp.ac.id", isVerified: true },
    { name: "Universitas Mpu Tantular", domain: "umt.ac.id", isVerified: true },
    { name: "Universitas Megou Pak Tulang Bawang", domain: "megoupak.ac.id", isVerified: true },
    { name: "Universitas Trinita", domain: "trinita.ac.id", isVerified: true },
    { name: "Universitas Hasyim Asy'ari", domain: "unhasy.ac.id", isVerified: true },
    { name: "Universitas Islam Indragiri", domain: "unisi.ac.id", isVerified: true },
    { name: "Universitas Wanita Internasional", domain: "uwi.ac.id", isVerified: true },
    { name: "Universitas Widya Gama Mahakam Samarinda", domain: "uwgm.ac.id", isVerified: true },
    { name: "Universitas Surakarta", domain: "uns.ac.id", isVerified: true },
    { name: "Universitas Bakti Indonesia", domain: "ubi.ac.id", isVerified: true },
    { name: "Universitas Mahaputra Muhammad Yamin", domain: "ummy.ac.id", isVerified: true },
    { name: "Universitas Islam Balitar", domain: "unisbablitar.ac.id", isVerified: true },
    { name: "Universitas Katolik Darma Cendika", domain: "ukdc.ac.id", isVerified: true },
    { name: "Universitas 17 Agustus 1945 Banyuwangi", domain: "untag-banyuwangi.ac.id", isVerified: true },
    { name: "Universitas Informatika Dan Bisnis Indonesia", domain: "ibi-kasatu.ac.id", isVerified: true },
    { name: "Universitas Bakti Tunas Husada", domain: "ubth.ac.id", isVerified: true },
    { name: "Universitas Wiraraja", domain: "wiraraja.ac.id", isVerified: true },
    { name: "Universitas Tulungagung", domain: "unitad.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Nusa Tenggara Barat", domain: "ununatb.ac.id", isVerified: true },
    { name: "Universitas Kristen Indonesia Tomohon", domain: "ukit.ac.id", isVerified: true },
    { name: "Universitas Asahan", domain: "una.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Lampung", domain: "uml.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Berau", domain: "umb.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Parepare", domain: "umpar.ac.id", isVerified: true },
    { name: "Universitas Widya Mataram", domain: "uwm.ac.id", isVerified: true },
    { name: "Universitas Katolik Widya Karya", domain: "uwika.ac.id", isVerified: true },
    { name: "Universitas Pendidikan Muhammadiyah Sorong", domain: "unimudasorong.ac.id", isVerified: true },
    { name: "Universitas Pembinaan Masyarakat Indonesia", domain: "upmi.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Indonesia", domain: "unusia.ac.id", isVerified: true },
    { name: "Universitas Sahid Surakarta", domain: "usahidsolo.ac.id", isVerified: true },
    { name: "Universitas Wijaya Kusuma Purwokerto", domain: "uwkp.ac.id", isVerified: true },
    { name: "Universitas Darma Agung", domain: "uda.ac.id", isVerified: true },
    { name: "Universitas Satya Negara Indonesia", domain: "usni.ac.id", isVerified: true },
    { name: "Universitas Al-washliyah Labuhan Batu", domain: "ualb.ac.id", isVerified: true },
    { name: "Universitas Surya", domain: "surya.ac.id", isVerified: true },
    { name: "Universitas Prof. DR. Hazairin SH.", domain: "unihaz.ac.id", isVerified: true },
    { name: "Universitas Widya Kartika", domain: "widya.ac.id", isVerified: true },
    { name: "Universitas San Pedro", domain: "usanpedro.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Yogyakarta", domain: "unuy.ac.id", isVerified: true },
    { name: "Universitas Timor", domain: "untim.ac.id", isVerified: true },
    { name: "Universitas PGRI Ronggolawe", domain: "unirow.ac.id", isVerified: true },
    { name: "Universitas Bina Insan", domain: "univbinainsan.ac.id", isVerified: true },
    { name: "Universitas Islam Batik", domain: "unisba.ac.id", isVerified: true },
    { name: "Universitas Gorontalo", domain: "ug.ac.id", isVerified: true },
    { name: "Universitas Madura", domain: "unira.ac.id", isVerified: true },
    { name: "Universitas Perjuangan Tasikmalaya", domain: "unper.ac.id", isVerified: true },
    { name: "Universitas Boyolali", domain: "uboy.ac.id", isVerified: true },
    { name: "Universitas Dwijendra", domain: "undwi.ac.id", isVerified: true },
    { name: "Universitas Katolik De La Salle", domain: "unikadelasalle.ac.id", isVerified: true },
    { name: "Universitas Panca Marga", domain: "upm.ac.id", isVerified: true },
    { name: "Universitas Rokania", domain: "rokania.ac.id", isVerified: true },
    { name: "Universitas Iskandarmuda", domain: "iskandarmuda.ac.id", isVerified: true },
    { name: "Universitas Soerjo", domain: "soerjo.ac.id", isVerified: true },
    { name: "Universitas Mahasaraswati Mataram", domain: "unmasmataram.ac.id", isVerified: true },
    { name: "Universitas Batam", domain: "universitasbatam.ac.id", isVerified: true },
    { name: "Universitas Azzahra", domain: "azzahra.ac.id", isVerified: true },
    { name: "Universitas Tama Jagakarsa", domain: "utj.ac.id", isVerified: true },
    { name: "Universitas Pancasakti Makassar", domain: "unpama.ac.id", isVerified: true },
    { name: "Universitas Sintuwu Maroso", domain: "unsimar.ac.id", isVerified: true },
    { name: "Universitas Pasifik Morotai", domain: "unipas.ac.id", isVerified: true },
    { name: "Universitas Kristen Indonesia Paulus", domain: "ukipaulus.ac.id", isVerified: true },
    { name: "Universitas Baiturrahmah", domain: "unbrah.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Wathan", domain: "unw.ac.id", isVerified: true },
    { name: "Universitas Tridinanti Palembang", domain: "univ-tridinanti.ac.id", isVerified: true },
    { name: "Universitas Ichsan Gorontalo", domain: "unisan.ac.id", isVerified: true },
    { name: "Universitas Doktor Nugroho Magetan", domain: "udn.ac.id", isVerified: true },
    { name: "Universitas PGRI Silampari", domain: "universitaspgrisilampari.ac.id", isVerified: true },
    { name: "Universitas Sains Cut Nyak Dhien", domain: "usacd.ac.id", isVerified: true },
    { name: "Universitas Bina Insani", domain: "ubi.ac.id", isVerified: true },
    { name: "Universitas Samawa", domain: "unsam.ac.id", isVerified: true },
    { name: "Universitas Methodist Indonesia", domain: "umi.ac.id", isVerified: true },
    { name: "Universitas Alkhairaat", domain: "unisa.ac.id", isVerified: true },
    { name: "Universitas Amir Hamzah", domain: "unhamzah.ac.id", isVerified: true },
    { name: "Universitas Antakusuma", domain: "uniska-bjm.ac.id", isVerified: true },
    { name: "Universitas Bali Internasional", domain: "unbi.ac.id", isVerified: true },
    { name: "Universitas Mulia", domain: "universitasmulia.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Maluku Utara", domain: "ummu.ac.id", isVerified: true },
    { name: "Universitas Kristen Indonesia Maluku", domain: "ukim.ac.id", isVerified: true },
    { name: "Universitas Billfath", domain: "billfath.ac.id", isVerified: true },
    { name: "Universitas Merdeka Madiun", domain: "unmermadiun.ac.id", isVerified: true },
    { name: "Universitas Selamat Sri", domain: "us.ac.id", isVerified: true },
    { name: "Universitas Baturaja", domain: "unbara.ac.id", isVerified: true },
    { name: "Universitas Sumatera Selatan", domain: "uss.ac.id", isVerified: true },
    { name: "Universitas Serang Raya", domain: "unsr.ac.id", isVerified: true },
    { name: "Universitas Mathla'ul Anwar", domain: "unma.ac.id", isVerified: true },
    { name: "Universitas Podomoro", domain: "podomorouniversity.ac.id", isVerified: true },
    { name: "Universitas Mitra Indonesia", domain: "umi.ac.id", isVerified: true },
    { name: "Universitas Merdeka Surabaya", domain: "unmer.ac.id", isVerified: true },
    { name: "Universitas Putra Indonesia", domain: "upi.ac.id", isVerified: true },
    { name: "Universitas Darul Ulum Islamic Centre Sudirman", domain: "unida.ac.id", isVerified: true },
    { name: "Universitas Panca Bhakti", domain: "upb.ac.id", isVerified: true },
    { name: "Universitas Pejuang Republik Indonesia", domain: "upri.ac.id", isVerified: true },
    { name: "Universitas Panji Sakti", domain: "unipas.ac.id", isVerified: true },
    { name: "Universitas Gajayana Malang", domain: "unigamalang.ac.id", isVerified: true },
    { name: "Universitas Karimun", domain: "unikar.ac.id", isVerified: true },
    { name: "Universitas Lintas Internasional Indonesia", domain: "uli.ac.id", isVerified: true },
    { name: "Universitas Ibnu Chaldun", domain: "uic.ac.id", isVerified: true },
    { name: "Universitas Jabal Ghafur", domain: "unjg.ac.id", isVerified: true },
    { name: "Universitas Bojonegoro", domain: "unigoro.ac.id", isVerified: true },
    { name: "Universitas Muhammadiyah Jambi", domain: "umjambi.ac.id", isVerified: true },
    { name: "Universitas Ngurah Rai", domain: "unr.ac.id", isVerified: true },
    { name: "Universitas Tamansiswa", domain: "unitas-pdg.ac.id", isVerified: true },
    { name: "Universitas Nusa Nipa", domain: "unnipa.ac.id", isVerified: true },
    { name: "Universitas Islam Al-Ihya Kuningan", domain: "unisa.ac.id", isVerified: true },
    { name: "Universitas Gunung Kidul", domain: "ugk.ac.id", isVerified: true },
    { name: "Universitas Teknologi Nusantara", domain: "utn.ac.id", isVerified: true },
    { name: "Universitas Universal", domain: "universal.ac.id", isVerified: true },
    { name: "Universitas Tjut Nyak Dhien", domain: "utnd.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Cirebon", domain: "unucirebon.ac.id", isVerified: true },
    { name: "Universitas Kader Bangsa", domain: "ukb.ac.id", isVerified: true },
    { name: "Universitas Teknologi Digital", domain: "utd.ac.id", isVerified: true },
    { name: "Universitas Muara Bungo", domain: "umb.ac.id", isVerified: true },
    { name: "Universitas Sisingamangaraja XII Tapanuli", domain: "ussit.ac.id", isVerified: true },
    { name: "Universitas Islam Ogan Komering Ilir Kayuagung", domain: "uniski.ac.id", isVerified: true },
    { name: "Universitas Sultan Fatah", domain: "usf.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Sumatera Utara", domain: "unusumatera.ac.id", isVerified: true },
    { name: "Universitas Sunan Giri Surabaya", domain: "unsuri.ac.id", isVerified: true },
    { name: "Universitas Al-Azhar", domain: "unaz.ac.id", isVerified: true },
    { name: "Universitas Islam Makassar", domain: "uinsmakassar.ac.id", isVerified: true },
    { name: "Universitas Dharmas Indonesia", domain: "undhari.ac.id", isVerified: true },
    { name: "Universitas Sains dan Teknologi Jayapura", domain: "ustj.ac.id", isVerified: true },
    { name: "Universitas Islam Jakarta", domain: "uij.ac.id", isVerified: true },
    { name: "Universitas Tompotika", domain: "untika.ac.id", isVerified: true },
    { name: "Universitas Wahidiyah", domain: "unwah.ac.id", isVerified: true },
    { name: "Universitas Teknologi Surabaya", domain: "utsurabaya.ac.id", isVerified: true },
    { name: "Universitas Gunung Rinjani", domain: "ugr.ac.id", isVerified: true },
    { name: "Universitas Jakarta", domain: "unj.ac.id", isVerified: true },
    { name: "Universitas Nusa Bangsa", domain: "unb.ac.id", isVerified: true },
    { name: "Universitas Bandung Raya", domain: "unbar.ac.id", isVerified: true },
    { name: "Universitas Banten Jaya", domain: "ubj.ac.id", isVerified: true },
    { name: "Universitas Gajah Putih", domain: "ugp.ac.id", isVerified: true },
    { name: "Universitas Patria Artha", domain: "upa.ac.id", isVerified: true },
    { name: "Universitas Quality", domain: "quality.ac.id", isVerified: true },
    { name: "Universitas Sunan Bonang", domain: "sunabon.ac.id", isVerified: true },
    { name: "Universitas Victory Sorong", domain: "unvic.ac.id", isVerified: true },
    { name: "Universitas Darwan Ali", domain: "undar.ac.id", isVerified: true },
    { name: "Universitas Alwashliyah", domain: "univa.ac.id", isVerified: true },
    { name: "Universitas Bondowoso", domain: "ub.ac.id", isVerified: true },
    { name: "Universitas Sulawesi Tenggara", domain: "unsultra.ac.id", isVerified: true },
    { name: "Universitas 45 Surabaya", domain: "unitomo.ac.id", isVerified: true },
    { name: "Universitas Sang Bumi Ruwa Jurai", domain: "usbrj.ac.id", isVerified: true },
    { name: "Universitas Mayjen Sungkono", domain: "ums.ac.id", isVerified: true },
    { name: "Universitas Simalungun", domain: "usimal.ac.id", isVerified: true },
    { name: "Universitas IBA", domain: "iba.ac.id", isVerified: true },
    { name: "Universitas Halmahera", domain: "uniera.ac.id", isVerified: true },
    { name: "Universitas Satyagama", domain: "satyagama.ac.id", isVerified: true },
    { name: "Universitas Yapis Papua", domain: "yapis.ac.id", isVerified: true },
    { name: "Universitas Yos Soedarso", domain: "uyoso.ac.id", isVerified: true },
    { name: "Universitas Lakidende Unaaha", domain: "ulunaha.ac.id", isVerified: true },
    { name: "Universitas Kristen Artha Wacana", domain: "ukaw.ac.id", isVerified: true },
    { name: "Universitas 45 Mataram", domain: "univ45mtr.ac.id", isVerified: true },
    { name: "Universitas Dayanu Ikhsanuddin", domain: "unikdi.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Kalimantan Timur", domain: "unukaltim.ac.id", isVerified: true },
    { name: "Universitas Al Ghifari", domain: "unfari.ac.id", isVerified: true },
    { name: "Universitas Mahendradatta", domain: "unmar.ac.id", isVerified: true },
    { name: "Universitas Sawerigading Makassar", domain: "unhasw.ac.id", isVerified: true },
    { name: "Universitas Pramita Indonesia", domain: "unpri.ac.id", isVerified: true },
    { name: "Universitas Sjakhyakirti", domain: "us.ac.id", isVerified: true },
    { name: "Universitas Al Asyariah Mandar", domain: "unsulbar.ac.id", isVerified: true },
    { name: "Universitas Siber Indonesia", domain: "univeris.ac.id", isVerified: true },
    { name: "Universitas Teknologi Sulawesi Utara", domain: "utsu.ac.id", isVerified: true },
    { name: "Universitas Madako Toli-toli", domain: "unimad.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Kalimantan Selatan", domain: "unukalsel.ac.id", isVerified: true },
    { name: "Universitas Kristen Teknologi Solo", domain: "ukts.ac.id", isVerified: true },
    { name: "Universitas Musi Rawas", domain: "unmura.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Surakarta", domain: "unus.ac.id", isVerified: true },
    { name: "Universitas 17 Agustus 1945 Cirebon", domain: "untagcirebon.ac.id", isVerified: true },
    { name: "Universitas Nasional Pasim", domain: "pasim.ac.id", isVerified: true },
    { name: "Universitas Mohammad Natsir Bukittinggi", domain: "umnb.ac.id", isVerified: true },
    { name: "Universitas Tamansiswa Palembang", domain: "unitasp.ac.id", isVerified: true },
    { name: "Universitas PGRI Palangkaraya", domain: "upgripalangkaraya.ac.id", isVerified: true },
    { name: "Universitas Tabanan", domain: "untab.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Kalimantan Barat", domain: "unukalbar.ac.id", isVerified: true },
    { name: "Universitas Nusantara Manado", domain: null, isVerified: false },
    { name: "Universitas Nahdlatul Ulama Sulawesi Tenggara", domain: "unusultra.ac.id", isVerified: true },
    { name: "Universitas Prisma", domain: null, isVerified: false },
    { name: "Universitas PGRI Wiranegara", domain: "uniwara.ac.id", isVerified: true },
    { name: "Universitas Persatuan Guru 1945 NTT", domain: "upg45ntt.ac.id", isVerified: true },
    { name: "Universitas Islam Labuhan Batu", domain: "uilabuhanbatu.ac.id", isVerified: true },
    { name: "Universitas Kaltara", domain: "unkaltar.ac.id", isVerified: true },
    { name: "Universitas Kristen Papua", domain: "ukip.ac.id", isVerified: true },
    { name: "Universitas Nahdlatul Ulama Sumatera Barat", domain: "unusbar.ac.id", isVerified: true },
    { name: "Universitas Nani Bili Nusantara", domain: null, isVerified: false },
    { name: "Universitas Ottow Geissler", domain: null, isVerified: false },
    { name: "Universitas Teknologi Sulawesi", domain: "utes.ac.id", isVerified: true },
    { name: "Universitas Efarina", domain: "efarina.ac.id", isVerified: true },
    { name: "Universitas Cordova", domain: "undova.ac.id", isVerified: true },
    { name: "Universitas Bumi Hijrah", domain: null, isVerified: false },
    { name: "Universitas Cokroaminoto Makassar", domain: "ucm.ac.id", isVerified: true },
    { name: "Universitas Gunung Leuser Aceh", domain: "ugla.ac.id", isVerified: true },
    { name: "Universitas Karya Dharma Makassar", domain: null, isVerified: false },
    { name: "Universitas Pawyatan Daha", domain: "unipd.ac.id", isVerified: true },
    { name: "Universitas Achmad Yani", domain: "unhani.ac.id", isVerified: true },
    { name: "Universitas Kristen Palangka Raya", domain: "ukpr.ac.id", isVerified: true },
    { name: "Universitas Tribuana Kalabahi", domain: "untribkalabahi.ac.id", isVerified: true },
    { name: "Universitas Kristen Tentena", domain: null, isVerified: false },
    { name: "Universitas Pembangunan Indonesia", domain: null, isVerified: false },
    { name: "Universitas Mochammad Sroedji Jember", domain: "umsj.ac.id", isVerified: true },
    { name: "Universitas Satya Wiyata Mandala", domain: null, isVerified: false },
    { name: "Universitas Aryasatya Deo Muri", domain: null, isVerified: false },
    { name: "Universitas Iqra Buru", domain: null, isVerified: false },
    { name: "Universitas Nuku", domain: null, isVerified: false },
    { name: "Universitas Nusa Lontar Rote", domain: "unirote.ac.id", isVerified: true },
    { name: "Universitas Islam Sumatera Barat", domain: "uisb.ac.id", isVerified: true },
    { name: "Universitas Tridharma Balikpapan", domain: "untri.ac.id", isVerified: true },
    { name: "Universitas Karyadarma Kupang", domain: "ukdk.ac.id", isVerified: true },
    { name: "Universitas Trunajaya", domain: null, isVerified: false },
    { name: "Universitas Karo", domain: null, isVerified: false },
    { name: "Universitas Surapati", domain: null, isVerified: false },
    { name: "Universitas Sari Putra Tomohon", domain: null, isVerified: false },
    { name: "Universitas Lumajang", domain: "unilu.ac.id", isVerified: true },
    { name: "Universitas Wiraswasta Indonesia", domain: null, isVerified: false },
    { name: "Universitas Pepabri Makassar", domain: null, isVerified: false },
    { name: "Universitas Hein Namotemo", domain: null, isVerified: false },
    { name: "Universitas Timika", domain: null, isVerified: false },
    { name: "Universitas Merdeka Ponorogo", domain: "unmerpo.ac.id", isVerified: true },
    { name: "Universitas Ratu Samban", domain: "unras.ac.id", isVerified: true },
    { name: "Universitas Dumoga Kotamobagu", domain: null, isVerified: false },
    { name: "Universitas Teknologi Indonesia", domain: "tui.ac.id", isVerified: true },
    { name: "Universitas Islam Attahiriyah", domain: "uniat.ac.id", isVerified: true },
    { name: "Universitas Nusa Tenggara Barat", domain: "untb.ac.id", isVerified: true },
    { name: "Universitas Kapuas Sintang", domain: null, isVerified: false },
    { name: "Universitas Timbul Nusantara", domain: null, isVerified: false },

]