import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Iran_universities = [

   // Iran
  
   { name: "University of Tehran", domain: "ut.ac.ir", isVerified: true },
   { name: "Sharif University of Technology", domain: "sharif.edu", isVerified: true },
   { name: "Tehran University of Medical Sciences", domain: "tums.ac.ir", isVerified: true },
   { name: "Shahid Beheshti University of Medical Sciences", domain: "sbmu.ac.ir", isVerified: true },
   { name: "Ferdowsi University of Mashhad", domain: "ferdowsi.um.ac.ir", isVerified: true },
   { name: "Mashhad University of Medical Sciences", domain: "mums.ac.ir", isVerified: true },
   { name: "Tarbiat Modares University", domain: "modares.ac.ir", isVerified: true },
   { name: "Iran University of Science and Technology", domain: "iust.ac.ir", isVerified: true },
   { name: "Isfahan University of Technology", domain: "iut.ac.ir", isVerified: true },
   { name: "Amirkabir University of Technology", domain: "aut.ac.ir", isVerified: true },
   { name: "Shahid Beheshti University", domain: "SBU.ac.ir", isVerified: true },
   { name: "Shiraz University of Medical Sciences", domain: "sums.ac.ir", isVerified: true },
   { name: "University of Isfahan", domain: "ui.ac.ir", isVerified: true },
   { name: "Tabriz University of Medical Sciences", domain: "tbzmed.ac.ir", isVerified: true },
   { name: "Shiraz University", domain: "shirazu.ac.ir", isVerified: true },
   { name: "Isfahan University of Medical Sciences", domain: "iums.ac.ir", isVerified: true },
   { name: "University of Tabriz", domain: "tabrizu.ac.ir", isVerified: true },
   { name: "Khaje Nasir Toosi University of Technology", domain: "kntu.ac.ir", isVerified: true },
   { name: "Institute for Research in Fundamental Sciences", domain: "ipm.ac.ir", isVerified: true },
   { name: "Allameh Tabataba'i University", domain: "atu.ac.ir", isVerified: true },
   { name: "The University of Guilan", domain: "gu.ac.ir", isVerified: true },
   { name: "Shahid Chamran University of Ahvaz", domain: "scu.ac.ir", isVerified: true },
   { name: "Alzahra University", domain: "alzahra.ac.ir", isVerified: true },
   { name: "University of Social Welfare and Rehabilitation Sciences", domain: "uswr.ac.ir", isVerified: true },
   { name: "Shahid Sadoughi University of Medical Sciences and Health Services", domain: "ssu.ac.ir", isVerified: true },
   { name: "Medical University of Ilam", domain: "mu.ilam.ac.ir", isVerified: true },
   { name: "University of Kashan", domain: "kashanu.ac.ir", isVerified: true },
   { name: "Bu-Ali Sina University", domain: "basu.ac.ir", isVerified: true },
   { name: "Yazd University", domain: "yazd.ac.ir", isVerified: true },
   { name: "Mazandaran University of Medical Sciences", domain: "mums.ac.ir", isVerified: true },
   { name: "Hamadan University of Medical Sciences", domain: "ums.hamedan.ac.ir", isVerified: true },
   { name: "Zanjan University", domain: "znu.ac.ir", isVerified: true },
   { name: "Semnan University", domain: "semnan.ac.ir", isVerified: true },
   { name: "University of Applied Science and Technology", domain: "uast.ac.ir", isVerified: true },
   { name: "Kerman Medical University", domain: "kmu.ac.ir", isVerified: true },
   { name: "Kharazmi University", domain: "khu.ac.ir", isVerified: true },
   { name: "Arak University of Medical Sciences", domain: "arums.ac.ir", isVerified: true },
   { name: "University of Sistan and Baluchestan", domain: "usb.ac.ir", isVerified: true },
   { name: "Urmia University", domain: "urmia.ac.ir", isVerified: true },
   { name: "Shahid Bahonar University of Kerman", domain: "uk.ac.ir", isVerified: true },
   { name: "Arak University", domain: "araku.ac.ir", isVerified: true },
   { name: "Kermanshah University of Medical Sciences", domain: "kums.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Science and Research of Fars", domain: "iausr.ac.ir", isVerified: true },
   { name: "Imam Khomeini International University", domain: "ikiu.ac.ir", isVerified: true },
   { name: "Urmia University of Medical Sciences", domain: "umsu.ac.ir", isVerified: true },
   { name: "Razi University", domain: "razi.ac.ir", isVerified: true },
   { name: "National University of Skill", domain: null, isVerified: false },
   { name: "Gilan University of Medical Sciences", domain: "gums.ac.ir", isVerified: true },
   { name: "Shahrekord University of Medical Sciences", domain: "skums.ac.ir", isVerified: true },
   { name: "University of Mohaghegh Ardabili", domain: "uma.ac.ir", isVerified: true },
   { name: "University of Birjand", domain: "birjand.ac.ir", isVerified: true },
   { name: "Kashan University of Medical Sciences", domain: "kashums.ac.ir", isVerified: true },
   { name: "University of Mazandaran", domain: "umz.ac.ir", isVerified: true },
   { name: "University of Kurdistan", domain: "uok.ac.ir", isVerified: true },
   { name: "Institute for Advanced Studies in Basic Sciences", domain: "iasbs.ac.ir", isVerified: true },
   { name: "Shahrood University of Technology", domain: "shru.ac.ir", isVerified: true },
   { name: "Zanjan University of Medical Sciences", domain: "zums.ac.ir", isVerified: true },
   { name: "Imam Sadiq University", domain: "imamu.ac.ir", isVerified: true },
   { name: "Golestan University of Medical Sciences", domain: "goms.ac.ir", isVerified: true },
   { name: "Qazvin University of Medical Sciences", domain: "qums.ac.ir", isVerified: true },
   { name: "Gorgan University of Agricultural Sciences and Natural Resources", domain: "gau.ac.ir", isVerified: true },
   { name: "Bushehr University of Medical Sciences", domain: "bpums.ac.ir", isVerified: true },
   { name: "Shahed University", domain: "shahed.ac.ir", isVerified: true },
   { name: "Babol Noshirvani University of Technology", domain: "nit.ac.ir", isVerified: true },
   { name: "Hormozgan University of Medical Sciences", domain: "hums.ac.ir", isVerified: true },
   { name: "Shahrekord University", domain: "scu.ac.ir", isVerified: true },
   { name: "Shahid Rajaee Teacher Training University", domain: "rtsu.ac.ir", isVerified: true },
   { name: "University of Qom", domain: "qom.ac.ir", isVerified: true },
   { name: "Qom University of Medical Sciences", domain: "qomums.ac.ir", isVerified: true },
   { name: "Kurdistan University of Medical Sciences", domain: "kums.ac.ir", isVerified: true },
   { name: "Sahand University of Technology", domain: "sahand.ac.ir", isVerified: true },
   { name: "Baqiyatallah Medical Sciences University", domain: "bmsu.ac.ir", isVerified: true },
   { name: "Yasuj University of Medical Sciences", domain: "yums.ac.ir", isVerified: true },
   { name: "Islamic Azad University Isfahan, Khorasgan Branch", domain: "iau.ac.ir", isVerified: true },
   { name: "Birjand University of Medical Sciences", domain: "bums.ac.ir", isVerified: true },
   { name: "Imam Hossein University", domain: "ihu.ac.ir", isVerified: true },
   { name: "Al Mustafa International University", domain: "amiu.ac.ir", isVerified: true },
   { name: "Islamic Azad University, South Tehran", domain: "iaushd.ac.ir", isVerified: true },
   { name: "University of Art", domain: "iua.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Tehran Medical", domain: "iautmu.ac.ir", isVerified: true },
   { name: "Ahvaz Jundishapur University of Medical Sciences", domain: "ajums.ac.ir", isVerified: true },
   { name: "Azarbaijan Shahid Madani University", domain: "smt.ac.ir", isVerified: true },
   { name: "Ardabil University of Medical Sciences", domain: "ardabilums.ac.ir", isVerified: true },
   { name: "Petroleum University of Technology", domain: "put.ac.ir", isVerified: true },
   { name: "Lorestan University", domain: "lru.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Mashhad", domain: "iaum.ac.ir", isVerified: true },
   { name: "Babol University of Medical Sciences", domain: "bums.ac.ir", isVerified: true },
   { name: "Persian Gulf University", domain: "pgu.ac.ir", isVerified: true },
   { name: "Gonabad University of Medical Sciences", domain: "gmu.ac.ir", isVerified: true },
   { name: "Semnan University of Medical Sciences", domain: "semums.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Karaj Branch", domain: "iaukaraj.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Tabriz", domain: "iaut.ac.ir", isVerified: true },
   { name: "Sabzevar University of Medical Sciences", domain: "sbmu.ac.ir", isVerified: true },
   { name: "Iran Polymer and Petrochemical Institute", domain: "ippi.ac.ir", isVerified: true },
   { name: "Lorestan University of Medical Sciences", domain: "lums.ac.ir", isVerified: true },
   { name: "Islamic Azad University Central Tehran Branch", domain: "iauctb.ac.ir", isVerified: true },
   { name: "Fasa University of Medical Sciences", domain: "fums.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Arak", domain: "iauarak.ac.ir", isVerified: true },
   { name: "Rafsanjan University of Medical Sciences", domain: "rums.ac.ir", isVerified: true },
   { name: "Hormozgan University", domain: "hormozgan.ac.ir", isVerified: true },
   { name: "University of Religions and Denominations", domain: "urd.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Rasht", domain: "iaurasht.ac.ir", isVerified: true },
   { name: "Sari Agricultural Sciences and Natural Resources University", domain: "sari.ac.ir", isVerified: true },
   { name: "Golestan University", domain: "gu.ac.ir", isVerified: true },
   { name: "North Khorasan University of Medical Sciences", domain: "nkum.ac.ir", isVerified: true },
   { name: "Ilam University", domain: "ilam.ac.ir", isVerified: true },
   { name: "Mofid University", domain: "mofid.ac.ir", isVerified: true },
   { name: "Hakim Sabzevari University", domain: "hsu.ac.ir", isVerified: true },
   { name: "University of Bojnord", domain: "ub.ac.ir", isVerified: true },
   { name: "Art University of Isfahan", domain: "aui.ac.ir", isVerified: true },
   { name: "Jahrom University of Medical Sciences", domain: "jums.ac.ir", isVerified: true },
   { name: "Sadjad University of Technology", domain: "sadjad.ac.ir", isVerified: true },
   { name: "Malek-Ashtar University of Technology", domain: "malek.ashtar.ac.ir", isVerified: true },
   { name: "Damghan University", domain: "damghan.ac.ir", isVerified: true },
   { name: "Zabol University of Medical Sciences", domain: "zums.ac.ir", isVerified: true },
   { name: "University of Maragheh", domain: "maragheh.ac.ir", isVerified: true },
   { name: "Shahroud University of Medical Sciences", domain: "shums.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Marvdasht", domain: "iaumrv.ac.ir", isVerified: true },
   { name: "Yasuj University", domain: "yazd.ac.ir", isVerified: true },
   { name: "Shiraz University of Technology", domain: "sutech.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shiraz", domain: "iaushiraz.ac.ir", isVerified: true },
   { name: "Zahedan University of Medical Sciences", domain: "zaums.ac.ir", isVerified: true },
   { name: "University of Torbat-e-Heydarieh", domain: null, isVerified: false },
   { name: "Islamic Azad University, Hamedan", domain: "iauh.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Kerman", domain: "iauk.ac.ir", isVerified: true },
   { name: "University of Zabol", domain: "uoz.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Kermanshah", domain: null, isVerified: false },
   { name: "ValiAsr University of Rafsanjan", domain: "varu.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shabestar", domain: null, isVerified: false },
   { name: "Tabriz Islamic Art University", domain: "tiau.ac.ir", isVerified: true },
   { name: "Gonbad Kavous University", domain: null, isVerified: false },
   { name: "Kermanshah University of Technology", domain: null, isVerified: false },
   { name: "Islamic Azad University, Quchan", domain: "iauq.ac.ir", isVerified: true },
   { name: "Baqir al-olum University", domain: null, isVerified: false },
   { name: "Urmia University of Technology", domain: "uut.ac.ir", isVerified: true },
   { name: "Imam Reza International University", domain: "iriu.ac.ir", isVerified: true },
   { name: "Qom University of Technology", domain: "qut.ac.ir", isVerified: true },
   { name: "International University of Chabahar", domain: "iuc.ac.ir", isVerified: true },
   { name: "Dezful University of Medical Sciences and Health Services", domain: "dums.ac.ir", isVerified: true },
   { name: "University of Quran and Hadith", domain: null, isVerified: false },            
   { name: "Islamic Azad University, Yazd", domain: "iauy.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Bandar Abbas", domain: "iaubband.ac.ir", isVerified: true },
   { name: "Graduate University of Advanced Technology", domain: "guat.ac.ir", isVerified: true },
   { name: "University of Bonab", domain: "bonabu.ac.ir", isVerified: true },
   { name: "School of International Relations", domain: "sir.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Semnan", domain: "iaus.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shahreza", domain: "iaush.ac.ir", isVerified: true },
   { name: "Khavaran Institute of Higher Education", domain: "khavaran.ac.ir", isVerified: true },
   { name: "Pars University of Architecture and Art", domain: "parsu.ac.ir", isVerified: true },
   { name: "Imam Khomeini Education and Research Institute", domain: "ikeri.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ahvaz", domain: "iauah.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Varamin", domain: "iauv.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ahar", domain: "iauahar.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Lahijan", domain: "iaulah.ac.ir", isVerified: true },
   { name: "Hamadan University of Technology", domain: "hut.ac.ir", isVerified: true },
   { name: "Chabahar Maritime University", domain: "chmu.ac.ir", isVerified: true },
   { name: "Quchan University of Advanced Technology", domain: "quatu.ac.ir", isVerified: true },
   { name: "Malayer University", domain: "malayeru.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Zahedan", domain: "iauza.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Neyshabur", domain: "iaun.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shahr Rey", domain: "iausr.ac.ir", isVerified: true },
   { name: "Khuzestan Agricultural Sciences and Natural Resources University", domain: "kasnr.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Sabzevar", domain: "iausab.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Gorgan", domain: "iaug.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Garmsar", domain: "iaugar.ac.ir", isVerified: true },
   { name: "Kosar University of Bojnord", domain: "kub.ac.ir", isVerified: true },
   { name: "Hazrat-e Masoumeh University", domain: "hmu.ac.ir", isVerified: true },
   { name: "Tafresh University", domain: "tafreshu.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Zanjan", domain: "iauz.ac.ir", isVerified: true },
   { name: "Arak University of Technology", domain: "autar.ac.ir", isVerified: true },
   { name: "University of Jiroft", domain: null, isVerified: false },
   { name: "Islamic Azad University, Maragheh", domain: "iaumar.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Qazvin", domain: "iauqv.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shahrood", domain: "iausr.ac.ir", isVerified: true },
   { name: "University of Garmsar", domain: null, isVerified: false },
   { name: "Islamic Azad University, Saveh", domain: "iausv.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Sanandaj Branch", domain: "iausdj.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Roudehen", domain: "iaurd.ac.ir", isVerified: true },
   { name: "Khorramshahr Marine Science and Technology University", domain: null, isVerified: false },
   { name: "Islamic Azad University, Naragh", domain: "iaunar.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Sari", domain: "iausari.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Damghan", domain: "iaudg.ac.ir", isVerified: true },
   { name: "Birjand University of Technology", domain: null, isVerified: false },
   { name: "Jundi-Shapur University of Technology", domain: "jsut.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Arsanjan", domain: "iauarj.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Sepidan", domain: "iausp.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Majlesi", domain: "iaumj.ac.ir", isVerified: true },
   { name: "Bozorgmehr University of Qaenat", domain: null, isVerified: false },
   { name: "Islamic Azad University, Mahabad", domain: "iaumhb.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ardabil", domain: "iauard.ac.ir", isVerified: true },    
   { name: "Shomal University", domain: "shomal.ac.ir", isVerified: true },
   { name: "Ardakan University", domain: "ardakan.ac.ir", isVerified: true },
   { name: "Jahrom university", domain: "jums.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Qom", domain: "iauq.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Mobarakeh", domain: "iaumob.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Bojnourd", domain: "iaubojn.ac.ir", isVerified: true },
   { name: "Ayatollah Borujerdi University", domain: "borujerd.ac.ir", isVerified: true },
   { name: "Sirjan University of Technology", domain: "sutech.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Dezful", domain: "iaudez.ac.ir", isVerified: true },
   { name: "University of Science and Technology of Mazandaran", domain: "ustm.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Firuzabad", domain: "iaufir.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Yasuj", domain: "iauyas.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Khomeinishahr", domain: "iaukhs.ac.ir", isVerified: true },
   { name: "Engineering Higher Education Complex of Esfarayen", domain: null, isVerified: false },
   { name: "Islamic Azad University, Birjand", domain: "iaubir.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Bushehr", domain: "iaubus.ac.ir", isVerified: true },
   { name: "Bam University", domain: "bam.ac.ir", isVerified: true },
   { name: "Shiraz Art University", domain: "sau.ac.ir", isVerified: true },
   { name: "Meybod University", domain: "meybod.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Tafresh", domain: "iautaf.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Khomain", domain: "iaukh.ac.ir", isVerified: true },
   { name: "University of Neyshabur", domain: "neyshabur.ac.ir", isVerified: true },
   { name: "Sheikhbahaee University", domain: "shbu.ac.ir", isVerified: true },
   { name: "Fasa University", domain: "fusa.ac.ir", isVerified: false },
   { name: "Salman Farsi University of Kazerun", domain: "sfuk.ac.ir", isVerified: true },
   { name: "University of Gonabad", domain: "gou.ac.ir", isVerified: true },
   { name: "Khatam Al Anbia Behbahan University of Technology", domain: "kabut.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Abhar", domain: "iauab.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Qaemshahr", domain: "iauqs.ac.ir", isVerified: true },
   { name: "Sayyed Jamaleddin Asadabadi University", domain: "sja.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Tonekabon", domain: "iautn.ac.ir", isVerified: true },
   { name: "Velayat University", domain: "velayat.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Astara", domain: "iauas.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shoushtar", domain: "iaush.ac.ir", isVerified: true },
   { name: "Ahlul Bayt International University", domain: "abiu.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Bonab", domain: "iaubon.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Firoozkooh", domain: "iaufk.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Babol", domain: "iaub.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Dehaghan", domain: "iaudh.ac.ir", isVerified: true },
   { name: "Islamic Azad University, West Tehran", domain: "iauwt.ac.ir", isVerified: true },
   { name: "Higher Education Complex of Larestan", domain: "hecl.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Kazeroon", domain: "iaukzr.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Eghlid", domain: "iauegh.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Ilam", domain: "iaui.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Urmia", domain: "iauu.ac.ir", isVerified: true },
   { name: "Mazandaran University of Science and Technology", domain: "must.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shirvan", domain: "iaushv.ac.ir", isVerified: true },
   { name: "Shohadaye Hoveizeh University of Technology", domain: "shut.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Borujerd", domain: "iaubor.ac.ir", isVerified: true },
   { name: "Higher Education Complex of Saravan", domain: "hecs.ac.ir", isVerified: true },
   { name: "Isfahan Institute of Higher Education", domain: "iihe.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Miyaneh", domain: "iaumi.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Damavand", domain: "iaudam.ac.ir", isVerified: true },
   { name: "Islamic Azad University, North Tehran", domain: "iaunt.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Jahrom", domain: "iaujah.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Darab", domain: "iaudar.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Kashan", domain: "iauksh.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Estahban", domain: "iauest.ac.ir", isVerified: true },
   { name: "Islamic Azad University-Sarab Branch", domain: "iausrb.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Takestan", domain: "iautak.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Eslamshahr", domain: "iauesl.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Fasa", domain: "iaufas.ac.ir", isVerified: true },
   { name: "Science and Arts University", domain: "sau-yazd.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Gonabad", domain: "iaugon.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Khoy", domain: "iaukhy.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ayatollah Amoli", domain: "iauaam.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Larestan", domain: "iaular.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Parand", domain: "iaupar.ac.ir", isVerified: true },
   { name: "Higher Education Complex of Torbat-e-Jam", domain: "hectj.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Shahr-e-Qods", domain: "iausq.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Abadeh", domain: "iauab.ac.ir", isVerified: true },
   { name: "Hazrat-e Narjes University of Rafsanjan", domain: null, isVerified: false },
   { name: "Islamic Azad University, Maybod", domain: "iaumyb.ac.ir", isVerified: true },
   { name: "Higher Education Complex of Zarand", domain: "hecz.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Golpayegan", domain: "iaugol.ac.ir", isVerified: true },
   { name: "Danesh Alborz University", domain: null, isVerified: false },
   { name: "Islamic Azad University, Parsabad Moghan", domain: "iaupm.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ashkezar", domain: "iauash.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ardestan", domain: "iauardst.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Mahdishahr", domain: "iaumsh.ac.ir", isVerified: true },
   { name: "Jami Institute of Technology", domain: null, isVerified: false },
   { name: "Islamic Azad University, Behshahr", domain: "iaubsh.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Masjed Soleyman", domain: "iaums.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Hidaj", domain: "iauhid.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Azadshahr", domain: "iauaz.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Gachsaran", domain: "iaugch.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Naein", domain: "iaunei.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Bandar-e Anzali", domain: "iaubza.ac.ir", isVerified: true },
   { name: "Islamic Azad University, East Tehran", domain: "iauet.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Abarkouh", domain: "iauabr.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ashtian", domain: "iauasht.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Bandar Gaz", domain: "iaubg.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Anar", domain: "iauanar.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Nur", domain: "iaunur.ac.ir", isVerified: true },
   { name: "Islamic Azad University of Medical Sciences, Qeshm", domain: null, isVerified: false },
   { name: "Allameh Mohaddes Nouri University", domain: null, isVerified: false },
   { name: "Islamic Azad University, Sirjan", domain: "iausir.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Baft", domain: "iaubaft.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Hashtrood", domain: "iauhash.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Behbahan", domain: "iaubeh.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Andimeshk", domain: "iauand.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Aligudarz", domain: "iaualg.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Dehloran", domain: "iaudel.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ardakan", domain: "iauard.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ferdows", domain: "iauferd.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Osku", domain: "iauosk.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Komijan", domain: "iaukom.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Izeh", domain: "iauize.ac.ir", isVerified: true },
   { name: "Islamic Azad University Kashmar Branch", domain: "iaukas.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ramhormoz", domain: "iaurhm.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Esfarayen", domain: "iauesf.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Zarand", domain: "iauzar.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Mahshahr", domain: "mhriau.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Omidiyeh", domain: "iauo.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Buin-Zahra", domain: "buiniau.ac.ir", isVerified: true },
   { name: "Iran Informatic Institute", domain: null, isVerified: false },
   { name: "Islamic Azad University, Abadan", domain: "iauabadan.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Ajabshir", domain: "ajabshiriau.ac.ir", isVerified: true },
   { name: "Shahid Sattari University of Aeronautical Engineering", domain: "ssau.ac.ir", isVerified: true },
   { name: "Islamic Azad University, Khorramabad", domain: null, isVerified: false },
   { name: "Iran University of Industries and Mines", domain: "iuim.ir", isVerified: true },
   { name: "Golbahar University of Science and New Technology", domain: null, isVerified: false },
   { name: "University of Shahreza", domain: null, isVerified: false },
   { name: "Nahavand University", domain: "nahgu.ac.ir", isVerified: true },
   { name: "Sabzevar University of New Technologies", domain: "sunt.ir", isVerified: true },
   { name: "Shiraz University of Applied Science and Technology", domain: "uast.ac.ir", isVerified: true },  
]