import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Iraq_universities = [

   // Iraq

   { name: "University of Baghdad", domain: "uobaghdad.edu.iq", isVerified: true },
   { name: "University of Diyala", domain: "uodiyala.edu.iq", isVerified: true },
   { name: "The University of Mustansiriyah", domain: "uomustansiriyah.edu.iq", isVerified: true },
   { name: "Tishk International University", domain: "tiu.edu.iq", isVerified: true },
   { name: "University of Babylon", domain: "uobabylon.edu.iq", isVerified: true },
   { name: "Al-Maarif University College", domain: "uoa.edu.iq", isVerified: true },
   { name: "Bilad Alrafidain University College", domain: "ruc.edu.iq", isVerified: true },
   { name: "University of Kufa", domain: "uokufa.edu.iq", isVerified: true },
   { name: "University of Mosul", domain: "uomosul.edu.iq", isVerified: true },
   { name: "University of Basrah", domain: "uobasrah.edu.iq", isVerified: true },
   { name: "University of Technology", domain: "uotechnology.edu.iq", isVerified: true },
   { name: "University of Anbar", domain: "uoanbar.edu.iq", isVerified: true },
   { name: "Soran University", domain: "soran.edu.iq", isVerified: true },
   { name: "Al-Furat Al-Awsat Technical University", domain: "atu.edu.iq", isVerified: true },
   { name: "The American University of Iraq, Sulaimani", domain: "auis.edu.krd", isVerified: true },
   { name: "Salahaddin University-Erbil", domain: "su.edu.krd", isVerified: true },
   { name: "University of Sulaimani", domain: "univsul.edu.iq", isVerified: true },
   { name: "University of Kerbala", domain: "uokerbala.edu.iq", isVerified: true },
   { name: "The University of Duhok", domain: "uod.ac", isVerified: true },
   { name: "University of Tikrit", domain: "tu.edu.iq", isVerified: true },
   { name: "University of Al-Qadisiyah", domain: "qu.edu.iq", isVerified: true },
   { name: "Koya University", domain: "koyauniversity.org", isVerified: true },
   { name: "Erbil Polytechnic University", domain: "epu.edu.iq", isVerified: true },
   { name: "Northern Technical University", domain: "ntu.edu.iq", isVerified: true },
   { name: "Al Nahrain University", domain: "nahrainuniv.edu.iq", isVerified: true },
   { name: "University of Thi-Qar", domain: "utq.edu.iq", isVerified: true },
   { name: "University of Kurdistan Hewlêr", domain: "ukh.edu.krd", isVerified: true },
   { name: "University of Zakho", domain: "uoz.edu.krd", isVerified: true },
   { name: "University of Wasit", domain: "uowasit.edu.iq", isVerified: true },
   { name: "Cihan University", domain: "cihanuniversity.edu.iq", isVerified: true },
   { name: "Middle Technical University", domain: "mtu.edu.iq", isVerified: true },
   { name: "Islamic University of Najaf", domain: "iunajaf.edu.iq", isVerified: true },
   { name: "Al Iraqia University", domain: "aliraqia.edu.iq", isVerified: true },
   { name: "Al-Muthanna University", domain: "mu.edu.iq", isVerified: true },
   { name: "Lebanese French University", domain: "lfu.edu.krd", isVerified: true },
   { name: "Sulaimani Polytechnic University", domain: "spu.edu.iq", isVerified: true },
   { name: "Hawler Medical University", domain: "hmu.edu.krd", isVerified: true },
   { name: "Komar University of Science and Technology", domain: "komar.edu.iq", isVerified: true },
   { name: "University of Information Technology and Communications", domain: "uoitc.edu.iq", isVerified: true },
   { name: "Al-Rasheed University College", domain: "alrasheedcol.edu.iq", isVerified: true },
   { name: "University of Misan", domain: "uomisan.edu.iq", isVerified: true },
   { name: "University of Kirkuk", domain: "uokirkuk.edu.iq", isVerified: true },
   { name: "University of Human Development", domain: "uhd.edu.iq", isVerified: true },
   { name: "Southern Technical University", domain: "stu.edu.iq", isVerified: true },
   { name: "Duhok Polytechnic University", domain: "dpu.edu.krd", isVerified: true },
   { name: "Ninevah University", domain: "uoninevah.edu.iq", isVerified: true },
   { name: "University of Garmian", domain: "garmian.edu.krd", isVerified: true },
   { name: "University of Alkafeel", domain: "alkafeel.edu.iq", isVerified: true },
   { name: "Al Safwa University College", domain: "alsafwa.edu.iq", isVerified: true },
   { name: "The American University of Kurdistan", domain: "auk.edu.krd", isVerified: true },
   { name: "Al Bayan University", domain: "al-bayan.edu.iq", isVerified: true },
   { name: "Hilla University College", domain: "huc.edu.iq", isVerified: true },
   { name: "University of Halabja", domain: "unihalabja.edu.krd", isVerified: true },
   { name: "Catholic University in Erbil", domain: "cueb.edu.krd", isVerified: true },
   { name: "Al-Noor University", domain: "alnoor.edu.iq", isVerified: true },
   { name: "Madenat Alelem University College", domain: null, isVerified: false },
   { name: "Knowledge University", domain: "ku.edu.krd", isVerified: true },
   { name: "Ahl al-Bayt University", domain: "abu.edu.iq", isVerified: true },
   { name: "University of Samarra", domain: "uosamarra.edu.iq", isVerified: true },
   { name: "Al-Farahidi University", domain: null, isVerified: false },
   { name: "University of Raparin", domain: "ur.edu.krd", isVerified: true },
   { name: "Al-Mansour University College", domain: "muc.edu.iq", isVerified: true },
   { name: "University of Fallujah", domain: "uofallujah.edu.iq", isVerified: true },
   { name: "Al-Karkh University of Science", domain: "karkhuniv.edu.iq", isVerified: true },
   { name: "Al-Esraa University College", domain: "esraa.edu.iq", isVerified: true },
   { name: "University of Telafer", domain: null, isVerified: false },
   { name: "Al-Rafidain University College", domain: "arc.edu.iq", isVerified: true },
   { name: "Al-Kitab University", domain: "kitab.edu.iq", isVerified: true },
   { name: "Nawroz University", domain: "nawroz.edu.krd", isVerified: true },
   { name: "University of Sumer", domain: null, isVerified: false },
   { name: "Jabir Ibn Hayyan Medical University", domain: "jihuniv.edu.iq", isVerified: true },
   { name: "Basra University of Oil an Gas", domain: "buog.edu.iq", isVerified: true },
   { name: "Dijlah University College", domain: "duc.edu.iq", isVerified: true },
   { name: "National University of Science and Technology", domain: "nust.edu.iq", isVerified: true },
   { name: "University of Al Hamdaniya", domain: null, isVerified: false },
   { name: "Al-Kut University College", domain: "kuc.edu.iq", isVerified: true },
   { name: "Imam Ja'afar Al-sadiq University", domain: "ijas.edu.iq", isVerified: true },
   { name: "Al Hikma University College", domain: "hikma.edu.iq", isVerified: true },
   { name: "Al-Qasim Green University", domain: "qgu.edu.iq", isVerified: true },
   { name: "Baghdad College of Economic Sciences University", domain: "bcesu.edu.iq", isVerified: true },        
   { name: "Al Qalam University College", domain: "alqalam.edu.iq", isVerified: true },
   { name: "Imam Al-Azam University College", domain: "imamaladham.edu.iq", isVerified: true },
   { name: "Al-Turath University", domain: "uoturath.edu.iq", isVerified: true },
   { name: "Shatt Al-Arab University College", domain: "sa-uc.edu.iq", isVerified: true },
   { name: "Al-Zahrawi University College", domain: "alzahu.edu.iq", isVerified: true },
   { name: "Iraq University College", domain: "iuc.edu.iq", isVerified: true },
   { name: "International University of Erbil", domain: "ue.edu.krd", isVerified: true },
   { name: "Alyarmok University College", domain: "al-yarmok.edu.iq", isVerified: true },
   { name: "Imam Al-Kadhim University College of Islamic Sciences", domain: "iku.edu.iq", isVerified: true },
   { name: "Ibn Sina University of Medical and Pharmaceutical Sciences", domain: "ibnsina.edu.iq", isVerified: true },
   { name: "Mazaya University College", domain: "mpu.edu.iq", isVerified: true },
   { name: "Al-Nukhba University College", domain: "alnukhba.edu.iq", isVerified: true },
   { name: "Kurdistan Institution for Strategic Studies and Scientific Research", domain: "kissr.edu.iq", isVerified: true },
   { name: "Bayan University", domain: "bnu.edu.iq", isVerified: true },
   { name: "Al-Nisour University College", domain: "nuc.edu.iq", isVerified: true },
   { name: "Al Mamoun University College", domain: "almamonuc.edu.iq", isVerified: true },
   { name: "Al-Kunooze University College", domain: "kunoozu.edu.iq", isVerified: true },
   { name: "Uruk University", domain: "uruk.edu.iq", isVerified: true },
   { name: "Charmo University", domain: "chu.edu.iq", isVerified: true },
   { name: "Altoosi University College", domain: "altoosi.edu.iq", isVerified: true },
   { name: "Al-Hadba University College", domain: "hcu.edu.iq", isVerified: true },
   { name: "Al-Mustafa University College", domain: "almustafauniversity.edu.iq", isVerified: true },
   { name: "Al-Hussain University College", domain: "huciraq.edu.iq", isVerified: true },
   { name: "Baghdad College of Medical Sciences", domain: "bcms.edu.iq", isVerified: true },
   { name: "Gilgamesh University", domain: "gu.edu.iq", isVerified: true },
   { name: "Al-Imam University College", domain: "alimamunc.edu.iq", isVerified: true },
   { name: "Osol Al-Deen University College", domain: "ouc.edu.iq", isVerified: true },
   { name: "Al-Taff University College", domain: "altuff.edu.iq", isVerified: true },
   { name: "Al-Amal University College", domain: "alamal.edu.iq", isVerified: true },
   { name: "Basra University College of Science and Technology", domain: "basrah-college.edu.iq", isVerified: true },
]