import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Ireland_universities = [
    
    // Ireland

    { name: "Trinity College Dublin, University of Dublin", domain: "tcd.ie", isVerified: true },
    { name: "University College Dublin", domain: "ucd.ie", isVerified: true },
    { name: "University College Cork", domain: "ucc.ie", isVerified: true },
    { name: "University of Galway", domain: "universityofgalway.ie", isVerified: true },
    { name: "Dublin City University", domain: "dcu.ie", isVerified: true },
    { name: "University of Limerick", domain: "ul.ie", isVerified: true },
    { name: "Technological University Dublin", domain: "tu.ie", isVerified: true },
    { name: "Maynooth University", domain: "maynoothuniversity.ie", isVerified: true },
    { name: "South East Technological University", domain: "setu.ie", isVerified: true },
    { name: "Technological University of the Shannon", domain: "tus.ie", isVerified: true },
    { name: "Atlantic Technological University", domain: "atu.ie", isVerified: true },
    { name: "Munster Technological University", domain: "mtu.ie", isVerified: true },
    { name: "Dundalk Institute of Technology", domain: "dkit.ie", isVerified: true },
    { name: "National College of Ireland", domain: "nci.ie", isVerified: true },
    { name: "National College of Art and Design", domain: "ncad.ie", isVerified: true },
    { name: "Dún Laoghaire Institute of Art, Design and Technology", domain: "iadt.ie", isVerified: true },
    { name: "National University of Ireland, System", domain: "nui.ie", isVerified: true },
    { name: "Institute of Public Administration", domain: "ipa.ie", isVerified: true },
    { name: "Royal Irish Academy of Music", domain: "riam.ie", isVerified: true },
    { name: "St Patrick's Pontifical University", domain: "maynoothcollege.ie", isVerified: true },
    { name: "Marino Institute of Education", domain: "mie.ie", isVerified: true },
    { name: "Carlow College", domain: "carlowcollege.ie", isVerified: true },
    { name: "Royal College of Surgeons in Ireland", domain: "rcsi.ie", isVerified: true },
    { name: "Universiteti i Tiranës", domain: "unitir.edu.al", isVerified: true },
    { name: "Universiteti Politeknik i Tiranës", domain: "upt.al", isVerified: true },
    { name: "Universiteti Europian i Tiranës", domain: "eut.edu.al", isVerified: true },
    { name: "Universiteti Epoka", domain: "epoka.edu.al", isVerified: true },
    { name: "Universiteti Bujqësor i Tiranës", domain: null, isVerified: false },
    { name: "Universiteti i Vlorës, Ismail Qemali", domain: "univlora.edu.al", isVerified: true },
    { name: "Universiteti Aleksandër Moisiu, Durrës", domain: "uamd.edu.al", isVerified: true },
    { name: "Universiteti i Shkodrës Luigj Gurakuqi", domain: "unishk.edu.al", isVerified: true },
    { name: "Universiteti Fan S. Noli, Korçë", domain: null, isVerified: false },
    { name: "Universiteti Polis", domain: null, isVerified: false },
    { name: "Universiteti Katolik Zoja e Këshillit Të Mirë", domain: null, isVerified: false },
    { name: "Universiteti i New York-ut në Tiranë", domain: "nyu.edu.al", isVerified: true },
    { name: "Universiteti i Elbasanit Aleksandër Xhuvani", domain: "uel.edu.al", isVerified: true },
    { name: "Universiteti Marin Barleti", domain: "barleti.edu.al", isVerified: true },
    { name: "Kolegji Universitar Bedër", domain: "beder.edu.al", isVerified: true },
    { name: "Universiteti Albanian University", domain: "albanianuniversity.edu.al", isVerified: true },
    { name: "Universiteti i Mjekësisë, Tiranë", domain: "um.edu.al", isVerified: true },
    { name: "Universiteti Metropolitan Tirana", domain: "umt.edu.al", isVerified: true },
    { name: "Universiteti Mesdhetar i Shqipërisë", domain: "umsh.edu.al", isVerified: true },
    { name: "Kolegji Universitar Instituti Kanadez i Teknologjisë", domain: "cit.edu.al", isVerified: true },
    { name: "Universiteti i Arteve", domain: "uarts.edu.al", isVerified: true },
    { name: "Universiteti Eqrem Çabej, Gjirokastër", domain: "ueq.edu.al", isVerified: true },
    { name: "Akademia e Shkencave e Shqipërisë", domain: null, isVerified: false },
    { name: "Universiteti Luarasi", domain: "luarasi.edu.al", isVerified: true },
    { name: "Universiteti i Sporteve të Tiranës", domain: null, isVerified: false },
    { name: "Akademia e Filmit dhe Multimedias Marubi", domain: "afmm.edu.al", isVerified: true },
    { name: "Universiteti Aldent", domain: "aldent.edu.al", isVerified: true },
    { name: "Kolegji Universitar Logos", domain: "logos.edu.al", isVerified: true },
    { name: "Tirana Business University College", domain: "tbuc.edu.al", isVerified: true },
    { name: "Kolegji Universitar Wisdom", domain: "wisdom.edu.al", isVerified: true },
    { name: "Kolegji Universitar Qiriazi", domain: "qiriazi.edu.al", isVerified: true },
    { name: "Kolegji Universitar i Biznesit", domain: "buc.edu.al", isVerified: true },
    { name: "Akademia Ivodent", domain: "ivodent.edu.al", isVerified: true },
    { name: "Kolegji Universitar Pavarësia Vlorë", domain: "pavar.edu.al", isVerified: true },
    { name: "Kolegji Universitar Reald", domain: "reald.edu.al", isVerified: true },
]