import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Israel_universities = [

    // Israel

    { name: "Tel Aviv University", domain: "tau.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Hebrew University of Jerusalem", domain: "huji.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Weizmann Institute of Science", domain: "weizmann.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Technion - Israel Institute of Technology", domain: "technion.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Ben-Gurion University of the Negev", domain: "bgu.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "University of Haifa", domain: "haifa.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Bar-Ilan University", domain: "biu.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Reichman University", domain: "runi.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Ariel University", domain: "ariel.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Bezalel Academy of Arts and Design", domain: "bezalel.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Holon Institute of Technology", domain: "hit.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Jerusalem College of Technology", domain: "jct.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "The College of Management - Academic Studies", domain: "colman.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Ono Academic College", domain: "ono.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "The Academic College of Tel-Aviv-Yaffo", domain: "mta.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Shenkar College of Engineering and Design", domain: "shenkar.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Sapir College", domain: "sapir.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Ruppin Academic Center", domain: "ruppin.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Tel-Hai Academic College", domain: "telhai.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "ORT Braude College", domain: "braude.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Netanya Academic College", domain: "netanya.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Shamoon College of Engineering", domain: "sce.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Kinneret Academic College", domain: "kinneret.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Afeka Tel Aviv Academic College of Engineering", domain: "afeka.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Schechter Institute of Jewish Studies", domain: "schechter.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Western Galilee College", domain: "wgalil.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Max Stern Academic College of Emek Yezreel", domain: "yvc.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Azrieli College of Engineering Jerusalem", domain: "jce.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "College of Law and Business", domain: "clb.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Achva Academic College", domain: "achva.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Jerusalem Multidisciplinary College", domain: null, region: "Asia", country: "Israel", isVerified: false },
    { name: "The Jerusalem Academy of Music and Dance", domain: "jamd.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Zefat Academic College", domain: "zefat.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Ashkelon Academic College", domain: "aac.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "The Academic College of Law and Science", domain: null, region: "Asia", country: "Israel", isVerified: false },
    { name: "Shalem College", domain: "shalem.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Peres Academic Center", domain: "pac.ac.il", region: "Asia", country: "Israel", isVerified: true },
    { name: "Ramat Gan Academic College", domain: null, region: "Asia", country: "Israel", isVerified: false },
]