import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Italy_universities = [

    // Italy

    { name: "Alma Mater Studiorum Università di Bologna", domain: "unibo.it", isVerified: true },
    { name: "Università degli Studi di Padova", domain: "unipd.it", isVerified: true },
    { name: "Politecnico di Milano", domain: "polimi.it", isVerified: true },
    { name: "Sapienza Università di Roma", domain: "uniroma1.it", isVerified: true },
    { name: "Università degli Studi di Milano", domain: "unimi.it", isVerified: true },
    { name: "Università degli Studi di Torino", domain: "uniroma1.it", isVerified: false },
    { name: "Università degli Studi di Pisa", domain: "unipi.it", isVerified: true },
    { name: "Politecnico di Torino", domain: "polito.it", isVerified: true },
    { name: "Università degli Studi di Firenze", domain: "unifi.it", isVerified: true },
    { name: "Università degli Studi di Napoli Federico II", domain: "unina.it", isVerified: true },
    { name: "Università degli Studi di Trento", domain: "unitn.it", isVerified: true },
    { name: "Università Ca' Foscari di Venezia", domain: "unive.it", isVerified: true },
    { name: "Università degli Studi di Genova", domain: "unige.it", isVerified: true },
    { name: "Università degli Studi di Milano-Bicocca", domain: "bicocca.it", isVerified: true },
    { name: "Università degli Studi di Pavia", domain: "unipv.it", isVerified: true },
    { name: "Università degli Studi di Roma Tor Vergata", domain: "uniroma2.it", isVerified: true },
    { name: "Università Cattolica del Sacro Cuore", domain: "unicatt.it", isVerified: true },
    { name: "Università Commerciale Luigi Bocconi", domain: "unibocconi.it", isVerified: true },
    { name: "Università degli Studi di Palermo", domain: "unipa.it", isVerified: true },
    { name: "Università degli Studi di Parma", domain: "unipr.it", isVerified: true },
    { name: "Università degli Studi di Catania", domain: "unict.it", isVerified: true },
    { name: "Università degli Studi Roma Tre", domain: "uniroma3.it", isVerified: true },
    { name: "Università degli Studi di Modena e Reggio Emilia", domain: "unimore.it", isVerified: true },
    { name: "Università degli Studi di Trieste", domain: "units.it", isVerified: true },
    { name: "Università degli Studi di Bari Aldo Moro", domain: "uniba.it", isVerified: true },
    { name: "Università degli Studi di Verona", domain: "univr.it", isVerified: true },
    { name: "Università degli Studi di Siena", domain: "unisi.it", isVerified: true },
    { name: "Università degli Studi di Cagliari", domain: "unica.it", isVerified: true },
    { name: "Università degli Studi di Ferrara", domain: "unife.it", isVerified: true },
    { name: "Università degli Studi di Udine", domain: "uniud.it", isVerified: true },
    { name: "Università degli Studi di Salerno", domain: "unisa.it", isVerified: true },
    { name: "Libera Università Internazionale degli Studi Sociali Guido Carli", domain: "luiss.it", isVerified: true },
    { name: "Università degli Studi di Perugia", domain: "unipg.it", isVerified: true },
    { name: "Scuola Internazionale Superiore di Studi Avanzati", domain: "sissa.it", isVerified: true },
    { name: "Università del Salento", domain: "unisalento.it", isVerified: true },
    { name: "Università della Calabria", domain: "unical.it", isVerified: true },
    { name: "Scuola Normale Superiore", domain: "sns.it", isVerified: true },
    { name: "Libera Università di Bolzano", domain: "unibz.it", isVerified: true },
    { name: "Scuola Superiore di Studi Universitari e Perfezionamento Sant'Anna", domain: "santannapisa.it", isVerified: true },
    { name: "Università degli Studi di Bergamo", domain: "unibg.it", isVerified: true },
    { name: "Università degli Studi di Brescia", domain: "unibs.it", isVerified: true },
    { name: "Università degli Studi di Messina", domain: "unime.it", isVerified: true },
    { name: "Università Politecnica delle Marche", domain: "univpm.it", isVerified: true },
    { name: "Università degli Studi di Urbino Carlo Bo", domain: "uniurb.it", isVerified: true },
    { name: "Università degli Studi dell'Aquila", domain: "univaq.it", isVerified: true },
    { name: "Università degli Studi G. d'Annunzio Chieti-Pescara", domain: "unich.it", isVerified: true },
    { name: "Università degli Studi della Campania Luigi Vanvitelli", domain: "unicampania.it", isVerified: true },
    { name: "Università degli Studi del Piemonte Orientale", domain: "uniupo.it", isVerified: true },
    { name: "Università degli Studi dell'Insubria", domain: "uninsubria.it", isVerified: true },
    { name: "Università degli Studi di Macerata", domain: "unimc.it", isVerified: true },
    { name: "Università degli Studi di Sassari", domain: "uniss.it", isVerified: true },
    { name: "Università degli Studi di Camerino", domain: "unicam.it", isVerified: true },
    { name: "Università Iuav di Venezia", domain: "iuav.it", isVerified: true },
    { name: "Libera Università di Lingue e Comunicazione IULM", domain: "iulm.it", isVerified: true },
    { name: "Università degli Studi della Tuscia", domain: "unitus.it", isVerified: true },
    { name: "Politecnico di Bari", domain: "poliba.it", isVerified: true },
    { name: "LIUC Università Cattaneo", domain: "liuc.it", isVerified: true },
    { name: "Università degli Studi di Napoli \"L'Orientale\"", domain: "orientale.it", isVerified: true },
    { name: "Libera Università Maria SS. Assunta", domain: "lumsa.it", isVerified: true },
    { name: "Università degli Studi di Foggia", domain: "unifg.it", isVerified: true },
    { name: "Università degli Studi di Cassino e del Lazio Meridionale", domain: "unicas.it", isVerified: true },
    { name: "Università degli Studi del Molise", domain: "unimol.it", isVerified: true },
    { name: "Università degli Studi Mediterranea di Reggio Calabria", domain: "unirc.it", isVerified: true },
    { name: "Università degli Studi della Basilicata", domain: "unibas.it", isVerified: true },
    { name: "Università per Stranieri di Perugia", domain: "unistrapg.it", isVerified: true },
    { name: "Università per Stranieri di Siena", domain: "unistrasi.it", isVerified: true },
    { name: "Università degli Studi di Teramo", domain: "unite.it", isVerified: true },
    { name: "Scuola IMT Alti Studi Lucca", domain: "imtlucca.it", isVerified: true },
    { name: "Università degli Studi del Sannio di Benevento", domain: "unisannio.it", isVerified: true },
    { name: "Università degli Studi di Napoli Parthenope", domain: "uniparthenope.it", isVerified: true },
    { name: "Università Campus Bio-Medico di Roma", domain: "unicampus.it", isVerified: true },
    { name: "Università Vita-Salute San Raffaele", domain: "unisr.it", isVerified: true },
    { name: "Università degli Studi di Scienze Gastronomiche", domain: "unisg.it", isVerified: true },
    { name: "Università degli Studi Suor Orsola Benincasa", domain: "unisob.na.it", isVerified: true },
    { name: "Università degli Studi Magna Graecia di Catanzaro", domain: "unicz.it", isVerified: true },
    { name: "Università degli Studi Link", domain: "link-campus.it", isVerified: true },
    { name: "Università HUMANITAS di Milano", domain: "humanitas.it", isVerified: true },
    { name: "Università degli Studi di Enna Kore", domain: "unkore.it", isVerified: true },
    { name: "Università degli Studi Internazionali di Roma", domain: "unint.eu", isVerified: true },
    { name: "Università Europea di Roma", domain: "uer.it", isVerified: true },
    { name: "Istituto Universitario di Studi Superiori", domain: "iusspavia.it", isVerified: true },
    { name: "Università LUM Jean Monnet", domain: "lum.it", isVerified: true },
    { name: "Università UniCamillus", domain: "unicamillus.org", isVerified: true },
    { name: "Università della Valle d'Aosta", domain: "univda.it", isVerified: true },
    { name: "Università degli Studi di Roma Foro Italico", domain: "foroit.it", isVerified: true },
    { name: "Università per stranieri Dante Alighieri di Reggio Calabria", domain: "unirc.it", isVerified: true },

]