import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Japan_universities = [

    // Japan

    { name: "Advanced Institute of Industrial Technology", domain: "aiit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Bunkyo University", domain: "aichi-bunkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Gakuin University", domain: "aichi-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Gakusen University", domain: "aichi-gakusen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Institute of Technology", domain: "ait.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Medical University", domain: "aichi-med-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Mizuho College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Aichi Prefectural University", domain: "aichi-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Sangyo University", domain: "asu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Shukutoku University", domain: "shu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi Toho University", domain: "toho-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi University", domain: "aichi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi University of Education", domain: "aichi-edu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi University of Technology", domain: "aut.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aichi University of the Arts", domain: "aia.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aikoku Gakuen University", domain: "aikoku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aino University", domain: "aino.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Akita International University", domain: "aiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Akita Prefectural University", domain: "akita-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Akita University", domain: "akita-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Akita University of Art", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Akita University of Nursing and Welfare", domain: "anwl.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aomori Chuo Gakuin University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Aomori Public University", domain: "aomori-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aomori University", domain: "aomori-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Aomori University of Health and Welfare", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Aoyama Gakuin University", domain: "aoyama.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Asahi University", domain: "asahi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Asahikawa Medical University", domain: "asahikawa-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Asahikawa University", domain: "asahikawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ashikaga University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Ashiya University", domain: "ashiya-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Asia University", domain: "asia-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Atomi University", domain: "atomi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Azabu University", domain: "azabu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Baika Women's University", domain: "baika.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Baiko Gakuin University", domain: "baiko.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Beppu University", domain: "beppu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Biwako Seikei Sport College", domain: "bssc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Biwako-Gakuin University", domain: "biwako-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Bukkyo University", domain: "bukkyo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Bunka Fashion Graduate University", domain: "bfgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Bunka Gakuen University", domain: "bunka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Bunkyo Gakuin University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Bunkyo University", domain: "bunkyo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Bunri University of Hospitality", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Bunsei University of Art", domain: "bunsei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Business Breakthrough University", domain: "bbu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chiba Institute of Science", domain: "cis.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chiba Institute of Technology", domain: "cit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chiba Keizai University", domain: "cku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chiba Prefectural University of Health Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Chiba University", domain: "chiba-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chiba University of Commerce", domain: "cuc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chikushi Jogakuen University", domain: "cju.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chinzei Gakuin University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Chitose Institute of Science and Technology", domain: "cist.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chubu Gakuin University", domain: "cgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chubu University", domain: "chubu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chugoku Gakuen University", domain: "cg.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chukyo Gakuin University", domain: "cgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chukyo University", domain: "chukyo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chuo Gakuin University", domain: "cgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Chuo University", domain: "chuo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Cyber University", domain: "cyber.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Daido University", domain: "daido-it.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Daiichi Institute of Technology", domain: "daiichi-kosho.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Daiichi University of Pharmacy", domain: "daiichi-bph.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Daito Bunka University", domain: "daito.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Den-en Chofu University", domain: "denenchofu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Digital Hollywood University", domain: "dhw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Doho University", domain: "doho.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Dokkyo Medical University", domain: "dokkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Dokkyo University", domain: "dokkyo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Doshisha University", domain: "doshisha.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Doshisha Women's College of Liberal Arts", domain: "dwc.doshisha.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Edogawa University", domain: "edogawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ehime Prefectural University of Health Sciences", domain: "epu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ehime University", domain: "ehime-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Eikei University of Hiroshima", domain: "eikei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Elisabeth University of Music", domain: "eum.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ferris University", domain: "ferris.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fuji University", domain: "fuji-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fuji Women's University", domain: "fwu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fujita Health University", domain: "fujita-hu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukui Health Science University", domain: "fhsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukui Prefectural University", domain: "fpu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukui University of Technology", domain: "fukui-ut.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Dental College", domain: "fdc-net.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Institute of Technology", domain: "fit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka International University", domain: "fukuoka-iu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka International University of Health and Welfare", domain: "fukuoka-int-welfare.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Jo Gakuin Nursing University", domain: "fukuoka-nu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Jo Gakuin University", domain: "fukuoka-jogakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Nursing College", domain: "fnu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Prefectural University", domain: "fpu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka University", domain: "fukuoka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuoka Women's University", domain: "fwu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukushima College", domain: "f-coll.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukushima Medical University", domain: "fmu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukushima University", domain: "fukushima-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuyama City University", domain: "fcu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuyama Heisei University", domain: "heisei-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Fukuyama University", domain: "fukuyama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Future University Hakodate", domain: "fun.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gakushuin University", domain: "univ.gakushuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gakushuin Women's College", domain: "gwc.gakushuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu College of Nursing", domain: "gifu-cn.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu Kyoritsu University", domain: "gku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu Pharmaceutical University", domain: "gifu-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu Shotoku Gakuen University", domain: "shotoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu University", domain: "gifu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu University of Health Sciences", domain: "gifuhoken.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu University of Medical Science", domain: "u-gifu-ms.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gifu Women's University", domain: "gijodai.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Graduate Institute for Entrepreneurial Studies", domain: "jigyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Graduate School of Management, Globis University", domain: "globis.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gunma Paz University", domain: "paz.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gunma Prefectural College of Health Sciences", domain: "gchs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gunma Prefectural Women's University", domain: "gpwu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gunma University", domain: "gunma-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Gunma University of Health and Welfare", domain: "shoken-gakuen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hachinohe Gakuin University", domain: "hachinohe-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hachinohe Institute of Technology", domain: "hi-tech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hagoromo University of International Studies", domain: "hagoromo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hakodate University", domain: "hakodate-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hakuoh University", domain: "hakuoh.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hamamatsu Gakuin University", domain: "hgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hamamatsu University School of Medicine", domain: "hama-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hanazono University", domain: "hanazono.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hannan University", domain: "hannan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Health Science University", domain: "kenkoudai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Health Sciences University of Hokkaido", domain: "hoku-iryo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Heian Jogakuin University", domain: "heian.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Heisei College of Music", domain: "heisei-music.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Heisei International University", domain: "hiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Higashi Nippon International University", domain: "shk-ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Higashiosaka College", domain: "higashiosaka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hijiyama University", domain: "hijiyama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Himeji Dokkyo University", domain: "himeji-du.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Himeji University", domain: "koutoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hirosaki Gakuin University", domain: "hirogaku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hirosaki University", domain: "hirosaki-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hirosaki University of Health and Welfare", domain: "hirosakiuhw.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Bunka Gakuen University", domain: "hbg.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Bunkyo University", domain: "h-bunkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Bunkyo Women's University", domain: "h-bunkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima City University", domain: "hiroshima-cu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Institute of Technology", domain: "it-hiroshima.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima International University", domain: "hirokoku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Jogakuin University", domain: "hju.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Kokusai Gakuin University", domain: "hkg.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima Shudo University", domain: "shudo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima University", domain: "hiroshima-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hiroshima University of Economics", domain: "hue.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hitotsubashi University", domain: "hit-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkai School of Commerce", domain: "hokkai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkaido Bunkyo University", domain: "do-bunkyodai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkaido Chitose College of Rehabilitation", domain: "chitose-reha.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkaido Information University", domain: "do-johodai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkaido University", domain: "hokudai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkaido University of Education", domain: "hokkyodai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkaido University of Science", domain: "hus.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokkai-Gakuen University", domain: "hgu.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokuriku Gakuin University", domain: "hokurikugakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokuriku University", domain: "hokuriku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokusei Gakuen University", domain: "hokusei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokusho University", domain: "hokusho-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hokuyo University", domain: "hokuyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hosei University", domain: "hosei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hosen College of Childhood Education", domain: "hosen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hoshi University", domain: "hoshi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hyogo Medical University", domain: "hyogo-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hyogo University", domain: "hyogo-dai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Hyogo University of Teacher Education", domain: "office.hyogo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ibaraki Christian University", domain: "icc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ibaraki Prefectural University of Health Sciences", domain: "ipu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ibaraki University", domain: "ibaraki.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ichinomiya Kenshin College", domain: "ikc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ikuei University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Ikueikan University", domain: "ikueikan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Institute of Advanced Media Arts and Sciences", domain: "iamas.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Institute of Information Security", domain: "iisec.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Institute of Technologists", domain: "iot.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "International Budo University", domain: "budo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "International Christian University", domain: "icu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "International College for Postgraduate Buddhist Studies", domain: "icabs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "International Pacific University", domain: "ipu-japan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "International University of Health and Welfare", domain: "iuhw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "International University of Japan", domain: "iu-japan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Iryo Sosei University", domain: "iryososei-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ishikawa Prefectural Nursing University", domain: "ishikawa-nu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ishikawa Prefectural University", domain: "ishikawa-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ishinomaki Senshu University", domain: "isenshu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Iwate Medical University", domain: "iwate-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Iwate Prefectural University", domain: "iwate-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Iwate University", domain: "iwate-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Iwate University of Health and Medical Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "J. F. Oberlin University", domain: "oberlin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan Advanced Institute of Science and Technology", domain: "jaist.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan College of Social Work", domain: "jcsw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan Health Care College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Japan Institute of the Moving Image", domain: "nihoneiga.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan International University", domain: "jiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan Lutheran College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Japan University of Economics", domain: "joe.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan University of Health Sciences", domain: "juhs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan Women's College of Physical Education", domain: "jwpe.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japan Women's University", domain: "jwu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japanese Red Cross Akita College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Japanese Red Cross College of Nursing", domain: "jrc-cn.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Japanese Red Cross Hiroshima College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Japanese Red Cross Hokkaido College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Japanese Red Cross Toyota College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Jichi Medical University", domain: "jichi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Jikei University of Health Care Sciences", domain: "jikei-hsc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Jin-ai University", domain: "jin-ai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Jissen Women's University", domain: "jissen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Jobu University", domain: "jobu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Joetsu University of Education", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Josai International University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Josai University", domain: "josai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Joshibi University of Art and Design", domain: "joshibi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Jumonji University", domain: "jumonji-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Junshin Gakuen University", domain: "junshin-fukuoka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Juntendo University", domain: "juntendo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kaetsu University", domain: "kaetsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kagawa Nutrition University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kagawa Prefectural University of Health Sciences", domain: "kpuhs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kagawa University", domain: "kagawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kagoshima Immaculate Heart University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kagoshima University", domain: "kagoshima-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kaichi International University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kamakura Women's University", domain: "kamakura-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kameda University of Health Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kanagawa Dental University", domain: "kdu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanagawa Institute of Technology", domain: "kait.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanagawa University", domain: "kanagawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanagawa University of Human Services", domain: "kuhs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanazawa College of Art", domain: "u-jca.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanazawa Gakuin University", domain: "kgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanazawa Institute of Technology", domain: "kanazawa-it.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanazawa Medical University", domain: "kmu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanazawa Seiryo University", domain: "seiryo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanazawa University", domain: "kanazawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanda University of International Studies", domain: "kuins.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai Gaidai University", domain: "kansai-gaidai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai Medical University", domain: "kmu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai University", domain: "kansai-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai University of Health Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kansai University of International Studies", domain: "kandai-kokusai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai University of Nursing and Health Sciences", domain: "kusw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai University of Social Welfare", domain: "kusw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kansai University of Welfare Sciences", domain: "kuws.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanto Gakuen University", domain: "kanto-gakuen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kanto Gakuin University", domain: "kanto-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kawamura Gakuen Woman's University", domain: "kgwu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kawasaki Medical School", domain: "med.kawasaki-m.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kawasaki University of Medical Welfare", domain: "kumaw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Keiai University", domain: "keiai-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Keio University", domain: "keio.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Keisen University", domain: "keisen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Keiwa College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kibi International University", domain: "kibidai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kindai University", domain: "kindai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kinjo Gakuin University", domain: "kinjo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kinjo University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kio University", domain: "kio.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kiryu University", domain: "kiryu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kitami Institute of Technology", domain: "kitami-it.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kitasato University", domain: "kitasato-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe City College of Nursing", domain: "kobe-ccn.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe City University of Foreign Studies", domain: "kcufs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe College", domain: "kobecollege.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Design University", domain: "kobe-du.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Gakuin University", domain: "kobegakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Institute of Computing", domain: "kic.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe International University", domain: "kobe-iu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Kaisei College", domain: "kobe-kaisei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Pharmaceutical University", domain: "kobepharma-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Shinwa Women's University", domain: "kobe-shinwa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Shoin Women's University", domain: "shoin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe Tokiwa University", domain: "kobe-tokiwa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe University", domain: "kobe-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kobe University of Future Health Sciences", domain: "uniRank.org", region: "Asia", country: "Japan", isVerified: false },
    { name: "Kobe Women's University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kochi Gakuen University", domain: "kochi-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kochi University", domain: "kochi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kochi University of Technology", domain: "kochi-tech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kogakkan University", domain: "kogakkan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kogakuin University", domain: "kogakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kokugakuin University", domain: "kokugakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kokushikan University", domain: "kokushikan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Komatsu University", domain: "komatsu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Komazawa University", domain: "komazawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Komazawa Women's University", domain: "komajo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Konan University", domain: "konan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Konan Women's University", domain: "konan-wu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Koshien University", domain: "koshien.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Koyasan University", domain: "koyasan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kumamoto Gakuen University", domain: "kumagaku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kumamoto Health Science University", domain: "kumamoto-hsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kumamoto University", domain: "kumamoto-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kunitachi College of Music", domain: "kcm.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kurashiki Sakuyo University", domain: "ksuc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kurashiki University of Science and the Arts", domain: "kusa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kurume Institute of Technology", domain: "kurume-it.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kurume University", domain: "kurume-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kushiro Public University of Economics", domain: "kpu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kwansei Gakuin University", domain: "kwansei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kwassui Women's University", domain: "kwassui.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoai Gakuen University", domain: "kyoai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoei University", domain: "kyoei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyorin University", domain: "kyorin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoritsu Women's University", domain: "kyoritsu-wu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Arts and Crafts University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kyoto Bunkyo University", domain: "kyoto-bunkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto City University of Arts", domain: "kcua.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto College of Graduate Studies for Informatics", domain: "kcg.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto College of Medical Science", domain: "kcmed.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto College of Nursing", domain: "kyoto-nurs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Institute of Technology", domain: "kit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Kacho University", domain: "kacho.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Koka Women's University", domain: "koka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Notre Dame University", domain: "notredame.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Pharmaceutical University", domain: "kyoto-phu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Prefectural University", domain: "kpu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Prefectural University of Medicine", domain: "kpu-m.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Saga University of Arts", domain: "kyoto-saga.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Sangyo University", domain: "kyoto-su.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Seika University", domain: "seika.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Tachibana University", domain: "tachibana-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto University", domain: "kyoto-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto University of Advanced Science", domain: "kuas.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto University of Education", domain: "kyokyo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto University of Foreign Studies", domain: "kufs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto University of the Arts", domain: "kyoto-geidai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyoto Women's University", domain: "kyoto-wu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu Dental University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kyushu Institute of Information Sciences", domain: "qiis.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu Institute of Technology", domain: "kyutech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu International University", domain: "kiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu Kyoritsu University", domain: "kyoritsu-k.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu Lutheran College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kyushu Nutrition Welfare University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kyushu Sangyo University", domain: "ksu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu University", domain: "kyushu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Kyushu University of Health and Welfare", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kyushu University of Nursing and Social Welfare", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Kyushu Women's University", domain: "kuw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "LEC Accounting Graduate School", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Maebashi Institute of Technology", domain: "maebit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Matsumoto College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Matsumoto Dental University", domain: "mdu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Matsumoto University", domain: "matsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Matsuyama Shinonome College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Matsuyama University", domain: "matsuyama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meiji Gakuin University", domain: "meijigakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meiji Pharmaceutical University", domain: "my-pharm.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meiji University", domain: "meiji.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meiji University of Integrative Medicine", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Meijo University", domain: "meijo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meikai University", domain: "meikai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meio University", domain: "meio-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Meisei University", domain: "meisei-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Mejiro University", domain: "mejiro-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Mie Prefectural College of Nursing", domain: "mcn.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Mie University", domain: "mie-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Mimasaka University", domain: "mimasaka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Minami Kyushu University", domain: "minamikyushu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Minobusan University", domain: "minobusan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Miyagi Gakuin Women’s University", domain: "miyagi-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Miyagi University", domain: "miyagi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Miyagi University of Education", domain: "mue.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Miyazaki International University", domain: "miu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Miyazaki Municipal University", domain: "miyazaki-mu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Miyazaki Prefectural Nursing University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Miyazaki Sangyo-keiei University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Momoyama Gakuin University", domain: "mgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Momoyama Gakuin University", domain: "mgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Morinomiya University of Medical Sciences", domain: "morinomiya-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Morioka University", domain: "morioka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Mukogawa Women’s University", domain: "mukogawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Muroran Institute of Technology", domain: "muroran-it.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Musashi University", domain: "musashi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Musashino Academia Musicae", domain: "musashino-music.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Musashino Art University", domain: "musabi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Musashino Gakuin University", domain: "musashino-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Musashino University", domain: "musashino-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagahama Institute of Bio-Science and Technology", domain: "nagahama-i-bio.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagano College of Nursing", domain: "nagano-nursing.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagano University", domain: "nagano-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagano University of Health and Medicine", domain: "nuhm.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagaoka Institute of Design", domain: "nid.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagaoka Sutoku University", domain: "nagaoka-su.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagaoka University", domain: "nagaoka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagaoka University of Technology", domain: "nagaoka‐tech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagasaki Institute of Applied Science", domain: "nias.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagasaki International University", domain: "nagasaki‐iu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagasaki Junshin Catholic University", domain: "nagasaki‐junshin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagasaki University", domain: "nagasaki‐u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagasaki University of Foreign Studies", domain: "nufs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya Bunri University", domain: "bunri‐u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya City University", domain: "nagoya‐cu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya College of Music", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Nagoya Gakuin University", domain: "ngu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya Institute of Technology", domain: "nitech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya Ryujo Women's University", domain: "nagoya‐ryujo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya Sangyo University", domain: "nsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya University", domain: "nagoya‐u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya University of Arts and Sciences", domain: "nua.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya University of Commerce and Business", domain: "nucba.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya University of Economics", domain: "nue.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya University of Foreign Studies", domain: "noufs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya University of the Arts", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Nagoya Women's University", domain: "nagoya‐wu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nagoya Zokei University of Art & Design", domain: "zokei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nakamura Gakuen University", domain: "nakamura-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nanzan University", domain: "nanzan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nara Institute of Science and Technology", domain: "naist.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nara Medical University", domain: "naramed-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nara Prefectural University", domain: "nara-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nara University", domain: "nara-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nara University of Education", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Nara Women's University", domain: "narawu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Naragakuen University", domain: "naragakuen-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Naruto University of Education", domain: "naruto-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "National College of Nursing, Japan", domain: "ncn.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "National Fisheries University", domain: "nfu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "National Graduate Institute for Policy Studies", domain: "grips.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "National Institute of Fitness and Sports in Kanoya", domain: "nifs-k.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nayoro City University", domain: "nayoro-cu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nihon Bunka University", domain: "nbu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nihon Fukushi University", domain: "fukushi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nihon Institute of Medical Science", domain: "nims.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nihon Pharmaceutical University", domain: "nihonyaku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nihon University", domain: "nihon-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nihon Wellness Sports University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Niigata Agro-Food University", domain: "niigataafu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Niigata College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Niigata Institute of Technology", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Niigata Sangyo University", domain: "nits.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Niigata Seiryo University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Niigata University", domain: "niigata-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Niigata University of Health and Welfare", domain: "nuhw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Niigata University of International and Information Studies", domain: "niis.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Niigata University of Management", domain: "num.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Niigata University of Pharmacy and Applied Life Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Niigata University of Rehabilitation", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Niimi University", domain: "niimi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nippon Bunri University", domain: "nipponbunri-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nippon Institute of Technology", domain: "nit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nippon Medical School", domain: "nms.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nippon Sport Science University", domain: "nssu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nippon Veterinary and Life Science University", domain: "nvlu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nishikyushu University", domain: "ns-kyushu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nishinippon Institute of Technology", domain: "nishitech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Nishogakusha University", domain: "nishogakusha-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "North Asia University", domain: "northasia-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Notre Dame Seishin University", domain: "seishin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Obihiro University of Agriculture and Veterinary Medicine", domain: "obihiro.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ochanomizu University", domain: "ocha.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ohkagakuen University", domain: "ohkagakuen-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ohu University", domain: "ohu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Oita University", domain: "oita-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Oita University of Nursing and Health Sciences", domain: "ounhs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okayama Gakuin University", domain: "okayama-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okayama Prefectural University", domain: "okayama-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okayama Shoka University", domain: "oshu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okayama University", domain: "okayama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okayama University of Science", domain: "ous.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okazaki Women's University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Okinawa Christian University", domain: "ocu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okinawa Institute of Science and Technology Graduate University", domain: "oist.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okinawa International University", domain: "oiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Okinawa Prefectural College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Okinawa Prefectural University of Arts", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Okinawa University", domain: "okinawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Onomichi City University", domain: "onomichi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Aoyama University", domain: "osaka-aoyama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Butsuryo University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Osaka College of Music", domain: "daion.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Dental University", domain: "osaka-dent.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Electro-Communication University", domain: "oecu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Gakuin University", domain: "ogu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Health Science University", domain: "osaka-hs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Institute of Technology", domain: "oit.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka International University", domain: "osaka-iu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Jogakuin University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Osaka Kawasaki Rehabilitation University", domain: "okrw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Kyoiku University", domain: "okiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Medical and Pharmaceutical University", domain: "omp-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Metropolitan University", domain: "omu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Ohtani University", domain: "osaka-ohtani.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Sangyo University", domain: "osaka-sandai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Seikei University", domain: "osaka-seikei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Shoin Women's University", domain: "osaka-shoin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka Tokiwakai University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Osaka University", domain: "osaka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka University of Arts", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Osaka University of Commerce", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Osaka University of Comprehensive Children Education", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Osaka University of Economics", domain: "osaka-ue.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka University of Economics and Law", domain: "osaka-econ.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka University of Health and Sport Sciences", domain: "osaka-hs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka University of Human Sciences", domain: "osaka-hum.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Osaka University of Tourism", domain: "osaka-tour.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Otani University", domain: "otani.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Otaru University of Commerce", domain: "uot.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Otemae University", domain: "otemae.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Otemon Gakuin University", domain: "otemon.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Otsuma Women's University", domain: "otsuma.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Polytechnic University", domain: "polytech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Prefectural University of Hiroshima", domain: "pu-hiroshima.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Prefectural University of Kumamoto", domain: "pu-kumamoto.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Rakuno Gakuen University", domain: "rakuno.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Reitaku University", domain: "reitaku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Rikkyo University", domain: "rikkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Rissho University", domain: "risho.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ritsumeikan Asia Pacific University", domain: "apu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ritsumeikan University", domain: "ritsumei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ryukoku University", domain: "ryukoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ryutsu Keizai University", domain: "rku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saga University", domain: "saga-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sagami Women's University", domain: "sagami-wu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saitama Gakuen University", domain: "saitama-gakuen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saitama Institute of Technology", domain: "sut.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saitama Medical University", domain: "saitama-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saitama Prefectural University", domain: "s-pu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saitama University", domain: "saitama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saku University", domain: "sakudai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sakushin Gakuin University", domain: "sakushin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Saniku Gakuin College", domain: "saniku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sanjo City University", domain: "sanjo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sanno University", domain: "sanno.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sanyo Gakuen University", domain: "sanyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sanyo-onoda City University", domain: "sanyo-onoda-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo City University", domain: "sapporo-cu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo Gakuin University", domain: "sapporo-gakuin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo International University", domain: "siu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo Medical University", domain: "sapporo-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo Otani University", domain: "sapporo-otani.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo University", domain: "sapporo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sapporo University of Health Sciences", domain: "suhs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "SBC Tokyo Medical University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Seian University of Art and Design", domain: "seian.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seigakuin University", domain: "seigakuin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seijo University", domain: "seijo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seijoh University", domain: "seijoh-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seikei University", domain: "seikei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seinan Gakuin University", domain: "seinan-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seinan Jo Gakuin University", domain: "seinan-jogakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seirei Christopher University", domain: "seirei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seisa Dohto University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Seisa University", domain: "seisa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seisen Jogakuin College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Seisen University", domain: "seisen-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seitoku University", domain: "seitoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Seiwa University", domain: "seiwa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sendai Shirayuri Women's College", domain: "sendai-shirayuri.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sendai University", domain: "sendai-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Senri Kinran University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Senshu University", domain: "senshu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Senzoku Gakuen College of Music", domain: "senzoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Setsunan University", domain: "setsunan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shibata Gakuen University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Shibaura Institute of Technology", domain: "shibaura-it.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shiga University", domain: "shiga-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shiga University of Medical Science", domain: "shiga-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shigakkan University", domain: "shigakkan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shigakukan University", domain: "shigakukan.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shijonawate Gakuen University", domain: "shijonawate-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shikoku Gakuin University", domain: "sg-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shikoku University", domain: "shikoku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shimane University", domain: "shimane-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shimonoseki City University", domain: "shimonoseki-cu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shinshu University", domain: "shinshu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shiraume Gakuen University", domain: "shiraume.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shirayuri University", domain: "shirayuri.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shiseikan University", domain: "shiseikan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shitennoji University", domain: "shitennoji.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shizuoka Eiwa Gakuin University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Shizuoka Graduate University of Public Health", domain: "guph.shizuoka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shizuoka Institute of Science and Technology", domain: "sits.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shizuoka Sangyo University", domain: "ssu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shizuoka University", domain: "u-shizuoka-ken.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shizuoka University of Art and Culture", domain: "suac.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shizuoka University of Welfare", domain: "suw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shobi University", domain: "shobi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shoin University", domain: "shoin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shokei Gakuin University", domain: "shokei-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shokei University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Shonan Institute of Technology", domain: "sots.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shonan Kamakura University of Medical Sciences", domain: "skums.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shonan University of Medical Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Showa Pharmaceutical University", domain: "spu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Showa University", domain: "showa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },                        
    { name: "Showa University of Music", domain: "sound.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Showa Women's University", domain: "swu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shubun University", domain: "shubun.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shuchiin University", domain: "shuchiin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shujitsu University", domain: "shujitsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shukutoku University", domain: "shukutoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shumei University", domain: "shumei-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Shunan University", domain: "shunan-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Soai University", domain: "soai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sojo University", domain: "sojo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Soka University", domain: "soka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sonoda Women's University", domain: "sonodaw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sophia University", domain: "sophia.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "St Catherine University", domain: "stcatherine-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "St. Luke's International University", domain: "universityofstluke.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "St. Marianna University School of Medicine", domain: "marianna-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "St. Mary's College", domain: "st-mary.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Sugino Fashion College", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Sugiyama Jogakuen University", domain: "sugiyama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Surugadai University", domain: "surugadai-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Suwa University of Science", domain: "susu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Suzuka University", domain: "suzuka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Suzuka University of Medical Science", domain: "sums.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Taisei Gakuin University", domain: "taisei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Taisho University", domain: "taisho.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takachiho University", domain: "takachiho-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takamatsu University", domain: "takamatsu-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takaoka University of Law", domain: "tulaw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takarazuka University", domain: "takarazuka-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takarazuka University of Medical and Health Care", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Takasaki City University of Economics", domain: "tcue.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takasaki University of Commerce", domain: "tuc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takasaki University of Health and Welfare", domain: "tuhw.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Takushoku University", domain: "takushoku-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tama Art University", domain: "tamabi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tama University", domain: "tama.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tamagawa University", domain: "tamagawa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Teikyo Heisei University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Teikyo University", domain: "teikyo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Teikyo University of Science", domain: "tus.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tenri University", domain: "tenri-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tenshi College", domain: "tenshi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tezukayama Gakuin University", domain: "tgu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tezukayama University", domain: "tezukayama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The Graduate School for the Creation of New Photonics Industries", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "The Graduate University for Advanced Studies, SOKENDAI", domain: "soken.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The International University of Kagoshima", domain: "iuk.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The Japanese Red Cross Kyushu International College of Nursing", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "The Jikei University School of Medicine", domain: "jikei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The Nippon Dental University", domain: "ndu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Aizu", domain: "u-aizu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Electro-Communications", domain: "uec.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Fukuchiyama", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "The University of Kitakyushu", domain: "u-kita.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Nagano", domain: "u-nagano.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Shiga Prefecture", domain: "usp.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Shimane", domain: "u-shimane.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "The University of Tokyo", domain: "u-tokyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toho College of Music", domain: "toho-music.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toho Gakuen School of Music", domain: "tohogakuen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toho University", domain: "toho-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Bunka Gakuen University", domain: "tohoku-bunka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Bunkyo College", domain: "tohoku-bunkyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Fukushi University", domain: "tohoku-fukushi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Gakuin University", domain: "tohoku-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Institute of Technology", domain: "tohtech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Medical and Pharmaceutical University", domain: "tohoku-mpu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku Seikatsu Bunka University", domain: "tohoku-seikatsu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku University", domain: "tohoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku University of Art and Design", domain: "tuad.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohoku University of Community Service and Science", domain: "tuc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tohto University", domain: "tohto-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toin University of Yokohama", domain: "yokohama-toin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokai Gakuen University", domain: "tokai-gakuen.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokai Gakuin University", domain: "tokai-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokai University", domain: "tokai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokiwa University", domain: "tokiwa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokoha University", domain: "tokoha-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokushima Bunri University", domain: "bunri-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokushima University", domain: "tokushima-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Ariake University of Medical and Health Sciences", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tokyo Christian University", domain: "tci.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo City University", domain: "tcu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo College of Music", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tokyo Denki University", domain: "tdu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Dental College", domain: "tdc.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Fuji University", domain: "tfu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Future University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tokyo Gakugei University", domain: "u-gakugei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Healthcare University", domain: "thu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Institute of Technology", domain: "titech.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo International University", domain: "tiu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Junshin University", domain: "junshin-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Kasei Gakuin University", domain: "kasei-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Kasei University", domain: "kasei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Keizai University", domain: "tku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Medical and Dental University", domain: "tokyo-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Medical University", domain: "tmu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Metropolitan University", domain: "tmu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Polytechnic University", domain: "tpu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Seiei College", domain: "seiei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Seitoku University", domain: "seitoku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Union Theological Seminary", domain: "tuts.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Agriculture", domain: "nodai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Agriculture and Technology", domain: "tuat.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Foreign Studies", domain: "tufs.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Information Sciences", domain: "tuis.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Marine Science and Technology", domain: "kaiyodai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Pharmacy and Life Sciences", domain: "toyaku.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Science", domain: "tus.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of Social Welfare", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tokyo University of Technology", domain: "tut.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo University of the Arts", domain: "geidai.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Woman's Christian University", domain: "twcu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Women's College of Physical Education", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tokyo Women's Medical University", domain: "twmu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tokyo Zokei University", domain: "zokei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tottori College of Nursing", domain: "tcn.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tottori University", domain: "tottori-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tottori University of Environmental Studies", domain: "tues.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyama Prefectural University", domain: "pu-toyama.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyama University of International Studies", domain: "tuins.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyo Eiwa University", domain: "toyoeiwa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyo Gakuen University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Toyo University", domain: "toyo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyohashi Sozo University", domain: "tsut.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyohashi University of Technology", domain: "tut.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Toyota Technological Institute", domain: "toyota-ti.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tsuda University", domain: "tsuda.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tsukuba International University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tsukuba University of Technology", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Tsuru University", domain: "tsuru.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tsuruga Nursing University", domain: "tsuruga-nu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Tsurumi University", domain: "tsurumi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ube Frontier University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Uekusa Gakuen University", domain: "uekusa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Ueno Gakuen University", domain: "ueno-gakuin.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of East Asia", domain: "uwa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Fukui", domain: "u-fukui.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Human Arts and Sciences", domain: "uhas.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Human Environments", domain: "uhe.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Hyogo", domain: "u-hyogo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Kochi", domain: "kochi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Marketing and Distribution Sciences", domain: "umds.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Miyazaki", domain: "miyazaki-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Nagasaki", domain: "unagasaki.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Niigata Prefecture", domain: "unii.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Occupational and Environmental Health, Japan", domain: "uoeh-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Shizuoka", domain: "u-shizuoka.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Teacher Education Fukuoka", domain: "fukuoka-edu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of the Ryukyus", domain: "u-ryukyus.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of the Sacred Heart, Tokyo", domain: "sacred-heart.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Toyama", domain: "u-toyama.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Tsukuba", domain: "tsukuba.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "University of Yamanashi", domain: "yamanashi.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Urawa University", domain: "urawa.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Utsunomiya Kyowa University", domain: "ukyowa-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Utsunomiya University", domain: "utsunomiya-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Wakayama Medical University", domain: "wakayama-med.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Wakayama University", domain: "wakayama-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Wako University", domain: "wako.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Waseda University", domain: "waseda.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Wayo Women’s University", domain: "wayo.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamagata Prefectural University of Health Sciences", domain: "ypu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamagata Prefectural Yonezawa University of Nutrition Sciences", domain: "u.yone.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamagata University", domain: "yamagata-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamaguchi University", domain: "yamaguchi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamanashi Eiwa College", domain: "yec.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamanashi Gakuin University", domain: "ygu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yamanashi Prefectural University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Yamato University", domain: "yamato-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yashima Gakuen University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Yasuda Women's University", domain: "yasuda-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yokkaichi Nursing and Medical Care University", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Yokkaichi University", domain: "yokkaichi-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yokohama City University", domain: "yokohama-cu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yokohama College of Commerce", domain: "yokohama-sogo-u.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yokohama National University", domain: "ynu.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yokohama Soei University", domain: "soei.ac.jp", region: "Asia", country: "Japan", isVerified: true },
    { name: "Yokohama University of Art and Design", domain: null, region: "Asia", country: "Japan", isVerified: false },
    { name: "Yokohama University of Pharmacy", domain: null, region: "Asia", country: "Japan", isVerified: false },    

]