import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Kazakhstan_universities = [

    // Kazakhstan

    { name: "East-Kazakhstan State Technical University", domain: "ektu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Nazarbayev University", domain: "nu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Al-Farabi Kazakh National University", domain: "kaznu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "L.N. Gumilyov Eurasian National University", domain: "enu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Satbayev University", domain: "satbayev.university", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Abylkas Saginov Karaganda Technical University", domain: "kstu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National Pedagogical University", domain: "kaznpu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "E.A. Buketov University of Karaganda", domain: "buketov.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Ahmet Yesevi Üniversitesi", domain: "ayu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Semipalatinsk State University", domain: "shakarim.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "S. Toraighyrov Pavlodar State University", domain: "tou.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "KIMEP University", domain: "kimep.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Suleyman Demirel University", domain: "sdu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh-British Technical University", domain: "kbtu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Narxoz University", domain: "narxoz.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Auezov South Kazakhstan State University", domain: "auezov.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Saken Seifullin Kazakh Agrotechnical University", domain: "kazatu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "South Kazakhstan Medical Academy", domain: "skma.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "West Kazakhstan State University", domain: "wku.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Maqsut Narikbayev University", domain: "mnu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "International IT University", domain: "iitu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "East-Kazakhstan State University", domain: "vku.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National Agricultural University", domain: "kaznaru.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National Medical University", domain: "kaznmu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Manash Kozybayev North Kazakhstan University", domain: "ku.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Academy of Public Administration under the President of Kazakhstan", domain: "apa.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Almaty University of Power Engineering and Telecommunications", domain: "aues.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh Ablai Khan University of International Relations and World Languages", domain: "ablaikhan.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "M. Kh. Dulati Taraz State University", domain: "dulaty.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Almaty Management University", domain: "almau.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Karaganda Medical University", domain: "qmu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "West Kazakhstan Agro-Technical University", domain: "wkau.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kostanay State University", domain: "ksu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National Women's Teacher Training University", domain: "qyzpu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Astana Medical University", domain: "amu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Turan University", domain: "turan.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Almaty University of Humanities and Economics", domain: "ageu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Caspian State University of Technologies and Engineering", domain: "yu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Aktobe Regional University named after K. Zhubanov", domain: "zhubanov.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kokshetau University named after Sh.Ualikhanov", domain: "shokan.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Semey Medical University", domain: "smu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Almaty Technological University", domain: "atu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Deutsch-Kasachische Universität", domain: "dku.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Innovative University of Eurasia", domain: "ineu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "University of International Business", domain: "uib.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kokshetau University named after A. Myrzakhmetov", domain: "kuam.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Pavlodar State Pedagogical University", domain: "ppu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Caspian University", domain: "cu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Atyrau State University", domain: "asu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Karaganda University of Economics", domain: "keu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Esil University", domain: "esil.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh Academy of Sport and Tourism", domain: "kazast.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Rudny Industrial Institute", domain: "rii.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "West Kazakhstan Marat Ospanov Medical University", domain: "zkmu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Zhetysu State University", domain: "zhetysu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "International University of Engineering and Technology", domain: "metu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh-American Free University", domain: "kafu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "South Kazakhstan State Pedagogical University", domain: "okmpu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Bolashaq Academy", domain: "bolashaq.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National Academy of Arts", domain: "kaznai.kz", region: "Asia", country: "Kazakhstan", isVerified: true },       
    { name: "Turan-Astana University", domain: "tau-edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Eurasian Institute for the Humanities", domain: "egi.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kyzylorda State University", domain: "korkyt.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kostanay Engineering-Pedagogical University", domain: "kineu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National Conservatory", domain: "conservatoire.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakhstan-Russian Medical University", domain: "krmu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Karaganda State Industrial University", domain: "kgiu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "University of Foreign Languages and Business Career", domain: "ydu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh University of Technology and Business", domain: "kaztbu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh National University of Arts", domain: "kaznui.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Eurasian Technological University", domain: "etu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Almaty Transport College of KazATK named after M. Tynyshpayev", domain: "alt.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh-American University", domain: "kau.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Alikhan Bokeikhan University", domain: "abu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh-Russian International University", domain: "kriu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Q University", domain: "q-university.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Zhezkazgan University", domain: "zhezu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Baishev University", domain: "bu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakhstan School of Public Health", domain: "ksph.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Taraz Innovative-Humanitarian University", domain: "tigu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "L.B. Goncharov Kazakh Road Academy", domain: "kazadi.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kostanay Social-Technical University", domain: "kosstu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "International Transport and Humanitarian University", domain: "mtgu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "University \"Miras\"", domain: "miras.edu.kz", isVerified: true },
    { name: "Eurasian Academy of Law after D.A. Kunaev", domain: "vuzkunaeva.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "University of Innovation and Technology of Western Kazakhstan", domain: "wkitu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Shymkent University", domain: "univershu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Central Kazakhstan Academy", domain: "c-k-a.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Atyrau University of Oil and Gas", domain: "aogu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakhstan Engineering and Pedagogical University of Friendship of Peoples", domain: "udn.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Humanitarian-Technical Academy", domain: "gta.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Bolashak University", domain: "bolashak-edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Altynsarin Institute", domain: "api.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Syrdariya University", domain: "sirdariya.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Kazakh Leading Academy of Architecture and Civil Engineering", domain: "kazgasa.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Regional Social and Innovation University", domain: "riu.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "SILKWAY International University", domain: "swiu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "KazAtiso Academy", domain: "kazatiso.edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Atyrau Institute of Engineering and Humanities", domain: "aigi.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "Financial Academy", domain: "ecmf.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "International Humanitarian Technical University", domain: "hgtu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
    { name: "South-Kazakhstan Humanitarian Institute", domain: "msi-edu.kz", region: "Asia", country: "Kazakhstan", isVerified: true },
]