import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Kenya_universities = [

    // Kenya

    { name: "University of Nairobi", domain: "uonbi.ac.ke", isVerified: true },
    { name: "Kenyatta University", domain: "ku.ac.ke", isVerified: true },
    { name: "Strathmore University", domain: "strathmore.ac.ke", isVerified: true },
    { name: "Jomo Kenyatta University of Agriculture and Technology", domain: "jkuat.ac.ke", isVerified: true },
    { name: "United States International University Africa", domain: "usiu.ac.ke", isVerified: true },
    { name: "Mount Kenya University", domain: "mku.ac.ke", isVerified: true },
    { name: "Egerton University", domain: "egerton.ac.ke", isVerified: true },
    { name: "Moi University", domain: "mu.ac.ke", isVerified: true },
    { name: "Kenya Methodist University", domain: "kmu.ac.ke", isVerified: true },
    { name: "KCA University", domain: "kca.ac.ke", isVerified: true },
    { name: "Technical University of Kenya", domain: "tukenya.ac.ke", isVerified: true },
    { name: "The Catholic University of Eastern Africa", domain: "cuea.edu", isVerified: true },
    { name: "Maseno University", domain: "maseno.ac.ke", isVerified: true },
    { name: "University of Embu", domain: "embuuni.ac.ke", isVerified: true },
    { name: "Murang'a University of Technology", domain: "mutu.ac.ke", isVerified: true },
    { name: "Daystar University", domain: "daystar.ac.ke", isVerified: true },
    { name: "Pwani University", domain: "pu.ac.ke", isVerified: true },
    { name: "Dedan Kimathi University of Technology", domain: "dkut.ac.ke", isVerified: true },
    { name: "Kabarak University", domain: "kabarak.ac.ke", isVerified: true },
    { name: "Chuka University", domain: "chuka.ac.ke", isVerified: true },  
    { name: "Tangaza University", domain: "tangaza.ac.ke", isVerified: true },
    { name: "Masinde Muliro University of Science and Technology", domain: "mmust.ac.ke", isVerified: true },
    { name: "Zetech University", domain: "zetech.ac.ke", isVerified: true },
    { name: "Meru University of Science and Technology", domain: "must.ac.ke", isVerified: true },
    { name: "South Eastern Kenya University", domain: "seku.ac.ke", isVerified: true },
    { name: "Technical University of Mombasa", domain: "tum.ac.ke", isVerified: true },
    { name: "Africa Nazarene University", domain: "anu.ac.ke", isVerified: true },
    { name: "Jaramogi Oginga Odinga University of Science and Technology", domain: "jooust.ac.ke", isVerified: true },
    { name: "Karatina University", domain: "karu.ac.ke", isVerified: true },
    { name: "Kisii University", domain: "kisiiuniversity.ac.ke", isVerified: true },
    { name: "University of Eldoret", domain: "uoeld.ac.ke", isVerified: true },
    { name: "St. Paul's University", domain: "spu.ac.ke", isVerified: true },
    { name: "Riara University", domain: "riara.ac.ke", isVerified: true },
    { name: "University of Eastern Africa, Baraton", domain: "ueab.ac.ke", isVerified: true },
    { name: "Great Lakes University of Kisumu", domain: "gluk.ac.ke", isVerified: true },
    { name: "Amref International University", domain: "amref.ac.ke", isVerified: true },
    { name: "Multimedia University of Kenya", domain: "muke.ac.ke", isVerified: true },
    { name: "The Co-operative University of Kenya", domain: "cukenya.ac.ke", isVerified: true },
    { name: "Maasai Mara University", domain: "mmarau.ac.ke", isVerified: true },
    { name: "Africa International University", domain: "aiu.ac.ke", isVerified: true },
    { name: "Machakos University", domain: "mu.ac.ke", isVerified: true },
    { name: "Kibabii University", domain: "kibu.ac.ke", isVerified: true },
    { name: "Management University of Africa", domain: "mua.ac.ke", isVerified: true },
    { name: "The Presbyterian University of East Africa", domain: "puea.ac.ke", isVerified: true },
    { name: "Kirinyaga University", domain: "kru.ac.ke", isVerified: true },
    { name: "Rongo University", domain: "rongo.ac.ke", isVerified: true },
    { name: "Garissa University", domain: "garissauniversity.ac.ke", isVerified: true },
    { name: "Laikipia University", domain: "laikipia.ac.ke", isVerified: true },
    { name: "University of Kabianga", domain: "uok.ac.ke", isVerified: true },
    { name: "Adventist University of Africa", domain: "aua.ac.ke", isVerified: true },
    { name: "Pioneer International University", domain: "piu.ac.ke", isVerified: true },
    { name: "Pan Africa Christian University", domain: "pachristianuniversity.ac.ke", isVerified: true },
    { name: "Umma University", domain: "umma.ac.ke", isVerified: true },
    { name: "Taita Taveta University", domain: "ttu.ac.ke", isVerified: true },
    { name: "Lukenya University", domain: null, isVerified: false },
    { name: "Kiriri Women's University of Science and Technology", domain: "kwust.ac.ke", isVerified: true },
    { name: "GRETSA University", domain: "gretsa.ac.ke", isVerified: true },
    { name: "Kaimosi Friends University", domain: "kafu.ac.ke", isVerified: true },
    { name: "Tom Mboya University", domain: "tmu.ac.ke", isVerified: true },
    { name: "Tharaka University", domain: "tharakauniversity.ac.ke", isVerified: true },    
    { name: "Scott Christian University", domain: "scott.ac.ke", isVerified: true },
    { name: "Islamic University of Kenya", domain: "iuk.ac.ke", isVerified: true },
    { name: "International Leadership University, Kenya", domain: "kenya.ilu.edu", isVerified: true },
    { name: "Kenya Highlands University", domain: "khu.ac.ke", isVerified: true },
    { name: "KAG East University", domain: "kag.east.ac.ke", isVerified: true },
    { name: "The East African University", domain: "eau.ac.ke", isVerified: true },
    { name: "Alupe University", domain: "au.ac.ke", isVerified: true },
    { name: "Uzima University", domain: "uzimauniversity.ac.ke", isVerified: true },
    { name: "Aga Khan University, Kenya", domain: "aku.edu", isVerified: true },
]