import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Kyrgyzstan_universities = [

    // Kyrgyzstan
  
    { name: "Kyrgyz Russian Slavic University", domain: "krsu.edu.kg", isVerified: true },
    { name: "American University of Central Asia", domain: "auca.kg", isVerified: true },
    { name: "Kirgizistan-Türkiye Manas Üniversitesi", domain: "manas.edu.kg", isVerified: true },
    { name: "University of Central Asia", domain: "ucentralasia.org", isVerified: true },
    { name: "Kyrgyz State Technical University named after I. Razzakov", domain: "kstu.edu.kg", isVerified: true },
    { name: "Kyrgyz National University named after J. Balasagyn", domain: "ksu.edu.kg", isVerified: true },
    { name: "OSCE Academy", domain: "osce-academy.net", isVerified: true },
    { name: "Osh State University", domain: "oshstateuniversity.org", isVerified: true },
    { name: "Ala-Too Uluslararasi Üniversitesi", domain: "ala-too.edu.kg", isVerified: true },
    { name: "Kyrgyz State Medical Academy", domain: "ksma.edu.kg", isVerified: true },
    { name: "Kyrgyz National Agrarian University", domain: "knau.kg", isVerified: true },
    { name: "International University of Kyrgyzstan", domain: "iuk.kg", isVerified: true },
    { name: "Bishkek State University named after K. Karasaev", domain: "bsu.edu.kg", isVerified: true },
    { name: "Kyrgyz State University named after I. Arabayev", domain: "arabayev.edu.kg", isVerified: true },
    { name: "Osh Technological University", domain: "oshtu.kg", isVerified: true },
    { name: "Issyk-Kul State University", domain: "iksu.edu.kg", isVerified: true },
    { name: "Kyrgyz State University of Construction, Transportation and Architecture", domain: "ksucta.edu.kg", isVerified: true },
    { name: "Kyrgyz Economic University", domain: "kseu.kg", isVerified: true },
    { name: "International Academy of Management, Law, Finance and Business", domain: "iamlfb.edu.kg", isVerified: true },
    { name: "Academy of Public Administration under the President of the Kyrgyz Republic", domain: "academy.gov.kg", isVerified: true },
    { name: "Batken State University", domain: "bsu.edu.kg", isVerified: true },
    { name: "ADAM University", domain: "adam.edu.kg", isVerified: true },
    { name: "International University of Innovative Technologies", domain: "iuioht.edu.kg", isVerified: true },
    { name: "International Medical University", domain: "imu.kg", isVerified: true },
    { name: "International University of Central Asia", domain: "iuca.kg", isVerified: true },
    { name: "Academy of Education of Kyrgyzstan", domain: "aokedu.kg", isVerified: true },
    { name: "Diplomatic Academy of the Ministry of Foreign Affairs of the Kyrgyz Republic", domain: "dipacademy.kg", isVerified: true },
    { name: "Jalalabad State University", domain: "jsu.kg", isVerified: true },
    { name: "International Higher School of Medicine", domain: "ihsm.kg", isVerified: true },
    { name: "Naryn State University", domain: "nsu.edu.kg", isVerified: true },
    { name: "Kyrgyz-German Institute for Applied Informatics", domain: "kgiai.edu.kg", isVerified: true },
    { name: "Kyrgyz Aviation Institute", domain: "aviation.edu.kg", isVerified: true },
    { name: "Swiss International University", domain: "siu.edu.kg", isVerified: true },
    { name: "Asian Medical Institute", domain: "ami.edu.kg", isVerified: true },
    { name: "Kuwait International University", domain: "kiu.edu.kg", isVerified: true },
    { name: "Kyrgyz-Uzbek International University", domain: "kuiu.edu.kg", isVerified: true },
    { name: "Osh State Pedagogical University", domain: "ospu.edu.kg", isVerified: true },
    { name: "Kyrgyz State University of Culture and Arts", domain: "ksuca.edu.kg", isVerified: true },
    { name: "K. Sh. Toktomamatova International University", domain: "toktomamatova.edu.kg", isVerified: true },
    { name: "Kyrgyz-Russian Academy of Education", domain: "krae.edu.kg", isVerified: true },
    { name: "Talas State University", domain: "tsu.edu.kg", isVerified: true },
    { name: "Kyrgyz State Academy of Physical Culture and Sports", domain: "ksapcs.edu.kg", isVerified: true },
    { name: "Institute of Modern Information Technologies in Education", domain: "imit.edu.kg", isVerified: true },
    { name: "Salymbekov University", domain: "salymbekov.edu.kg", isVerified: true },
    { name: "Kyrgyz National Conservatory", domain: "knc.edu.kg", isVerified: true },
    { name: "Avicenna International Medical University", domain: "avicenna.edu.kg", isVerified: true },
    { name: "Medical and Social Research Institute", domain: "msri.edu.kg", isVerified: true },
    { name: "Royal Metropolitan University", domain: "rmu.edu.kg", isVerified: true },
    { name: "Osh International Medical University", domain: "oimu.edu.kg", isVerified: true },
    { name: "Kyrgyz-Kazakh University", domain: "kku.edu.kg", isVerified: true },
    { name: "Academy of Tourism", domain: "at.edu.kg", isVerified: true },
    { name: "Jalal-Abad International University", domain: "jaiu.kg", isVerified: true },
    { name: "Islamic University of Kyrgyzstan", domain: "kiu.kg", isVerified: true },
    { name: "Agrarian and Economic College", domain: null, isVerified: false },
    { name: "Chui University named after Sultan Mambetkaliev", domain: "chu.edu.kg", isVerified: true },
    { name: "Korean Institute of Central Asia", domain: "kica.kg", isVerified: true },
    { name: "Eurasian International University", domain: "eiu.edu.kg", isVerified: true },
    { name: "KEIIN International Institute", domain: "keiin.kg", isVerified: true },
    { name: "Kyrgyz International University NRZ", domain: "kiunrz.com", isVerified: true },
    { name: "Institute of Economics and Finance", domain: "ief.kg", isVerified: true },
    { name: "National Academy of Arts of the Kyrgyz Republic", domain: "academyart.kg", isVerified: true },
    { name: "Kyrgyz Institute of Languages and Culture", domain: "kiuc.kg", isVerified: true },
    { name: "Modern International University", domain: null, isVerified: false },
    { name: "International European University", domain: "ieu.edu.kg", isVerified: true },
    { name: "Eurasian University", domain: null, isVerified: false },
    { name: "Altamimi International University", domain: "altamimiedu.com", isVerified: true },
    { name: "University of South Asia", domain: "usa.com.kg", isVerified: true },
    { name: "Peoples' Friendship University of Asia", domain: "jagk.kg", isVerified: true },
    { name: "Kyrgyz Medical and Dental Institute", domain: "kmsi.edu.kg", isVerified: true },
    { name: "International Meta Science University", domain: "metascience.edu.kg", isVerified: true },
    { name: "Central Asian International University of Sciences and Technologies", domain: "camunt.kg", isVerified: true },
    { name: "Academy of Business and Social Development", domain: "isrip.kg", isVerified: true },
    { name: "Academy of Labor and Social Relations", domain: "esma.edu.kg", isVerified: true },
    { name: "Kyrgyz State Law Academy", domain: "ksla.kg", isVerified: true },
]