import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Libya_universities = [

    // Libya

    { name: "University of Tripoli", domain: "uot.edu.ly", isVerified: true },
    { name: "University of Benghazi", domain: "uob.edu.ly", isVerified: true },
    { name: "Sebha University", domain: "sebha.edu.ly", isVerified: true },
    { name: "Misurata University", domain: "mu.edu.ly", isVerified: true },
    { name: "Tobruk University", domain: "tu.edu.ly", isVerified: true },
    { name: "Libyan International University", domain: "liu.edu.ly", isVerified: true },
    { name: "Omar Al-Mukhtar University", domain: "omu.edu.ly", isVerified: true },
    { name: "Alasmarya Islamic University", domain: "asmu.edu.ly", isVerified: true },
    { name: "Sirte University", domain: "sirte.edu.ly", isVerified: true },
    { name: "University of Zawia", domain: "uoz.edu.ly", isVerified: true },
    { name: "Tripoli National University", domain: "tnu.edu.ly", isVerified: true },
    { name: "Libyan Academy for Postgraduate Studies", domain: null, isVerified: false },
    { name: "Islamic University of Mohamed Bin Ali Al Sanussi", domain: null, isVerified: false },
    { name: "University of Gharyan", domain: "uog.edu.ly", isVerified: true },
    { name: "Elmergib University", domain: "elu.edu.ly", isVerified: true },
    { name: "Sabratha University", domain: "sabu.edu.ly", isVerified: true },
    { name: "Azzaytuna University", domain: "azu.edu.ly", isVerified: true },
    { name: "Bright Star University", domain: "bsu.edu.ly", isVerified: true },
    { name: "Bani Waleed University", domain: "bwu.edu.ly", isVerified: true },
    { name: "Attahadi University", domain: "atu.edu.ly", isVerified: true },  
    { name: "University of Zintan", domain: "uzt.edu.ly", isVerified: true },
    { name: "Berenice University of Architecture and Urbanism", domain: "baru.edu.ly", isVerified: true },
    { name: "Alghad University", domain: "alghad.edu.ly", isVerified: true },
    { name: "Nalut University", domain: "unalut.edu.ly", isVerified: true },
    { name: "Alrefak University", domain: "alrefak.edu.ly", isVerified: true },
    { name: "Gulf of Sidra University", domain: "gsu.edu.ly", isVerified: true },
    { name: "Aljafara University", domain: "aljafara.edu.ly", isVerified: true },
    { name: "University of Alhadera", domain: "uhad.edu.ly", isVerified: true },
    { name: "University of Ajdabia", domain: "uajd.edu.ly", isVerified: true },
    { name: "Saraya Al-Hamra University", domain: "sahu.edu.ly", isVerified: true },
    { name: "Fezzan University", domain: "fu.edu.ly", isVerified: true },
    { name: "African University of Humanities and Applied Sciences", domain: "auhas.edu.ly", isVerified: true },
    { name: "Al-Jafra University", domain: "ajf.edu.ly", isVerified: true },
    { name: "Assalam International University", domain: "aiu.edu.ly", isVerified: true },
    { name: "Libyan University of Humanities and Applied Sciences", domain: "luhas.edu.ly", isVerified: true },
    { name: "Alassema University", domain: "ause.edu.ly", isVerified: true },
    { name: "Al-Maarefa University for Humanities and Applied Sciences", domain: "amuhas.edu.ly", isVerified: true },
    { name: "Benghazi Modern University", domain: "bmu.edu.ly", isVerified: true },
    { name: "Al-Quds Ahliya University", domain: "aqu.edu.ly", isVerified: true },
    { name: "Global University", domain: "globalu.edu.ly", isVerified: true },
    { name: "University of Zintan", domain: "uoz.edu.ly", isVerified: true },
    { name: "Belgray University", domain: "ub.edu.ly", isVerified: true },
    { name: "International University of Cyrene", domain: "qiu.edu.ly", isVerified: true },
    { name: "Lebda Al Kubra Al Ahlia University", domain: "lku.edu.ly", isVerified: true },
    { name: "Darub Asaria Private University", domain: "asarya.edu.ly", isVerified: true },
]