import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Malaysia_universities = [

    // Malaysia

    { name: "Universiti Malaya", domain: "um.edu.my", isVerified: true },
    { name: "Universiti Sains Malaysia", domain: "usm.edu.my", isVerified: true },
    { name: "Universiti Putra Malaysia", domain: "upm.edu.my", isVerified: true },
    { name: "Universiti Teknologi MARA", domain: "uitm.edu.my", isVerified: true },
    { name: "Universiti Teknologi Malaysia", domain: "utm.my", isVerified: true },
    { name: "Universiti Kebangsaan Malaysia", domain: "ukm.my", isVerified: true },
    { name: "Universiti Islam Antarabangsa Malaysia", domain: "iium.edu.my", isVerified: true },
    { name: "Universiti Utara Malaysia", domain: "uum.edu.my", isVerified: true },
    { name: "Universiti Multimedia", domain: "mmu.edu.my", isVerified: true },
    { name: "Universiti Tun Hussein Onn Malaysia", domain: "uthm.edu.my", isVerified: true },
    { name: "Universiti Sains Islam Malaysia", domain: "usim.edu.my", isVerified: true },
    { name: "Universiti Malaysia Sarawak", domain: "unimas.my", isVerified: true },
    { name: "Universiti Malaysia Sabah", domain: "ums.edu.my", isVerified: true },
    { name: "Universiti Tunku Abdul Rahman", domain: "utar.edu.my", isVerified: true },
    { name: "Universiti Teknologi Petronas", domain: "utp.edu.my", isVerified: true },
    { name: "Universiti Pendidikan Sultan Idris", domain: "upsi.edu.my", isVerified: true },
    { name: "Universiti Malaysia Perlis", domain: "unimap.edu.my", isVerified: true },
    { name: "Universiti Teknikal Malaysia Melaka", domain: "utem.edu.my", isVerified: true },
    { name: "Al-Madinah International University", domain: "mediu.edu.my", isVerified: true },
    { name: "Universiti Malaysia Pahang Al-Sultan Abdullah", domain: "ump.edu.my", isVerified: true },
    { name: "Universiti Kuala Lumpur", domain: "unikl.edu.my", isVerified: true },
    { name: "Monash University Malaysia", domain: "monash.edu.my", isVerified: true },
    { name: "Asia Pacific University of Technology and Innovation", domain: "apu.edu.my", isVerified: true },
    { name: "Universiti Malaysia Terengganu", domain: "umt.edu.my", isVerified: true },
    { name: "Universiti Tenaga Nasional", domain: "uniten.edu.my", isVerified: true },
    { name: "Universiti Sunway", domain: "sunway.edu.my", isVerified: true },
    { name: "University of Nottingham Malaysia", domain: "nottingham.edu.my", isVerified: true },
    { name: "Universiti Perubatan Antarabangsa", domain: "imu.edu.my", isVerified: true },
    { name: "Universiti Pengurusan & Teknologi Tunku Abdul Rahman", domain: "utar.edu.my", isVerified: true },
    { name: "Universiti Sultan Zainal Abidin", domain: "unisza.edu.my", isVerified: true },
    { name: "Universiti UCSI", domain: "ucsi.edu.my", isVerified: true },
    { name: "Taylor's University", domain: "taylors.edu.my", isVerified: true },
    { name: "Universiti Malaysia Kelantan", domain: "umk.edu.my", isVerified: true },
    { name: "Universiti HELP", domain: "help.edu.my", isVerified: true },
    { name: "Universiti SEGi", domain: "segi.edu.my", isVerified: true },
    { name: "Management and Science University", domain: "msu.edu.my", isVerified: true },
    { name: "Swinburne University of Technology Sarawak", domain: "swinburne.edu.my", isVerified: true },
    { name: "Universiti Selangor", domain: "unisel.edu.my", isVerified: true },
    { name: "Universiti Pertahanan Nasional Malaysia", domain: "upnm.edu.my", isVerified: true },
    { name: "Xiamen University Malaysia", domain: "xmu.edu.my", isVerified: true },
    { name: "UNITAR International University", domain: "unitar.my", isVerified: true },
    { name: "University of Wollongong Malaysia", domain: "uow.edu.my", isVerified: true },
    { name: "Curtin University, Malaysia", domain: "curtin.edu.my", isVerified: true },
    { name: "Quest International University", domain: "quest.edu.my", isVerified: true },
    { name: "Universiti Islam Selangor", domain: "unisel.edu.my", isVerified: true },
    { name: "INCEIF University", domain: "inceif.edu.my", isVerified: true },
    { name: "Asia e University", domain: "aeu.edu.my", isVerified: true },
    { name: "Universiti Infrastruktur Kuala Lumpur", domain: "unikl.edu.my", isVerified: true },
    { name: "Universiti Tun Abdul Razak", domain: "unitar.my", isVerified: true },
    { name: "City University of Malaysia", domain: "city.edu.my", isVerified: true },
    { name: "Universiti AIMST", domain: "aimst.edu.my", isVerified: true },
    { name: "MAHSA University", domain: "mahsa.edu.my", isVerified: true },
    { name: "Universiti Nilai", domain: "nilai.edu.my", isVerified: true },
    { name: "Universiti Sultan Azlan Shah", domain: "usas.edu.my", isVerified: true },
    { name: "Universiti Sains dan Teknologi Malaysia", domain: "ustm.edu.my", isVerified: true },
    { name: "Binary University of Management and Entrepreneurship", domain: "binary.edu.my", isVerified: true },
    { name: "KPJ Healthcare University", domain: "kpjuc.edu.my", isVerified: true },
    { name: "Universiti Cyberjaya", domain: "cyberjaya.edu.my", isVerified: true },
    { name: "University of Reading Malaysia", domain: "reading.edu.my", isVerified: true },
    { name: "Universiti Antarabangsa Albukhary", domain: "albukhary.edu.my", isVerified: true },
    { name: "Universiti Islam Antarabangsa Sultan Abdul Halim Mu'adzam Shah", domain: "unishams.edu.my", isVerified: true },
    { name: "Universiti Teknologi Sarawak", domain: "uts.edu.my", isVerified: true },
    { name: "Universiti Perdana", domain: "perdanauniversity.edu.my", isVerified: true },
    { name: "Universiti Malaya-Wales", domain: "umwales.edu.my", isVerified: true },
    { name: "Universiti UCYP", domain: "ucyp.edu.my", isVerified: true },
    { name: "Universiti Manipal GlobalNxt", domain: "globalnxt.edu.my", isVerified: true },
    { name: "Universiti MISI", domain: "misi.edu.my", isVerified: true },
    { name: "Universiti Poly-Tech Malaysia", domain: "uptm.edu.my", isVerified: true },
    { name: "MILA University", domain: "mila.edu.my", isVerified: true },
    { name: "Universiti Islam Antarabangsa Tuanku Syed Sirajuddin", domain: "kuips.edu.my", isVerified: true },
    { name: "DRB-HICOM University of Automotive Malaysia", domain: "dhu.edu.my", isVerified: true },
    { name: "University of Southampton Malaysia", domain: "southamptonmalaysia.edu.my", isVerified: true },
    { name: "Universiti Metropolitan Asia", domain: "amu.edu.my", isVerified: true },
    { name: "Raffles University", domain: "raffles-university.edu.my", isVerified: true },
    { name: "University Malaysia of Computer Science and Engineering", domain: "unimy.edu.my", isVerified: true },
    { name: "Royal College of Surgeons in Ireland and University College Dublin Malaysia", domain: "rcsiucd.edu.my", isVerified: true },
    { name: "Universiti Geomatika Malaysia", domain: "geomatika.edu.my", isVerified: true },
    { name: "Universiti Islam Melaka", domain: "unimel.edu.my", isVerified: true },
    { name: "Universiti Islam Pahang Sultan Ahmad Shah", domain: "unipsas.edu.my", isVerified: true },
    { name: "Universiti Islam Malaysia", domain: "uim.edu.my", isVerified: true },            
    { name: "University of Tsukuba, Malaysia", domain: null, isVerified: false },
    { name: "Universiti Muhammadiyah Malaysia", domain: null, isVerified: false },
    { name: "Universiti Keusahawanan Koperasi Malaysia", domain: null, isVerified: false },
    { name: "Meritus University", domain: "meritus.edu.my", isVerified: true },
    { name: "Newcastle University Medicine Malaysia", domain: "numed.edu.my", isVerified: true },
    { name: "Heriot-Watt University Malaysia", domain: "hw.edu.my", isVerified: true },
    { name: "Universiti Antarabangsa INTI", domain: "newinti.edu.my", isVerified: true },
    { name: "Universiti Teknologi Kreatif Limkokwing", domain: "limkokwing.edu.my", isVerified: true },
]