import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Mexico_universities = [

    // Mexico

    { name: "Universidad Nacional Autónoma de México", domain: "unam.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Tecnológico de Monterrey", domain: "tec.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Nuevo León", domain: "uanl.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Guadalajara", domain: "udg.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Politécnico Nacional", domain: "ipn.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Veracruzana", domain: "uv.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma Metropolitana", domain: "uam.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma del Estado de Hidalgo", domain: "uaeh.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Benemérita Universidad Autónoma de Puebla", domain: "buanp.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Guanajuato", domain: "ugto.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de las Américas Puebla", domain: "udlap.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Iberoamericana A.C.", domain: "ibero.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Baja California", domain: "uabc.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "El Colegio de México", domain: "colmex.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Yucatán", domain: "uady.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac México Norte", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Michoacana de San Nicolás de Hidalgo", domain: "umich.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma del Estado de México", domain: "uaem.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Ciudad Juárez", domain: "uacj.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Sonora", domain: "unison.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Aguascalientes", domain: "uaa.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico Autónomo de México", domain: "itam.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "ITESO – Instituto Tecnológico y de Estudios Superiores de Occidente", domain: "iteso.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Colima", domain: "ucol.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Panamericana", domain: "up.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro de Investigación y Docencia Económicas", domain: "cide.edu", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Sinaloa", domain: "uas.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de México", domain: "utm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de San Luis Potosí", domain: "uaslp.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Querétaro", domain: "uaq.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Chihuahua", domain: "uach.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Monterrey", domain: "udem.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Chiapas", domain: "unach.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma del Estado de Morelos", domain: "uaem.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Guadalajara", domain: "uagl.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de México", domain: "uvm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Juárez Autónoma de Tabasco", domain: "ujat.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad TecMilenio", domain: "tecmilenio.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Popular Autónoma del Estado de Puebla", domain: "upaep.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "CETYS Universidad", domain: "cetys.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Tamaulipas", domain: "uat.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Zacatecas", domain: "uaz.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Coahuila", domain: "uadec.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de la Ciudad de México", domain: "uacm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto de Estudios Universitarios A.C.", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Latinoamericana S.C.", domain: "ulatina.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Nayarit", domain: "uan.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Guerrero", domain: "uagro.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Chapingo", domain: "chapingo.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle", domain: "lasalle.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Pedagógica Nacional, Mexico", domain: "upn.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Quintana Roo", domain: "uqroo.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Juárez del Estado de Durango", domain: "ujed.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma Benito Juárez de Oaxaca", domain: "uabjo.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Sonora", domain: "itson.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac Mayab", domain: "mayab.unam.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Autónoma de Occidente", domain: "uao.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Montemorelos A.C.", domain: "uem.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Campeche", domain: "uacam.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Durango", domain: "uad.edu.mx", region: "North America", country: "Mexico", isVerified: true },    
    { name: "Universidad Autónoma de Tlaxcala", domain: "uatx.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma del Carmen", domain: "uacam.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Mixteca", domain: "utmixteca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Baja California Sur", domain: "uabcs.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Estatal de Sonora", domain: "uest.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Ciencias y Artes de Chiapas", domain: "unicach.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma Agraria Antonio Narro", domain: "uaaan.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Atemajac A.C.", domain: "uniat.ac.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Escuela Bancaria y Comercial", domain: "ebc.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Intercontinental", domain: "inter.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Durango", domain: "itdurango.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Regiomontana", domain: "ur.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "El Colegio de Sonora", domain: "colmex.sonora.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad del Mar", domain: "unimar.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "El Colegio Mexiquense A.C.", domain: "colmex.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Noroeste A.C.", domain: "lasalle.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad de la Salle Bajío A.C.", domain: "lasallebajio.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Iguala", domain: "itiguala.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Metropolitana de Monterrey", domain: "umm.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Madero", domain: "umad.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Celaya", domain: "itcelaya.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Internacional", domain: "uninter.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Cristóbal Colón", domain: "ucc.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Sierra Sur", domain: "unsis.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Puebla S.C.", domain: "uvp.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Claustro de Sor Juana", domain: "claustro.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Mexicali", domain: "itmexicali.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad ICEL", domain: "icel.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de La Paz", domain: "itlapaz.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Aguascalientes", domain: "ita.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro de Estudios Universitarios Xochicalco", domain: "xochicalco.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Jalisco", domain: "utj.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma del Noreste", domain: "uane.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Interamericana para el Desarrollo", domain: "unid.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma Intercultural de Sinaloa", domain: "uais.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Pachuca A.C.", domain: "lasallep.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Chihuahua", domain: "itch.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Latina de America", domain: "unla.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Tlaxcala", domain: "uptlax.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Querétaro", domain: "itq.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Caribe, Mexico", domain: "ucaribe.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Chihuahua", domain: "utch.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Noreste A.C.", domain: "une.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Celaya", domain: "udec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Vasco de Quiroga A.C.", domain: "uvaq.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tehuacán", domain: "ittehuacan.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Nezahualcóyotl", domain: "utneza.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Toluca", domain: "toluca.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Querétaro", domain: "utq.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Estado de Morelos", domain: "upemor.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Valles", domain: "valles.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Latina", domain: "universidadlatina.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de la Laguna", domain: "ual.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Humanitas", domain: "humanitas.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica General Mariano Escobedo", domain: "utgme.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tula-Tepeji", domain: "utt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Mérida", domain: "itmerida.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Saltillo", domain: "saltillo.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de León", domain: "utleon.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de La Laguna", domain: "laguna.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Negocios ISEC", domain: "isec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Insurgentes S.C.", domain: "insurgentes.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de San Luís Potosí", domain: "upslp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Tapachula", domain: "uptapachula.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro de Estudios Superiores de Diseño de Monterrey S.C.", domain: "cedim.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Morelia", domain: "morelia.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Veracruz", domain: "itver.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Puebla", domain: "utpuebla.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de San Juan del Río", domain: "utsjr.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Londres A.C.", domain: "ulondres.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Guanajuato", domain: "upgto.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Coahuila", domain: "utc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Chihuahua A.C.", domain: "lasallechihuahua.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Ciudad Juárez", domain: "utcj.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Matamoros", domain: "utmatamoros.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Huejotzingo", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Instituto Tecnológico de Ciudad Juárez", domain: "itcj.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Oriente, Mexico", domain: "unoriente.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Apizaco", domain: "itapizaco.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Aguascalientes", domain: "utags.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de San Luís Potosí", domain: "itslp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tijuana", domain: "tectijuana.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "TecNM Campus Zitácuaro", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Instituto Tecnológico de Tuxtla Gutiérrez", domain: "ittg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Pontificia de Mexico", domain: "upm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Metropolitana, Mexico", domain: "utm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Acapulco", domain: "itacapulco.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de León, Mexico", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Tecnológica del Estado de Zacatecas", domain: "utezac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro de Estudios Superiores del Noroeste", domain: "cesun.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Campeche", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Popular de la Chontalpa", domain: "upch.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Cancún", domain: "utcancun.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Hermosillo", domain: "ith.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Laguna", domain: "ulsalaguna.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Olmeca A.C.", domain: "olmeca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad España", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Mesoamericana de San Agustín A.C.", domain: "umsa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Tijuana", domain: "cut.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Pachuca", domain: "itpachuca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Tulancingo", domain: "upt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Pedagógica de Durango", domain: "updurango.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Papaloapan", domain: "unpa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Regional del Sureste A.C.", domain: "urso.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Colima", domain: "itcolima.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Xalapa A.C.", domain: "ux.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Chiapas", domain: "upchiapas.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Estatal del Valle de Ecatepec", domain: "uneve.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Sinaloa", domain: "upsin.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Madero", domain: "itcm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Cancún A.C.", domain: "ulsacancun.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Nuevo León", domain: "itnl.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Pachuca", domain: "upp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tepic", domain: "ittepic.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Comunicación S.C.", domain: "uc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro de Estudios Superiores de San Ángel S.C.", domain: "cessa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Norte de Guanajuato", domain: "utnog.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Valle del Mezquital", domain: "utvm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Aguascalientes", domain: "upa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto de Especialización para Ejecutivos", domain: "iee.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Simón Bolivar", domain: "usb.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tamaulipas Norte", domain: "uttn.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Victoria", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad La Salle Cuernavaca", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Tecnológica de Tijuana", domain: "utt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico Latinoamericano", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Pedro de Gante", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Mexicana S.C.", domain: "unimex.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad ETAC", domain: "etac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Estudios Avanzados", domain: "unea.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "TecNM campus Oaxaca", domain: "oaxaca.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Selva", domain: "utselva.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Emiliano Zapata del Estado de Morelos", domain: "utez.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tulancingo", domain: "upt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Piedras Negras", domain: "uppn.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Baja California", domain: "upbc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Morelia A.C.", domain: "unim.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro de Estudios Universitarios", domain: "ceu.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Valle del Grijalva S.C.", domain: "uvg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tabasco", domain: "uttab.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Hipócrates", domain: "hipocrates.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Norte de Aguascalientes", domain: "utna.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Benavente A.C.", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Tecnológica de La Huasteca Hidalguense", domain: "uthh.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de León", domain: "itleon.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Chihuhahua Sur", domain: "utchsur.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Villahermosa", domain: "itvillahermosa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Querétaro", domain: "upq.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Santa Rosa Jáuregui", domain: "upsrj.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Norte A.C.", domain: "udn.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de las Américas A.C.", domain: "udla.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Nuevo Laredo", domain: "itnld.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Loyola del Pacífico A.C.", domain: "loyola.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Morelia", domain: "utmorelia.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Marista de Guadalajara", domain: "umg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Kino A.C.", domain: "ukin.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Puebla", domain: "itpuebla.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Morelia A.C.", domain: "ulsamorelia.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad José Vasconcelos", domain: "ujv.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Cuauhtémoc", domain: "ucuauhtemoc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Chetumal", domain: "itch.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Istmo, Oaxaca", domain: "unistmo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Centro de Veracruz", domain: "utcver.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de San Luis Potosí", domain: "utslp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Chihuahua II", domain: "itch2.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Instituto Tecnológico de Orizaba", domain: "itorizaba.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de San Juan del Río", domain: "itsjr.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Obrera de México", domain: "uom.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tlaxcala", domain: "utlax.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Sierra Hidalguense", domain: "utsh.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de los Valles Centrales de Oaxaca", domain: "uteo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Victoria", domain: "upvictoria.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Hermosillo, Sonora", domain: "uthermosillo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Izúcar de Matamoros", domain: "utimam.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Regional del Norte", domain: "urn.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Durango", domain: "updurango.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Sierra Juárez", domain: "unijua.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Modelo", domain: "um.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Desarrollo Empresarial y Pedagógico", domain: "udep.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Los Mochis", domain: "itmoc.edu.mx", region: "North America", country: "Mexico", isVerified: true },            
    { name: "Universidad Politécnica de Francisco I. Madero", domain: "upfim.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica Metropolitana de Hidalgo", domain: "upmh.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Valle de México", domain: "upvm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Minatitlán", domain: "itminatitlan.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Chihuahua", domain: "upchihuahua.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Xicotepec de Juárez", domain: "utxicotepec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "UGMEX", domain: "ugmex.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Tepeyac", domain: "tepeyac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tuxtepec", domain: "ittuxtepec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Mundial", domain: "universidadmundial.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Huatusco", domain: "uphuatusco.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tangamanga S.C.", domain: "utangamanga.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Bahía de Banderas", domain: "utbb.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Cancún", domain: "itcancun.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Ecatepec", domain: "universidadecatepec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Matamoros", domain: "itmatamoros.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Marista A.C.", domain: "marista.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Santa Catarina", domain: "utsantacatarina.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Centro de México", domain: "ucem.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Centro", domain: "upcentro.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Zacatecas", domain: "itzac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Cuautitlán Izcalli", domain: "unici.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Culiacán", domain: "itculiacan.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tizimín", domain: "ittizimin.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tehuacán", domain: "uttehuacan.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Nayarit", domain: "utnayarit.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Golfo de México Norte", domain: "ugmn.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Loyola de America", domain: "loyal.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Mexiquense del Bicentenario", domain: "unimexico.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Orizaba", domain: "uvOR.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Puebla", domain: "uppuebla.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de la Zona Metropolitana de Guadalajara", domain: "upzmg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Hebraica", domain: "uhebraica.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad México Americana del Norte A.C.", domain: "uman.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Cañada", domain: "unca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Interamericana A.C.", domain: "lainter.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Torreón", domain: "utt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tecámac", domain: "uttecamac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Fidel Velázquez", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Instituto Tecnológico de Mazatlán", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Politécnica de Puebla", domain: "uppuebla.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de la Zona Metropolitana de Guadalajara", domain: "upzmg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Hebraica", domain: "uhebraica.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad México Americana del Norte A.C.", domain: "uman.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Cañada", domain: "unca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Interamericana A.C.", domain: "lainter.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Torreón", domain: "utt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tecámac", domain: "uttecamac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Fidel Velázquez", domain: "utfv.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Mazatlán", domain: "mazatlan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico José Mario Molina Pasquel y Henríquez", domain: "tecmm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Durango", domain: "utd.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Linda Vista", domain: "ulv.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Guzmán", domain: "cdguzman.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Ciénega del Estado de Michoacán de Ocampo", domain: "ucemich.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Valle del Guadiana", domain: "itvalledelguadiana.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Concordia", domain: "universidadlaconcordia.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad YMCA", domain: "uniymca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Lucerna S.C.", domain: "lucerna.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Victoria", domain: "itvictoria.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Gómez Palacio", domain: "upgop.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Escuinapa", domain: "utescuinapa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Salamanca", domain: "utsalamanca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Boca del Río", domain: "bdelrio.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Valle de Oaxaca", domain: "voaxaca.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Pedregal", domain: "universidaddelpedregal.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Americana de Acapulco", domain: "uaa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Gutiérrez Zamora", domain: "utgz.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Sur del Estado de México", domain: "utsem.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tapachula", domain: "tapachula.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Quintana Roo", domain: "upqroo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Quetzalcóatl", domain: "uqi.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica El Retoño", domain: "utretoño.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Benito Juarez", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Tecnológica del Valle de Toluca", domain: "utvt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de La Riviera Maya", domain: "utrivieramaya.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Lázaro Cárdenas", domain: "lazarocardenas.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Pabellón de Arteaga", domain: "pabellon.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Istmo", domain: "istmo.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Nogales", domain: "nogales.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de las Californias Internacional S.C.", domain: "udci.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Zacatepec", domain: "zacatepec.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Parral", domain: "parral.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad La Salle Saltillo", domain: "ulsasaltillo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Usumacinta", domain: "utusumacinta.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Sierra", domain: "unisierra.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Westhill", domain: "westhill.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Suroeste de Guanajuato", domain: "utsog.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Costa Grande de Guerrero", domain: "utcgg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Mundo Maya", domain: "umm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Torreón", domain: "torreon.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Don Vasco A.C.", domain: "udv.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Conkal", domain: "conkal.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Agua Prieta", domain: "aguaprieta.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Regional del Sur", domain: "utregionaldelsur.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Atitalaquia", domain: "atitalaquia.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Bicentenario", domain: "upbicentenario.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Latina de México S.C.", domain: "ulm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Franco-Mexicana S.C.", domain: "ufram.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica Metropolitana de Puebla", domain: "upmetropolitana.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "El Colegio de Chihuahua", domain: "cochih.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Sur de Sonora", domain: "utss.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Americana", domain: "ute.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Albert Einstein, Mexico", domain: "uaeinstein.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Tecamachalco", domain: "uttecamachalco.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Chapultepéc A.C.", domain: "uchapultepec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de la Sierra A.C.", domain: "unisierra.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "TecNM Campus Comitán", domain: "comitan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ensenada", domain: "ensenada.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Corregidora", domain: "utcorregidora.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Multicultural CUDEC", domain: "cudec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Salesiana", domain: "unisalesiana.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Nogales, Sonora", domain: "utnogales.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Calvillo", domain: "utcalvillo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Sotavento A.C.", domain: "us.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Cientifica Latino Americana de Hidalgo", domain: "uclah.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de El Salto", domain: "elsalto.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tláhuac", domain: "tlahuac.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Costa", domain: "utcosta.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Apodaca", domain: "upapodaca.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Campeche", domain: "utcam.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Parral", domain: "utparral.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Motolinia del Pedregal A.C.", domain: "motolinia.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Jiquilpan", domain: "jiquilpan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Mesoamericana", domain: "umes.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tlalnepantla", domain: "tlalnepantla.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Chiná", domain: "china.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Roque", domain: "roque.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Golfo", domain: "universidaddelgolfo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Región Norte de Guerrero", domain: "utrng.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Distrito Federal S.C.", domain: "udf.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Altamira", domain: "upaltamira.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica Juventino Rosas", domain: "upjr.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Golfo de México", domain: "upgm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de La Zona Maya", domain: "zonamaya.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Comunicación Avanzada", domain: "unica.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Úrsulo Galván", domain: "ursulogalvan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Privada del Estado de México", domain: "upem.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Delicias", domain: "delicias.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Ramos Arizpe", domain: "upra.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Norte de Coahuila", domain: "utnc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Valle de Morelia", domain: "valledemorelia.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Altamira", domain: "utaltamira.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Tlaxcala", domain: "uvt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Mayab", domain: "utmayab.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Interamericana del Norte y Tecnológico Sierra Madre", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Internacional de La Paz", domain: "unipaz.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Lerma", domain: "lerma.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Cerro Azul", domain: "cerroazul.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Cuautla", domain: "cuautla.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },                                 
    { name: "Instituto Tecnológico de Reynosa", domain: "reynosa.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Zona Metropolitana de Guadalajara", domain: "utzmg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Minera de Zimapán", domain: "utminera.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Centro, Mexico", domain: "utcentro.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Valle del Yaqui", domain: "yaqui.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Sur de Zacatecas", domain: "upsz.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Milpa Alta", domain: "milpaalta.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Tarahumara", domain: "uttarahumara.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de San Miguel de Allende", domain: "utsma.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Sur del Estado de Morelos", domain: "utsurmorelos.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ocotlán", domain: "ocotlan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Piedras Negras", domain: "piedrasnegras.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Cadereyta", domain: "utcadereyta.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "TecNM Campus Altiplano de Tlaxcala", domain: "altiplano.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Alva Edison", domain: "uae.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Pinotepa", domain: "pinotepa.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Zacatecas", domain: "upz.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Altiplano", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Instituto Tecnológico de La Piedad", domain: "lapiedad.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Paccioli de Córdoba", domain: "paccioli.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto de Estudios Superiores del Bajío", domain: "iesbajio.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Camargo", domain: "utcamargo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Sureste de Veracruz", domain: "utsv.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Hispana", domain: "universidadhispana.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de San Luis Río Colorado", domain: "utslrc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Fray Luca Paccioli", domain: "uflp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Cuauhtémoc", domain: "cuauhtemoc.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Frontera Comalapa", domain: "fronteracomalapa.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Mesoamericana Puebla", domain: "mesoamericana.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Nuevo Laredo", domain: "utnl.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de la Costa Grande", domain: "costagrande.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Interserrana del Estado de Puebla Ahuacatlán", domain: "uiepa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Poniente", domain: "utponiente.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Manzanillo", domain: "utmanzanillo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tláhuac II", domain: "tlahuac2.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Mexiquense", domain: "umex.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Zona Metropolitana del Valle de México", domain: "utzmvm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de San Miguel A.C.", domain: "usanmiguel.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Puerto Peñasco", domain: "utpp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de la Chontalpa", domain: "chontalpa.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Etchojoa", domain: "utetchojoa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Cuernavaca", domain: "uvac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Pénjamo", domain: "upp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Amozoc", domain: "upa.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tlajomulco", domain: "tlajomulco.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Hispanoamericana Justo Sierra", domain: "uhjs.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Maya", domain: "universidadmaya.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Isidro Fabela de Toluca S.C.", domain: "uifat.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Paquimé", domain: "utpaquime.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Realística de México", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Salazar", domain: "universidadsalazar.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Gustavo A. Madero", domain: "gustavoamadero.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Catolica de Culiacan A.C.", domain: "ucc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Región Centro de Coahuila", domain: "utrc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Dorados", domain: "universidaddorados.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Uruapan", domain: "upu.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de El Llano Aguascalientes", domain: "elllano.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Bahía de Banderas", domain: "bahiabanderas.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Iztapalapa II", domain: "iztapalapa2.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica Linares", domain: "utlinares.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Privada de Irapuato", domain: "upi.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Acapulco", domain: "utacapulco.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tláhuac III", domain: "tlahuac3.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Guaymas", domain: "guaymas.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Valle de Toluca", domain: "upvt.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Pochutla", domain: "pochutla.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Chilpancingo", domain: "chilpancingo.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de La Laguna Durango", domain: "utlagunadurango.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Huejutla", domain: "uph.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Huejutla", domain: "huejutla.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Bacalar", domain: "upb.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Guaymas", domain: "utguaymas.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Iztapalapa", domain: "iztapalapa.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Los Altos de Chiapas S.C.", domain: "unachiapas.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Partenón Cozumel A.C.", domain: "partenoncozumel.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Huatabampo", domain: "huatabampo.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Estado de Guerrero", domain: "upegro.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica Cuencamé", domain: "upcuencame.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Linares", domain: "linares.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Fresnillo", domain: "uaf.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de La Zona Olmeca", domain: "zonaolmeca.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Poanas", domain: "utpoanas.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Interserrana del Estado de Puebla-Chilchotla", domain: "uiepchilchotla.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Villasunción", domain: "uv.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Tecnológica del Mar de Tamaulipas Bicentenario", domain: "utmar.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Chetumal", domain: "utchetumal.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Nacional de Estudios Fiscales", domain: "inef.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Cuauhnáhuac", domain: "unic.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politecnica Hispano Mexicana", domain: "uphm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Matehuala", domain: "matehuala.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Justo Sierra A.C.", domain: "ujs.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de la Región Ribereña", domain: "uprr.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica Mesoamericana", domain: "upm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Alica", domain: "universidaddelalica.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Norte de Nayarit", domain: "nortenayarit.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Oriental", domain: "utdeoriental.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Babícora", domain: "utb.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de las Ciencias de la Comunicación de Puebla S.C.", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Politécnica de Tecámac", domain: "uptecamac.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de La Cuenca del Papaloapan", domain: "cpapaloapan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Altamira", domain: "altamira.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Región Carbonífera", domain: "utrc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Valle de Évora", domain: "upve.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Centro Universitario de Integración Humanística A.C.", domain: "cuih.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tecomatlán", domain: "tecomatlan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tlaxiaco", domain: "tlaxiaco.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Culiacán", domain: "utculiacan.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Centro de Mexico S.C.", domain: "utcm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Santa Fe A.C.", domain: "usf.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Texcoco", domain: "uptex.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Lázaro Cárdenas", domain: "uplc.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Candelaria", domain: "utcandelaria.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Hermosillo A.C.", domain: "udeh.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Altamirano", domain: "ciudadaltamirano.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Álvaro Obregón", domain: "alvaroobregon.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Salina Cruz", domain: "salinacruz.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Pacífico de Chiapas", domain: "upchiapas.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Xicotepetl A.C.", domain: "ux.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad San Marcos S.C.", domain: "usm.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de La Paz", domain: "utlp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Guadiana", domain: "uvg.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Sur de Nayarit", domain: "surnayarit.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Sierra Sur de Oaxaca", domain: "utssso.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Tlalpan", domain: "tlalpan.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Iztapalapa III", domain: "iztapalapa3.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica de Tlaxcala Región Poniente", domain: "uptlp.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Privada del Estado de Morelos S.C.", domain: "upemorelos.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Politécnica del Mar y la Sierra", domain: "upmys.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Rodeo", domain: "utrodeo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Sierra", domain: "utsi.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Continental Justo Sierra", domain: "ucjs.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Autónoma de Piedras Negras", domain: "uapn.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico del Valle de Etla", domain: "valleetla.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Centro del Bajío", domain: "ucbajio.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de San Marcos", domain: "sanmarcos.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica del Mar del Estado de Guerrero", domain: "utmar.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Sinaloa de Leyva", domain: "sinaloadeleyva.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Ciudad Jiménez", domain: "jimenez.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Gustavo A. Madero II", domain: "gamadero2.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Alzate de Ozumba", domain: "uao.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Lasallista Benavente S.C.", domain: "ulbenavente.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Comitancillo", domain: "comitancillo.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Huimanguillo", domain: "huimanguillo.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Instituto Tecnológico de Milpa Alta II", domain: "milpaalta2.tecnm.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Zinacantepec", domain: "utzinacantepec.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de la Tierra Caliente", domain: "uttiercal.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac México Sur", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad de Norteamerica", domain: "un.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac de Oaxaca", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Toluca", domain: "uvt.edu.mx", region: "North America", country: "Mexico", isVerified: true },    
    { name: "Universidad Pedagógica Veracruzana", domain: null, region: "North America", country: "Mexico", isVerified: false },
    { name: "Instituto de Estudios Superiores de Tamaulipas A.C.", domain: "iest.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad del Valle de Matatipac S.C.", domain: "uvm.edu.mx", region: "North America", country: "Mexico", isVerified: false },
    { name: "Universidad Anáhuac Cancún", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac de Xalapa", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Ateneo de Monterrey", domain: "ateneodemonterrey.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Tecnológica de Saltillo", domain: "utsaltillo.edu.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac Puebla", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Universidad Anáhuac Querétaro", domain: "anahuac.mx", region: "North America", country: "Mexico", isVerified: true },
    { name: "Arte A.C.", domain: "arteac.edu.mx", region: "North America", country: "Mexico", isVerified: true },

]