import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Mongolia_universities = [

    // Mongolia

    { name: "National University of Mongolia", domain: "num.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian University of Science and Technology", domain: "must.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian National University of Medical Sciences", domain: "mnums.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian University of Life Sciences", domain: "muls.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian State University of Education", domain: "msue.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian National University of Arts and Culture", domain: "mnuac.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "University of Finance and Economics", domain: "ufe.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Huree University", domain: "huree.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Khovd University", domain: "khu.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "University of the Humanities", domain: "humanities.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "International University of Ulaanbaatar", domain: "iuu.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Academy of Management", domain: "naog.gov.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "University of Pharmaceutical Science", domain: "monos.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolia International University", domain: "miu.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "German-Mongolian Institute for Resources and Technology", domain: "gmit.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Citi University", domain: "citi.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Otgontenger University", domain: "otgontenger.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mandakh University", domain: "mandakh.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Ulaanbaatar State University", domain: null, region: "Asia", country: "Mongolia", isVerified: false },
    { name: "Soyol-Erdem College", domain: "soyolerdem.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Global Leadership University", domain: "glu.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Institute of Engineering and Technology", domain: "iet.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "The Ikh Zasag University", domain: "ikhzasag.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Etugen University", domain: "etugen.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian National University", domain: "mnun.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Dornod University", domain: "dornod.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Ider University", domain: "ider.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Tsetsee Goun Institute of Management", domain: "tsetsee-goun.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Shihihutug Law Institute", domain: "shihihutug.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Orkhon University", domain: "orkhon.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian National Institute of Physical Education", domain: "nipe.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Ach Medical University", domain: "ach.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Institute of Railways", domain: "ubtz.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Otoch Manramba University", domain: "otoch.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongolian State Conservatory", domain: "conservatory.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Nomera Institute", domain: "nomera.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mon-Altius Institute", domain: "altius.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "The Institute of International Studies", domain: "iis.ac.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Darkhan Institute", domain: "darkhandeed.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Avarga Institute", domain: "avarga.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Gazarchin University of Mongolia", domain: "gazarchin.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Ulaanbaatar University", domain: "ubu.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Institute of Education, Culture and Law", domain: "ecl.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Sun University", domain: "san.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "New Medicine Institute", domain: "ncm.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Enerel Medical Institute", domain: "enerel.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "New Civilization Polytechnic College", domain: null, region: "Asia", country: "Mongolia", isVerified: false },
    { name: "Mongolian Labour and Social Relations Institute", domain: "mlsri.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Zasagt Khan Institute", domain: "zasagtkhan.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Tenger Institute", domain: "tenger.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "National University of Economics", domain: "mnue.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "National Technical University", domain: "utis.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "International University of Economics and Business", domain: "iieb.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Khangai University", domain: "hangaiuniversity.com", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Gurvan Erdene Institute of Pedagogy", domain: null, region: "Asia", country: "Mongolia", isVerified: false },
    { name: "Language and Civilisation Institute", domain: "khel-irgenshil.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Great Mongol Institute", domain: null, region: "Asia", country: "Mongolia", isVerified: false },
    { name: "Gurvan Tamir College", domain: "gurvantamir.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Institute of Social Science", domain: "nuds.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Sutai Institute", domain: "sutai.edu.mn", region: "Asia", country: "Mongolia", isVerified: true },
    { name: "Mongol Institute", domain: null, region: "Asia", country: "Mongolia", isVerified: false },
    { name: "Tushee Institute", domain: "tushee.mn", region: "Asia", country: "Mongolia", isVerified: true },
]