import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Myanmar_universities = [

    // Myanmar

    { name: "Yangon University", domain: "uy.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Computer Studies, Yangon", domain: "ucsy.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Yezin Agricultural University", domain: "yau.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Yangon Technological University", domain: "ytu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Yangon University of Economics", domain: "yueco.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medicine, Mandalay", domain: "ummdy.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Dagon University", domain: "dagonuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Nursing, Yangon", domain: "uonygn.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medicine 2, Yangon", domain: "um2ygn.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Monywa University of Economics", domain: "mue.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medicine 1, Yangon", domain: "um1yangon.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medicine, Magway", domain: "ummg.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Computer Studies, Mandalay", domain: "ucsm.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Veterinary Science, Yezin", domain: "uvs.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Mandalay Technological University", domain: "tum-mandalay.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Dental Medicine, Yangon", domain: "udmyangon-edu.com", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Yangon University of Education", domain: "yuoe.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Pathein University", domain: "patheinuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Hpaan University", domain: "hpaan.university", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Foreign Languages, Yangon", domain: "yufl.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "East Yangon University", domain: "eyu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medical Technology, Yangon", domain: "umty.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Myanmar Maritime University", domain: "mmu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Technology, Yadanabon Cyber City", domain: "utycc.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Public Health, Yangon", domain: "uph-myanmar.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Dental Medicine, Mandalay", domain: "udmmandalay.info", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Nursing, Mandalay", domain: "uonmdy.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Hmawbi", domain: "hbtu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Yadanabon University", domain: "ydnbu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "West Yangon Technological University", domain: "wytu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Mandalay", domain: "tum-mandalay.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Thanlyin", domain: "tuthanlyin.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Myanmar Aerospace Engineering University", domain: "maeu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Myeik", domain: "tumyeik.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Myitkyina", domain: "tumka.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Hinthada University", domain: "hu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Hinthada", domain: "tuhtd.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medicine, Taunggyi", domain: "umtgi.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Pharmacy, Mandalay", domain: "uopmdy.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Taunggyi University", domain: "tgu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Community Health, Magway", domain: "uch.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Taungoo", domain: "tutoungoo.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Myeik University", domain: "myeikuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Banmaw", domain: "banmawtu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Loikaw", domain: "tuloikaw.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Mandalay University of Foreign Languages", domain: "mufl.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Meikhtila", domain: "tumeiktila.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Lashio University", domain: "lsouni.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Lashio", domain: "tulashio.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Shwebo University", domain: "sbu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Bhamo University", domain: "bmwuni.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Pharmacy, Yangon", domain: "uopygn.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Pyay Technological University", domain: "ptu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Maubin University", domain: "maubinuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Sagaing", domain: "tusagaing.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Monywa", domain: "tumonywa.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Hpaan", domain: "tuhpn.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Kalay", domain: "tukalay.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Kyaing Tong", domain: "tukt.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Kyaukse Technological University", domain: "kyauksetu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Sagaing University of Education", domain: "suoe.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Pakokku University", domain: "pakokkuuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Pyay", domain: "pyayuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Meiktila University", domain: "mtluniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Loikaw University", domain: "loikawuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Taungoo University", domain: "taungoou.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Maubin", domain: "tumaubin.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Mawlamyine", domain: "tumawlamyine.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Taunggyi", domain: "tutaunggyi.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Naypyitaw Technological University", domain: "ntu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Sittwe", domain: "tusittwe.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Panglong", domain: "tuplon.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Sagaing University", domain: "sagainguni.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Yamethin", domain: "tuymt.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Bago University", domain: "bagouni.moe.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Meiktila University of Economics", domain: "mtlaeco.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Magway", domain: "tumg.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Dawei", domain: "tudawei.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Panglong University", domain: "upanglong.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Dawei University", domain: "daweiuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Forestry and Environmental Science, Yezin", domain: "ufes.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Kalay University", domain: null, region: "Asia", country: "Myanmar", isVerified: false },
    { name: "Kyaing Tong University", domain: "kyaingtonguniversity.moe.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Kyaukse University", domain: "kyaukseuniversity.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Magway University", domain: "umgy.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Mandalay University", domain: "mu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "National University of Arts and Culture, Mandalay", domain: "nuacmdy.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Mawlamyine University", domain: "mlmuni.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Monywa University", domain: "monywau.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Technological University, Pakokku", domain: "tupku.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Medical Technology, Mandalay", domain: "umtmandalay.gov.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "Sittway University", domain: null, region: "Asia", country: "Myanmar", isVerified: false },
    { name: "Technological University, Pathein", domain: "patheintu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of West Yangon", domain: "wyu.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "University of Myitkyina", domain: "umkn.edu.mm", region: "Asia", country: "Myanmar", isVerified: true },
    { name: "National University of Arts and Culture, Yangon", domain: null, region: "Asia", country: "Myanmar", isVerified: false },
]