import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Netherlands_universities = [

  // Netherlands

  { name: "Utrecht University", domain: "uu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Amsterdam", domain: "uva.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Groningen", domain: "rug.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Leiden University", domain: "leidenuniv.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Delft University of Technology", domain: "tudelft.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Vrije Universiteit Amsterdam", domain: "vu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Erasmus University Rotterdam", domain: "eur.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Radboud University Nijmegen", domain: "ru.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Wageningen University & Research", domain: "wur.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Maastricht University", domain: "maastrichtuniversity.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Eindhoven University of Technology", domain: "tue.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Twente", domain: "utwente.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Tilburg University", domain: "tilburguniversity.edu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Hanze University of Applied Sciences Groningen", domain: "hanze.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Arnhem and Nijmegen University of Applied Sciences", domain: "han.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Avans University of Applied Sciences", domain: "avans.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Amsterdam University of Applied Sciences", domain: "hva.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Fontys University of Applied Sciences", domain: "fontys.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Saxion Universities of Applied Sciences", domain: "saxion.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Applied Sciences Utrecht", domain: "hu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Inholland University of Applied Sciences", domain: "inholland.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Theological University", domain: "tukampen.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Windesheim University of Applied Sciences", domain: "windesheim.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Rotterdam School of Management, RSM Erasmus University", domain: "rsm.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Zuyd University of Applied Sciences", domain: "zuyd.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Open University of the Netherlands", domain: "ou.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of the Arts Utrecht", domain: "hku.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Royal Academy of Art, The Hague", domain: "kabk.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Amsterdam University of the Arts", domain: "ahk.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "ArtEZ University of the Arts", domain: "artez.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Rijksakademie van Beeldende Kunsten", domain: "rijksakademie.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Maastricht School of Management", domain: "msm.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "CODARTS School of the Arts", domain: "codarts.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Hague University of Applied Sciences", domain: "hhs.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Institute for Housing and Urban Development Studies", domain: "ihs.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "LOI Distance Education", domain: "loi.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "TIAS School for Business and Society", domain: "tias.edu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Wittenborg University of Applied Sciences", domain: "wittenborg.eu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "NTI Distance Education", domain: "nti.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Design Academy Eindhoven", domain: "designacademy.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "ROC van Twente", domain: "rocvt.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Applied Sciences Leiden", domain: "hsleiden.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Rotterdam University of Applied Sciences", domain: "ruas.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Nyenrode Business University", domain: "nyenrode.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Zeeland University of Applied Sciences - HZ", domain: "hz.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "TIO University of Applied Sciences", domain: "tio.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "ROC Event", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Hotel School The Hague", domain: "hotelschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Van Hall Larenstein University of Applied Sciences", domain: "vanhalllarenstein.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Erasmus University International Institute of Social Studies in The Hague", domain: "iss.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Protestant Theological University", domain: "pthu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Tinbergen Institute", domain: "tinbergen.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "NHL University of Applied Sciences", domain: "nhl.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Royal Conservatory of The Hague", domain: "koncon.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Eurocollege Hogeschool", domain: "eurocollege.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Business School Netherlands", domain: "bsn.eu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Academic Center for Dentistry Amsterdam", domain: "acta.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "UP Learning", domain: "uplearning.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Applied Sciences for Pedagogical and Social Education SPO Groningen", domain: "spo-groningen.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Humanistic Studies", domain: "uvh.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Casimir Research School", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Thim van der Laan International University of Applied Sciences for Physiotherapy", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Theological University of Apeldoorn", domain: "thua.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Christian University of Ede", domain: "che.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Breda University of Applied Sciences", domain: "buas.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Professional Teacher Education PABO Zwolle", domain: "christelijkepabo.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Webster University", domain: "webster.edu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University College Roosevelt", domain: "ucr.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "HAS University of Applied Sciences", domain: "has.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Maastricht Hotel School", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Erasmus Center for Maritime Economics and Logistics", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "New School for Information Services", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Graduate School VLAG Advanced Studies in Food Technology, Agrobiotechnology, Nutrition and Health Sciences", domain: "vlag.wur.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "IHE Delft Institute for Water Education", domain: "un-ihe.org", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Sandberg Institute", domain: "sandberg.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "C T de Wit Graduate School for Production Ecology & Resource Conservation", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Institute for Automotive Industry and Management Driebergen", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "CAE Oxford Aviation Academy", domain: "cae.com", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Graduate School Experimental Plant Sciences Wageningen", domain: "eps.wur.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "KLM Flight Academy", domain: "klmflightacademy.com", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Holland Research School of Molecular Chemistry", domain: "hrsmc.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Network University", domain: "networkuniversity.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Gerrit Rietveld Academy", domain: "rietveldacademie.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Stenden University of Applied Sciences", domain: "stenden.com", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Christian Institute for Higher Professional Education de Driestar", domain: "driestarhogeschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "EuroPort Business School", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Cruyff Institute for Sport Studies", domain: "cruyffinstitute.org", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "TSM Business School", domain: "tsm.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Hogeschool de Kempel", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Duisenberg School of Finance", domain: "dsf.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Hague University of Applied Sciences", domain: "hhs.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Professional Education Schoevers", domain: "schoevers.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Marnix Academy", domain: "marnix.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Business School Nut Tree", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "CAH Vilentum Dronten and Almere", domain: "vilentum.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Dirksen Education", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Havo for Music and Dance", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "University of Applied Sciences IPABO Amsterdam", domain: "ipabo.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "STOAS Wageningen Vilentum University of Applied Sciences", domain: "stoaswag.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Pro Education Amsterdam University of Applied Sciences", domain: "proeducation.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Islamic University Rotterdam", domain: "islamicuniversityrotterdam.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Plant Animal and Technology Plus", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "School for Public Health and Primary Care CAPHRI", domain: "caphri.unimaas.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Transfer group Rotterdam", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "TMO University of Fashion Management", domain: "tmo.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "University of Amsterdam Department of Media Studies", domain: "uva.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Interuniversity Center for Social Science Theory and Methodology", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "NOVI University of Applied Sciences", domain: "novi-hogeschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Reformed University of Applied Sciences", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "DOC Education & Training", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Institute for Psychosynthesis", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Midwifery Academy Amsterdam Groningen", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "University of Applied HBO Netherlands", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Iselinge University of Applied Sciences", domain: "iselinge.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Wittenberg University of Applied Sciences and Equipment Center", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Tyndale Theological Seminary", domain: "tyndale.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Major Seminary Rolduc", domain: "rolduc.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "European Pilot Selection and Training", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "ABC University of Applied Sciences Dordrecht and Surroundings", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "University of Interpretation and Translation", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Schumann Academie University of Professional Education", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Interuniversity Graduate School of Psychometrics and Sociometrics", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Western Netherlands University of Applied Sciences for Translator and Interpreter", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Cornerstone Bible College", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Bible School Training School Foundation 4 Life", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Inter College Business School", domain: "intercollege.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Azusa Theological College", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Utrecht University Infection & Immunity Center", domain: "uu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Bourdon School of Music", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Netherlands School of Primary Care Research", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "National Dutch Graduate School of Polymer Science & Technology", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Netherlands Graduate Research School of Science, Technology and Modern Culture", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Azusa Theological College", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Utrecht University Infection & Immunity Center", domain: "uu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Bourdon School of Music", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Netherlands School of Primary Care Research", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "National Dutch Graduate School of Polymer Science & Technology", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Netherlands Graduate Research School of Science, Technology and Modern Culture", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "De Horst Institute for Social Work", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "SDO University of Applied Sciences Foundation Part-time Education", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "J M Burgerscentrum Research School for Fluid Mechanics", domain: "burgerscentrum.tudelft.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Bernard Lievegoed University", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Cancer Stem cells & Developmental Biology Research School", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Eurythmy Academy The Hague", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Theo Thijssen Academy", domain: "academietheothijssen.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Global University Systems", domain: "globaluniversitysystems.com", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "CAH Vilentum Christian Agricultural College", domain: "vilentum.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Driestar University of Applied Sciences", domain: "driestarhogeschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Royal Tropical Institute (KIT)", domain: "kit.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Stoas University of Applied Sciences", domain: "stoashogeschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Hague University of Applied Sciences", domain: "hhs.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Wittenborg University of Applied Sciences – Wittenborg Business University", domain: "wittenborg.eu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Zuyd University of Applied Sciences", domain: "zuyd.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "United International Business Schools (UIBS)", domain: "uibs.eu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Rotterdam School of Management, Erasmus University", domain: "rsm.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Saxion Universities of Professional Education", domain: "saxion.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Hogeschool Zuyd", domain: "zuyd.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Van Hall Larenstein, University of Applied Sciences", domain: "vanhalllarenstein.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Amsterdam University College (AUC)", domain: "auc.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Tias Business School", domain: "tias.edu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Hague University of Applied Sciences", domain: "hhs.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Wetsus Academy", domain: "wetsus.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Amsterdam Business School", domain: "abs.uva.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Faculty of Health, Medicine and Life Sciences", domain: "maastrichtuniversity.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Holland Education Consortium", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Windesheim University of Applied Sciences", domain: "windesheim.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Scholar Ship", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Erasmus School of Economics", domain: "ese.eur.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Utrecht University", domain: "uu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Saxion University of Applied Sciences", domain: "saxion.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "TIAS School for Business and Society", domain: "tias.edu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "European Leadership University", domain: "elu.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Amsterdam University of Applied Sciences", domain: "hhs.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Jheronimus Academy of Data Science (JADS)", domain: "jads.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Studyportals", domain: "studyportals.com", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Elevate Academy", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "IMF Academy", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Maastricht University - Center for European Studies", domain: "maastrichtuniversity.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Wink Academy", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Maastricht Summer School", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Energy Delta Institute", domain: "edi.rug.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Utrecht Summer School", domain: "summeruniversity.eu", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "International Business School, The Hague", domain: "ibsh.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "ESTIEM (European Students of Industrial Engineering and Management)", domain: "estiem.org", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The BD School", domain: "bdschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The International ARLT Foundation", domain: "arltfoundation.org", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Rotterdam Business School", domain: "rotterdambusinessschool.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "St. Joost Master Institute for Visual Cultures", domain: "stjoostmasters.com", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "HZ University of Applied Sciences", domain: "hz.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Netherlands Maritime University", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Codarts Rotterdam", domain: "codarts.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Holland International Study Centre (ISC)", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Inholland University of Applied Sciences", domain: "inholland.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Global School for Entrepreneurship", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Amsterdam University College", domain: "auc.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "The Hague Pathway College", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Global School for Entrepreneurship & SRH - Haarlem Campus", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Erasmus University College", domain: "euc.eur.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Twente Pathway College", domain: null, region: "Europe", country: "Netherlands", isVerified: false },
  { name: "Team Academy", domain: "teamacademy.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Amsterdam International College (AIU College)", domain: "aiucollege.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Johan Cruyff Institute", domain: "cruyffinstitute.org", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Maastricht University", domain: "maastrichtuniversity.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Leiden University College The Hague (LUC The Hague)", domain: "luc.leidenuniv.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "Nuffic Neso India", domain: "nesoindia.nl", region: "Europe", country: "Netherlands", isVerified: true },
  { name: "ETS Global B.V. Academic & Business Assessments Strawinskylaan", domain: "etsglobal.org", region: "Europe", country: "Netherlands", isVerified: true },

]