import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Nicaragua_universities = [

  // Nicaragua

  { name: "Universidad Nacional Autónoma de Nicaragua, Managua", domain: "unan.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional Agraria", domain: "una.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional Autónoma de Nicaragua, León", domain: "unanleon.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional de Ingeniería", domain: "uni.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Americana, Nicaragua", domain: "uam.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de las Regiones Autónomas de la Costa Caribe Nicaragüense", domain: "uraccan.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Católica Redemptoris Mater", domain: "ucrm.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de Ciencias Comerciales", domain: "ucc.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Central de Nicaragua", domain: "ucn.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad del Valle, Nicaragua", domain: "uvn.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Martín Lutero", domain: "uml.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Centroamericana de Ciencias Empresariales", domain: "ucem.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Iberoamericana de Ciencia y Tecnología", domain: "unicit.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Bluefields Indian and Caribbean University", domain: "bicu.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Thomas More", domain: "utm.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Tecnológica La Salle", domain: "ulsa.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional Francisco Luis Espinoza Pineda", domain: "unfesp.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Keiser University Latin American Campus", domain: "keiseruniversity.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional Politécnica", domain: "unp.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de Managua", domain: "uman.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },  
  { name: "Universidad Internacional Antonio de Valdivieso", domain: "uniav.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad American College", domain: "americancollege.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de Tecnología y Comercio", domain: "unitec.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Anunciata", domain: "uanunciata.com", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de las Américas, Nicaragua", domain: "ulam.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nicaragüense de Ciencia y Tecnología", domain: "ucyt.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de Ciencias Médicas, Nicaragua", domain: "ucm.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Internacional para el Desarrollo Sostenible", domain: "unides.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional Multidisciplinaria Ricardo Morales Avilés", domain: "unm.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Técnica de Comercio", domain: "utc.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Jean Jacques Rousseau", domain: "unijjar.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Tecnológica Nicaragüense", domain: null, region: "North America", country: "Nicaragua", isVerified: false },
  { name: "La American University", domain: "laamericanuniversity.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Nacional Padre Gaspar García Laviana", domain: "uncpggl.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad de Ciencias de la Salud y Energías Renovables", domain: "ucser.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Internacional de Integración de América Latina", domain: "univalnicaragua.com", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Autonoma de Chinandega", domain: "uach.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Hispanoamericana, Nicaragua", domain: "uhispam.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Popular de Nicaragua", domain: "uponic.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Católica Inmaculada Concepción de la Arquidiócesis de Managua", domain: null, region: "North America", country: "Nicaragua", isVerified: false },
  { name: "Universidad de Occidente UDO", domain: "udomanagua.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
  { name: "Universidad Evangélica Nicaragüense Martin Luther King", domain: "uenicmlk.edu.ni", region: "North America", country: "Nicaragua", isVerified: true },
]