import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Nigeria_universities = [

   // Nigeria

   { name: "University of Lagos", domain: "unilag.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Ibadan", domain: "ui.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Port Harcourt", domain: "uniport.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Covenant University", domain: "covenantuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Nigeria", domain: "unn.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Obafemi Awolowo University", domain: "oauife.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ahmadu Bello University", domain: "abu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Oye-Ekiti", domain: "fuoye.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Benin", domain: "uniben.edu", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Olabisi Onabanjo University", domain: "oouagoiwoye.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Lagos State University", domain: "lasu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Ilorin", domain: "unilorin.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University of Technology, Akure", domain: "futa.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Babcock University", domain: "babcock.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Abuja", domain: "uniabuja.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University of Agriculture, Abeokuta", domain: "funaab.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Afe Babalola University", domain: "abuad.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ladoke Akintola University of Technology", domain: "lautech.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Alex Ekwueme Federal University", domain: "aefunai.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University of Technology, Minna", domain: "futminna.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Rivers State University", domain: "riversstateuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Nnamdi Azikiwe University", domain: "unizik.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Jos", domain: "unijos.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ekiti State University, Ado Ekiti", domain: "eksu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Godfrey Okoye University", domain: "gouni.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Adekunle Ajasin University", domain: "aaua.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Nile University of Nigeria", domain: "nun.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Bayero University Kano", domain: "buk.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Thomas Adewumi University", domain: "tau.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Uyo", domain: "uniuyo.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Lokoja", domain: "fulokoja.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Lafia", domain: "fulafia.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kwara State University", domain: "kwasu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Landmark University", domain: "lmu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University of Technology, Owerri", domain: "futo.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Edo State University Uzairue", domain: "esu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Delta State University, Abraka", domain: "delsu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Redeemer's University", domain: "run.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Pan-Atlantic University", domain: "pau.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Osun State University", domain: "uniosun.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "American University of Nigeria", domain: "aun.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Usmanu Danfodio University", domain: "udu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Caleb University", domain: "calebuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Bauchi State University", domain: "basug.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Mcpherson University", domain: "mpu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "African University of Science and Technology", domain: null, region: "Africa", country: "Nigeria", isVerified: false },
   { name: "University of Calabar", domain: "unical.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Lead City University", domain: "lcu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Maiduguri", domain: "unimaid.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Veritas University", domain: "veritas.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Dutsin-Ma", domain: "fudutsinma.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Abubakar Tafawa Balewa University", domain: "atbu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Bowen University", domain: "bowen.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Southwestern University, Nigeria", domain: "swuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Enugu State University of Science and Technology", domain: "esut.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ebonyi State University", domain: "ebsu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Michael Okpara University of Agriculture", domain: "mouau.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University of Petroleum Resources", domain: "fupre.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Umaru Musa Yar'Adua University", domain: "umyu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Baze University", domain: "bazeuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Benson Idahosa University", domain: "biu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Nasarawa State University", domain: "nsuk.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Chukwuemeka Odumegwu Ojukwu University", domain: "coou.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Tai Solarin University of Education", domain: "tasued.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Bells University of Technology", domain: "bellsuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Adeleke University", domain: "adelekeuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Abia State University", domain: "abiastateuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Niger Delta University", domain: "ndu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Medical Sciences", domain: "unimed.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Elizade University", domain: "elizadeuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Benue State University", domain: "bsum.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "The Technical University", domain: "techuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: false },
   { name: "Fountain University, Osogbo", domain: "fuo.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Al-Hikmah University", domain: "alhikmah.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Birnin Kebbi", domain: "fubk.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ambrose Alli University", domain: "aaue.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Dutse", domain: "fud.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Skyline University Nigeria", domain: "sun.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Bingham University", domain: "binghamuni.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kaduna State University", domain: "kasu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },    
   { name: "Prince Abubakar Audu University", domain: "pabuau.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Northwest University, Kano", domain: "nwu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Mountain Top University", domain: "mountaintop.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Akwa Ibom State University", domain: "aksu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Modibbo Adama University, Yola", domain: "mautech.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Taraba State University", domain: "tarbatech.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Sule Lamido University", domain: "sulelamido.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ajayi Crowther University", domain: "acu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Igbinedion University Okada", domain: "igbuni.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Anchor University, Lagos", domain: "anchoruniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Otuoke", domain: "fuotuoke.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Joseph Sarwuan Tarka University", domain: "jstu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Achievers University, Owo", domain: "achievers.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Gregory University, Uturu", domain: "guu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Madonna University, Nigeria", domain: "madonnauniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Sokoto State University", domain: "ssu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ibrahim Badamasi Babangida University", domain: "ibbu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Joseph Ayo Babalola University", domain: "jabu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ondo State University of Science and Technology", domain: "osustech.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kano University of Science and Technology, Wudil", domain: "kustwudil.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },    
   { name: "University of Cross River State", domain: "unical.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Dominican University, Ibadan", domain: "dominicanuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Imo State University", domain: "imsu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Kashere", domain: "fukashere.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Rhema University", domain: "rhemauniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Crescent University, Abeokuta", domain: "crescentuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti", domain: "boueti.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Crawford University", domain: "crawforduniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Edwin Clark University", domain: "ecu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Gombe State University", domain: "gombestateuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Summit University, Offa", domain: "summituniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Novena University", domain: "novenauniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Wesley University of Science and Technology", domain: "wesleyuni.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Gusau", domain: "fugusau.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kola Daisi University", domain: "koladaisiuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Glorious Vision University", domain: "gvu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kebbi State University of Science and Technology", domain: "ksust.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Moshood Abiola Polytechnic", domain: "mapoly.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Wukari", domain: "fuwukari.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Adamawa State University", domain: "adasu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Oduduwa University", domain: "oduduwauniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Africa", domain: "uoa.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ignatius Ajuru University of Education", domain: "iaue.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Augustine University", domain: "augustineuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Yobe State University", domain: "ysu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Paul University", domain: "pauluniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Federal University, Gashua", domain: "fugashua.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Admiralty University of Nigeria", domain: "adun.edu.ng", region: "Africa", country: "Nigeria", isVerified: false },
   { name: "Caritas University", domain: "caritasuni.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Salem University", domain: "salemuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kingsley Ozumba Mbadiwe University", domain: "komu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Tansian University", domain: "tansianuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kings University", domain: "kingsuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Obong University", domain: "obonguniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Plateau State University", domain: "pstu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Kwararafa University", domain: "kwararafauniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Renaissance University", domain: "renuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Chrisland University", domain: "chrislanduniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "University of Mkar", domain: "unimkar.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Hallmark University", domain: "hallmarkuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Western Delta University", domain: "wdu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Coal City University", domain: "ccu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Al-Qalam University, Katsina", domain: "alqalamuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Christopher University", domain: "christopheruniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Hezekiah University", domain: "hezekiahuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Mewar International University", domain: "mewaruniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Clifford University", domain: "clifforduniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Evangel University, Akaeze", domain: "evangeluniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Atiba University", domain: "atibauniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Ritman University", domain: "ritmanuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Legacy University, Okija", domain: "legacyuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Arthur Jarvis University", domain: "arthurjarvisuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "PAMO University of Medical Sciences", domain: "pamoscience.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Michael and Cecilia Ibru University", domain: "mciu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Precious Cornerstone University", domain: "pcu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Eko University of Medical and Health Sciences", domain: "ekoumh.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Nigerian Maritime University, Okerenkoko", domain: "nmu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Wellspring University", domain: "wellspringuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Borno State University", domain: "bosu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Zamfara State University", domain: "zasu.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Spiritan University Nneochi", domain: "spiritanuniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Peaceland University, Enugu", domain: "peacelanduni.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Karl Kumm University, Vom", domain: "kku.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Gombe State University of Science and Technology, Kumo", domain: "gsust.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
   { name: "Crown Hill University", domain: "crownhilluniversity.edu.ng", region: "Africa", country: "Nigeria", isVerified: true },
]