import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Pakistan_universities = [

    // Pakistan

    { name: "Lahore University of Management Sciences", domain: "lums.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Aga Khan University", domain: "aku.edu", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of the Punjab", domain: "pu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National University of Sciences and Technology", domain: "nust.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "COMSATS University Islamabad", domain: "comsats.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Institute of Business Administration", domain: "iba.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Central Punjab", domain: "ucp.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National University of Computer and Emerging Sciences", domain: "nu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Management and Technology", domain: "umt.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Quaid-i-Azam University", domain: "qau.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Bahria University", domain: "bahria.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Engineering and Technology, Lahore", domain: "uet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "International Islamic University, Islamabad", domain: "iiui.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Health Sciences, Lahore", domain: "uhs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The University of Lahore", domain: "uol.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Sindh", domain: "usindh.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Government College University, Lahore", domain: "gcu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Riphah International University", domain: "riphah.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Peshawar", domain: "upesh.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "NED University of Engineering and Technology", domain: "neduet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Agriculture, Faisalabad", domain: "uaf.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Bahauddin Zakariya University", domain: "bzu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Pakistan Institute of Development Economics", domain: "pide.org.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National University of Modern Languages", domain: "numl.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Islamia University of Bahawalpur", domain: "iub.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Iqra University", domain: "iqra.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Mehran University of Engineering and Technology", domain: "muet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Sargodha", domain: "uos.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology", domain: "gik.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Khyber Medical University", domain: "kmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Government College University, Faisalabad", domain: "gcuf.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Liaquat University of Medical and Health Sciences", domain: "lumhs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Forman Christian College", domain: "fccollege.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Education", domain: "ue.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "DOW University of Health Sciences", domain: "duhs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Karachi", domain: "uok.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Superior University", domain: "superior.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sukkur Institute of Business Administration", domain: "iba-suk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Karachi Institute of Economics and Technology", domain: "kiet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Institute of Business Management", domain: "iobm.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shifa Tameer-e-Millat University", domain: "stmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sir Syed University of Engineering and Technology", domain: "ssuet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology", domain: "szabist.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Pakistan Institute of Engineering and Applied Sciences", domain: "pieas.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Pir Mehr Ali Shah Arid Agriculture University", domain: "uaar.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Air University", domain: "au.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Information Technology University", domain: "itu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Hazara University", domain: "hu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Habib University", domain: "habib.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Veterinary and Animal Sciences", domain: "uvas.edu.pk", region: "Asia", country: "Pakistan", isVerified: true }, 
    { name: "University of Gujrat", domain: "uog.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Balochistan University of Information Technology, Engineering and Management Sciences", domain: "buitems.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Fatima Jinnah Women University", domain: "fjwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Engineering and Technology, Taxila", domain: "uettaxila.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ziauddin University", domain: "zu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sindh Madresatul Islam University", domain: "smiu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National Textile University", domain: "ntu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Institute of Space Technology", domain: "ist.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Federal Urdu University of Arts, Sciences and Technology", domain: "fuuast.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "King Edward Medical University", domain: "kemu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The University of Agriculture, Peshawar", domain: "aup.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lahore College for Women University", domain: "lcwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lahore Garrison University", domain: "lgu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Jinnah University for Women", domain: "jinnah.edu", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "DHA Suffa University", domain: "dsu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National Defence University", domain: "ndu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Hamdard University", domain: "hamdard.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Foundation University Islamabad", domain: "fui.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Qurtaba University of Science and Information Technology", domain: "qurtuba.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Capital University of Science and Technology", domain: "cust.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Azad Jammu and Kashmirs", domain: "ajku.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Balochistan", domain: "uob.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National University of Medical Sciences", domain: "nums.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lahore University of Biological and Applied Sciences", domain: null, region: "Asia", country: "Pakistan", isVerified: false },
    { name: "Minhaj University", domain: "mul.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Baltistan, Skardu", domain: "uobs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The University of Faisalabad", domain: "tuf.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National College of Arts", domain: "nca.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Mohammad Ali Jinnah University", domain: "maju.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Institute of Management Sciences", domain: "imsciences.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Kinnaird College for Women", domain: "kinnaird.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "GIFT University", domain: "gift.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Abdul Wali Khan University Mardan", domain: "awkum.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Isra University", domain: "isra.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sindh Institute of Medical Sciences", domain: null, region: "Asia", country: "Pakistan", isVerified: false },
    { name: "Jinnah Sindh Medical University", domain: "jsmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Quaid-e-Awam University of Engineering, Science and Technology", domain: "quest.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Beaconhouse National University", domain: "bnu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shah Abdul Latif University", domain: "salu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Engineering and Technology, Peshawar", domain: "uetpeshawar.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "ILMA University", domain: "ilmauniversity.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Karakurum International University", domain: "kiu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lahore School of Economics", domain: "lse.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Chitral", domain: "uoch.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Abbottabad University of Science and Technology", domain: "aust.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Malakand", domain: "uom.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Zulfiqar Ali Bhutto Medical University", domain: "szabmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Haripur", domain: "uoh.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Kohat University of Science and Technology", domain: "kust.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Southern Punjab", domain: "usp.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of South Asia", domain: "usa.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Indus University, Pakistan", domain: "indus.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Balochistan University of Engineering and Technology", domain: "buetk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Mirpur University of Science and Technology", domain: "must.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sarhad University of Science and Information Technology", domain: "sarhad.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Faisalabad Medical University", domain: "fmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Khwaja Fareed University of Engineering & Information Technology", domain: "kfueit.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Indus Valley School of Art and Architecture", domain: "ivs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "City University of Science and Information Technology", domain: "cusit.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Benazir Bhutto Women University", domain: "sbbwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "CECOS University", domain: "cecos.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Gomal University", domain: "gomal.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sindh Agriculture University", domain: "sau.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Rawalpindi Medical University", domain: "rmur.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Namal University", domain: "namal.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Hajvery University", domain: "hup.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Swat", domain: "uswat.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sardar Bahadur Khan Women's University", domain: "sbkwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Muhammad Nawaz Shareef University of Agriculture, Multan", domain: "mnsuam.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Baqai Medical University", domain: "baqai.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National University of Technology", domain: "nutech.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Government College Women University, Faisalabad", domain: "gcwuf.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "KASB Institute of Technology", domain: "kasbit.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Okara", domain: "uo.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sir Syed CASE Institute of Technology", domain: "case.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National College of Business Administration and Economics", domain: "ncbae.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lahore Leads University", domain: "leads.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Textile Institute of Pakistan", domain: "tip.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology", domain: "paf-iast.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Pakistan Institute of Fashion and Design", domain: "pifd.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Preston University", domain: "preston.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Gandhara University", domain: "gandhara.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Abasyn University", domain: "abasyn.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Wah", domain: "uow.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Islamia College Peshawar", domain: "icp.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Bacha Khan University", domain: "bkuc.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "HITEC University", domain: "hitecuni.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Greenwich University", domain: "greenwich.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Al-Hamd Islamic University", domain: "aiu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Sialkot", domain: "uskt.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Northern University", domain: "northern.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Dawood University of Engineering and Technology", domain: "duet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Women University Multan", domain: "wum.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Science and Technology, Bannu", domain: "ustb.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lasbela University of Agriculture, Water and Marine Sciences", domain: "luawms.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National Skills University", domain: "nsu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Benazir Bhutto University", domain: "sbbu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Karachi School for Business and Leadership", domain: "ksbl.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Government College Women University, Sialkot", domain: "gcwus.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Mohi-ud-Din Islamic University", domain: "miu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Green International University", domain: "tgiu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Nishtar Medical University", domain: "nmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ghazi University", domain: "ghazi.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Peoples University of Medical and Health Sciences for Women", domain: "pumhs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Dadabhoy Institute of Higher Education", domain: "dadabhoy.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Rawalpindi Women University", domain: "rwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Mohtarma Benazir Bhutto Medical University", domain: "smbbmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Turbat", domain: "uot.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Engineering and Applied Sciences Swat", domain: "ueas.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Benazir Bhutto Shaheed University Lyari", domain: "bbsul.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Iqra National University", domain: "inu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Bolan University of Medical and Health Sciences", domain: "bumhs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Government Sadiq College Women University", domain: "gscwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Poonch Rawalakot", domain: "upr.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Salim Habib University", domain: "shu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Newports Institute of Communications and Economics", domain: "newports.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Fatima Jinnah Medical University", domain: "fjmu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Imperial College of Business Studies", domain: "imperial.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Institute for Art and Culture", domain: "iac.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ibadat International University", domain: "ibadat.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Emerson University, Multan", domain: "eum.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Child Health Sciences", domain: "uchs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Lakki Marwat", domain: "ulm.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Loralai", domain: "uoli.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Women University Mardan", domain: "wumardan.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Grand Asian University, Sialkot", domain: "gaus.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Institute of Management Sciences, Lahore", domain: "pakaims.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Sahiwal", domain: "uosahiwal.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Engineering and Technology, Mardan", domain: "uetmardan.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "NFC Institute of Engineering and Technology", domain: "nfciet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Muhammad Nawaz Sharif University of Engineering and Technology", domain: "mnsuet.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Buner", domain: "ubuner.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Home Economics, Lahore", domain: "uhe.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Swabi", domain: "uoswabi.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Gambat Institute of Medical Sciences", domain: "gims.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Nur International University", domain: "niu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Muslim Youth University", domain: "myu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Kotli Azad Jammu and Kashmir", domain: "uokajk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Mianwali", domain: "umw.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Benazir Bhutto University Shaheed Benazirabad", domain: "sbbusba.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },                            
    { name: "Baba Guru Nanak University", domain: "bgnu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Al-Khair University", domain: "alkhair.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Chenab", domain: "uchenab.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Gwadar", domain: "ug.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Kohsar University Murree", domain: "kum.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Qarshi University", domain: "qu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Allah Buksh Soomro University of Arts, Design and Heritages", domain: "sabsu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The Shaikh Ayaz University Shikarpur", domain: "saus.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "UIT University, Karachi", domain: "uitu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ali Institute of Education", domain: "aie.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Government College University, Hyderabad", domain: "gcuh.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Commecs Institute of Business and Emerging Sciences", domain: "commecsinstitute.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Women University Swabi", domain: "wus.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Cholistan University of Veterinary and Animal Sciences", domain: "cuvas.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Aror University of Art, Architecture, Design and Heritage", domain: "aror.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Millennium Institute of Technology and Entrepreneurship", domain: "mite.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Khushal Khan Khattak University", domain: "kkkuk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Nazeer Hussain University", domain: "nhu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Zulfiqar Ali Bhutto University of Law", domain: "szabul.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Narowal", domain: "uon.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Jhang", domain: "uoj.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Thal University", domain: "tu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sohail University", domain: "sohailuniversity.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Chakwal", domain: "uoc.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Al-Ghazali University", domain: "agu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Multan University of Science and Technology", domain: "multanust.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Begum Nustrat Bhutto Women University", domain: "bnbwu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Al-Kawthar University", domain: "alkawthar.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Punjab Tianjin University of Technology", domain: "ptut.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Benazir Bhutto Shaheed University of Technology and Skill Development", domain: "bbsutsd.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Punjab University of Technology", domain: "put.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "International Institute of Science, Arts and Technology", domain: "iisat.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Rashid Latif Khan University", domain: "rlku.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "FATA University", domain: "fatu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Karachi Institute of Technology and Entrepreneurship", domain: "kite.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Emaan Institute of Management and Sciences", domain: "eims.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Women University of Azad Jammu and Kashmir Bagh", domain: "wuajk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Benazir Bhutto University of Veterinary and Animal Sciences", domain: "sbbvavs.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Layyah", domain: "uolayyah.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Metropolitan University Karachi", domain: "muk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Lahore Institute of Science and Technology", domain: "list.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The University of Agriculture, D. I. Khan", domain: "uadikh.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Sufism and Modern Sciences", domain: "usms.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ghazi National Institute of Engineering and Sciences", domain: "gnies.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The University of Modern Sciences", domain: "ums.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Benazir Bhutto City University", domain: "sbbcu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Malir University of Science and Technology", domain: "mustk.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Sindh Institute of Management and Technology", domain: "simt.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Art and Culture, Jamshoro", domain: "uacj.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Dar-ul-Madina International University", domain: "dmiu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Pakistan Global Institute", domain: "pgi.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Al-Karam International Institute", domain: "akaii.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "The University of Agriculture, Swat", domain: "uaswat.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Hands-Institute of Development Studies", domain: "hids.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "National University of Pakistan", domain: "nup.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Shaheed Benazir Bhutto Dewan University", domain: "sbbdu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Ibn-e-Sina University", domain: "isu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "Saifee Burhani University", domain: "sbu.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
    { name: "University of Makran", domain: "uomakran.edu.pk", region: "Asia", country: "Pakistan", isVerified: true },
]