import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Peru_universities = [

   // Peru

   { name: "Pontificia Universidad Católica del Perú", domain: "pucp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Mayor de San Marcos", domain: "unmsm.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana de Ciencias Aplicadas", domain: "upc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Tecnológica del Perú", domain: "utp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Ingeniería", domain: "uni.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad César Vallejo", domain: "ucv.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de Lima", domain: "ulima.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad del Pacífico", domain: "up.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Hermilio Valdizán", domain: "unheval.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada del Norte", domain: "upn.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de Piura", domain: "udep.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de San Martín de Porres", domain: "usmp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Católica de Santa María", domain: "ucsm.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana Cayetano Heredia", domain: "upch.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Científica del Sur", domain: "ucs.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad San Ignacio de Loyola", domain: "usil.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Agraria La Molina", domain: "unalm.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Trujillo", domain: "unitru.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de San Agustín de Arequipa", domain: "unsa.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad ESAN", domain: "esan.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Ricardo Palma", domain: "urp.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional de San Antonio Abad del Cusco", domain: "unsaac.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Privada Antenor Orrego", domain: "upao.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Continental", domain: "continental.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Peruana Unión", domain: "upeu.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Católica San Pablo", domain: "ucsp.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Privada Norbert Wiener", domain: "uwiener.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional San Luis Gonzaga", domain: "unica.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Andina Néstor Cáceres Velásquez", domain: "uancv.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Católica Santo Toribio de Mogrovejo", domain: "usat.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad de Ingeniería y Tecnología", domain: "utec.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional del Centro del Perú", domain: "uncp.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional Federico Villarreal", domain: "unfv.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Señor de Sipán", domain: "uss.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Andina del Cusco", domain: "uandina.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional del Callao", domain: "unac.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Femenina del Sagrado Corazón", domain: "unife.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional de Educación Enrique Guzmán y Valle", domain: "une.edu.pe", region: "South America", country: "Peru", isVerified: true },  
   { name: "Universidad Nacional Jorge Basadre Grohmann", domain: "unjbg.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional José Faustino Sánchez Carrión", domain: "unjfsc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Alas Peruanas", domain: "uap.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Cajamarca", domain: "unc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Católica Sedes Sapientiae", domain: "uss.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana Los Andes", domain: "upla.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Pedro Ruíz Gallo", domain: "unprg.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada de Tacna", domain: "upt.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Huancavelica", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad Nacional de Piura", domain: "unp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada San Juan Bautista", domain: "upsjb.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Antonio Ruiz de Montoya", domain: "uram.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Inca Garcilaso de la Vega", domain: "universidad.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional del Santa", domain: "uns.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Santiago Antúnez de Mayolo", domain: "unsam.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Tumbes", domain: "unt.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Daniel Alcides Carrión", domain: "undac.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de San Martín", domain: "unasam.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de la Amazonía Peruana", domain: "unap.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de Ciencias y Humanidades", domain: "uch.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Toribio Rodríguez de Mendoza", domain: "untrm.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional José Faustino Sánchez Carrión", domain: "unjfsc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Alas Peruanas", domain: "uap.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Cajamarca", domain: "unc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Católica Sedes Sapientiae", domain: "uss.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana Los Andes", domain: "upla.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Pedro Ruíz Gallo", domain: "unprg.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada de Tacna", domain: "upt.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Huancavelica", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad Nacional de Piura", domain: "unp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada San Juan Bautista", domain: "upsjb.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Antonio Ruiz de Montoya", domain: "uram.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Inca Garcilaso de la Vega", domain: "universidad.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional del Santa", domain: "uns.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Santiago Antúnez de Mayolo", domain: "unsam.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Tumbes", domain: "unt.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Daniel Alcides Carrión", domain: "undac.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de San Martín", domain: "unasam.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de la Amazonía Peruana", domain: "unap.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de Ciencias y Humanidades", domain: "uch.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Toribio Rodríguez de Mendoza", domain: "untrm.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Moquegua", domain: "unam.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de Huánuco", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad Nacional de Ucayali", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad de Ciencias y Artes de América Latina", domain: "ucal.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad San Pedro", domain: "usp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad María Auxiliadora", domain: "uma.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Católica de Trujillo Benedicto XVI", domain: "ucat.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Autónoma del Perú", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad Nacional Micaela Bastidas de Apurímac", domain: "unamba.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad José Carlos Mariátegui", domain: "ujcm.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Marcelino Champagnat", domain: "champagnat.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Autónoma de Ica", domain: "uai.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Tecnológica de Lima Sur", domain: "unatels.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional José María Arguedas", domain: "unajma.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Cañete", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad Particular de Chiclayo", domain: "upch.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Jaén", domain: "unj.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Científica del Perú", domain: "ucip.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad La Salle, Peru", domain: "lasalle.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Le Cordon Bleu", domain: "lecordonbleu.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Barranca", domain: "unab.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional del Altiplano", domain: "unap.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Amazónica de Madre de Dios", domain: "unamad.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Autónoma de Chota", domain: "unach.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Frontera", domain: "unf.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Autónoma de Alto Amazonas", domain: "unaaa.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Latinoamericana CIMA", domain: "ulc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada de Huancayo Franklin Roosevelt", domain: "uroosevelt.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Jaime Bausate y Meza", domain: "bausate.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Intercultural de la Amazonía", domain: "unia.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Autónoma de Huanta", domain: "unah.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de Juliaca", domain: "unaj.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada TELESUP", domain: "utelesup.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana de las Américas", domain: "ulasamericas.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Intercultural de Bagua", domain: "unibagua.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana de Ciencias e Informatica", domain: "upci.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana Austral del Cusco", domain: "uaustral.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Intercultural de la Selva Central", domain: "uniscjsa.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada de Pucallpa", domain: "upp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada San Carlos", domain: "upsc.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada Peruano Alemana", domain: "upal.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Santo Domingo de Guzmán", domain: "usdg.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Interamericana para el Desarrollo, Peru", domain: "unidx.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional de San Cristóbal de Huamanga", domain: "unsch.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana del Centro", domain: "upecen.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada de Trujillo", domain: "uprit.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Ciro Alegría", domain: "unca.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Politécnica Amazónica", domain: "upa.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada Líder Peruana", domain: "ulp.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Sergio Bernales", domain: "upsb.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad de Ayacucho Federico Froebel", domain: "froebel.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada Juan Mejía Baca", domain: "umb.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada Autónoma del Sur", domain: "upads.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana de Integración Global", domain: "upig.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Peruana Simón Bolivar", domain: "usb.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Arzobispo Loayza", domain: "ual.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Tecnológica de San Juan de Lurigancho", domain: "untsjl.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Agraria de la Selva", domain: "unas.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Autónoma Municipal de Los Olivos", domain: null, region: "South America", country: "Peru", isVerified: false },
   { name: "Universidad Nacional Autónoma de Tayacaja", domain: "unat.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Autónoma Altoandina de Tarma", domain: "unaat.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Nacional Intercultural de Quillabamba", domain: "uniq.edu.pe", region: "South America", country: "Peru", isVerified: true },
   { name: "Universidad Privada Antonio Guillermo Urrelo", domain: "upagu.edu.pe", region: "South America", country: "Peru", isVerified: true },
]