import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Phillippines_universities = [

    // Philippines

    { name: "University of the Philippines Diliman", domain: "upd.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Polytechnic University of the Philippines", domain: "pup.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Ateneo de Manila University", domain: "ateneo.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "De La Salle University", domain: "dlsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Philippines System", domain: "up.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Santo Tomas", domain: "ust.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Philippines Los Baños", domain: "uplb.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Ateneo de Davao University", domain: "addu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Philippines Manila", domain: "upm.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Our Lady of Fatima University", domain: "fatima.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "De La Salle-College of Saint Benilde", domain: "benilde.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of San Carlos", domain: "usc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Xavier University-Ateneo de Cagayan", domain: "xu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Batangas State University", domain: "batstate-u.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Mindanao State University - Iligan Institute of Technology", domain: "msuiit.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Adamson University", domain: "adamson.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Southeastern Philippines", domain: "usep.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Silliman University", domain: "su.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Mapúa University", domain: "mapua.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Saint Louis University, Baguio City", domain: "slu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Ateneo de Naga University", domain: "adnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Asian Institute of Management", domain: "aim.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Mindanao", domain: "umindanao.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Eastern Visayas State University", domain: "evsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "National University, Philippines", domain: "national-u.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Visayas State University", domain: "vsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Far Eastern University", domain: "feu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of San Jose-Recoletos", domain: "usjr.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Central Mindanao University", domain: "cmu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Technological University of the Philippines", domain: "tup.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Central Philippine University", domain: "cpu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Philippines in the Visayas", domain: "upv.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Adventist International Institute of Advanced Studies", domain: "aiias.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cavite State University", domain: "cvsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Lyceum of the Philippines University", domain: "lpu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Asia and the Pacific", domain: "uap.asia", region: "Asia", country: "Philippines", isVerified: true },
    { name: "New Era University", domain: "neu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Science and Technology of Southern Philippines", domain: "ustp.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Cebu", domain: "uc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "De La Salle Medical and Health Sciences Institute", domain: "dlsmhsi.edu.ph", region: "Asia", country: "Philippines", isVerified: true },  
    { name: "University of the East", domain: "ue.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Perpetual Help System DALTA", domain: "perpetualdalta.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Philippine Christian University", domain: "pcu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Centro Escolar University", domain: "ceu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Baguio", domain: "ubaguio.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Philippines Baguio", domain: "upb.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Bicol University", domain: "bicol-u.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Batangas", domain: "ub.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Ateneo de Zamboanga University", domain: "adzu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Pamantasan ng Lungsod ng Maynila", domain: "plm.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Miriam College", domain: "mc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Southern Mindanao", domain: "usm.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Emilio Aguinaldo College", domain: "eac.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Philippine Normal University", domain: "pnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Mariano Marcos State University", domain: "mmsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "De La Salle Lipa", domain: "dlsl.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Western Mindanao State University", domain: "wmsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Misamis University", domain: "mu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Technological Institute of the Philippines", domain: "tip.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "West Visayas State University", domain: "wvsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Philippines Mindanao", domain: "upmin.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cebu Technological University", domain: "ctu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Universidad de Zamboanga", domain: "uz.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Mindanao State University", domain: "msumain.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Caraga State University", domain: "carsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Don Honorio Ventura Technological State University", domain: "dhvsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Immaculate Conception", domain: "uic.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of St. La Salle", domain: "usls.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Tarlac State University", domain: "tsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Adventist University of the Philippines", domain: "aup.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Angeles University Foundation", domain: "auf.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Asia Pacific College", domain: "apc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "San Beda University", domain: "sanbeda.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Nueva Caceres", domain: "unc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Central Luzon State University", domain: "clsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Holy Angel University", domain: "hau.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the East Ramon Magsaysay", domain: "uerm.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "John B. Lacson Foundation Maritime University", domain: "jblfmu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Sacred Heart College", domain: "sacredheartcollege.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cebu Normal University", domain: "cnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Saint Mary's University of Bayombong", domain: "smu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Manila Central University", domain: "mcu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Lorma Colleges", domain: "lorma.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Manuel S. Enverga University Foundation", domain: "msenverga.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Bulacan State University", domain: "bulsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Bohol Island State University", domain: "bisu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cagayan State University", domain: "csu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Benguet State University", domain: "bsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "FEU Institute of Technology", domain: "feutech.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Holy Cross of Davao College", domain: "hcdc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Trinity University of Asia", domain: "tua.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Cordilleras", domain: "uc-bcf.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Negros Occidental - Recoletos", domain: "uno-r.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Bataan Peninsula State University", domain: "bpsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cebu Institute of Technology", domain: "cit.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Southern Leyte State University", domain: "slsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Nueva Ecija University of Science and Technology", domain: "neust.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Chiang Kai Shek College", domain: "cksc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "José Rizal University", domain: "jru.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Saint Louis", domain: "usl.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Bukidnon State University", domain: "buksu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Tarlac Agricultural University", domain: "tca.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Aquinas University of Legazpi", domain: "aquinas.edu.ph", region: "Asia", country: "Philippines", isVerified: false },
    { name: "University of Perpetual Help System Jonelta", domain: "uphsl.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Pangasinan State University", domain: "psu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Don Mariano Marcos Memorial State University", domain: "dmmmsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "AMA Computer University", domain: "ama.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Colegio de San Juan de Letran", domain: "letran.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "The Philippine Women's University", domain: "pwu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Aklan State University", domain: "asu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Rizal Technological University", domain: "rtu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Urdaneta City University", domain: "ucu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "National Defense College of the Philippines", domain: "ndcp.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Davao Doctors College", domain: "davdocs.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Arellano University", domain: "arellano.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Visayas", domain: "uv.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Southwestern University - PHINMA", domain: "swu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Iloilo Science and Technology University", domain: "istu.edu.ph", region: "Asia", country: "Philippines", isVerified: false },
    { name: "University of Bohol", domain: "universityofbohol.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Scholastica's College", domain: "ssc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Paul University Philippines", domain: "spup.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cebu Doctors' University", domain: "cebudoctorsuniversity.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Saint Jude College", domain: "sjc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Luke's College of Medicine - WHQM", domain: "stlukesmedcollege.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Isabela State University", domain: "isu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Sultan Kudarat State University", domain: "sksu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Holy Name University", domain: "hnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Northern Philippines", domain: "unp.edu.ph", region: "Asia", country: "Philippines", isVerified: true },    
    { name: "University of San Agustin", domain: "usa.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Camarines Norte State College", domain: "cnsc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Camarines Sur Polytechnic Colleges", domain: "cspc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Manuel L. Quezon University", domain: "mlqu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Philippine School of Business Administration", domain: "psba.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Palawan State University", domain: "psu.palawan.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "PATTS College of Aeronautics", domain: "patts.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Samar State University", domain: "ssu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Mountain View College", domain: "mvc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "La Salle University, Ozamiz City", domain: "lsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of the Assumption", domain: "ua.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Capiz State University", domain: "capsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Assumption College San Lorenzo", domain: "assumption.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Nueva Vizcaya State University", domain: "nvsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Don Bosco Technical College", domain: "dbtc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Universidad de Dagupan", domain: "dagupan.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Asian Institute of Journalism and Communication", domain: "aijc.com.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Leyte Normal University", domain: "lnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Northwestern University, Philippines", domain: "nwu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Liceo de Cagayan University", domain: "liceo.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Notre Dame of Marbel University", domain: "ndmu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Laguna State Polytechnic University", domain: "lspu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Paul University Manila", domain: "spumanila.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Father Saturnino Urios University", domain: "fsuu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Northwest Samar State University", domain: "nwssu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Rizal System", domain: "urs.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Sorsogon State University", domain: "ssu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Bulacan Agricultural State College", domain: "basc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Capitol University", domain: "cu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Biliran Province State University", domain: "bipsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cor Jesu College", domain: "cjc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Notre Dame of Dadiangas University", domain: "nddu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Ilocos Sur Polytechnic State College", domain: "ispsc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Catanduanes State University", domain: "catanduanesstateu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "National Teachers College", domain: "ntc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Quirino State University", domain: "qsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Asian Social Institute", domain: "asiansocialinstitute.org", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Central Colleges of the Philippines", domain: "ccp.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Aurora State College of Technology", domain: "ascot.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Negros Oriental State University", domain: "norsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "North Eastern Mindanao State University", domain: "nemsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Wesleyan University-Philippines", domain: "wup.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Antique", domain: "antiquespride.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Universidad de Sta. Isabel", domain: "usi.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Eastern Samar State University", domain: "essu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "President Ramon Magsaysay State University", domain: "prmsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },        
    { name: "Partido State University", domain: "parsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Saint Joseph Institute of Technology", domain: "sjit.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "La Consolacion College Manila", domain: "lccm.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Filamer Christian University", domain: "fcu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Western Philippines University", domain: "wpu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "La Consolacion University Philippines", domain: "lcup.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Paul University Quezon City", domain: "spuqc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Lyceum-Northwestern University", domain: "lnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Paul University Iloilo", domain: "spuiloilo.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "College of the Holy Spirit", domain: "chsmanila.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Virgen Milagrosa University Foundation", domain: "vmuf.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Southern Luzon State University", domain: "slsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Paul University Dumaguete", domain: "spud.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "San Sebastian College-Recoletos de Cavite", domain: "sscr.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "FEATI University", domain: "featiu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Eulogio \"Amang\" Rodriguez Institute of Science and Technology", domain: "earist.edu.ph", isVerified: true },
    { name: "St. Paul University Surigao", domain: "spusurigao.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Guimaras State University", domain: "gsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },    
    { name: "Lourdes College", domain: "lourdescollege.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Iloilo - PHINMA", domain: "ui.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Aldersgate College", domain: "aldersgate.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Notre Dame University", domain: "ndu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "National College of Business and Arts", domain: "ncba.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Baliuag University", domain: "baliuagu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Araullo University - PHINMA", domain: "arau.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Pangasinan - PHINMA", domain: "upang.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Cebu Institute of Medicine", domain: "cebudoctorsuniversity.edu", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Cagayan Valley", domain: "ucv.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Southern Philippines Foundation", domain: "uspf.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Saint Michael's College of Laguna", domain: "smcl.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "The University of Manila", domain: "umak.edu.ph", region: "Asia", country: "Philippines", isVerified: false },
    { name: "Central Philippine Adventist College", domain: "cpac.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Saint Pedro Poveda College", domain: "poveda.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Luzon", domain: "ul.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Holy Trinity University", domain: "htu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Union Christian College", domain: "ucc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Pasig Catholic College", domain: "pcc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Zamboanga State College of Marine Sciences and Technology", domain: "zscmst.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Romblon State University", domain: "rsu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of Eastern Philippines", domain: "uep.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Abra State Institute of Science and Technology", domain: "asist.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Western Institute of Technology", domain: "wit.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Meycauayan College", domain: "meycauayancollege.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Olivarez College", domain: "olivarezcollege.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "STI West Negros University", domain: "wnu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "University of La Salette", domain: "universityoflasalette.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Northern Luzon Adventist College", domain: "nlac.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Marinduque State University", domain: "msu.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Siena College of Taytay", domain: "sienataytay.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Asian Institute of Maritime Studies", domain: "aims.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Notre Dame of Kidapawan College", domain: "ndkc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Joseph's College of Quezon City", domain: "sjcqc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Mary's College", domain: "smcqc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Republic Central Colleges", domain: "rcc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "St. Louis College Valenzuela", domain: "slcv.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Christ the King College", domain: "ctkc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Santa Isabel College", domain: "sic.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Guagua National Colleges", domain: "gnc.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Misamis Oriental State College of Agriculture and Technology", domain: "moscat.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "Lipa City Colleges", domain: "lipacitycolleges.edu.ph", region: "Asia", country: "Philippines", isVerified: true },
    { name: "La Consolacion College", domain: "lccl.edu.ph", region: "Asia", country: "Philippines", isVerified: true },

]