import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Poland_universities = [

    // Poland

    { name: "Uniwersytet Warszawski", domain: "uw.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Jagielloński", domain: "uj.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Górniczo-Hutnicza", domain: "agh.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet im. Adama Mickiewicza w Poznaniu", domain: "amu.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Mikołaja Kopernika w Toruniu", domain: "umk.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Warszawska", domain: "pw.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Wrocławska", domain: "pwr.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Wrocławski", domain: "uni.wroc.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Gdański", domain: "ug.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Gdańska", domain: "pg.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Śląski w Katowicach", domain: "us.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Poznańska", domain: "put.poznan.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Śląska", domain: "polsl.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytety WSB Merito", domain: "wsb.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Marii Curie-Skłodowskiej w Lublinie", domain: "umcs.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Szkoła Główna Gospodarstwa Wiejskiego", domain: "sggw.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Katolicki Uniwersytet Lubelski Jana Pawła II", domain: "kul.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Krakowska im. Tadeusza Kościuszki", domain: "pk.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Szkola Glówna Handlowa w Warszawie", domain: "sgh.waw.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Warmińsko-Mazurski w Olsztynie", domain: "uwm.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Rzeszowska im. Ignacego Łukasiewicza", domain: "prz.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet w Białymstoku", domain: "uwb.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytetu Komisji Edukacji Narodowej w Krakowie", domain: "up.krakow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Ekonomiczny w Krakowie", domain: "uek.krakow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Zielonogórski", domain: "uz.zgora.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet SWPS", domain: "swps.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie", domain: "uksw.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Rzeszowski", domain: "ur.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Białostocka", domain: "pb.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Łódzka", domain: "p.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Opolski", domain: "uni.opole.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Medyczny im. Piastów Śląskich we Wrocławiu", domain: "umw.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Lubelska", domain: "pollub.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Kazimierza Wielkiego w Bydgoszczy", domain: "ukw.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Leona Koźmińskiego", domain: "kozminski.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Szczeciński", domain: "usz.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Częstochowska", domain: "pcz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Ekonomiczny w Poznaniu", domain: "ue.poznan.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Warszawski Uniwersytet Medyczny", domain: "wum.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Ekonomiczny we Wrocławiu", domain: "ue.wroc.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Zachodniopomorski Uniwersytet Technologiczny w Szczecinie", domain: "zut.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Gdański Uniwersytet Medyczny", domain: "gumed.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Przyrodniczy we Wroclawiu", domain: "upwr.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Medyczny im. Karola Marcinkowskiego w Poznaniu", domain: "ump.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Łódzki", domain: "uni.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Ekonomiczny w Katowicach", domain: "ue.katowice.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Przyrodniczy w Poznaniu", domain: "up.poznan.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia WSB", domain: "wsb.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Rolniczy w Krakowie", domain: "urk.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Finansów i Biznesu Vistula", domain: "vistula.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Bydgoska im. Jana i Jędrzeja Śniadeckich", domain: "pbs.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Medyczny w Łodzi", domain: "umed.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Opolska", domain: "po.opole.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Polsko-Japońska Akademia Technik Komputerowych", domain: "pja.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Jana Kochanowskiego w Kielcach", domain: "ujk.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Śląski Uniwersytet Medyczny w Katowicach", domain: "sum.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Medyczny w Lublinie", domain: "umlub.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Morski w Gdyn", domain: "umg.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Humanistyczno-Ekonomiczna w Łodzi", domain: "ahe.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Pomorski w Słupsku", domain: "upsl.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Medyczny w Bialymstoku", domain: "umb.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Jana Długosza w Częstochowie", domain: "ujd.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Biznesu - National-Louis University", domain: "wsb-nlu.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uczelnia Łazarskiego", domain: "lazarski.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Pięknych w Warszawie", domain: "asp.waw.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Pedagogiki Specjalnej im. Marii Grzegorzewskiej", domain: "aps.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Przyrodniczo-Humanistyczny w Siedlcach", domain: "uph.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Wychowania Fizycznego im. Polskich Olimpijczyków we Wroclawiu", domain: "awf.wroc.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Pomorski Uniwersytet Medyczny w Szczecinie", domain: "pum.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Pięknych im. Jana Matejki w Krakowie", domain: "asp.krakow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Artystyczny w Poznaniu", domain: "uap.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Pięknych im. Władysława Strzemińskiego w Łodzi", domain: "asp.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Informatyki i Zarządzania", domain: "wsiz.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Szkoła Filmowa w Łodzi", domain: "filmschool.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Pięknych im. Eugeniusza Gepperta we Wrocławiu", domain: "asp.wroc.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Muzyczny Fryderyka Chopina", domain: "chopin.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Morska w Szczecinie", domain: "pm.szczecin.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Świętokrzyska w Kielcach", domain: "tu.kielce.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Technologiczno-Humanistyczny im. Kazimierza Pułaskiego w Radomiu", domain: "uthrad.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna im. Grażyny i Kiejstuta Bacewiczów w Łodzi", domain: "amuz.lodz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Wychowania Fizycznego Józefa Piłsudskiego w Warszawie", domain: "awf.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Wychowania Fizycznego im. Eugeniusza Piaseckiego w Poznaniu", domain: "awf.poznan.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Wychowania Fizycznego im. Jerzego Kukuczki w Katowicach", domain: "awf.katowice.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uczelnia Techniczno-Handlowa im. Heleny Chodkowskiej", domain: "uth.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Ekonomii i Innowacji w Lublinie", domain: "wsei.lublin.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna w Krakowie", domain: "amuz.krakow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Lomżyńska", domain: "al.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Górnośląska im. Wojciecha Korfantego w Katowicach", domain: "ags.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyzsza Szkola Ekonomii i Informatyki w Krakowie", domain: "wsei.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Informatyki i Umiejętności z siedzibą w Łodzi", domain: "wsinf.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Zarządzania i Bankowości w Krakowie", domain: "wszib.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna im. Karola Szymanowskiego w Katowicach", domain: "am.katowice.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Pięknych w Katowicach", domain: "asp.katowice.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Pięknych w Gdańsku", domain: "asp.gda.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Bielsko-Bialski", domain: "ubb.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna im. Ignacego Jana Paderewskiego w Poznaniu", domain: "amuz.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Zachodniopomorska Szkoła Biznesu w Szczecinie", domain: "zpsb.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uniwersytet Przyrodniczy w Lublinie", domain: "up.lublin.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Przedsiębiorczości i Administracji w Lublinie", domain: "wspa.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna im. Stanisława Moniuszki w Gdańsku", domain: "amuz.gda.pl", region: "Europe", country: "Poland", isVerified: true },      
    { name: "Akademia Kultury Fizycznej im. Bronisława Czecha w Krakowie", domain: "awf.krakow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Państwowa Akademia Nauk Stosowanych w Chełmie", domain: "panschelm.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wschodnioeuropejska Akademia Nauk Stosowanych w Białymstoku", domain: "wans.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Wychowania Fizycznego i Sportu im. Jędrzeja Śniadeckiego", domain: "awf.gda.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna im. Karola Lipińskiego we Wrocławiu", domain: "amuz.wroc.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Muzyczna im. Feliksa Nowowiejskiego w Bydgoszczy", domain: "amuz.bydgoszcz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Informatyki Stosowanej i Zarządzania", domain: "wsiiz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Nauk Stosowanych im. Stanisława Staszica w Pile", domain: "ans.pila.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Chrześcijańska Akademia Teologiczna w Warszawie", domain: "chat.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademii Sztuki w Szczecinie", domain: "akademiasztuki.eu", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Sztuk Teatralnych im. Stanisława Wyspiańskiego w Krakowie", domain: "ast.krakow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Pedagogiczna im. Janusza Korczaka w Warszawie", domain: "korczak.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Politechnika Koszalińska", domain: "tu.koszalin.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Lingwistyczna w Częstochowie", domain: "wsl.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Zdrowia w Gdańsku", domain: "wsz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Polonijna w Częstochowie", domain: "ap.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Staropolska Szkoła Wyższa w Kielcach", domain: "staropolska.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Bielska Wyższa Szkoła im. Józefa Tyszkiewicza", domain: "tyszkiewicz.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Międzynarodowa Wyższa Szkoła Logistyki i Transportu we Wrocławiu", domain: "msl.com.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Szkoła Wyższa im. Pawła Włodkowica w Płocku", domain: "wlodkowic.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Ekonomii, Prawa i Nauk Medycznych", domain: "wsepinm.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Państwowa Akademia Nauk Stosowanych im. Ignacego Mościckiego w Ciechanowie", domain: "pansciechanow.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uczelnia Jana Wyżykowskiego", domain: "ujw.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Społeczno-Ekonomiczna w Gdańsku", domain: "wsse.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Uczelnia Medyczna im. Marii Skłodowskiej - Curie w Warszawie", domain: "uczelniawarszawska.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Akademia Nauk Stosowanych w Wałczu", domain: "answalcz.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Informatyki i Zarządzania im. Prof. Tadeusza Kotarbińskiego", domain: "wsiiz.olsztyn.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Nadbużańska Szkoła Wyższa im. Marka J. Karpia w Siemiatyczach", domain: "nsw.siemiatycze.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wojskowa Akademia Techniczna im. Jarosława Dąbrowskiego", domain: "wat.edu.pl", region: "Europe", country: "Poland", isVerified: true },
    { name: "Wyższa Szkoła Zarządzania i Administracji w Zamościu", domain: "wsziaz.edu.pl", region: "Europe", country: "Poland", isVerified: true },

]