import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Portugal_universities = [

    // Portugal

    { name: "Universidade de Lisboa", domain: "ulisboa.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade do Porto", domain: "up.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade de Coimbra", domain: "uc.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Nova de Lisboa", domain: "novaims.ul.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade do Minho", domain: "uminho.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade de Aveiro", domain: "ua.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Universitário de Lisboa", domain: "iscte-iul.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Católica Portuguesa", domain: "ucp.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico do Porto", domain: "ipp.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade de Évora", domain: "uevora.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade da Beira Interior", domain: "ubi.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade do Algarve", domain: "ualg.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Bragança", domain: "ipb.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Lusófona do Porto", domain: "ulusofona.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade de Trás‑os‑Montes e Alto Douro", domain: "utad.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Lusófona de Humanidades e Tecnologias", domain: "ulusofona.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Leiria", domain: "ipleiria.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade dos Açores", domain: "uac.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Lisboa", domain: "ipl.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade da Madeira", domain: "uma.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Viseu", domain: "ipvc.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Setúbal", domain: "ips.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Portucalense Infante D. Henrique", domain: "upt.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Castelo Branco", domain: "ipcb.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Coimbra", domain: "ipc.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Tomar", domain: "ipt.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Fernando Pessoa", domain: "ufp.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Santarém", domain: "ipsantarem.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "ISPA - Instituto Universitário de Ciências Psicológicas, Sociais e da Vida", domain: "ispa.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico do Cávado e do Ave", domain: "ipca.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Viana do Castelo", domain: "ipvc.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Lusíada de Lisboa", domain: "ulusofona.pt", region: "Europe", country: "Portugal", isVerified: false },
    { name: "Instituto Politécnico de Beja", domain: "ipbeja.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Autónoma de Lisboa Luís de Camões", domain: "unialc.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Europeia", domain: "universidadeeuropea.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Portalegre", domain: "ipportalegre.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade da Maia", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Instituto Politécnico da Guarda", domain: "ipg.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Universitário de Ciências da Saúde", domain: "iusc.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Enfermagem de Coimbra", domain: "esenfcoimbra.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Piaget", domain: "piaget.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Artes e Design", domain: "esad.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Hotelaria e Turismo do Estoril", domain: "eshte.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Administração e Gestão", domain: "isag.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Português de Administração de Marketing", domain: "ipam.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Educação de Paula Frassinetti", domain: "ese-pf.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior Politécnico Gaya", domain: "ispgaya.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Enfermagem do Porto", domain: "esenfporto.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Egas Moniz - Cooperativa de Ensino Superior", domain: "egasmoniz.edu.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior Miguel Torga", domain: "ismt.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Educação e Ciências", domain: "isec-lisboa.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Enfermagem de Lisboa", domain: "esel.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Gestão", domain: "isg.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Universidade Atlântica", domain: "uatlantica.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior Náutica Infante D. Henrique", domain: "enautica.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Saúde do Alcoitão", domain: "essa.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Saúde de Santa Maria", domain: "esssm.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior Artística do Porto", domain: "esap.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Entre Douro e Vouga", domain: "isedv.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Ciências Empresariais e do Turismo", domain: "iscet.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Ciências da Informação e da Administração", domain: "iscia.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Ciências Educativas do Douro", domain: "iscedouro.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Saúde Norte da Cruz Vermelha Portuguesa", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Escola Superior de Saúde da Cruz Vermelha Portuguesa", domain: "esscvp.eu", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior Manuel Teixeira Gomes", domain: "ismat.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico da Maia", domain: "ipmaia.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico de Gestão e Tecnologia", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Instituto Superior de Tecnologias Avançadas de Lisboa", domain: "istal.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Ciências Educativas", domain: "isce.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Universitária Vasco da Gama", domain: "vascodagama.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto de Estudos Superiores de Fafe", domain: "iesf.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Serviço Social do Porto", domain: "isssp.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Negócios Atlântico", domain: "atlantico.edu.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Politécnico da Lusofonia", domain: "ipluso.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Enfermagem São Francisco das Misericórdias", domain: "esesfm.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior de Saúde do Alto Ave", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Instituto Superior de Administração e Línguas", domain: "isal.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Atividades Imobiliárias", domain: "esai.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Enfermagem de São José de Cluny", domain: "essjcluny.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Instituto Superior D. Dinis", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Escola Superior de Saúde Cruz Vermelha Portuguesa - Alto Tâmega", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Instituto Superior de Novas Profissões", domain: "insp.pt", region: "Europe", country: "Portugal", isVerified: true },
    { name: "Escola Superior de Educação de João de Deus", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Escola Superior de Educadores de Infância Maria Ulrich", domain: null, region: "Europe", country: "Portugal", isVerified: false },
    { name: "Academia Nacional Superior de Orquestra", domain: "metropolitana.pt", region: "Europe", country: "Portugal", isVerified: true },

]