import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Romania_universities = [

    // Romania

    { name: "Universitatea Babes-Bolyai", domain: "ubbcluj.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Politehnica din Bucuresti", domain: "upb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Alexandru Ioan Cuza din Iasi", domain: "uaic.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea din București", domain: "unibuc.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Academia de Studii Economice din Bucuresti", domain: "ase.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Vest din Timisoara", domain: "uvt.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Transilvania din Brasov", domain: "unitbv.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Technică din Cluj-Napoca", domain: "utcluj.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Tehnică Gheorghe Asachi din Iasi", domain: "tuiasi.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Politehnica din Timisoara", domain: "upt.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Stefan cel Mare Suceava", domain: "usv.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Dunărea de Jos din Galati", domain: "ugal.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Lucian Blaga din Sibiu", domain: "ulbsibiu.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea din Craiova", domain: "ucv.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Ovidius Constanta", domain: "univ-ovidius.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea din Oradea", domain: "uoradea.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "UMFST George Emil Palade din Targu Mures", domain: "umfst.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Medicină si Farmacie Iuliu Hatieganu", domain: "umfcluj.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea 1 Decembrie 1918 din Alba Iulia", domain: "uab.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "USAMV din Bucuresti", domain: "usamv.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "USAMV din Cluj-Napoca", domain: "usamvcluj.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Centrul Universitar Pitești", domain: "upit.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Sapientia", domain: "sapientia.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Româno-Americană", domain: "rau.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "UMF Carol Davila din Bucuresti", domain: "umfcd.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "UMF Gr. T. Popa din Iasi", domain: "umfiasi.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Scoala Natională de Studii Politice si Administrative", domain: "snspa.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Tehnică de Constructii Bucuresti", domain: "utcb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Vasile Alecsandri din Bacău", domain: "ub.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Arhitectură si Urbanism Ion Mincu", domain: "uauim.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "UMF Victor Babes din Timisoara", domain: "umft.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Aurel Vlaicu din Arad", domain: "uav.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Valahia din Târgovişte", domain: "valahia.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Petrol-Gaze din Ploiesti", domain: "upg-ploiesti.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Danubius Galati", domain: "univ-danubius.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "USAMV a Banatului Timisoara", domain: "usab-tm.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Constantin Brâncusi", domain: "utgjiu.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Spiru Haret", domain: "spiruharet.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Vest Vasile Goldis din Arad", domain: "uvvg.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Medicină si Farmacie din Craiova", domain: "umfcv.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Ştiinţele Vieţii Ion Ionescu de la Brad", domain: "iunisb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "UNATC Ion Luca Caragiale", domain: "unatc.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Agora din Oradea", domain: "univagora.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea din Petrosani", domain: "upet.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Crestină Dimitrie Cantemir", domain: "ucdc.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Titu Maiorescu", domain: "utm.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "UNAGE George Enescu Iasi", domain: "arteiasi.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Naţională de Muzică din Bucureşti", domain: "unmb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Maritimă din Constanta", domain: "cmu-edu.eu", region: "Europe", country: "Romania", isVerified: true },
    { name: "Academia Natională de Muzică Gheorghe Dima", domain: "amgd.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Natională de Arte din Bucuresti", domain: "unarte.org", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Crestină Partium", domain: "partium.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Nicolae Titulescu din Bucuresti", domain: "unt.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Artă si Design din Cluj-Napoca", domain: "uad.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Ecologică din Bucuresti", domain: "ueb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea de Arte din Târgu Mures", domain: "uat.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea HYPERION", domain: "hyperion.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Tibiscus din Timisoara", domain: "tibiscus.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Naţională de Educaţie Fizică şi Sport", domain: "unefs.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Emanuel din Oradea", domain: "emanuel.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea George Bacovia Bacău", domain: "ugb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Petre Andrei din Iaşi", domain: "upa.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Apollonia din Iasi", domain: "apollonia.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Andrei Saguna", domain: "andreisaguna.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Constantin Brâncoveanu", domain: "univcb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Dimitrie Cantemir Târgu Mureş", domain: "cantemir.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Artifex din Bucuresti", domain: "artifex.org.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Institutul de Administrare a Afacerilor din Bucuresti", domain: "ibb.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Bioterra din Bucuresti", domain: "bioterra.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Mihail Kogalniceanu Iasi", domain: "umk.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Athenaeum din Bucuresti", domain: "athenaeum.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Româno-Germană din Sibiu", domain: "roger-univ.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Bogdan Voda din Cluj-Napoca", domain: "ubv.ro", region: "Europe", country: "Romania", isVerified: true },
    { name: "Universitatea Europeană Drăgan din Lugoj", domain: "ued.ro", region: "Europe", country: "Romania", isVerified: true },

]