import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Russia_universities = [

    // Russia

    { name: "Moscow State University", domain: "msu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "National Research University Higher School of Economics", domain: "hse.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State University", domain: "spbu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "ITMO University", domain: "itmo.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural Federal University", domain: "urfu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tomsk State University", domain: "tsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian Presidential Academy of National Economy and Public Administration", domain: "ranepa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan Federal University", domain: "kpfu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Institute of Physics and Technology", domain: "mipt.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Synergy University", domain: "synergy.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Novosibirsk State University", domain: "nsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Peter the Great St.Petersburg Polytechnic University", domain: "spbstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian Federal University", domain: "sfu-kras.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "RUDN University", domain: "rudn.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tomsk Polytechnic University", domain: "tpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "National Research Nuclear University MEPhI", domain: "mephi.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "South Ural State University", domain: "susu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Institute of International Relations", domain: "mgimo.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bauman Moscow State Technical University", domain: "bmstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Lobachevsky State University of Nizhny Novgorod", domain: "unn.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Finance Academy under the Government of the Russian Federation", domain: "fa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Technical University ‑ MIREA", domain: "mirea.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "First Moscow State Medical University", domain: "msmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State University for the Humanities", domain: "rsuh.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Far Eastern Federal University", domain: "dvfu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Voronezh State University", domain: "vsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Belgorod State University", domain: "bsu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "National University of Science and Technology \"MISIS\"", domain: "misis.ru", isVerified: true },
    { name: "Southern Federal University", domain: "sfedu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Samara National Research University", domain: "samarauniversity.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "University of Tyumen", domain: "utmn.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ufa University of Science and Technology", domain: "ufanet.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saratov State University", domain: "sgu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Herzen State Pedagogical University of Russia", domain: "herzen.spb.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Altai State University", domain: "asbr.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Novosibirsk State Technical University", domain: "nstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North‑Eastern Federal University", domain: "ysu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Aviation Institute", domain: "mai.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Polytech", domain: "mgupa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saint Petersburg State Electrotechnical University", domain: "etspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Irkutsk National Research Technical University", domain: "eng.istl.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State University of Oil and Gas", domain: "gubkin.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow City Teachers' Training University", domain: "mpgu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Perm State University", domain: "psu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Power Engineering Institute", domain: "mpei.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Plekhanov Russian University of Economics", domain: "rea.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Pedagogical University", domain: "mgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Northern Arctic Federal University", domain: "narfu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Tchaikovsky Conservatory", domain: "mgc.uc.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ogarev Mordovia State University", domain: "mrsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Immanuel Kant Baltic Federal University", domain: "kantiana.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian National Research Medical University", domain: "psma.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Petrozavodsk State University", domain: "psu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tomsk State University of Control Systems and Radioelectronics", domain: "tusur.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State Agricultural University", domain: "rsa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Perm State Technical University", domain: "pstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tver State University", domain: "tversu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Irkutsk State University", domain: "isu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State University of Economics", domain: "unecon.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian University of Sport", domain: "russport.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Industrial University of Tyumen", domain: "tyuiu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "The State University of Management", domain: "gum.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Samara State Technical University", domain: "sstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Don State Technical University", domain: "donstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orenburg State University", domain: "osuniversity.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kuzbass State Technical University", domain: "kuzstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chelyabinsk State University", domain: "csu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tambov State Technical University", domain: "tstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North Caucasus Federal University", domain: "ncstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "National Research University of Electronic Technology", domain: "netuniversity.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Civil Engineering", domain: "mgsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kuban State University", domain: "ksu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Penza State University", domain: "pgups.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Novgorod State University", domain: "novsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Psychology and Education", domain: "mgppu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kutafin Moscow State Law University", domain: "rgups.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vladivostok State University of Economics and Service", domain: "vsues.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saint Tikhon's Orthodox University", domain: "stoou.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Novosibirsk State Pedagogical University", domain: "nspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ufa State Petroleum Technological University", domain: "usuptu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State Social University", domain: "rssu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan National Research Technical University \"KAI\"", domain: "tu-kai.ru", isVerified: true },
    { name: "Tomsk State Pedagogical University", domain: "tomskpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "New Economic School", domain: "nes.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Yaroslavl State University", domain: "ysu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "European University at St. Petersburg", domain: "eu.spb.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saint Petersburg Mining University", domain: "spmi.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kemerovo State University", domain: "kemerovo.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Syktyvkar State University", domain: "syktsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Togliatti State University", domain: "tlt.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan State Technological University", domain: "kstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ulyanovsk State Technical University", domain: "ulstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Altai State Pedagogical Academy", domain: "aspa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Udmurt State University", domain: "udsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dostoevsky Omsk State University", domain: "omgu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian University of Transport", domain: "rutt.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vladimir State University for the Humanities", domain: "vlsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State University of Architecture and Civil Engineering", domain: "spbgasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North-Western State Medical University", domain: "nwmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Belgorod State Agricultural University", domain: "bsau.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saratov State Technical University", domain: "sstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "The Bonch‑Bruevich St. Petersburg State University of Telecommunications", domain: "sut.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Mendeleev University of Chemical Technology of Russia", domain: "muctr.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State University of Economics", domain: "uratufe.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State University of Aerospace Instrumentation", domain: "suai.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volgograd State University", domain: "volsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian New University", domain: "rnu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian State Aerospace University", domain: "sibsau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kalashnikov Izhevsk State Technical University", domain: "istu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dagestan State University", domain: "dsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pacific National University", domain: "pnu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volgograd State Technical University", domain: "vgstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ulyanovsk State University", domain: "ulstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Financial and Law University", domain: "mfua.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State University of Industrial Technologies and Design", domain: "ispu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chuvash State University", domain: "chuvsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volgograd State Medical Academy", domain: "vsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Linguistic University", domain: "linguan.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nizhny Novgorod State Technical University", domain: "nnstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Novosibirsk State University of Economics and Management", domain: "suno.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Banzarov Buryat State University", domain: "bsu-edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State Hydrometeorological University", domain: "rsuh.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "South‑Western State University", domain: "swosu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Technological University \"Stankin\"", domain: "stankin.ru", isVerified: true },
    { name: "Omsk State Technical University", domain: "omgtu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nizhny Novgorod State Pedagogical University", domain: "nnpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vyatka State University", domain: "vntu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Krasnoyarsk State Medical University", domain: "ksmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kabardino‑Balkarian State University", domain: "kbsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian State Medical University", domain: "ssmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ugra State University", domain: "ugrasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pavlov First St. Petersburg State Medical University", domain: "smu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Gaidar Institute for Economic Policy", domain: "gaidar-institute.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saratov State University of Genetics, Biotechnology and Engineering named after N. I. Vavilova", domain: "sgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Yaroslavl State Pedagogical University", domain: "yspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State Pediatric Medical Academy", domain: "gpmu.org", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ivanovo State Power University", domain: "ispu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Geodesy and Cartography", domain: "mgsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Technical University of Communications and Informatics", domain: "mtuci.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Automobile and Road Construction State Technical University", domain: "mzstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State Pedagogical University", domain: "ustu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Polzunov Altai State Technical University", domain: "astu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kursk State Medical University", domain: "ksmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Admiral Makarov State University of Maritime and Inland Shipping", domain: "sumaski.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "M. Akmullah Bashkir State Pedagogical University", domain: "gbpuufa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pskov State Pedagogical University", domain: "pspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orel State University", domain: "oru.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Samara State Medical University", domain: "samsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ivanovo State University of Chemistry and Technology", domain: "isuct.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Voronezh State Technical University", domain: "vstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volgograd State Socio-Pedagogical University", domain: "vspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Voronezh State Medical University", domain: "vsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saint-Petersburg State University of Film and Television", domain: "gikit.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Omsk State Pedagogical University", domain: "omgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Baltic State Technical University \"Voenmeh\"", domain: "voenmeh.ru", isVerified: true },
    { name: "Altai State Medical University", domain: "asmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Magnitogorsk State Technical University", domain: "magtu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dubna State University", domain: "uni-dubna.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State Conservatory", domain: "conservatory.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pushkin State Russian Language Institute", domain: "pushkin.institute", region: "Europe", country: "Russia", isVerified: true },
    { name: "Amur State University", domain: "amursu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nizhnevartovsk State University", domain: "nvsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Omsk State Medical Academy", domain: "omsk-osma.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Mari State University", domain: "mariuniversity.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tambov State University", domain: "tsutmb.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State Law Academy", domain: "usla.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow International Higher Business School", domain: "mirbis.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ryazan State Medical University", domain: "rzgmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Surgut State University", domain: "surguniversity.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Metropolitan Governance University", domain: null, region: "Europe", country: "Russia", isVerified: false },
    { name: "Belgorod State Technological University", domain: "bstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "South-Russian State Technical University", domain: "srstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State University of Railway Transport", domain: "usurt.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pyatigorsk State University", domain: "pgu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volga State University of Technology", domain: "volgatech.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Technology and Management", domain: "msutm.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kaliningrad State Technical University", domain: "kstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Samara State Economic University", domain: "sseu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Maritime State University", domain: "msun.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Astrakhan State University", domain: "asu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "State University of Education", domain: null, region: "Europe", country: "Russia", isVerified: false },
    { name: "Siberian State Transport University", domain: "sibgups.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tula State Pedagogical University", domain: "tspu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nizhny Novgorod State University of Architecture and Civil Engineering", domain: "nngasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Voronezh State Pedagogical University", domain: "vgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian State University of Telecommunications and Informatics", domain: "sibsutis.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kuban State Agricultural University", domain: "kubsau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State University A.N. Kosygin", domain: "kosygin.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saratov State Medical University", domain: "ssmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saint Petersburg State Institute of Technology", domain: null, region: "Europe", country: "Russia", isVerified: false },
    { name: "Ivanovo State University", domain: "ivanovo.ac.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kuban State University of Technology", domain: "kubstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kuban State Medical University", domain: "ksmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North State Medical University", domain: "nsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dagestan State Medical University", domain: "dgmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Astrakhan State Technical University", domain: "astu.org", region: "Europe", country: "Russia", isVerified: true },
    { name: "Perm State Pedagogical University", domain: "pspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State Marine Technical University", domain: "spbmtu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bashkir State Agricultural University", domain: "bashgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian State Industrial University", domain: "sibsiu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Stavropol State Agrarian University", domain: "stgau.ru", region: "Europe", country: "Russia", isVerified: true },  // official site stgau.ru :contentReference[oaicite:1]{index=1}
    { name: "Kazan State Medical University", domain: "ksmu.ru", region: "Europe", country: "Russia", isVerified: true },  // KSMU verified from university info and directories :contentReference[oaicite:2]{index=2}
    { name: "Krasnoyarsk State Pedagogical University", domain: "kspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Rostov State University of Economics", domain: "rostovececon.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tomsk State University of Architecture and Building", domain: "tsuab.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saratov State Academy of Law", domain: "academy-law-saratov.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Food Production", domain: "mfup.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Murmansk Arctic University", domain: "mamor.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State Geological Prospecting University", domain: "rsgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Sergei Witte University of Moscow", domain: "witte.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bashkir State Medical University", domain: "bsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Komsomolsk‑on‑Amur State Technical University", domain: "kgstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kurgan State University", domain: "kurgasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Gorno‑Altaisk State University", domain: "gasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan State Power Engineering University", domain: "kspeu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "East Siberia State University of Technology and Management", domain: "essutm.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Rostov State Medical University", domain: "rsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow University for the Humanities", domain: "mug.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Far Eastern State Transport University", domain: "vestu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Far Eastern State Medical University", domain: "vsmu.ru", region: "Europe", country: "Russia", isVerified: true }, 
    { name: "Tula State University", domain: "tsu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Modern University for the Humanities", domain: "mgh.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Yaroslavl State Medical University", domain: "yarsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Adyghe State University", domain: "adyghe.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kostroma State University", domain: "kgasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Krasnoyarsk State Agricultural University", domain: "ksau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Omsk State Agrarian University named after P.A. Stolypin", domain: "ostu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Technical University of Civil Aviation", domain: "caa.mstuca.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State Mining University", domain: "usmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volga State University of Telecommunications and Informatics", domain: "volgatech.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vologda State University", domain: "vogu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Baikal State University", domain: "bsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ryazan State University", domain: "ryazangov.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Novosibirsk State Medical University of Economics and Management", domain: "nsuem.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Banzarov Buryat State University", domain: "bsu-edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State Hydrometeorological University", domain: "rshu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "South‑Western State University", domain: "swosu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Technological University \"Stankin\"", domain: "stankin.ru", isVerified: true },
    { name: "Omsk State Technical University", domain: "omstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nizhny Novgorod State Pedagogical University", domain: "nnpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vyatka State University", domain: "vntu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Krasnoyarsk State Medical University", domain: "ksmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kabardino‑Balkarian State University", domain: "kbsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian State Medical University", domain: "ssmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ugra State University", domain: "ugrasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pavlov First St. Petersburg State Medical University", domain: "smu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Gaidar Institute for Economic Policy", domain: "gaidar-institute.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saratov State University of Genetics, Biotechnology and Engineering named after N.I. Vavilov", domain: "sgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Yaroslavl State Pedagogical University", domain: "yspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State Pediatric Medical Academy", domain: "gpmu.org", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ivanovo State Power University", domain: "ispu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Geodesy and Cartography", domain: "mgsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Technical University of Communications and Informatics", domain: "mtuci.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Automobile and Road Construction State Technical University", domain: "mzstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State Pedagogical University", domain: "ustu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Polzunov Altai State Technical University", domain: "astu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kursk State Medical University", domain: "ksmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Admiral Makarov State University of Maritime and Inland Shipping", domain: "sumaski.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "M. Akmullah Bashkir State Pedagogical University", domain: "gbpuufa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pskov State Pedagogical University", domain: "pspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orel State University", domain: "oru.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Samara State Medical University", domain: "samsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ivanovo State University of Chemistry and Technology", domain: "isuct.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Voronezh State Technical University", domain: "vstu.ru", region: "Europe", country: "Russia", isVerified: true },   
    { name: "Moscow International University", domain: "miu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ryazan State Radio Engineering University", domain: "rsreu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State Forestry University", domain: "usfeu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Smolensk State University", domain: "smolgu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Institute of Culture", domain: "mgik.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "International Banking Institute", domain: "ibi.spb.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North Ossetian State University", domain: "nosu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kalmyk State University", domain: "kalmsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Sakhalin State University", domain: "sakhgu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "State University of Land Management", domain: "mgul.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pacific State Medical University", domain: "pgmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Omsk State Transport University", domain: "ostu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Linguistic University of Nizhny Novgorod", domain: "lunn.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg University of Management Technologies and Economics", domain: "spbume.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan State University of Architecture and Engineering", domain: "kgasu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kaluga State University", domain: "kgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chelyabinsk State Pedagogical University", domain: "cspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tver State Technical University", domain: "tvgtu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ulyanovsk State Pedagogical University", domain: "ulgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Privolzhsky Research Medical University", domain: "prmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orenburg State Pedagogical University", domain: "ospu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "South Ural State Medical University", domain: "sumus.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kemerovo State Institute of Culture", domain: "kgik.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State Agrarian University", domain: "spbgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Lesgaft National State University of Physical Education, Sport and Health", domain: "lesgaft.spb.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Yelets State University", domain: "elstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "St. Petersburg State University of Civil Aviation", domain: "suca.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State University of Tourism and Services", domain: "rguts.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volga State University of Physical Culture, Sports and Tourism", domain: "vsupc.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ivanovo State Medical University", domain: "ismu.ac.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kemerovo State Medical University", domain: "kemsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Maikop State Technological University", domain: "mstuniversity.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orenburg State Medical University", domain: "orsmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Cherepovets State University", domain: "chsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tver State Medical University", domain: "tversmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Saint-Petersburg State Chemical Pharmaceutical University", domain: "spcpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bryansk State University", domain: "brsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Perm State Medical University", domain: "psmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kirov State Medical University", domain: "ksmu-kirov.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bryansk State Technical University", domain: "bstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Rybinsk State Aviation Technical University", domain: "rsatu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Armavir State Pedagogical University", domain: "aspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bratsk State University", domain: "brstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Izhevsk State Medical Academy", domain: "isma.izh.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Michurinsk State Agrarian University", domain: "msau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Blagoveshchensk State Pedagogical University", domain: "bgpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Stavropol State Medical University", domain: "stavmu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chuvash State Pedagogical University", domain: "chgpu.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Russian State Institute of Performing Arts", domain: "rgisi.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Penza State Technological University", domain: "pgta.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Industrial Art University", domain: "mgpai.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Astrakhan State Medical Academy", domain: "asma.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Far Eastern State Technical Fisheries University", domain: "festfu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dagestan State Technical University", domain: "dstu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Amur State Medical Academy", domain: "amursma.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Buryat State Academy of Agriculture", domain: "bgsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Khabarovsk State University of Economics and Law", domain: "khse.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orenburg State Agrarian University", domain: "orgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State University of Physical Culture", domain: "usupc.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chita State Academy of Medicine", domain: "chitamed.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Orel State Agrarian University", domain: "orelsau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Irkutsk State Medical University", domain: "ismu.baikal.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chechen State University", domain: "chechsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Volgograd State University of Architecture and Civil Engineering", domain: "vsuace.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Lipetsk State Pedagogical University", domain: "lspu-lipetsk.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan State Agricultural University", domain: "kazan-agri.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Penza State University of Architecture and Construction", domain: "pgsaa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Bryansk State Agrarian University", domain: "bgsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vologda State Dairy Farming Academy", domain: "vsdafa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Petrozavodsk State Conservatory", domain: "glazunovcons.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ryazan State Agrotechnological University", domain: "rgatu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tyva State University", domain: "tyuiu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kamchatka State University named after Vitus Bering", domain: "ksu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Don State University of Agriculture", domain: "dsau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kuban State University of Physical Culture, Sport and Tourism", domain: "kubgufk.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Far East State Agrarian University", domain: "dalgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State Academy of Physical Culture", domain: "mgafk.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Institute of Public Administration and Law", domain: "mipap.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Siberian State University of Physical Culture and Sports", domain: "ssupcs.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow State University of Environmental Engineering", domain: "msuee.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Udmurt State Agrarian University", domain: "udgau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "State Agrarian University of the Northern Trans-Urals", domain: "gsau-ntu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan State University of Culture and Arts", domain: "kguki.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Angarsk State Technical University", domain: "astu38.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "The Rostov State Conservatoire", domain: "rostcons.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow Information Technology University – Moscow Institute of Architecture and Civil Engineering", domain: "mitu-maci.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dagestan State Pedagogical University", domain: "dspu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "University of Humanities", domain: "ug.uic.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ural State Conservatory", domain: "uralconsv.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Arctic State Agrotechnological University", domain: "agatu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kamchatka State Technical University", domain: "kamchatgtu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "South Ural State Agrarian University", domain: "ugsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North Caucasian Institute of Mining and Metallurgy", domain: "ncimm.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Northern Ossetian State Academy of Medicine", domain: "nosma.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "North-Eastern State University", domain: "svgu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kazan State Conservatory", domain: "kgk-kazan.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Yaroslavl State Academy of Agriculture", domain: "yaragro.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pyatigorsk State Pharmaceutical Academy", domain: "pgfa.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Chuvash State Agricultural Academy", domain: "csha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Pushchino State Institute of Natural Science", domain: "psin.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Dagestan State Agrarian University", domain: "dgsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Penza State Agricultural Academy", domain: "pgsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tambov State Musical-Pedagogical Institute named after S.V. Rachmaninov", domain: "tgmpu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ivanovo State Academy of Agriculture", domain: "ivgsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Ingush State University", domain: "inggu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Magnitogorsk State Conservatory", domain: "mgk.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vyatka State Humanities University", domain: "vyatsu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "International University of Fundamental Studies, St. Petersburg", domain: "iufs.edu", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nayanova University", domain: "nayanova.edu.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Kabardino-Balkarian State Agricultural University", domain: "kbsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Gorsky State Agrarian University", domain: "gorsau.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nizhny Novgorod State Agricultural Academy", domain: "nnsha.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Moscow University Touro", domain: "touro.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Tchaikovsky State Academy of Physical Culture and Sports", domain: "chgafk.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Nevsky Institute of Language and Culture", domain: "nevskyinstitute.com", region: "Europe", country: "Russia", isVerified: true },
    { name: "Astrakhan State Conservatory", domain: "astrcons.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Vladikavkaz Institute of Economics, Management and Law", domain: "vieup.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Institute of International Business Education", domain: "iibe.ru", region: "Europe", country: "Russia", isVerified: true },
    { name: "Altai State Pedagogical University", domain: "agpu.net", region: "Europe", country: "Russia", isVerified: true },
    { name: "Murmansk State Technical University", domain: "murman.ru", region: "Europe", country: "Russia", isVerified: true },

]