import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Saudi_Arabia_universities = [

    // Saudi Arabia

    { name: "King Saud University", domain: "ksu.edu.sa", isVerified: true },
    { name: "King Abdullah University of Science and Technology", domain: "kaust.edu.sa", isVerified: true },
    { name: "King AbdulAziz University", domain: "kau.edu.sa", isVerified: true },
    { name: "King Fahd University of Petroleum and Minerals", domain: "kfupm.edu.sa", isVerified: true },
    { name: "Umm Al-Qura University", domain: "uqu.edu.sa", isVerified: true },
    { name: "Al-Imam Muhammad Ibn Saud Islamic University", domain: "imamu.edu.sa", isVerified: true },
    { name: "King Faisal University", domain: "kfu.edu.sa", isVerified: true },
    { name: "Qassim University", domain: "qu.edu.sa", isVerified: true },
    { name: "Imam Abdulrahman Bin Faisal University", domain: "iau.edu.sa", isVerified: true },
    { name: "Islamic University of Madinah", domain: "iu.edu.sa", isVerified: true },
    { name: "Taibah University", domain: "taibahu.edu.sa", isVerified: true },
    { name: "King Khalid University", domain: "kku.edu.sa", isVerified: true },
    { name: "Princess Nora bint Abdulrahman University", domain: "pnu.edu.sa", isVerified: true },
    { name: "Taif University", domain: "tu.edu.sa", isVerified: true },
    { name: "Jazan University", domain: "jazanu.edu.sa", isVerified: true },
    { name: "Institute of Public Administration, Saudi Arabia", domain: "ipa.edu.sa", isVerified: true },
    { name: "Prince Sattam Bin Abdulaziz University", domain: "psau.edu.sa", isVerified: true },
    { name: "Majmaah University", domain: "mu.edu.sa", isVerified: true },
    { name: "Prince Sultan University", domain: "psu.edu.sa", isVerified: true },
    { name: "University of Jeddah", domain: "uj.edu.sa", isVerified: true },
    { name: "King Saud bin Abdulaziz University for Health Sciences", domain: "ksau-hs.edu.sa", isVerified: true },
    { name: "Prince Mohammad Bin Fahd University", domain: "pmu.edu.sa", isVerified: true },
    { name: "Alfaisal University", domain: "alfaisal.edu", isVerified: true },
    { name: "University of Tabuk", domain: "ut.edu.sa", isVerified: true },
    { name: "University of Ha'il", domain: "uoh.edu.sa", isVerified: true },
    { name: "Najran University", domain: "nu.edu.sa", isVerified: true },
    { name: "Effat University", domain: "effat.edu.sa", isVerified: true },
    { name: "Al Jouf University", domain: "ju.edu.sa", isVerified: true },
    { name: "Al Maarefa University", domain: "almaarefa.edu.sa", isVerified: true },
    { name: "Dar Al-Hekma University", domain: "dah.edu.sa", isVerified: true },
    { name: "Shaqra University", domain: "su.edu.sa", isVerified: true },
    { name: "Northern Borders University", domain: "nbu.edu.sa", isVerified: true },
    { name: "Al Baha University", domain: "bu.edu.sa", isVerified: true },
    { name: "University of Hafr Al Batin", domain: "uhb.edu.sa", isVerified: true },
    { name: "University of Business and Technology", domain: "ubt.edu.sa", isVerified: true },
    { name: "Al Yamamah University", domain: "yu.edu.sa", isVerified: true },
    { name: "University of Bisha", domain: "ub.edu.sa", isVerified: true },
    { name: "Buraydah Colleges", domain: "bc.edu.sa", isVerified: true },
    { name: "Fahad Bin Sultan University", domain: "fbsu.edu.sa", isVerified: true },
    { name: "Batterjee Medical College", domain: "bmc.edu.sa", isVerified: true },
    { name: "Ibn Sina National College For Medical Studies", domain: "ibnsina.edu.sa", isVerified: true },
    { name: "University of Prince Mugrin", domain: "upm.edu.sa", isVerified: true },
    { name: "Riyadh Elm University", domain: "riyadh.edu.sa", isVerified: true },
    { name: "Dar Al Uloom University", domain: "dau.edu.sa", isVerified: true },
    { name: "Onaizah Colleges", domain: "oc.edu.sa", isVerified: true },
    { name: "Jeddah International College", domain: "jicollege.edu.sa", isVerified: true },
    { name: "Sulaiman Al Rajhi University", domain: "sr.edu.sa", isVerified: true },
    { name: "Gulf Colleges", domain: "gulf.edu.sa", isVerified: true },
    { name: "Alasala Colleges", domain: "alasala.edu.sa", isVerified: true },
    { name: "Mustaqbal University", domain: "uom.edu.sa", isVerified: true },
    { name: "Al Ghad International Colleges", domain: "gc.edu.sa", isVerified: true },
    { name: "Arab East Colleges", domain: "arabeast.edu.sa", isVerified: true },
    { name: "Inaya Medical Colleges", domain: "inaya.edu.sa", isVerified: true },
    { name: "Fakeeh College for Medical Sciences", domain: "fakeehcollege.edu.sa", isVerified: true },
    { name: "Al Rayyan Colleges", domain: null, isVerified: false },
    { name: "Mohammed Al-Mana College for Medical Sciences", domain: "machs.edu.sa", isVerified: true },
    { name: "Al-Baha Private College of Science", domain: "bpcs.education", isVerified: true },
    { name: "Vision Colleges", domain: "vision.edu.sa", isVerified: true },
    { name: "Ibn Rushd College of Management Sciences", domain: "ibnrushd.edu.sa", isVerified: true },
    { name: "AlFayha College", domain: "fayha.edu.sa", isVerified: true },
    { name: "Al-Riyada College for Health Science", domain: "alriyada.edu.sa", isVerified: true },
    { name: "Al-Moosa College of Health Sciences", domain: "almoosacollege.edu.sa", isVerified: true },
    { name: "Northern College of Nursing", domain: null, isVerified: false },
    { name: "Saad College of Nursing and Allied Health Sciences", domain: "saadcollege.edu.sa", isVerified: true },
]