import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Singapore_universities = [

    // Singapore

    { name: "National University of Singapore", domain: "nus.edu.sg", isVerified: true },
    { name: "Nanyang Technological University", domain: "ntu.edu.sg", isVerified: true },
    { name: "Singapore Management University", domain: "smu.edu.sg", isVerified: true },
    { name: "Nanyang Polytechnic", domain: "nyp.edu.sg", isVerified: true },
    { name: "Singapore Polytechnic", domain: "sp.edu.sg", isVerified: true },
    { name: "Temasek Polytechnic", domain: "tp.edu.sg", isVerified: true },
    { name: "Singapore University of Technology and Design", domain: "sutd.edu.sg", isVerified: true },
    { name: "Ngee Ann Polytechnic", domain: "np.edu.sg", isVerified: true },
    { name: "National Institute of Education", domain: "nie.edu.sg", isVerified: true },
    { name: "Singapore Institute of Technology", domain: "sit.edu.sg", isVerified: true },
    { name: "Republic Polytechnic", domain: "rp.edu.sg", isVerified: true },
    { name: "Kaplan Singapore", domain: "kaplan.com.sg", isVerified: true },
    { name: "MDIS - Management Development Institute of Singapore", domain: "mdis.edu.sg", isVerified: true },
    { name: "PSB Academy Singapore", domain: "psb-academy.edu.sg", isVerified: true },
    { name: "Singapore Institute of Management", domain: "sim.edu.sg", isVerified: true },
    { name: "James Cook University Singapore", domain: "jcu.edu.sg", isVerified: true },
    { name: "LASALLE College of the Arts", domain: "lasalle.edu.sg", isVerified: true },
    { name: "Nanyang Academy of Fine Arts", domain: "nafa.edu.sg", isVerified: true },
    { name: "Duke-NUS Graduate Medical School Singapore", domain: "dukenus.edu.sg", isVerified: true },
    { name: "German Institute of Science & Technology Singapore", domain: null, isVerified: false },
    { name: "Curtin University Singapore", domain: "curtin.edu.sg", isVerified: true },
    { name: "TMC Academy", domain: "tmc.edu.sg", isVerified: true },
    { name: "Singapore Raffles Music College", domain: "rafflesmusiccollege.edu.sg", isVerified: true },
    { name: "Singapore University of Social Sciences", domain: "suss.edu.sg", isVerified: true },
    { name: "Informatics Academy Singapore", domain: "informaticsacademy.edu.sg", isVerified: true },
    { name: "Auston Institute of Management", domain: "auston.edu.sg", isVerified: true },
    { name: "Aventis School of Management", domain: "aventis.edu.sg", isVerified: true },
    { name: "EASB East Asia Institute of Management", domain: "easb.edu.sg", isVerified: true },
    { name: "Ngee Ann–Adelaide Education Centre", domain: "naaec.edu.sg", isVerified: true },
    { name: "BMC International College", domain: "bmc.edu.sg", isVerified: true },
    { name: "Biblical Graduate School of Theology", domain: "bgst.edu.sg", isVerified: true },
    { name: "Academy of Medicine", domain: "academyofmedicine.edu.sg", isVerified: true },
    { name: "University of Nevada Las Vegas Singapore", domain: "unlv.edu", isVerified: true },
    { name: "SMF Institute of Higher Learning", domain: "smf.edu.sg", isVerified: true },
    { name: "Singapore-MIT Alliance for Research and Technology", domain: "smart.mit.edu", isVerified: true },
    { name: "ERC Institute Singapore", domain: "erc.edu.sg", isVerified: true },
    { name: "Marketing Institute of Singapore", domain: "mis.org.sg", isVerified: true },
    { name: "Stansfield College", domain: "stansfield.edu.sg", isVerified: true },
    { name: "Temple University Singapore", domain: "temple.edu.sg", isVerified: true },
    { name: "Chatsworth Mediart Academy", domain: "chatsworthmediartacademy.com", isVerified: true },
    { name: "Singapore Institute of Engineering Technology", domain: "siet.edu.sg", isVerified: true },
    { name: "New York University Tisch School of the Arts", domain: null, isVerified: false },
    { name: "University of New South Wales Asia", domain: null, isVerified: false },
    { name: "European Business Schools", domain: null, isVerified: false },
    { name: "GEOS Language Centre", domain: "geos.edu.sg", isVerified: true },
    { name: "London School of Business and Finance", domain: "lsbf.edu.sg", isVerified: true },
    { name: "Intellectual Property Academy of Singapore", domain: "ipa.org.sg", isVerified: true },
    { name: "NUS Postgraduate", domain: null, isVerified: false },
    { name: "NUS Business School", domain: "bschool.nus.edu.sg", isVerified: true },
    { name: "NUS Business Analytics Centre", domain: "bac.nus.edu.sg", isVerified: true },
    { name: "LASALLE College of the Arts", domain: "lasalle.edu.sg", isVerified: true },
    { name: "S P Jain School of Global Management – Dubai", domain: "spjain.org", isVerified: true },
    { name: "Asia Pacific Management Institute", domain: null, isVerified: false },
    { name: "Graduate School of Business", domain: "gsb.nus.edu.sg", isVerified: true },
    { name: "SIM Global Education", domain: "simge.edu.sg", isVerified: true },
    { name: "Hyper Island Institute of Higher Education", domain: "hyperisland.com", isVerified: true },
    { name: "Lee Kong Chian School of Business", domain: "lksb.nus.edu.sg", isVerified: true },
    { name: "Nanyang Centre for Public Administration", domain: "ncap.ntu.edu.sg", isVerified: true },
    { name: "Rutgers Business School Asia Pacific", domain: "apac.rutgers.edu", isVerified: true },
    { name: "German Institute of Science & Technology – TUM Asia", domain: "tum-asia.edu.sg", isVerified: true },
    { name: "Singapore Manufacturers' Federation SMA", domain: null, isVerified: false },
    { name: "ESSEC Asia-Pacific", domain: "apec.essec.edu", isVerified: true },
    { name: "Aalto Executive Education Academy", domain: "aaltoee.com", isVerified: true },
    { name: "Center for American Education", domain: "cfe.edu.sg", isVerified: true },
    { name: "School of Law", domain: null, isVerified: false },
    { name: "U21 Global", domain: null, isVerified: false },
    { name: "Cornell-Nanyang Institute of Hospitality Management", domain: "cornellntu.ntu.edu.sg", isVerified: true },
    { name: "RSIS – NTU, Singapore", domain: "rsis.ntu.edu.sg", isVerified: true },
    { name: "Hartford Management Centre", domain: null, isVerified: false },
    { name: "Institute of Systems Science", domain: "iss.nus.edu.sg", isVerified: true },
    { name: "Raffles College of Higher Education", domain: "raffles-college.edu.sg", isVerified: true },
    { name: "PSB Academy Pte Ltd", domain: "psb-academy.edu.sg", isVerified: true },
    { name: "National University of Singapore Graduate School for Integrative Sciences and Engineering", domain: "gsis.nus.edu.sg", isVerified: true },
    { name: "Lee Kuan Yew School of Public Policy, National University of Singapore", domain: "lkyspp.nus.edu.sg", isVerified: true },
    { name: "Institute of Systems Science, National University of Singapore", domain: "iss.nus.edu.sg", isVerified: true },
    { name: "SMU – School of Computing and Information Systems", domain: "scis.smu.edu.sg", isVerified: true },
    { name: "INSEAD Singapore", domain: "insead.edu", isVerified: true },
    { name: "National Institute of Education, Nanyang Technological University, Singapore", domain: "nie.edu.sg", isVerified: true },
    { name: "NUS Business School", domain: "bschool.nus.edu.sg", isVerified: true },
    { name: "Nanyang Business School, Singapore", domain: "nbs.ntu.edu.sg", isVerified: true },
]