import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Somalia_universities = [

   // Somalia

   { name: "SIMAD University", domain: "simad.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Mogadishu University", domain: "mu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "University of Hargeisa", domain: "uoh-edu.net", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Puntland State University", domain: "psu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Amoud University", domain: "amouduniversity.org", region: "Africa", country: "Somalia", isVerified: true },
   { name: "University of Burao", domain: "uob-edu.net", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Benadir University", domain: "bu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "University of Somalia", domain: "uniso.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Indian Ocean University", domain: "iou.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Horseed International University", domain: "hiu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "East Africa University", domain: "eau.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "University of Southern Somalia", domain: "uss.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Somali National University", domain: "snu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Jamhuriya University of Science and Technology", domain: "just.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "East Africa University — Bosaso Campus", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Lafoole University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "University of Gedo", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Kismayo University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "New Generation University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Bay University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Himilo University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Abraar University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Hormuud University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Caalamiga Soomaaliya University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Red Sea University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Capital University of Somalia", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Sanaag University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Eelo University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Koonfur Galbeed University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Bosaso University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Nile University of Science and Technology", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Jobkey University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Al-Imaam Al-Shaafici University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Beder University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Daaru Salaam University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Islamic University of Mogadishu", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Health Sciences University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Salaam University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Daarul Xikma University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Frontier University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "SIMAD University", domain: "simad.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Mogadishu University", domain: "mu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "University of Hargeisa", domain: "uoh-edu.net", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Puntland State University", domain: "psu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Amoud University (Jaamacada Camuud)", domain: "amouduniversity.org", region: "Africa", country: "Somalia", isVerified: true },
   { name: "University of Burao", domain: "uob-edu.net", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Benadir University", domain: "bu.edu.so", region: "Africa", country: "Somalia", isVerified: true },                            
   { name: "University of Somalia", domain: "uniso.edu.so", region: "Africa", country: "Somalia", isVerified: true },                     
   { name: "Indian Ocean University", domain: "iou.edu.so", region: "Africa", country: "Somalia", isVerified: true },                     
   { name: "Horseed International University", domain: "hiu.edu.so", region: "Africa", country: "Somalia", isVerified: true },            
   { name: "East Africa University", domain: "eau.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Somali National University", domain: "snu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Jamhuriya University of Science and Technology", domain: "just.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Kismayo University", domain: "kmu.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Plasma University", domain: "plasma.edu.so", region: "Africa", country: "Somalia", isVerified: true },                         
   { name: "Golis University", domain: "golis.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Zamzam University", domain: "zamzam.edu.so", region: "Africa", country: "Somalia", isVerified: true },
   { name: "Nugaal University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "City University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
   { name: "Jazeera University", domain: null, region: "Africa", country: "Somalia", isVerified: false },
]