import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const South_Korea_universities = [

    // South Korea

    { name: "Ajou University", domain: "ajou.ac.kr", isVerified: true },
    { name: "Andong National University", domain: "anu.ac.kr", isVerified: true },
    { name: "Anyang University", domain: "anyang.ac.kr", isVerified: true },
    { name: "Baekseok University", domain: "baekseok.ac.kr", isVerified: true },
    { name: "Busan National University of Education", domain: "pen.go.kr", isVerified: true },
    { name: "Busan Presbyterian University", domain: "cpu.ac.kr", isVerified: true },
    { name: "Busan University of Foreign Studies", domain: "bufs.ac.kr", isVerified: true },
    { name: "Busan Women's College", domain: "bwc.ac.kr", isVerified: true },
    { name: "Calvin University", domain: "calvin.ac.kr", isVerified: true },
    { name: "Catholic Kwandong University", domain: "cku.ac.kr", isVerified: true },
    { name: "Catholic University of Daegu", domain: "cu.ac.kr", isVerified: true },
    { name: "Catholic University of Daejeon", domain: "cude.ac.kr", isVerified: true },
    { name: "Catholic University of Pusan", domain: "cup.ac.kr", isVerified: true },
    { name: "CHA University", domain: "cha.ac.kr", isVerified: true },
    { name: "Changwon National University", domain: "changwon.ac.kr", isVerified: true },
    { name: "Cheongju National University of Education", domain: "cnue.ac.kr", isVerified: true },
    { name: "Cheongju University", domain: "cju.ac.kr", isVerified: true },
    { name: "Chinju National University of Education", domain: "jnue.ac.kr", isVerified: true },
    { name: "Chodang University", domain: "chodang.ac.kr", isVerified: true },
    { name: "Chongshin University", domain: "chongshin.ac.kr", isVerified: true },
    { name: "Chonnam National University", domain: "chonnam.ac.kr", isVerified: true },
    { name: "Chosun University", domain: "chosun.ac.kr", isVerified: true },
    { name: "Chugye University for the Arts", domain: "chugye.ac.kr", isVerified: true },
    { name: "Chuncheon National University of Education", domain: "cnue.ac.kr", isVerified: true },
    { name: "Chung-Ang University", domain: "cau.ac.kr", isVerified: true },
    { name: "Chungbuk National University", domain: "cbnu.ac.kr", isVerified: true },
    { name: "Chungnam National University", domain: "cnu.ac.kr", isVerified: true },
    { name: "Chungwoon University", domain: "chungwoon.ac.kr", isVerified: true },
    { name: "Daegu Arts University", domain: "daeguarts.ac.kr", isVerified: true },
    { name: "Daegu Haany University", domain: "dha.ac.kr", isVerified: true },
    { name: "Daegu National University of Education", domain: "dnue.ac.kr", isVerified: true },
    { name: "Daegu University", domain: "daegu.ac.kr", isVerified: true },
    { name: "Daejeon University", domain: "dju.ac.kr", isVerified: true },
    { name: "Daejin University", domain: "daejin.ac.kr", isVerified: true },
    { name: "Daeshin University", domain: "daeshin.ac.kr", isVerified: true },
    { name: "Dankook University", domain: "dankook.ac.kr", isVerified: true },
    { name: "Dong-A University", domain: "donga.ac.kr", isVerified: true },
    { name: "Dongduk Women’s University", domain: "dongduk.ac.kr", isVerified: true },
    { name: "Dong-Eui University", domain: "deu.ac.kr", isVerified: true },
    { name: "Dongguk University", domain: "dongguk.ac.kr", isVerified: true },
    { name: "Dongseo University", domain: "dongseo.ac.kr", isVerified: true },
    { name: "Dongshin University", domain: "dongshin.ac.kr", isVerified: true },
    { name: "Dongyang University", domain: "dongyang.ac.kr", isVerified: true },
    { name: "Duksung Women’s University", domain: "duksung.ac.kr", isVerified: true },
    { name: "Eulji University", domain: "eulji.ac.kr", isVerified: true },
    { name: "Ewha Womans University", domain: "ewha.ac.kr", isVerified: true },
    { name: "Far East University, Korea", domain: "feu.ac.kr", isVerified: true },
    { name: "Gachon University", domain: "gachon.ac.kr", isVerified: true },
    { name: "Gangneung-Wonju National University", domain: "gwnu.ac.kr", isVerified: true },
    { name: "Gangseo University", domain: "gangseo.ac.kr", isVerified: true },
    { name: "Geumgang University", domain: "geumgang.ac.kr", isVerified: true },
    { name: "Gimcheon University", domain: "gimcheon.ac.kr", isVerified: true },
    { name: "Gongju National University of Education", domain: "gnue.ac.kr", isVerified: true },
    { name: "Gwangju Catholic University", domain: "gju.ac.kr", isVerified: true },
    { name: "Gwangju National University of Education", domain: "gnue.ac.kr", isVerified: true },
    { name: "Gwangju University", domain: "gwu.ac.kr", isVerified: true },
    { name: "Gyeongin National University of Education", domain: "ginue.ac.kr", isVerified: true },
    { name: "Gyeongsang National University", domain: "gnu.ac.kr", isVerified: true },
    { name: "Halla University", domain: "halla.ac.kr", isVerified: true },
    { name: "Hallym University", domain: "hallym.ac.kr", isVerified: true },
    { name: "Hanbat National University", domain: "hanbat.ac.kr", isVerified: true },
    { name: "Handong Global University", domain: "handong.edu", isVerified: true },
    { name: "Hankuk University of Foreign Studies", domain: "hufs.ac.kr", isVerified: true },
    { name: "Hankyong National University", domain: "hknu.ac.kr", isVerified: true },
    { name: "Hannam University", domain: "hannam.ac.kr", isVerified: true },
    { name: "Hansei University", domain: "hansei.ac.kr", isVerified: true },
    { name: "Hanseo University", domain: "hanseo.ac.kr", isVerified: true },
    { name: "Hanshin University", domain: "hanshin.ac.kr", isVerified: true },
    { name: "Hansung University", domain: "hansung.ac.kr", isVerified: true },
    { name: "Hanyang University", domain: "hanyang.ac.kr", isVerified: true },
    { name: "Honam University", domain: "honam.ac.kr", isVerified: true },
    { name: "Hongik University", domain: "hongik.ac.kr", isVerified: true },
    { name: "Hoseo University", domain: "hoseo.ac.kr", isVerified: true },
    { name: "Howon University", domain: "howon.ac.kr", isVerified: true },
    { name: "Hwasung Medi Science University", domain: null, isVerified: false },
    { name: "Hyupsung University", domain: "hyupsung.ac.kr", isVerified: true },
    { name: "Incheon Catholic University", domain: null, isVerified: false },
    { name: "Inha University", domain: "inha.ac.kr", isVerified: true },
    { name: "Inje University", domain: "inje.ac.kr", isVerified: true },
    { name: "Jeju International University", domain: null, isVerified: false },
    { name: "Jeju National University", domain: "jnu.ac.kr", isVerified: true },
    { name: "Jeonbuk National University", domain: "jbnu.ac.kr", isVerified: true },
    { name: "Jeonju National University of Education", domain: "jnue.ac.kr", isVerified: true },
    { name: "Jeonju University", domain: null, isVerified: false },
    { name: "Jesus University", domain: null, isVerified: false },
    { name: "Joongang Sangha University", domain: null, isVerified: false },
    { name: "Joongbu University", domain: "joongbu.ac.kr", isVerified: true },
    { name: "Jungwon University", domain: "jungwon.ac.kr", isVerified: true },
    { name: "KAIST", domain: "kaist.ac.kr", isVerified: true },
    { name: "Kangnam University", domain: "kangnam.ac.kr", isVerified: true },
    { name: "Kangwon National University", domain: "kangwon.ac.kr", isVerified: true },
    { name: "Kaya University", domain: "kaya.ac.kr", isVerified: true },
    { name: "Keimyung University", domain: "keimyung.ac.kr", isVerified: true },
    { name: "Kkottongnae University", domain: "kkottong.ac.kr", isVerified: true },
    { name: "Kongju National University", domain: "kongju.ac.kr", isVerified: true },
    { name: "Konkuk University", domain: "konkuk.ac.kr", isVerified: true },
    { name: "Konyang University", domain: "konyang.ac.kr", isVerified: true },
    { name: "Kookmin University", domain: "kookmin.ac.kr", isVerified: true },
    { name: "Korea Aerospace University", domain: "kau.ac.kr", isVerified: true },
    { name: "Korea Baptist Theological University", domain: "kbtu.ac.kr", isVerified: true },
    { name: "Korea Maritime and Ocean University", domain: "kmou.ac.kr", isVerified: true },
    { name: "Korea National Sport University", domain: "knsu.ac.kr", isVerified: true },
    { name: "Korea National University of Education", domain: "knue.ac.kr", isVerified: true },
    { name: "Korea National University of Transportation", domain: "knut.ac.kr", isVerified: true },
    { name: "Korea Nazarene University", domain: null, isVerified: false },
    { name: "Korea University", domain: "korea.ac.kr", isVerified: true },
    { name: "Korea University of Technology and Education", domain: "koreatech.ac.kr", isVerified: true },
    { name: "Korean Bible University", domain: "kbu.ac.kr", isVerified: true },
    { name: "Korean National University of Arts", domain: "knuart.ac.kr", isVerified: true },
    { name: "Kosin University", domain: "kosin.ac.kr", isVerified: true },
    { name: "Kumoh National University of Technology", domain: "kumoh.ac.kr", isVerified: true },
    { name: "Kunsan National University", domain: "kunsan.ac.kr", isVerified: true },
    { name: "Kwangju Women's University", domain: "kw.ac.kr", isVerified: true },
    { name: "Kwangshin University", domain: "kwangshin.ac.kr", isVerified: true },
    { name: "Kwangwoon University", domain: "kw.ac.kr", isVerified: true },
    { name: "Kyonggi University", domain: "kyonggi.ac.kr", isVerified: true },
    { name: "Kyung Hee University", domain: "khu.ac.kr", isVerified: true },
    { name: "Kyungdong University", domain: "kyungdong.ac.kr", isVerified: true },
    { name: "Kyungil University", domain: "kyungil.ac.kr", isVerified: true },
    { name: "Kyungnam University", domain: "kyungnam.ac.kr", isVerified: true },
    { name: "Kyungpook National University", domain: "knu.ac.kr", isVerified: true },
    { name: "Kyungsung University", domain: "ks.ac.kr", isVerified: true },
    { name: "Kyungwoon University", domain: "kw.ac.kr", isVerified: true },
    { name: "Luther University", domain: "luther.ac.kr", isVerified: true },
    { name: "Mokpo Catholic University", domain: "mcu.ac.kr", isVerified: true },
    { name: "Mokpo National Maritime University", domain: "mnmu.ac.kr", isVerified: true },
    { name: "Mokpo National University", domain: "mpu.ac.kr", isVerified: true },
    { name: "Mokwon University", domain: "mw.ac.kr", isVerified: true },
    { name: "Myongji University", domain: "myongji.ac.kr", isVerified: true },
    { name: "Nambu University", domain: "nambu.ac.kr", isVerified: true },
    { name: "Namseoul University", domain: "namseoul.ac.kr", isVerified: true },
    { name: "Pai Chai University", domain: "pc.ac.kr", isVerified: true },
    { name: "Pohang University of Science and Technology", domain: "postech.ac.kr", isVerified: true },
    { name: "Presbyterian University and Theological Seminary", domain: "put.ac.kr", isVerified: true },
    { name: "Pukyong National University", domain: "pknu.ac.kr", isVerified: true },
    { name: "Pusan National University", domain: "pnu.ac.kr", isVerified: true },
    { name: "Pyeongtaek University", domain: "ptu.ac.kr", isVerified: true },
    { name: "Sahmyook University", domain: "syu.ac.kr", isVerified: true },
    { name: "Sangji University", domain: "sangji.ac.kr", isVerified: true },
    { name: "Sangmyung University", domain: "smu.ac.kr", isVerified: true },
    { name: "Sehan University", domain: "sehan.ac.kr", isVerified: true },
    { name: "Sejong University", domain: "sejong.ac.kr", isVerified: true },
    { name: "Semyung University", domain: "smy.ac.kr", isVerified: true },
    { name: "Seokyeong University", domain: "skuniv.ac.kr", isVerified: true },
    { name: "Seoul Christian University", domain: "scu.ac.kr", isVerified: true },
    { name: "Seoul Jangsin University", domain: "jsu.ac.kr", isVerified: true },
    { name: "Seoul National University", domain: "snu.ac.kr", isVerified: true },
    { name: "Seoul National University of Education", domain: "snue.ac.kr", isVerified: true },
    { name: "Seoul National University of Science and Technology", domain: "seoultech.ac.kr", isVerified: true },
    { name: "Seoul Theological University", domain: "stu.ac.kr", isVerified: true },
    { name: "Seoul Women's University", domain: "swu.ac.kr", isVerified: true },
    { name: "Seowon University", domain: "seowon.ac.kr", isVerified: true },
    { name: "Silla University", domain: "silla.ac.kr", isVerified: true },
    { name: "Singyeongju University", domain: "sgu.ac.kr", isVerified: true },
    { name: "Sogang University", domain: "sogang.ac.kr", isVerified: true },
    { name: "Sookmyung Women's University", domain: "sookmyung.ac.kr", isVerified: true },
    { name: "Soonchunhyang University", domain: "soonchun.ac.kr", isVerified: true },
    { name: "Soongsil University", domain: "ssu.ac.kr", isVerified: true },
    { name: "Sun Moon University", domain: "sunmoon.ac.kr", isVerified: true },
    { name: "Sunchon National University", domain: "sunchon.ac.kr", isVerified: true },
    { name: "Sungkonghoe University", domain: "skhu.ac.kr", isVerified: true },
    { name: "Sungkyul University", domain: "sungkyul.ac.kr", isVerified: true },
    { name: "Sungkyunkwan University", domain: "skku.edu", isVerified: true },
    { name: "Sungshin University", domain: "sungshin.ac.kr", isVerified: true },
    { name: "Suwon Catholic University", domain: "suwon.ac.kr", isVerified: true },
    { name: "Tech University of Korea", domain: "tech.ac.kr", isVerified: true },
    { name: "The Catholic University of Korea", domain: "catholic.ac.kr", isVerified: true },
    { name: "The University of Suwon", domain: "su.ac.kr", isVerified: true },
    { name: "Tongmyung University", domain: "tmu.ac.kr", isVerified: true },
    { name: "U1 University", domain: "u1.ac.kr", isVerified: true },
    { name: "Uiduk University", domain: "uiduk.ac.kr", isVerified: true },
    { name: "Ulsan National Institute of Science and Technology", domain: "unist.ac.kr", isVerified: true },
    { name: "University of Incheon", domain: "incheon.ac.kr", isVerified: true },
    { name: "University of Science and Technology Korea", domain: "ust.ac.kr", isVerified: true },
    { name: "University of Seoul", domain: "us.ac.kr", isVerified: true },
    { name: "University of Ulsan", domain: "uos.ac.kr", isVerified: true },
    { name: "Wonkwang University", domain: "wonkwang.ac.kr", isVerified: true },
    { name: "Woosong University", domain: "woosong.ac.kr", isVerified: true },
    { name: "Woosuk University", domain: "woosuk.ac.kr", isVerified: true },
    { name: "Yeungnam University", domain: "ynu.ac.kr", isVerified: true },
    { name: "Yewon Arts University", domain: "yewon.ac.kr", isVerified: true },
    { name: "Yong-In University", domain: "yun.ac.kr", isVerified: true },
    { name: "Yonsei University", domain: "yonsei.ac.kr", isVerified: true },
    { name: "Youngnam Theological University and Seminary", domain: "ytu.ac.kr", isVerified: true },
    { name: "Youngsan University", domain: "youngsan.ac.kr", isVerified: true },
    { name: "Youngsan University of Son Studies", domain: null, isVerified: false },          
]