import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Spain_universities = [

    // Spain

    { name: "Universidad de Barcelona", domain: "ub.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Complutense de Madrid", domain: "ucm.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Autónoma de Barcelona", domain: "uab.cat", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Valencia", domain: "uv.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Granada", domain: "ugr.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Politécnica de Madrid", domain: "upm.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Politécnica de Cataluña", domain: "upc.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad del País Vasco", domain: "ehu.eus", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Politécnica de València", domain: "upv.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Sevilla", domain: "us.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Pompeu Fabra", domain: "upf.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Autónoma de Madrid", domain: "uam.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Alicante", domain: "ua.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Zaragoza", domain: "unizar.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Málaga", domain: "uma.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Murcia", domain: "um.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Carlos III de Madrid", domain: "uc3m.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Salamanca", domain: "usal.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Santiago de Compostela", domain: "usc.gal", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Valladolid", domain: "uva.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Navarra", domain: "unav.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidade de Vigo", domain: "uvigo.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Castilla-La Mancha", domain: "uclm.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Oviedo", domain: "uniovi.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Rey Juan Carlos", domain: "urjc.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Jaime I", domain: "uji.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Las Palmas de Gran Canaria", domain: "ulpgc.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Córdoba", domain: "uco.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Rovira i Virgili", domain: "urv.cat", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de les Illes Balears", domain: "uib.eu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Cádiz", domain: "uca.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Alcalá", domain: "uah.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de La Laguna", domain: "ull.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidade da Coruña", domain: "udc.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Cantabria", domain: "unican.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de La Rioja", domain: "unirioja.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universitat de Lleida", domain: "udl.cat", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Pontificia Comillas", domain: "comillas.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Extremadura", domain: "unex.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Jaén", domain: "ujaen.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Almería", domain: "ual.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de León", domain: "unileon.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Gerona", domain: "udg.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Pablo de Olavide", domain: "upo.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Deusto", domain: "deusto.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Miguel Hernández de Elche", domain: "umh.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Huelva", domain: "uhu.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Pública de Navarra", domain: "unavarra.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad CEU San Pablo", domain: "ceu.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Ramon Llull", domain: "url.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Politécnica de Cartagena", domain: "upct.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Burgos", domain: "ubu.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Antonio de Nebrija", domain: "nebrija.com", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Católica San Antonio de Murcia", domain: "ucam.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Alfonso X el Sabio", domain: "uax.com", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Vich - Universidad Central de Cataluña", domain: "uvic.cat", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Católica de Valencia San Vicente Mártir", domain: "ucv.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Francisco de Vitoria", domain: "ufv.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad de Mondragón", domain: "mondragon.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universitat Internacional de Catalunya", domain: "uic.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Internacional Menéndez Pelayo", domain: "uimp.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Internacional de Andalucía", domain: "unia.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Camilo José Cela", domain: "ucjc.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Pontificia de Salamanca", domain: "upsa.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad San Jorge", domain: "usj.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad CEU Cardenal Herrera", domain: "uch.ceu.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Loyola Andalucía", domain: "uloyola.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Europea Miguel de Cervantes", domain: "uemc.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Abat Oliba CEU", domain: "uao.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Católica de Ávila", domain: "ucavila.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Europea del Atlántico", domain: "uneatlantico.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "CUNEF Universidad", domain: "cunef.edu", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad del Atlántico Medio", domain: "ugatlantico.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "Universidad Fernando Pessoa Canarias", domain: null, region: "Europe", country: "Spain", isVerified: false },
    { name: "Universidad Europea de Madrid", domain: "uem.es", region: "Europe", country: "Spain", isVerified: true },
    { name: "IE University", domain: "ie.edu", region: "Europe", country: "Spain", isVerified: true },

]