import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Sudan_universities = [

   // Sudan

   { name: "Mashreq University", domain: "mashreq.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Khartoum", domain: "uofk.edu", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Sudan University of Science and Technology", domain: "sustech.edu", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Ahfad University for Women", domain: "ahfad.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Science and Technology", domain: "ust.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Neelain University", domain: "neelain.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "International University of Africa", domain: "iua.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Gezira", domain: "uog.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Omdurman Islamic University", domain: "oiu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Alsalam University", domain: "alsalam.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "The Future University", domain: "fu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Nile Valley University", domain: "nilevalley.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "National University-Sudan", domain: "nu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Medical Sciences and Technology", domain: "umst-edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Shendi", domain: "ush.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Elrazi University", domain: "elrazi.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Al Zaiem Al Azhari University", domain: "aau.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Elsheikh Abdallah Elbadri University", domain: "eaeu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Kassala", domain: "kassalauni.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Gadarif", domain: "gaduniv.edu.sd", region: "Africa", country: "Sudan", isVerified: true },  
   { name: "University of Bahri", domain: "bahri.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Karary University", domain: "karary.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Al Fashir University", domain: "fashir.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of the Holy Quran and Islamic Sciences", domain: "quran-unv.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Kordofan", domain: "kordofan.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Nyala", domain: "nyalau.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Omdurman Ahlia University", domain: "oau.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Dongola", domain: "uofd.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of El Imam El Mahdi", domain: "mahdi.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "AlMughtaribeen University", domain: "mu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Red Sea University", domain: "rsu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Ibn Sina University", domain: "isu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Merowe University of Technology", domain: "merowe.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Sudan Academy of Sciences", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "West Kordofan University", domain: "wku.edu.sd", region: "Africa", country: "Sudan", isVerified: false },
   { name: "National Ribat University", domain: "ribat.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Sinnar University", domain: "uofs.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of Zalingei", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "University of Bakhtalruda", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "University of Albutana", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "White Nile University", domain: "wnu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Sudan International University", domain: "siu-sd.com", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Wad Medani Ahlia University", domain: "wadmedani-ahlia.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "University of El Geneina", domain: "gu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
   { name: "Sudan Technological University", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "University of East Kordofan", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "University of Garden City", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "Managil University of Science and Technology", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "University of Technology Khartoum", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "Eldaein University", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "Dalanj University", domain: null, region: "Africa", country: "Sudan", isVerified: false },
   { name: "University of Blue Nile", domain: "bnu.edu.sd", region: "Africa", country: "Sudan", isVerified: true },
]