import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Tai_universities = [

   // Taiwan

   { name: "National Taiwan University", domain: "ntu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Yang Ming Chiao Tung University", domain: "nycu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Cheng Kung University", domain: "ncku.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taiwan Normal University", domain: "ntnu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Tsing Hua University", domain: "nthu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Chengchi University", domain: "nccu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tamkang University", domain: "tku.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Sun Yat-Sen University", domain: "nsysu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Central University", domain: "ncu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Chung Hsing University", domain: "nchu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Kaohsiung University of Science and Technology", domain: "nkust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Fu Jen Catholic University", domain: "fju.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chinese Culture University", domain: "pccu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taiwan University of Science and Technology", domain: "ntust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Chung Cheng University", domain: "ccu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "China Medical University, Taiwan", domain: "cmu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Feng Chia University", domain: "fcu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tunghai University", domain: "thu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Taipei Medical University", domain: "tmu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taipei University of Technology", domain: "ntut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Ming Chuan University", domain: "mcu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Soochow University, Taiwan", domain: "scu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Chi Nan University", domain: "ncnu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "I-Shou University", domain: "isu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taiwan Ocean University", domain: "ntou.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Yuan Ze University", domain: "yzu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Dong Hwa University", domain: "ndhu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Providence University", domain: "pu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taipei University", domain: "ntpu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chung Yuan Christian University", domain: "cycu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true }, 
   { name: "Kaohsiung Medical University", domain: "kmu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Yunlin University of Science and Technology", domain: "nyust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Changhua University of Education", domain: "ncue.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chaoyang University of Technology", domain: "cyut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National University of Kaohsiung", domain: "nuk.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Asia University, Taiwan", domain: "asia.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chang Gung University", domain: "cgu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Shih Hsin University", domain: "shu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Southern Taiwan University of Science and Technology", domain: "stust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tatung University", domain: "tatung.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Chiayi University", domain: "ncyu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Pingtung University of Science and Technology", domain: "npust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National University of Tainan", domain: "nutn.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taipei University of Education", domain: "ntue.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tzu Chi University", domain: "tcu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taiwan University of Arts", domain: "ntua.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Kaohsiung Normal University", domain: "nknu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chung Hua University", domain: "chu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Formosa University", domain: "nfu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Asia Eastern University of Science and Technology", domain: "aeust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Taipei National University of the Arts", domain: "tnua.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Shih Chien University", domain: "usc.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taichung University of Education", domain: "ntcue.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Nanhua University", domain: "nhu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Wenzao Ursuline University of Languages", domain: "wzu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "University of Taipei", domain: "utaipei.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Pingtung University", domain: "nptu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chung Shan Medical University", domain: "csmu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Kun Shan University", domain: "ksu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Da-Yeh University", domain: "dayeh.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taitung University", domain: "nttu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Ilan University", domain: "niu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Dharma Drum Institute of Liberal Arts", domain: "dila.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Chin-Yi University of Technology", domain: "ncut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National United University", domain: "nuu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taichung University of Science and Technology", domain: "nutc.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Shu-Te University", domain: "stu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chang Jung Christian University", domain: "cjcu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Nan Kai University of Technology", domain: "nkut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Minghsin University of Science and Technology", domain: "must.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Aletheia University", domain: "au.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chia Nan University of Pharmacy and Science", domain: "cnu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Huafan University", domain: "hfu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Hungkuang University", domain: "hk.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Cheng Shiu University", domain: "csu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tainan National University of the Arts", domain: "tnnua.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Fo Guang University", domain: "fgu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taipei University of Nursing and Health Sciences", domain: "ntunhs.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "China University of Technology", domain: "cute.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chien Hsin University of Science and Technology", domain: "uch.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Fooyin University", domain: "fy.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Kainan University", domain: "knu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Lunghwa University of Science and Technology", domain: "lhu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taipei University of Business", domain: "ntub.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chihlee University of Technology", domain: "chihlee.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Kaohsiung University of Hospitality and Tourism", domain: "nkuht.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Hsuan Chuang University", domain: "hcu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tajen University", domain: "tajen.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taiwan University of Sport", domain: "ntus.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Central Taiwan University of Science and Technology", domain: "ctust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Ming Chi University of Technology", domain: "mcut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tainan University of Technology", domain: "tut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Yuanpei University", domain: "ypu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Taiwan Steel University of Science and Technology", domain: "tsust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Yu Da University of Science and Technology", domain: "ydu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Vanung University", domain: "vnu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Hsiuping University of Science and Technology", domain: "hsu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Quemoy University", domain: "nqu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Ling Tung University", domain: "ltu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Penghu University of Science and Technology", domain: "npust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "CTBC Financial Management College", domain: "ctbc.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Takming University of Science and Technology", domain: "takming.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chienkuo Technology University", domain: "ctu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chung Hwa University of Medical Technology", domain: "chmt.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "National Taiwan Sport University", domain: "ntus.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "MingDao University", domain: "mingdao.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Jinwen University of Science and Technology", domain: "just.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tungnan University", domain: "tnu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "St John's University", domain: "sju.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Chang Gung University of Science and Technology", domain: "cgust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "China University of Science and Technology", domain: "cute.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Hsing Wu University", domain: "hwu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "WuFeng University", domain: "wfu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Taipei City University of Science and Technology", domain: "tpcu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Meiho University", domain: "meiho.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Overseas Chinese University", domain: "ocu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Hwa Hsia University of Technology", domain: "hhust.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Taipei University of Maritime Technology", domain: "tmut.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "HungKuo Delin University of Technology", domain: "hdu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "CTBC University of Technology", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "Nanya Institute of Technology", domain: "niit.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "University of Kang Ning", domain: "knu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Deh Yu College of Nursing and Health", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "Tung Fang Design University", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "Lee-Ming Institute of Technology", domain: "lmu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Minth University of Science and Technology", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "National Taiwan College of Performing Arts", domain: "ntcpa.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Dahan Institute of Technology", domain: "dahan.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Taiwan Shoufu University", domain: "tsu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Tatung Institute of Commerce and Technology", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "Chungyu University of Film and Arts Technology", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "TransWorld University", domain: "twu.edu.tw", region: "Asia", country: "Taiwan", isVerified: true },
   { name: "Lan Yang Institute of Technology", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "Nan Jeon University of Science and Technology", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
   { name: "Toko University", domain: null, region: "Asia", country: "Taiwan", isVerified: false },
]