import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Thailand_universities = [

    // Thailand

    { name: "Mahidol University", domain: "mahidol.ac.th", isVerified: true },
    { name: "Chulalongkorn University", domain: "chula.ac.th", isVerified: true },
    { name: "Chiang Mai University", domain: "cmu.ac.th", isVerified: true },
    { name: "Kasetsart University", domain: "ku.ac.th", isVerified: true },
    { name: "Thammasat University", domain: "tu.ac.th", isVerified: true },
    { name: "Prince of Songkla University", domain: "psu.ac.th", isVerified: true },
    { name: "Khon Kaen University", domain: "kku.ac.th", isVerified: true },
    { name: "Asian Institute of Technology", domain: "ait.ac.th", isVerified: true },
    { name: "Ramkhamhaeng University", domain: "rmu.ac.th", isVerified: true },
    { name: "King Mongkut's University of Technology Thonburi", domain: "kmutt.ac.th", isVerified: true },
    { name: "King Mongkut's Institute of Technology Ladkrabang", domain: "kmitl.ac.th", isVerified: true },
    { name: "Burapha University", domain: "buu.ac.th", isVerified: true },
    { name: "Naresuan University", domain: "nu.ac.th", isVerified: true },
    { name: "Suan Sunandha Rajabhat University", domain: "ssru.ac.th", isVerified: true },
    { name: "Srinakharinwirot University", domain: "swu.ac.th", isVerified: true },
    { name: "Silpakorn University", domain: "su.ac.th", isVerified: true },
    { name: "Suranaree University of Technology", domain: "sut.ac.th", isVerified: true },
    { name: "Assumption University", domain: "au.edu.th", isVerified: true },
    { name: "King Mongkut's University of Technology North Bangkok", domain: "kmutnb.ac.th", isVerified: true },
    { name: "Walailak University", domain: "wu.ac.th", isVerified: true },
    { name: "Sripatum University", domain: "spu.ac.th", isVerified: true },
    { name: "Ubon Ratchathani University", domain: "ubru.ac.th", isVerified: true },
    { name: "Mahasarakham University", domain: "msu.ac.th", isVerified: true },
    { name: "Mahachulalongkornrajavidyalaya University", domain: "mcu.ac.th", isVerified: true },
    { name: "Bangkok University", domain: "bu.ac.th", isVerified: true },
    { name: "Nakhon Ratchasima Rajabhat University", domain: "nrru.ac.th", isVerified: true },
    { name: "Maejo University", domain: "mju.ac.th", isVerified: true },
    { name: "National Institute of Development Administration", domain: "nida.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Thanyaburi", domain: "rut.ac.th", isVerified: true },
    { name: "Mae Fah Luang University", domain: "mfu.ac.th", isVerified: true },
    { name: "Suan Dusit University", domain: "dusit.ac.th", isVerified: true },
    { name: "Rangsit University", domain: "rsu.ac.th", isVerified: true },
    { name: "Stamford International University", domain: "stamford.edu", isVerified: true },
    { name: "Rajamangala University of Technology Isarn", domain: "rmuti.ac.th", isVerified: true },
    { name: "Yala Rajabhat University", domain: "yru.ac.th", isVerified: true },
    { name: "Thaksin University", domain: "thaksin.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Srivijaya", domain: "rmutr.ac.th", isVerified: true },
    { name: "Lampang Rajabhat University", domain: "lru.ac.th", isVerified: true },
    { name: "Buriram Rajabhat University", domain: "brru.ac.th", isVerified: true },
    { name: "University of the Thai Chamber of Commerce", domain: "utcc.ac.th", isVerified: true },
    { name: "Sripatum University", domain: "spu.ac.th", isVerified: true },
    { name: "Ubon Ratchathani University", domain: "ubu.ac.th", isVerified: true },
    { name: "Mahasarakham University", domain: "msu.ac.th", isVerified: true },
    { name: "Mahachulalongkornrajavidyalaya University", domain: "mcu.ac.th", isVerified: true },
    { name: "Bangkok University", domain: "bu.ac.th", isVerified: true },
    { name: "Nakhon Ratchasima Rajabhat University", domain: "nrru.ac.th", isVerified: true },
    { name: "Maejo University", domain: "mju.ac.th", isVerified: true },
    { name: "National Institute of Development Administration", domain: "nida.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Thanyaburi", domain: "rut.ac.th", isVerified: true },
    { name: "Mae Fah Luang University", domain: "mfu.ac.th", isVerified: true },
    { name: "Suan Dusit University", domain: "dusit.ac.th", isVerified: true },
    { name: "Rangsit University", domain: "rsu.ac.th", isVerified: true },
    { name: "Stamford International University", domain: "stamford.edu", isVerified: true },
    { name: "Rajamangala University of Technology Isarn", domain: "rmuti.ac.th", isVerified: true },
    { name: "Yala Rajabhat University", domain: "yru.ac.th", isVerified: true },
    { name: "Thaksin University", domain: "thaksin.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Srivijaya", domain: "rmutr.ac.th", isVerified: true },
    { name: "Lampang Rajabhat University", domain: "lru.ac.th", isVerified: true },
    { name: "Buriram Rajabhat University", domain: "brru.ac.th", isVerified: true },
    { name: "University of the Thai Chamber of Commerce", domain: "utcc.ac.th", isVerified: true },
    { name: "Phetchaburi Rajabhat University", domain: "pbru.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Krungthep", domain: "rmutk.ac.th", isVerified: true },
    { name: "Songkhla Rajabhat University", domain: "skru.ac.th", isVerified: true },
    { name: "Nakhon Sawan Rajabhat University", domain: "nsru.ac.th", isVerified: true },
    { name: "Sakon Nakhon Rajabhat University", domain: "snru.ac.th", isVerified: true },
    { name: "Ubon Ratchathani Rajabhat University", domain: "ubru.ac.th", isVerified: true },
    { name: "Chulabhorn Royal Academy", domain: "cra.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Rattanakosin", domain: "rmutr.ac.th", isVerified: true },
    { name: "Valaya Alongkorn Rajabhat University", domain: "vru.ac.th", isVerified: true },
    { name: "Nakhon Phanom University", domain: "npu.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Suvarnabhumi", domain: "rmutsb.ac.th", isVerified: true },
    { name: "Mahamakut Buddhist University", domain: "mbu.ac.th", isVerified: true },
    { name: "Rambhai Barni Rajabhat University", domain: "rbru.ac.th", isVerified: true },
    { name: "Phuket Rajabhat University", domain: "pkru.ac.th", isVerified: true },
    { name: "Dhonburi Rajabhat University", domain: "dru.ac.th", isVerified: true },
    { name: "North Eastern University", domain: "neu.ac.th", isVerified: true },
    { name: "Kasem Bundit University", domain: "kbu.ac.th", isVerified: true },
    { name: "Western University", domain: "western.ac.th", isVerified: true },
    { name: "Phranakhon Rajabhat University", domain: "pnru.ac.th", isVerified: true },
    { name: "Nakhon Si Thammarat Rajabhat University", domain: "nstru.ac.th", isVerified: true },
    { name: "Loei Rajabhat University", domain: "lru.ac.th", isVerified: true },
    { name: "Surindra Rajabhat University", domain: "srru.ac.th", isVerified: true },
    { name: "Phranakhon Si Ayutthaya Rajabhat University", domain: "aru.ac.th", isVerified: true },
    { name: "Sisaket Rajabhat University", domain: "sskru.ac.th", isVerified: true },
    { name: "Thepsatri Rajabhat University", domain: "tru.ac.th", isVerified: true },
    { name: "Krirk University", domain: "krirk.ac.th", isVerified: true },
    { name: "Kalasin University", domain: "ksu.ac.th", isVerified: true },
    { name: "Fatoni University", domain: "ftu.ac.th", isVerified: true },
    { name: "Princess Galyani Vadhana Institute of Music", domain: "pgvim.ac.th", isVerified: true },
    { name: "Roi-et Rajabhat University", domain: "reru.ac.th", isVerified: true },   
    { name: "Chaiyaphum Rajabhat University", domain: "cpru.ac.th", isVerified: true },
    { name: "Kanchanaburi Rajabhat University", domain: "kbru.ac.th", isVerified: true },
    { name: "Christian University of Thailand", domain: "cut.ac.th", isVerified: true },
    { name: "Muban Chombueng Rajabhat University", domain: "mcru.ac.th", isVerified: true },
    { name: "Uttaradit Rajabhat University", domain: "uru.ac.th", isVerified: true },
    { name: "Phetchabun Rajabhat University", domain: "pru.ac.th", isVerified: true },
    { name: "Rajapruk University", domain: "rpu.ac.th", isVerified: true },
    { name: "Thonburi University", domain: "thonburiu.ac.th", isVerified: true },
    { name: "Hatyai University", domain: "hu.ac.th", isVerified: true },
    { name: "Princess of Naradhiwas University", domain: "pnu.ac.th", isVerified: true },
    { name: "Bangkok Thonburi University", domain: "btu.ac.th", isVerified: true },
    { name: "South-East Asia University", domain: "seau.ac.th", isVerified: true },
    { name: "Asia-Pacific International University", domain: "apiu.ac.th", isVerified: true },
    { name: "North Bangkok University", domain: "nbu.ac.th", isVerified: true },
    { name: "Navamindradhiraj University", domain: "nru.ac.th", isVerified: true },
    { name: "Eastern Asia University", domain: "eau.ac.th", isVerified: true },
    { name: "Rattana Bundit University", domain: "rbu.ac.th", isVerified: true },
    { name: "St Teresa International University", domain: "stiu.ac.th", isVerified: true },
    { name: "North Chiang Mai University", domain: "ncmu.ac.th", isVerified: true },
    { name: "Vongchavalitkul University", domain: "vcu.ac.th", isVerified: true },
    { name: "Phetchaburi Rajabhat University", domain: "pbru.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Krungthep", domain: "rmutk.ac.th", isVerified: true },
    { name: "Songkhla Rajabhat University", domain: "skru.ac.th", isVerified: true },
    { name: "Nakhon Sawan Rajabhat University", domain: "nsru.ac.th", isVerified: true },
    { name: "Sakon Nakhon Rajabhat University", domain: "snru.ac.th", isVerified: true },
    { name: "Ubon Ratchathani Rajabhat University", domain: "ubru.ac.th", isVerified: true },
    { name: "Chulabhorn Royal Academy", domain: "cra.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Rattanakosin", domain: "rmutr.ac.th", isVerified: true },
    { name: "Valaya Alongkorn Rajabhat University", domain: "vru.ac.th", isVerified: true },
    { name: "Nakhon Phanom University", domain: "npu.ac.th", isVerified: true },
    { name: "Rajamangala University of Technology Suvarnabhumi", domain: "rmutsb.ac.th", isVerified: true },
    { name: "Mahamakut Buddhist University", domain: "mbu.ac.th", isVerified: true },
    { name: "Rambhai Barni Rajabhat University", domain: "rbru.ac.th", isVerified: true },
    { name: "Phuket Rajabhat University", domain: "pkru.ac.th", isVerified: true },
    { name: "Dhonburi Rajabhat University", domain: "dru.ac.th", isVerified: true },
    { name: "North Eastern University", domain: "neu.ac.th", isVerified: true },
    { name: "Kasem Bundit University", domain: "kbu.ac.th", isVerified: true },
    { name: "Western University", domain: "western.ac.th", isVerified: true },
    { name: "Phranakhon Rajabhat University", domain: "pnru.ac.th", isVerified: true },
    { name: "Nakhon Si Thammarat Rajabhat University", domain: "nstru.ac.th", isVerified: true },
    { name: "Chaiyaphum Rajabhat University", domain: "cpru.ac.th", isVerified: true },
    { name: "Kanchanaburi Rajabhat University", domain: "kbru.ac.th", isVerified: true },
    { name: "Christian University of Thailand", domain: "cut.ac.th", isVerified: true },
    { name: "Muban Chombueng Rajabhat University", domain: "mcru.ac.th", isVerified: true },
    { name: "Uttaradit Rajabhat University", domain: "uru.ac.th", isVerified: true },
    { name: "Phetchabun Rajabhat University", domain: "pru.ac.th", isVerified: true },
    { name: "Rajapruk University", domain: "rpu.ac.th", isVerified: true },
    { name: "Thonburi University", domain: "thonburiu.ac.th", isVerified: true },
    { name: "Hatyai University", domain: "hu.ac.th", isVerified: true },
    { name: "Princess of Naradhiwas University", domain: "pnu.ac.th", isVerified: true },
    { name: "Bangkok Thonburi University", domain: "btu.ac.th", isVerified: true },
    { name: "South-East Asia University", domain: "seau.ac.th", isVerified: true },
    { name: "Asia-Pacific International University", domain: "apiu.ac.th", isVerified: true },
    { name: "North Bangkok University", domain: "nbu.ac.th", isVerified: true },
    { name: "Navamindradhiraj University", domain: "nru.ac.th", isVerified: true },
    { name: "Eastern Asia University", domain: "eau.ac.th", isVerified: true },
    { name: "Rattana Bundit University", domain: "rbu.ac.th", isVerified: true },
    { name: "St Teresa International University", domain: "stiu.ac.th", isVerified: true },
    { name: "North Chiang Mai University", domain: "ncmu.ac.th", isVerified: true },
    { name: "Vongchavalitkul University", domain: "vcu.ac.th", isVerified: true },
    { name: "Pathumwan Institute of Technology", domain: "pit.ac.th", isVerified: true },
    { name: "The Far Eastern University", domain: "feu.ac.th", isVerified: true },
    { name: "Shinawatra University", domain: "siu.ac.th", isVerified: true },
    { name: "Nation University", domain: "nation.ac.th", isVerified: true },
    { name: "Chaopraya University", domain: "cpu.ac.th", isVerified: true },
    { name: "Ratchathani University", domain: "rtu.ac.th", isVerified: true },
    { name: "Pathumthani University", domain: null, isVerified: false },
    { name: "The University of Central Thailand", domain: "uct.ac.th", isVerified: true },
    { name: "Tapee University", domain: "tapee.ac.th", isVerified: true },
    { name: "Chalermkarnchana University", domain: null, isVerified: false },
    { name: "Saint John's University", domain: "sju.ac.th", isVerified: true },
    { name: "Bangkok Suvarnabhumi University", domain: "bsu.ac.th", isVerified: true },
    { name: "Phitsanulok University", domain: null, isVerified: false },
]