import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Tunisia_universities = [

// Tunisia

{ name: "Université de Tunis El Manar", domain: "utm.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Ingénierie et de Technologie", domain: "esprit.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Carthage", domain: "ucar.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Sfax", domain: "univ-sfax.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Centrale", domain: "universitecentrale.net", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Monastir", domain: "um.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de la Manouba", domain: "uma.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Sousse", domain: "uc.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Tunis", domain: "utunis.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "South Mediterranean University", domain: "smu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Libre de Tunis", domain: "ult-tunisie.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Gabès", domain: "univgb.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Privée des Hautes Etudes à Tunis", domain: "ihet.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Jendouba", domain: "uj.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Gafsa", domain: "ugaf.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université de Kairouan", domain: "univ-k.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Ez-Zitouna", domain: "uz.rnu.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université SESAME", domain: "universitesesame.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Montplaisir Tunis", domain: "umt.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée des Technologies de l'Information et de Management de Nabeul", domain: "itbs.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Polytechnique Privée de Sousse", domain: "polytecsousse.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "EPI Sousse", domain: "episup.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Européenne de Tunis", domain: "universiteeuropeenne.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Paris Dauphine-PSL, Campus de Tunis", domain: "tunis.dauphine.psl.eu", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée de l'Aéronautique et des Technologies", domain: "esat.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Internationale de Tunis", domain: "univ-internationale.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Ibn Khaldoun", domain: "uik.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Administration des Affaires et de Droit Avicenne", domain: "apbs.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée de Technologie et de Management", domain: "suptech.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Mahmoud El Materi", domain: "umm-tunisie.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "TIME Université", domain: "time.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Instituts Supérieurs des Etudes Technologiques", domain: null, region: "Africa", country: "Tunisia", isVerified: false },
{ name: "Institut Supérieur Privé d'Administration des Entreprises", domain: "iaetunis.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Privée des Hautes Etudes à Sousse", domain: "ihes.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Polytechnique Internationale Privée de Tunis", domain: "pi.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut International de Technologie", domain: "iit.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée des Technologies d'Informatique et de Management", domain: "estim.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Privée des Etudes Scientifiques et Technologiques de Mégrine", domain: "upes-megrine.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "International School of Business", domain: "isb.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Arabe des Sciences", domain: "uas.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Assurance et de Finance", domain: "espaf-businessschool.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Informatique et d'Administration des Affaires", domain: "ebs.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Faculté des Sciences de la Santé", domain: "supsat-univ.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "American University in North Africa", domain: "auna.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Privée de Sousse", domain: "ups.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Leaders University", domain: "leaders-university.net", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Architecture, d'Audiovisuel et de Design", domain: "esad.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Méditerranéenne", domain: "mit-monplaisir.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Ingénierie et de Technologie Appliquée", domain: "espita.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Internationale Supérieure Privée de Droit et des Affaires", domain: "lbs.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Polytechnique Internationale Privée de Sfax", domain: "espin.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée d'Ingénieurs de Monastir", domain: "esprim.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Polytechnique privé des Sciences Avancées de Sfax", domain: "ipsas-ens.net", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Université Technologique Privée de Gabès", domain: "essat-gabes.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Privée des Etudes Administratives et Commerciales", domain: "eseac.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Superieure d'Ingénieurs Privée de Gafsa", domain: "esip.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "FMSA School of Digital Business", domain: "fmsa-tunisie.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Supérieure Polytechnique Privée de Monastir", domain: "polytechmonastir.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Supérieur Privé des Sciences Infirmières de Sousse", domain: "isis-infirmier.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Supérieur des Etudes Paramédicales et Sciences Infirmières", domain: "etoile-formation.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Supérieur Privé des Sciences Infirmières El Amed", domain: "universite-amed.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Tunisia Tech University", domain: "ttu.ens.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut Supérieur Privé des Sciences Infirmières de Kairouan", domain: "ispsik.com", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "Institut International du Numérique et de l'Audiovisuel", domain: "iina.tn", region: "Africa", country: "Tunisia", isVerified: true },
{ name: "École Centrale Supérieure Privée de Technologie", domain: null, region: "Africa", country: "Tunisia", isVerified: false },
{ name: "Institut Supérieur Privé des Sciences, de la Technologie et des Affaires du Centre", domain: "ict-edu.tn", region: "Africa", country: "Tunisia", isVerified: true },
]