import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Turkey_universities = [

    // Turkey
  
    { name: "Anadolu Üniversitesi", domain: "anadolu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Boğaziçi Üniversitesi", domain: "bogazici.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Orta Doğu Teknik Üniversitesi", domain: "metu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Teknik Üniversitesi", domain: "itu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Üniversitesi", domain: "istanbul.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bilkent Üniversitesi", domain: "bilkent.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Hacettepe Üniversitesi", domain: "hacettepe.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ankara Üniversitesi", domain: "ankara.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ege Üniversitesi", domain: "ege.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Dokuz Eylül Üniversitesi", domain: "deu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Koç Üniversitesi", domain: "koc.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Sabanci Üniversitesi", domain: "sabanci.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Atatürk Üniversitesi", domain: "ataturk.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Marmara Üniversitesi", domain: "marmara.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Gazi Üniversitesi", domain: "gazi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yıldız Teknik Üniversitesi", domain: "yildiz.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Akdeniz Üniversitesi", domain: "akdeniz.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Çukurova Üniversitesi", domain: "cukurova.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Selçuk Üniversitesi", domain: "selcuk.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Uludağ Üniversitesi", domain: "uludag.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Sakarya Üniversitesi", domain: "sakarya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Erciyes Üniversitesi", domain: "erciyes.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Bilgi Üniversitesi", domain: "bilgi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ondokuz Mayıs Üniversitesi", domain: "omu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Pamukkale Üniversitesi", domain: "pamukkale.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Karadeniz Teknik Üniversitesi", domain: "ktu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Gaziantep Üniversitesi", domain: "gantep.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Eskişehir Osmangazi Üniversitesi", domain: "osmangazi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Süleyman Demirel Üniversitesi", domain: "sdu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Çanakkale Onsekiz Mart Üniversitesi", domain: "comu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kadir Has Üniversitesi", domain: "khas.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Başkent Üniversitesi", domain: "baskent.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Aydın Adnan Menderes Üniversitesi", domain: "adu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Sivas Cumhuriyet Üniversitesi", domain: "cumhuriyet.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İnönü Üniversitesi", domain: "inonu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yeditepe Üniversitesi", domain: "yeditepe.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Trakya Üniversitesi", domain: "trakya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Aydın Üniversitesi", domain: "aiu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bahçeşehir Üniversitesi", domain: "bahcesehir.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Balıkesir Üniversitesi", domain: "balikesir.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kocaeli Üniversitesi", domain: "kocaeli.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Medipol Üniversitesi", domain: "medipol.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bolu Abant İzzet Baysal Üniversitesi", domain: "aku.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İzmir Yüksek Teknoloji Enstitüsü", domain: "iztech.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Kültür Üniversitesi", domain: "istanbulkultur.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Muğla Sıtkı Koçman Üniversitesi", domain: "mu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Fırat Üniversitesi", domain: "firat.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Mersin Üniversitesi", domain: "mersin.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Afyon Kocatepe Üniversitesi", domain: "afyon.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "TOBB Ekonomi ve Teknoloji Üniversitesi", domain: "tobb.edu.tr", region: "Asia", country: "Turkey", isVerified: true },   
    { name: "Karabük Üniversitesi", domain: "karabuk.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Düzce Üniversitesi", domain: "duzce.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Özyeğin Üniversitesi", domain: "ozyegin.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Van Yüzüncü Yıl Üniversitesi", domain: "yuzuncuyil.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Tekirdağ Namık Kemal Üniversitesi", domain: "namikkemal.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Harran Üniversitesi", domain: "harran.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Necmettin Erbakan Üniversitesi", domain: "erbakan.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Çankaya Üniversitesi", domain: "cankaya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Zonguldak Bülent Ecevit Üniversitesi", domain: "beun.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yaşar Üniversitesi", domain: "yasar.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Galatasaray Üniversitesi", domain: "gsu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kütahya Dumlupınar Üniversitesi", domain: "dpu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Manisa Celal Bayar Üniversitesi", domain: "cbu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Dicle Üniversitesi", domain: "dicle.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Tokat Gaziosmanpaşa Üniversitesi", domain: "gop.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Üsküdar Üniversitesi", domain: "uskudar.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Atilim Üniversitesi", domain: "atilim.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ankara Yıldırım Beyazıt Üniversitesi", domain: "ybu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kahramanmaraş Sütçü İmam Üniversitesi", domain: "ksu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Istanbul Gelişim Üniversitesi", domain: "istanbulgelisim.edu.tr", region: "Asia", country: "Turkey", isVerified: true },  
    { name: "Hatay Mustafa Kemal Üniversitesi", domain: "mku.edu.tr", region: "Asia", country: "Turkey", isVerified: true },                           
    { name: "İzmir Ekonomi Üniversitesi", domain: "ieu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Burdur Mehmet Akif Ersoy Üniversitesi", domain: "mehmetakif.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Beykent Üniversitesi", domain: "beykent.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Mimar Sinan Güzel Sanatlar Üniversitesi", domain: "msgsu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kırıkkale Üniversitesi", domain: "kku.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yeditepe Üniversitesi", domain: "yeditepe.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Trakya Üniversitesi", domain: "trakya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Aydın Üniversitesi", domain: "aydin.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bahçeşehir Üniversitesi", domain: "bahcesehir.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Balıkesir Üniversitesi", domain: "balikesir.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kocaeli Üniversitesi", domain: "kocaeli.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Medipol Üniversitesi", domain: "medipol.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bolu Abant İzzet Baysal Üniversitesi", domain: "aku.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İzmir Yüksek Teknoloji Enstitüsü", domain: "iztech.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Kültür Üniversitesi", domain: "istanbulkultur.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Muğla Sıtkı Koçman Üniversitesi", domain: "mu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Fırat Üniversitesi", domain: "firat.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Mersin Üniversitesi", domain: "mersin.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Afyon Kocatepe Üniversitesi", domain: "afyon.edu.tr", region: "Asia", country: "Turkey", isVerified: true },    
    { name: "Kastamonu Üniversitesi", domain: "karabuk.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Hitit Üniversitesi", domain: "hitit.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Üniversitesi-Cerrahpaşa", domain: "cerrahpasa.istanbul.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Okan Üniversitesi", domain: "okan.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Uşak Üniversitesi", domain: "usak.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kütahya Dumlupınar Üniversitesi", domain: "klu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kafkas Üniversitesi", domain: "kafkas.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "KTO Karatay Üniversitesi", domain: "karatay.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Recep Tayyip Erdoğan Üniversitesi", domain: "recep.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Fatih Sultan Mehmet Vakıf Üniversitesi", domain: "fsm.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yozgat Bozok Üniversitesi", domain: "bozok.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Nişantaşı Üniversitesi", domain: "nisantasi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Altınbaş Üniversitesi", domain: "altinbas.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Abdullah Gül Üniversitesi", domain: "agu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Çankırı Karatekin Üniversitesi", domain: "karatekin.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Sabahattin Zaim Üniversitesi", domain: "zaim.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Karamanoğlu Mehmetbey Üniversitesi", domain: null, region: "Asia", country: "Turkey", isVerified: false },
    { name: "Amasya Üniversitesi", domain: "amasya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ahi Evran Üniversitesi", domain: "ahievran.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bingöl Üniversitesi", domain: "bingol.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Giresun Üniversitesi", domain: "giresun.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Medeniyet Üniversitesi", domain: "medeniyet.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yalova Üniversitesi", domain: "yalova.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Antalya Bilim Üniversitesi", domain: "antalyabilim.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İzmir Kâtip Çelebi Üniversitesi", domain: "ikc.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bursa Teknik Üniversitesi", domain: "btu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Arel Üniversitesi", domain: "arel.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Mardin Artuklu Üniversitesi", domain: "artuklu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ağrı İbrahim Çeçen Üniversitesi", domain: null, region: "Asia", country: "Turkey", isVerified: false },
    { name: "Gümüşhane Üniversitesi", domain: "gumushane.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ted Üniversitesi", domain: "tedu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bayburt Üniversitesi", domain: "bayburt.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Osmaniye Korkut Ata Üniversitesi", domain: "osmaniye.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Hasan Kalyoncu Üniversitesi", domain: "hku.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Sağlık Bilimleri Üniversitesi", domain: "sbu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Sinop Üniversitesi", domain: "sinop.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Artvin Çoruh Üniversitesi", domain: "coruh.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ordu Üniversitesi", domain: "ordu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstinye Üniversitesi", domain: "istinye.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bandırma Onyedi Eylül Üniversitesi", domain: "beu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Çağ Üniversitesi", domain: "cag.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Acıbadem Üniversitesi", domain: "acibadem.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Batman Üniversitesi", domain: "batman.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Kilis 7 Aralık Üniversitesi", domain: "kilis.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Iğdır Üniversitesi", domain: "igdir.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ankara Sosyal Bilimler Üniversitesi", domain: "asbu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Türk-Alman Üniversitesi", domain: "tau.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bezmiâlem Vakıf Üniversitesi", domain: "bezmi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Biruni Üniversitesi", domain: "biruni.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ardahan Üniversitesi", domain: "ardahan.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ibn Haldun Üniversitesi", domain: "ibnhaldun.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Piri Reis Üniversitesi", domain: "pirireis.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bitlis Eren Üniversitesi", domain: "bere.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Istanbul Topkapı Üniversitesi", domain: "topkapi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Alanya Alaaddin Keykubat Üniversitesi", domain: "alaaddin.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Siirt Üniversitesi", domain: "siirt.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "MEF Üniversitesi", domain: "mef.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Fenerbahçe Üniversitesi", domain: "fenerbahce.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Muş Alparslan Üniversitesi", domain: null, region: "Asia", country: "Turkey", isVerified: false },
    { name: "Erzurum Teknik Üniversitesi", domain: null, region: "Asia", country: "Turkey", isVerified: false },
    { name: "Türk Hava Kurumu Üniversitesi", domain: "thu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Beykoz Üniversitesi", domain: "beykoz.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", domain: "atu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Istanbul Yeni Yüzyıl Üniversitesi", domain: "yunus.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Ufuk Üniversitesi", domain: "ufuk.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Bakırçay Üniversitesi", domain: "bakircay.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Şırnak Üniversitesi", domain: "sirnak.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İzmir Demokrasi Üniversitesi", domain: "idu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İskenderun Teknik Üniversitesi", domain: "iste.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Istanbul 29 Mayıs Üniversitesi", domain: "soru.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Munzur Üniversitesi", domain: "munzur.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Esenyurt Üniversitesi", domain: "esenyurt.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Toros Üniversitesi", domain: "toros.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Hakkari Üniversitesi", domain: "hakkari.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Alanya Üniversitesi", domain: "alanya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Kent Üniversitesi", domain: "kent.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Konya Gıda ve Tarım Üniversitesi", domain: "agtu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "İstanbul Rumeli Üniversitesi", domain: "rumeli.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Avrasya Üniversitesi", domain: "avrasya.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Demiroğlu Bilim Üniversitesi", domain: "dbu.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Nuh Naci Yazgan Üniversitesi", domain: "nny.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Sanko Üniversitesi", domain: "sanko.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Yüksek İhtisas Üniversitesi", domain: "yi.edu.tr", region: "Asia", country: "Turkey", isVerified: true },
    { name: "Antalya Belek Üniversitesi", domain: null, region: "Asia", country: "Turkey", isVerified: false },
]