import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Uganda_universities = [

   // Uganda

   { name: "Makerere University", domain: "mak.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Kampala International University", domain: "kiu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Mbarara University of Science and Technology", domain: "must.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Uganda Christian University", domain: "ucu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Kyambogo University", domain: "kyambogo.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Uganda Martyrs University", domain: "umu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Busitema University", domain: "busitema.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Gulu University", domain: "gu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Kabale University", domain: "kab.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Ndejje University", domain: "ndejje.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Uganda Technology and Management University", domain: "utamu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Islamic University in Uganda", domain: "iuiu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Kumi University", domain: "kumiuniversity.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Nkumba University", domain: "nkumba.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "International University of East Africa", domain: "iuea.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "International Business, Science and Technology University", domain: "isbatuniversity.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Clarke International University", domain: "ciu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Mountains of the Moon University", domain: "mmu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Bugema University", domain: "bugema.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Muni University", domain: "muni.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Victoria University, Kampala", domain: "vu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Bishop Stuart University", domain: "bsu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Cavendish University Uganda", domain: "cavendish.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Lira University", domain: "lira.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Kampala University", domain: "kampalauniversity.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Soroti University", domain: "soroti.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "African Rural University", domain: "afru.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Muteesa I Royal University", domain: "mru.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "LivingStone International University", domain: "liu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "King Ceasor University", domain: "kcu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Africa Renewal University", domain: "afru.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "St Lawrence University", domain: "slu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "University of the Sacred Heart Gulu", domain: "ush.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Uganda Pentecostal University", domain: "upu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Valley University of Science and Technology", domain: "vust.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Metropolitan International University", domain: "miu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "African Bible University", domain: "abu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Avance International University", domain: "aiu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Team University", domain: "teamuni.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Ibanda University", domain: "ibanda.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "All Saints University Lango", domain: "asul.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
   { name: "Ankole Western University", domain: "awu.ac.ug", region: "Africa", country: "Uganda", isVerified: true },
]