import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const UK_universities = [
    
  // United Kingdom

  { name: "Abertay University", domain: "abertay.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Aberystwyth University", domain: "aber.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Anglia Ruskin University", domain: "anglia.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Arts University Bournemouth", domain: "aub.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Arts University Plymouth", domain: "auap.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Aston University", domain: "aston.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Bangor University", domain: "bangor.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Bath Spa University", domain: "bathspa.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Birkbeck, University of London", domain: "bbk.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Birmingham City University", domain: "bcu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Birmingham Newman University", domain: "bnu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Bishop Grosseteste University", domain: "bishopg.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Bournemouth University", domain: "bournemouth.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "BPP University", domain: "bpp.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Brunel University London", domain: "brunel.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Buckinghamshire New University", domain: "bucks.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Canterbury Christ Church University", domain: "canterbury.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Cardiff Metropolitan University", domain: "cardiffmet.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Cardiff University", domain: "cardiff.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "City, University of London", domain: "city.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Coventry University", domain: "coventry.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Cranfield University", domain: "cranfield.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "De Montfort University", domain: "dmu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Durham University", domain: "durham.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Edge Hill University", domain: "edgehill.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Edinburgh Napier University", domain: "napier.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "European School of Economics", domain: "ese.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Falmouth University", domain: "falmouth.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Glasgow Caledonian University", domain: "gcu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Goldsmiths, University of London", domain: "gold.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Guildhall School of Music and Drama", domain: "gsmd.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Harper Adams University", domain: "harper-adams.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Hartpury University and Hartpury College", domain: "hartpury.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Heriot-Watt University", domain: "hw.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Imperial College London", domain: "imperial.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Keele University", domain: "keele.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "King's College London", domain: "kcl.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Kingston University", domain: "kingston.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Lancaster University", domain: "lancaster.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Leeds Arts University", domain: "leedarts.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Leeds Beckett University", domain: "leedsbeckett.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Leeds Conservatoire", domain: "leedsconservatoire.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Leeds Trinity University", domain: "leedstrinity.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Liverpool Hope University", domain: "hope.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Liverpool John Moores University", domain: "ljmu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Liverpool School of Tropical Medicine", domain: "lstmed.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "London Business School", domain: "london.edu", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "London Metropolitan University", domain: "londonmet.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "London School of Hygiene & Tropical Medicine", domain: "lshtm.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "London South Bank University", domain: "lsbu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Loughborough University", domain: "lboro.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Manchester Metropolitan University", domain: "mmu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Middlesex University", domain: "mdx.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Newcastle University", domain: "ncl.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Northern School of Contemporary Dance", domain: "nscd.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Northumbria University", domain: "northumbria.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Norwich University of the Arts", domain: "nua.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Nottingham Trent University", domain: "ntu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Oxford Brookes University", domain: "brookes.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Plymouth Marjon University", domain: "pmu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Queen Margaret University", domain: "qmu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Queen Mary University of London", domain: "qmul.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Queen's University Belfast", domain: "qub.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Ravensbourne University London", domain: "ravensbourne.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Regent's University London", domain: "regents.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Richmond, The American International University in London", domain: "richmond.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Robert Gordon University", domain: "rgu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Rose Bruford College", domain: "bruford.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Royal College of Art", domain: "rca.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Royal College of Music", domain: "rcm.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Royal Conservatoire of Scotland", domain: "rcs.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Royal Holloway, University of London", domain: "royalholloway.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Royal Northern College of Music", domain: "rncm.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "School of Advanced Study, University of London", domain: "sas.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Scotland's Rural College", domain: "sruc.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Sheffield Hallam University", domain: "shu.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "SOAS, University of London", domain: "soas.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Solent University", domain: "solent.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "St George's, University of London", domain: "sgul.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "St Mary's University, Twickenham", domain: "stmarys.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Staffordshire University", domain: "staffs.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Swansea University", domain: "swansea.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Teesside University", domain: "tees.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Courtauld Institute of Art", domain: "courtauld.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Glasgow School of Art", domain: "gsa.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Liverpool Institute for Performing Arts", domain: "lipa.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The London School of Economics and Political Science", domain: "lse.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Royal Academy of Music", domain: "ram.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Royal Agricultural University", domain: "rau.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Royal Central School of Speech and Drama", domain: "cssd.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The Royal Veterinary College", domain: "rvc.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The University of Buckingham", domain: "buckingham.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The University of Law", domain: "law.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The University of Northampton", domain: "northampton.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "The University of York", domain: "york.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Trinity Laban Conservatoire of Music and Dance", domain: "trinitylaban.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Ulster University", domain: "ulster.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University College Birmingham", domain: "ucb.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University College London", domain: "ucl.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University for the Creative Arts", domain: "uca.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Aberdeen", domain: "abdn.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Bath", domain: "bath.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Bedfordshire", domain: "beds.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Birmingham", domain: "bham.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Bradford", domain: "bradford.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Brighton", domain: "brighton.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Bristol", domain: "bristol.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Cambridge", domain: "cam.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Central Lancashire", domain: "uclan.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Chester", domain: "chester.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Chichester", domain: "chi.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Cumbria", domain: "cumbria.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Derby", domain: "derby.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Dundee", domain: "dundee.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of East Anglia", domain: "uea.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of East London", domain: "uel.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Edinburgh", domain: "ed.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Essex", domain: "essex.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Exeter", domain: "exeter.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Glasgow", domain: "gla.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Gloucestershire", domain: "glos.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Greater Manchester", domain: "oldham.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Greenwich", domain: "gre.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Hertfordshire", domain: "herts.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Huddersfield", domain: "hud.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Hull", domain: "hull.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Kent", domain: "kent.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Leeds", domain: "leeds.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Leicester", domain: "leicester.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Lincoln", domain: "lincoln.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Liverpool", domain: "liverpool.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of London", domain: "london.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Manchester", domain: "manchester.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Nottingham", domain: "nottingham.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Oxford", domain: "ox.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Plymouth", domain: "plymouth.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Portsmouth", domain: "port.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Reading", domain: "reading.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Roehampton", domain: "roe.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Salford", domain: "salford.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Sheffield", domain: "sheffield.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of South Wales", domain: "southwales.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Southampton", domain: "southampton.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of St Andrews", domain: "st-andrews.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Stirling", domain: "stir.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Strathclyde", domain: "strath.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Suffolk", domain: "uos.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Sunderland", domain: "sunderland.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Surrey", domain: "surrey.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Sussex", domain: "sussex.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of the Arts London", domain: "arts.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of the Highlands and Islands", domain: "uhi.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of the West of England", domain: "uwe.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of the West of Scotland", domain: "uws.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Wales", domain: "wales.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Wales Trinity Saint David", domain: "uwtsd.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Warwick", domain: "warwick.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of West London", domain: "uwl.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Westminster", domain: "westminster.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Winchester", domain: "winchester.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Wolverhampton", domain: "wlv.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "University of Worcester", domain: "worcester.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Walbrook Institute London", domain: "walbrook.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "Wrexham University", domain: "wrexham.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },
  { name: "York St John University", domain: "yorksj.ac.uk", region: "Europe", country: "United Kingdom", isVerified: true },

]