import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Ukraine_universities = [

   // Ukraine

   { name: "Taras Shevchenko National University of Kyiv", domain: "knu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National Technical University of Ukraine Kyiv Polytechnic Institute", domain: "kpi.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "V. N. Karazin Kharkiv National University", domain: "karazin.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ivan Franko National University of Lviv", domain: "lnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv Polytechnic National University", domain: "lpnu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Kyiv-Mohyla Academy", domain: "ukma.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Sumy State University", domain: "sumdu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Life and Environmental Sciences of Ukraine", domain: "nubip.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ukrainian Catholic University", domain: "ucu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Precarpathian National University", domain: "pnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National Aviation University", domain: "nau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National Technical University Kharkiv Polytechnic Institute", domain: "khpi.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Zaporizhzhya National University", domain: "znu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv National University of Radioelectronics", domain: "nure.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Yuriy Fedkovych Chernivtsi National University", domain: "chnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Borys Grinchenko Kyiv Metropolitan University", domain: "kubg.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National University", domain: "onu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ukrainian State University named after Mykhailo Drahomanov", domain: "npu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "West Ukrainian National University", domain: "wunu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Uzhhorod National University", domain: "uzhnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Yaroslav Mudryi National Law University", domain: "nlu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "V.I. Vernadsky Crimean Federal University", domain: "cfuv.ru", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National Aerospace University", domain: "khai.edu", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Dnipro University of Technology", domain: "nmu.org.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv National Economic University", domain: "kneu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "H.S. Skovoroda Kharkiv National Pedagogical University", domain: "hnpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Vinnytsia National Technical University", domain: "vntu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ukrainian State University of Science and Technologies", domain: "ust.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lesya Ukrainka Volyn National University", domain: "vnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "I. Horbachevsky Ternopil National Medical University", domain: "tnmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Khmelnytskyi National University", domain: "khnu.km.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ternopil National Technical University", domain: "tntu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv National Medical University", domain: "knmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Pharmacy", domain: "nuph.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University 'Zaporizhzhia Polytechnic'", domain: "zp.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Interregional Academy of Personnel Management", domain: "maup.com.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donetsk National Technical University", domain: "donntu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Zhytomyr Polytechnic State University", domain: "zhytomyr.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "O.O. Bogomolets National Medical University", domain: "nmuofficial.com", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "KROK University", domain: "krok.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Food Technologies", domain: "nuft.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Chernihiv Polytechnic National University", domain: "cpnu.cn.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Simon Kuznets Kharkiv National University of Economics", domain: "hneu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ivano-Frankivsk National Technical University of Oil and Gas", domain: "nung.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Ostroh Academy", domain: "oa.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ternopil Volodymyr Hnatiuk National Pedagogical University", domain: "tnpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Oles Honchar Dnipro National University", domain: "dnu.dp.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Bukovinian State Medical University", domain: "bsmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Water and Environmental Engineering", domain: "nuwm.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv National University of Construction and Architecture", domain: "knuba.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Uman State Pedagogical University", domain: "udpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "V.I. Vernadsky Taurida National University", domain: "tanu.pro", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Cherkasy", domain: "cdu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Tavria State Agrotechnological University", domain: "tsatu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National Technological University", domain: "ontu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Black Sea National University", domain: "chdu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Zaporizhia State Medical and Pharmaceutical University", domain: "zsmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University Yuri Kondratyuk Poltava Polytechnic", domain: "nupp.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "State University of Trade and Economics", domain: "knteu.kiev.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kherson State University", domain: "ksu.ks.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Zhytomyr Ivan Franko State University", domain: "zu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "O.M. Beketov National University of Urban Economy in Kharkiv", domain: "kname.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv National Medical University", domain: "meduniv.lviv.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National Polytechnic University", domain: "opu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Melitopol State Pedagogical University", domain: "mdpu.org.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Vasyl' Stus Donetsk National University", domain: "donnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lutsk National Technical University", domain: "lntu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv National University of Internal Affairs", domain: "univd.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University Odesa Law Academy", domain: "onua.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv National University of Technologies and Design", domain: "knutd.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Mariupol State University", domain: "mdu.in.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Vinnitsa National Medical University", domain: "vnmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Luhansk Taras Shevchenko National University", domain: "luguniv.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donbass State Pedagogical University", domain: "dnpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Sevastopol State University", domain: "sevsu.ru", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "State Tax University", domain: "nusta.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Central Ukrainian State University named after Volodymyr Vinnichenko", domain: "cuspu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Poltava State Medical University", domain: "pdmud.umed.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "State Biotechnological University", domain: "sbsedu.kh.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "East Ukrainian National University", domain: "snu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Diplomatic Academy of Ukraine", domain: "diplomaticacademy.gov.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Dnipro State Medical University", domain: "dsma.dp.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv National University of Culture and Arts", domain: "knukim.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kremenchuk Mykhailo Ostrohradskyi National University", domain: "krnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Poltava State Agrarian University", domain: "pdaa.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "South Ukrainian National Pedagogical University", domain: "pdpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University of Physical Education and Sports of Ukraine", domain: "uni-sport.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "State University of Information and Communication Technology", domain: "duikt.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kamyanets-Podilsky Ivan Ohienko National University", domain: "kpnu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Dnipro State University of Internal Affairs", domain: "dduvs.in.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv National Automobile and Highway University", domain: "khadi.kharkov.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kryvyi Rih State Pedagogical University", domain: "kdpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Poltava V. G. Korolenko National Pedagogical University", domain: "npdu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Cherkasy State Technological University", domain: "chdtu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Mykolayiv National Agrarian University", domain: "mnau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National Medical University", domain: "onmedu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Mykolayiv National University", domain: "mdu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "T.H. Shevchenko National University 'Chernihiv Collegium'", domain: "chnpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Sumy State Pedagogical University", domain: "sspu.sumy.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Poltava University of Economics and Trade", domain: "puet.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Sumy National Agrarian University", domain: "snau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Vinnytsia National Agrarian University", domain: "vsau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Prydniprovska State Academy of Civil Engineering and Architecture", domain: "pgasa.dp.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Alfred Nobel University", domain: "duan.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv National Linguistic University", domain: "knlu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Shupyk National Healthcare University of Ukraine", domain: "nmapo.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Hryhorii Skovoroda University in Pereiaslav", domain: "phdpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Open International University of Human Development 'Ukraine'", domain: "vmurol.com.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ukrainian State University of Railway Transport", domain: "kart.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National Economics University", domain: "oneu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Vinnitsa State Pedagogical University", domain: "vspu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv State University of Internal Affairs", domain: "lvduvs.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Drohobych State Pedagogical University", domain: "dspu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kryvyi Rih National University", domain: "nmu.org.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kirovohrad National Technical University", domain: "kntu.kr.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Admiral Makarov National University of Shipbuilding", domain: "nuos.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ivano-Frankivsk National Medical University", domain: "ifnmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa State Environmental University", domain: "odeku.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Polissia National University", domain: "polyuniv.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Pryazovskyi State Technical University", domain: "pstu.edu", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Uman National University of Horticulture", domain: "udau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donetsk National Medical University", domain: "dnmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kherson National Technical University", domain: "kntu.net.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National Forestry University of Ukraine", domain: "nltu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "State University of Intellectual Technologies and Communications", domain: "suitc.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv State University of Physical Culture", domain: "ldufk.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "University of Educational Management", domain: "umo.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "International Science and Technology University", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "National Transport University", domain: "ntu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Nizhyn Gogol State University", domain: "ndu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa State Academy of Civil Engineering and Architecture", domain: "ogasa.org.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv National Academy of Arts", domain: "lnam.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv State University of Life Safety", domain: "ldubgd.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Bila Tserkva National Agrarian University", domain: "btsau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National Maritime University", domain: "onmu.odessa.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv National Environmental University", domain: "lnau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv State Academy of Design and Arts", domain: "ksada.org", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv Humanitarian University", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Ukrainian State University of Chemical Technology", domain: "udhtu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Dnipropetrovsk State Agrarian and Economic University", domain: "dsau.dp.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "European University", domain: "e-u.in.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National Academy of Management of Culture and Arts", domain: "namca.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Rivne State Humanitarian University", domain: "rshu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Dniprovsk State Technical University", domain: "dstu.dp.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Izmail State University of Humanities", domain: "idgu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "National University Odessa Maritime Academy", domain: "oma.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Petro Tchaikovsky National Music Academy of Ukraine", domain: "knmau.com.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Mukachevo State University", domain: "msu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa State Agrarian University", domain: "osau.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "State University of Infrastructure and Technology", domain: "duit.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odesa State University of Internal Affairs", domain: "oduvs.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kherson State Agrarian and Economic University", domain: "ksaeu.ks.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "University of Customs and Finance", domain: "umsf.dp.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kherson State Maritime Academy", domain: "ksma.ks.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Berdyansk State Pedagogical University", domain: "bdpu.org", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv I. P. Kotlyarevsky National University of Arts", domain: "num.kharkiv.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv National University of Theatre, Cinema and Television", domain: "knutct.com", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Odessa National Academy of Music", domain: "odma.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv University of Trade and Economics", domain: "lute.lviv.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donetsk National University of Economics and Trade", domain: "donnuet.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv National Music Academy", domain: "lnma.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lviv National University of Veterinary Medicine and Biotechnologies", domain: "vetuniver.lviv.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Ukrainian Academy of Printing", domain: "ukrprint.dp.ua", region: "Europe", country: "Ukraine", isVerified: false },
   { name: "National Academy of Visual Arts and Architecture", domain: "naba.kiev.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kerch State Marine Technology University", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Podillia State University", domain: "pdatu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "King Danylo University", domain: "iful.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv Medical University", domain: "kmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donetsk State University of Internal Affairs", domain: "dnuvs.in.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Hlukhiv National Pedagogical University", domain: "hnpu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lugansk State Medical University", domain: "lsmu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donbass State Technical University", domain: "donstu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Pylyp Orlyk International Classical University", domain: "orlyk.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "International Humanitarian University", domain: "vmurol.com.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv State Academy of Culture", domain: "academy.kharkov.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kyiv University of Law of the National Academy of Sciences of Ukraine", domain: "kul.kiev.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Donbas National Academy of Civil Engineering and Architecture", domain: "dnauba.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Zaporizhzhya Institute of Economics and Information Technology", domain: "zieit.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "East European University", domain: "eenu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Lugansk State University of Internal Affairs", domain: "lduvs.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Kharkiv State Academy of Physical Culture", domain: "khdafk.kharkov.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "Berdyansk University of Management and Business", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Cherkasy State Business College", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Dnipro Humanitarian University", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Ukraine Sigmund Freud University", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Kiev College of Civil Engineering, Architecture and Design", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Kharkiv International Medical University", domain: "khimu.edu.ua", region: "Europe", country: "Ukraine", isVerified: true },
   { name: "International Technological University Mykolaiv Polytechnic", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
   { name: "Luhansk State Academy of Culture and Arts", domain: null, region: "Europe", country: "Ukraine", isVerified: false },
]