import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const United_Arab_Emirates_universities = [

    // United Arab Emirates

    { name: "University of Sharjah", domain: "sharjah.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "United Arab Emirates University", domain: "uaeu.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Khalifa University", domain: "ku.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "New York University Abu Dhabi", domain: "nyuad.nyu.edu", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "American University of Sharjah", domain: "aus.edu", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Zayed University", domain: "zu.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Higher Colleges of Technology", domain: "hct.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Mohamed bin Zayed University of Artificial Intelligence", domain: "mbzuai.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Ajman University", domain: "ajman.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "American University in Dubai", domain: "aud.edu", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Abu Dhabi University", domain: "adu.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "University of Wollongong in Dubai", domain: "uowdubai.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Skyline University College", domain: "skylineuniversity.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Gulf Medical University", domain: "gmu.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Canadian University of Dubai", domain: "cud.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Al Ain University", domain: "aau.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "American University of Ras Al Khaimah", domain: "aurak.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Université Paris-Sorbonne Abou Dhabi", domain: "upad.abudhabi", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "University of Dubai", domain: "ud.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Middlesex University Dubai", domain: "mdx.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "The British University in Dubai", domain: "bud.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Mohammed Bin Rashid University of Medicine and Health Sciences", domain: "mbru.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Emirates Aviation University", domain: "eau.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Mohammed Bin Rashid School of Government", domain: "mbrsg.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "American University in the Emirates", domain: "aue.edu.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Amity University Dubai", domain: "amityuniversity.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "The Emirates Academy of Hospitality Management", domain: "eahm.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Al Qasimia University", domain: "qasimia.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Manipal University, Dubai", domain: "manipaldubai.com", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Liwa University", domain: "liwauniversity.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "City University Ajman", domain: "cityuniversityajman.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Al Falah University", domain: "alfalahuniversity.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Murdoch University Dubai", domain: "murdochdubai.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Mohamed Bin Zayed University for Humanities", domain: "mbzuh.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Dubai Institute of Design and Innovation", domain: "didi.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Institute of Management Technology Dubai", domain: "imt.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Dubai Medical College", domain: "dmc.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Ras al-Khaimah Medical and Health Sciences University", domain: "rkmhsu.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Abu Dhabi Polytechnic", domain: "adpoly.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "University of Fujairah", domain: "uof.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Jumeira University", domain: "ju.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Fatima College of Health Sciences", domain: "fchs.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Emirates College for Advanced Education", domain: "ecae.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Emirates Institute of Finance", domain: "eif.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Abu Dhabi School of Management", domain: "adsm.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Dubai Pharmacy College", domain: "dpc.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "University of Science and Technology of Fujairah", domain: "ustf.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Islamic Azad University U.A.E. Branch", domain: null, region: "Asia", country: "United Arab Emirates", isVerified: false },
    { name: "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology Dubai", domain: "szabist.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Al Wasl University", domain: "awu.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "ALDAR Academy for Vocational Education", domain: "aldaracademy.ac.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Umm Al Quwain University", domain: "uqu.edu.ae", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Imam Malik College for Islamic Sharia and Law", domain: null, region: "Asia", country: "United Arab Emirates", isVerified: false },
    { name: "University of Birmingham Dubai", domain: "birmingham.ac.uk", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "Rochester Institute of Technology, Dubai", domain: "dubai.rit.edu", region: "Asia", country: "United Arab Emirates", isVerified: true },
    { name: "European University College", domain: null, region: "Asia", country: "United Arab Emirates", isVerified: false },
    { name: "Université Saint-Joseph de Dubai", domain: null, region: "Asia", country: "United Arab Emirates", isVerified: false },
]