import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Uzbekistan_universities = [

    // Uzbekistan

    { name: "O'zbekiston Davlat Jahon Tillari Universiteti", domain: "uzswlu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Muhammad al-Xorazmiy nomidagi Toshkent Axborot Texnologiyalari Universiteti", domain: "tuit.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Samarqand Davlat Tibbiyot Universiteti", domain: "sammu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Buxoro Davlat Universiteti", domain: "buxdu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Pedagogika Universiteti", domain: "tdpu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston Milliy Universiteti", domain: "nuu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Farg'ona Politexnika Instituti", domain: "ferpi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Iqtisodiyot Universiteti", domain: "tsue.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent irrigatsiya va qishloq xo'jaligini mexanizatsiyalash muhandislari instituti", domain: "tiiame.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Samarkand Davlat Universiteti", domain: "samdu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Jahon Iqtisodiyoti va Diplomatiya Universiteti", domain: "uwed.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Shahridagi Xalqaro Vestminster Universiteti", domain: "wiut.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Namangan Davlat Pedagogika Instituti", domain: "namspi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Qoraqalpoq Davlat Universiteti", domain: "karsu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Termiz Davlat Universiteti", domain: null, region: "Asia", country: "Uzbekistan", isVerified: false },
    { name: "Urganch Davlat Universiteti", domain: "urdu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Tibbiyot Akademiyasi", domain: "tma.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Yuridik Universiteti", domain: "tsul.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Xalqaro Nordik Universiteti", domain: "nordicuniversity.org", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston Davlat Jismoniy Tarbiya va Sport Universiteti", domain: "jtsu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Bank-moliya Akademiyasi", domain: "bfa.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Texnika Universiteti", domain: "tdtu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Pediatriya Tibbiyot Instituti", domain: "tashpmi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Farg'ona Davlat Universiteti", domain: "fdu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Sharqshunoslik Universiteti", domain: "tsuos.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Transport Universiteti", domain: "tstu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Jizzax Davlat Pedagogika Universiteti", domain: "jdpu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Buxoro Muhandislik-Texnologiya Instituti", domain: "bmti.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Qarshi Muhandislik Iqtisodiyot Instituti", domain: "qmii.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Turan International University", domain: "tiu-edu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Nukus Davlat Pedagogika Instituti", domain: "ndpi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Agrar Universiteti", domain: "tdau.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Samarqand Iqtisodiyot va Servis Instituti", domain: "sies.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Andijon Davlat Tibbiyot Instituti", domain: "adti.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Moliya Instituti", domain: "tfi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston Davlat Konservatoriyasi", domain: "konservatoriya.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Alisher Navoiy nomidagi Toshkent davlat o'zbek tili va adabiyoti universiteti", domain: "tsuull.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Shahridagi Singapur Menejmentni Rivojlantirish Instituti", domain: "mdis.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Abu Ali ibn Sino nomidagi Buxoro Davlat Tibbiyot Instituti", domain: "bsmi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Andijon Davlat Universiteti", domain: "adu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Kamoliddin Behzod Nomidagi Milliy Rassomlik Va Dizayn Instituti", domain: "mrdi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston xalqaro islom akademiyasi", domain: "iiau.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Namangan Muhandislik-Texnologiya Instituti", domain: "nammti.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Navoiy Davlat Pedagogika Instituti", domain: "nspi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Jizzax Politexnika Instituti", domain: "jizpi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Shahridagi Turin Politexnika Universiteti", domain: "turin.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Andijon Qishloq Xo'jalik Instituti", domain: "andqxai.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Guliston Davlat Universiteti", domain: "guldu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Samarqand davlat veterinariya meditsinasi, chorvachilik va biotexnologiyalar universiteti", domain: "ssuv.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Shahridagi Inha Universiteti", domain: "inha.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Denov tadbirkorlik va pedagogika instituti", domain: "dtpi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Silk Road International University of Tourism and Cultural Heritage", domain: "univ-silkroad.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston Davlat San'at va Madaniyat Instituti", domain: "dsmi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Davlat Stomatologiya Instituti", domain: "tsdi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Navoiy davlat konchilik va texnologiyalar universiteti", domain: "nsumt.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Farmatsevtika Instituti", domain: "pharmi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Kimyo-Texnologiya Instituti", domain: "tkti.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent Arxitektura-Qurilish Universiteti", domain: "taqu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Qarshi Davlat Universiteti", domain: "qarshidu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Samarqand davlat arxitektura-qurilish universiteti", domain: "samdaqi.edu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Qo'qon Davlat Pedagogika Instituti", domain: "kspi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkentagi M. V. Lomonosov nomidagi Moskva Davlat Universiteti", domain: "msu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Chirchiq davlat pedagogika universiteti", domain: "cspu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Rossiya Davlat Neft va Gaz Universitetining Toshkent Shahridagi Filiali", domain: "gubkin.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Andijon Mashinasozlik Instituti", domain: "andmiedu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Qo'qon Universiteti", domain: "kokanduni.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Toshkent To'qimachilik va Yengil Sanoat Instituti", domain: "titli.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Namangan muhandislik qurilish instituti", domain: "nammqi.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston Respublikasi Davlat soliq qo'mitasi huzuridagi Fiskal institut", domain: "fiin.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Rossiya iqtisodiyot universitetining Toshkent shahridagi filiali", domain: "reu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Ma'mun nomidagi Jahon tillari universiteti", domain: "mamunedu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston-Koreya Xalqaro Universiteti", domain: "ukiu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekiston davlat xoreografiya akademiyasi", domain: "uzdxa.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "O'zbekistondagi Sharda Universiteti", domain: "shardauniversity.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Farg'ona jamoat salomatligi tibbiyot instituti", domain: "fmiph.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Buxoro Innovatsion Ta'lim va Tibbiyot universiteti", domain: "bimu.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Buxoro psixologiya va xorijiy tillar instituti", domain: "bui.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "Angren Universiteti", domain: "auni.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
    { name: "SAMBHRAM Universiteti", domain: "sambhram.uz", region: "Asia", country: "Uzbekistan", isVerified: true },
]