import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Venezuela_universities = [

   // Venezuela

   { name: "Universidad de Los Andes", domain: "ula.ve", region: "South America", country: "Venezuela", isVerified: true },                          
   { name: "Universidad Central de Venezuela", domain: "ucv.ve", region: "South America", country: "Venezuela", isVerified: true },                    
   { name: "Universidad Simón Bolívar", domain: "usb.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Católica Andrés Bello", domain: "ucab.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad de Carabobo", domain: "uc.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Dr. Rafael Belloso Chacín", domain: "urbe.edu", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental de los Llanos Occidentales", domain: "unellez.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Centro Occidental Lisandro Alvarado", domain: "ucla.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Pedagógica Experimental Libertador", domain: "upel.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Metropolitana", domain: "unimet.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad del Zulia", domain: "luz.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Yacambú", domain: "uniyacambu.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental del Táchira", domain: "unet.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad de Oriente, Venezuela", domain: "udo.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nueva Esparta", domain: "une.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental Politécnica Antonio José de Sucre", domain: "unexpo.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental Simón Rodríguez", domain: "unesr.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad José Antonio Páez", domain: "ujap.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental de Guayana", domain: "uneg.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Bolivariana de Venezuela", domain: "ubv.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Monteávila", domain: "monteavila.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Bicentenaria de Aragua", domain: "uba.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Tecnológica del Centro", domain: "utcc.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Católica del Táchira", domain: "ucat.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental de la Seguridad", domain: "uneseg.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental Rafael María Baralt", domain: "unermb.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Fermín Toro", domain: "uft.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Rafael Urdaneta", domain: "uru.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Santa María", domain: "usm.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad de Ciencias de la Salud", domain: null, region: "South America", country: "Venezuela", isVerified: false },
   { name: "Universidad Nacional Experimental Francisco de Miranda", domain: "unefm.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Católica Cecilio Acosta", domain: "ucca.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Católica Santa Rosa", domain: "ucsr.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Arturo Michelena", domain: "uam.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad José María Vargas", domain: "ujmv.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad de Margarita", domain: "unimarg.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental Marítima del Caribe", domain: "unemca.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Valle del Momboy", domain: "uvm.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental de los Llanos Centrales", domain: "unellez.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental Sur del Lago Jesús María Semprum", domain: null, region: "South America", country: "Venezuela", isVerified: false },
   { name: "Universidad Nororiental privada Gran Mariscal de Ayacucho", domain: "ugma.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental de las Artes", domain: "unearte.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Deportiva del Sur", domain: "uds.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Alejandro de Humboldt", domain: "uah.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Nacional Experimental del Yaracuy", domain: "uney.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Panamericana del Puerto", domain: "unipap.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Alonso de Ojeda", domain: "uniojeda.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad de Falcón", domain: "udefa.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Latinoamericana y del Caribe", domain: "ulac.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Dr. José Gregorio Hernández", domain: "ujgh.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Politécnica Jose Felix Ribas", domain: "uptjfr.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Bolivariana de Trabajadores Jesús Rivero", domain: "ubtjr.edu.ve", region: "South America", country: "Venezuela", isVerified: true },
   { name: "Universidad Campesina de Venezuela Argimiro Gabaldón", domain: null, region: "South America", country: "Venezuela", isVerified: false },
   { name: "Universidad Nacional Experimental Indígena del Tauca", domain: null, region: "South America", country: "Venezuela", isVerified: false },
   { name: "Universidad Venezolana de los Hidrocarburos", domain: null, region: "South America", country: "Venezuela", isVerified: false },  
]