import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Vietnam_universities = [

    // Vietnam

    { name: "Vietnam National University, Hanoi", domain: "vnu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Science and Technology", domain: "hust.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "The University of Da Nang", domain: "udn.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Technology", domain: "hcmut.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Economics Ho Chi Minh City", domain: "ueh.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "National Economics University", domain: "neu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Can Tho University", domain: "ctu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Technology and Education", domain: "hcmute.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Thuyloi University", domain: "thuyloi.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Duy Tan University", domain: "duytan.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Foreign Trade University", domain: "ftu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Social Sciences and Humanities", domain: "hcmussh.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Nguyen Tat Thanh University", domain: "ntt.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Vietnam National University, Ho Chi Minh City", domain: "vnuhcm.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "HUTECH University", domain: "hutech.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi National University of Education", domain: "hnue.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Science", domain: "hcmus.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Education", domain: "hcmue.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Van Lang University", domain: "vlu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Medicine and Pharmacy at Ho Chi Minh City", domain: "ump.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Vietnam National University of Agriculture", domain: "vnua.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Information Technology", domain: "uit.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City International University", domain: "hcmiu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Industry", domain: "haui.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Agriculture and Forestry", domain: "hcmuaf.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi Medical University", domain: "hmu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hue University", domain: "hueuni.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hoa Sen University", domain: "hoasen.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University", domain: "hanu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Transport", domain: "ut.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Economics and Law", domain: "uel.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Civil Engineering", domain: "nuce.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Nha Trang University", domain: "ntu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Thuongmai University", domain: "tmu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Transport and Communications", domain: "utc.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Thai Nguyen University", domain: "tnu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Vinh University", domain: "vinhuni.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "VNU University of Engineering and Technology", domain: "uet.vnu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Dalat University", domain: "dlu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Foreign Languages and Information Technology", domain: "huflit.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi Law University", domain: "hlu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Vietnam Maritime University", domain: "vimaru.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Law", domain: "hcmulaw.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Mining and Geology", domain: "humg.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Industry and Trade", domain: "huit.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "An Giang University", domain: "agu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hong Bang International University", domain: "hiu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Quy Nhon University", domain: "qnu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Saigon University", domain: "sgu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Van Hien University", domain: "vanhien.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Economics - Technology for Industries", domain: "uneti.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Baria Vungtau University", domain: "bvu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi Architectural University", domain: "hau.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Lac Hong University", domain: "lhu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Dong Nai University of Technology", domain: "dntu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Ho Chi Minh City University of Architecture", domain: "uah.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Pharmacy", domain: "hup.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Thai Binh University of Medicine and Pharmacy", domain: "tbump.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hai Phong Medical University", domain: "hpmu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Business and Technology", domain: "hubt.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Culture", domain: "huc.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hong Duc University", domain: "hdu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "FPT University", domain: "fpt.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "VNU University of Science", domain: "hus.vnu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Saigon International University", domain: "siu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Tay Bac University", domain: "utb.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Phuong Dong University", domain: "phuongdong.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Vo Truong Toan University", domain: "vttu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Eastern University of Technology", domain: "mut.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hung Vuong University", domain: "hvu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi Industrial Textile Garment University", domain: "hict.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Technology & Management", domain: "utm.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Bac Lieu University", domain: "blu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Mientrung University of Civil Engineering", domain: "muce.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "University of Education", domain: "education.vnu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Dong Do International University", domain: "hdiu.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
    { name: "Hanoi University of Industrial Fine Arts", domain: null, region: "Asia", country: "Vietnam", isVerified: false },
    { name: "University of Hai Duong", domain: "uhd.edu.vn", region: "Asia", country: "Vietnam", isVerified: true },
]