import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const Yemen_universities = [

    // Yemen

    { name: "Al-Razi University", domain: "alraziuni.edu.ye", isVerified: true },
    { name: "Sana'a University", domain: "su.edu.ye", isVerified: true },
    { name: "Queen Arwa University", domain: "qau.edu.ye", isVerified: true },
    { name: "University of Science and Technology", domain: "ust.edu", isVerified: true },
    { name: "University of Aden", domain: "aden-univ.net", isVerified: true },
    { name: "Al-Ahgaff University", domain: "ahgaff.edu", isVerified: true },
    { name: "Hadhramout University", domain: "hu.edu.ye", isVerified: true },
    { name: "Al-Nasser University", domain: "nu.edu.ye", isVerified: true },
    { name: "Thamar University", domain: "tu.edu.ye", isVerified: true },
    { name: "Al-Eman University", domain: "jameataleman.org", isVerified: true },
    { name: "Ibb University", domain: "ibbuniv.edu.ye", isVerified: true },
    { name: "Taiz University", domain: "taiz.edu.ye", isVerified: true },
    { name: "Future University", domain: "futureuniversity.com", isVerified: true },
    { name: "Saba University", domain: "saba.edu.ye", isVerified: true },
    { name: "Al Janad University for Science and Technology", domain: "just.edu.ye", isVerified: true },
    { name: "Alandalus University for Science and Technology", domain: "andalusuniv.net", isVerified: true },
    { name: "Hodeidah University", domain: "hoduniv.net.ye", isVerified: true },
    { name: "Lebanese International University Yemen", domain: "ye.liu.edu.lb", isVerified: true },
    { name: "University of Modern Sciences", domain: "ums.edu.ye", isVerified: true },
    { name: "Emirates International University", domain: "eiu.edu.ye", isVerified: true }, 
    { name: "Al Jazeera University", domain: "aljazeeraibb.edu.ye", isVerified: true },
    { name: "National University, Yemen", domain: "national-univ.net", isVerified: true },
    { name: "Dar Al-Salam International University for Science and Technology", domain: "dsuye.education", isVerified: true },
    { name: "Albaydha University", domain: "baydaauniv.net", isVerified: true },
    { name: "Yemeni University", domain: "yuniv.net", isVerified: true },
    { name: "Al-Saeeda University", domain: "alsaeeduni.edu.ye", isVerified: true },
    { name: "Yemenia University", domain: null, isVerified: false },
    { name: "Amran University", domain: "amu.edu.ye", isVerified: true },
    { name: "University of Civilization", domain: "civilizationuniv.edu.ye", isVerified: true },
    { name: "Al-Rayan University", domain: "alrayan-university.edu.ye", isVerified: true },
    { name: "International University of Technology Twintech", domain: "iutt.edu.ye", isVerified: true },
    { name: "Azal University of Human Development", domain: "auhd.edu.ye", isVerified: true },
    { name: "Yemeni Jordanian University", domain: "yju.edu.ye", isVerified: true },
    { name: "Iqra'a University for Science and Technology", domain: "iqraa.edu.ye", isVerified: true },
    { name: "Arab University for Science and Technology", domain: null, isVerified: false },
    { name: "Ibn Khaldoun University", domain: null, isVerified: false },
    { name: "Knowledge and Modern Science University", domain: "kmsu.edu.ye", isVerified: true },
    { name: "Yemen and the Gulf University of Science and Technology", domain: null, isVerified: false },
    { name: "Al-Hikma University", domain: "hikma.edu.ye", isVerified: true },
    { name: "Al-Imam Al-Shafi'i University", domain: null, isVerified: false },
    { name: "May 22 College of Applied Medical Sciences", domain: null, isVerified: false },
    { name: "Hajjah University", domain: "hau.edu.ye", isVerified: true },
    { name: "Azal University of Science and Technology", domain: null, isVerified: false },
    { name: "University of Islamic Sciences Al Hudaydah", domain: null, isVerified: false },
    { name: "Union University of Science and Technology", domain: null, isVerified: false },
]